Repository MudBlazor/MudBlazor, pull requests merged in 2021-12, with the labels that each got.

#3169 MudDataGrid
  src/MudBlazor.Docs.Compiler/TestsForExamples.cs
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAdvancedExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridInlineEditingExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridVisualStylingExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiSelectExample.razor
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor.UnitTests.Viewer/Properties/launchSettings.json
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCellTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridChildRowContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColGroupTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEventCallbacksTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterableTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFiltersTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFooterTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridHeaderTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridInlineEditTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridInlineEditWithTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridLoadingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridNoRecordsContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridPaginationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerPaginationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerSideSortableTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSortableTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridVisualStylingTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/UserAttributes/UserAttributesTests.cs
  src/MudBlazor/Components/DataGrid/Cell.razor
  src/MudBlazor/Components/DataGrid/Cell.razor.cs
  src/MudBlazor/Components/DataGrid/Column.cs
  src/MudBlazor/Components/DataGrid/ColumnType.cs
  src/MudBlazor/Components/DataGrid/DataGridEditMode.cs
  src/MudBlazor/Components/DataGrid/DataGridRowClickEventArgs.cs
  src/MudBlazor/Components/DataGrid/DataGridRowValidator.cs
  src/MudBlazor/Components/DataGrid/Filter.razor
  src/MudBlazor/Components/DataGrid/Filter.razor.cs
  src/MudBlazor/Components/DataGrid/FilterDefinition.cs
  src/MudBlazor/Components/DataGrid/FooterCell.razor
  src/MudBlazor/Components/DataGrid/FooterCell.razor.cs
  src/MudBlazor/Components/DataGrid/GridState.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
  src/MudBlazor/Components/DataGrid/Row.razor
  src/MudBlazor/Components/DataGrid/Row.razor.cs
  src/MudBlazor/Extensions/DataGridExtensions.cs
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_datagrid.scss
  src/MudBlazor/Styles/utilities/_zindex.scss
Labels: new component, PR: needs review, hacktoberfest-accepted

#3110 NumericField: Add Clearable Parameter
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: enhancement

#3401 Checkbox, Switch, Picker: Fix Esc key conflict with Dialog
  src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogUsageExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Switch/SwitchPage.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: bug, PR: needs review

#3309 Autocomplete: open drop-down when text changes and call searchfunc when textchanged is handled
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, enhancement

#3372 Docs: Add a note in MessageBox page regarding its dependency on DialogService
  src/MudBlazor.Docs/Pages/Components/MessageBox/MessageBoxPage.razor
Labels: docs

#3481 DatePicker: Obsolete AllowKeyboardInput parameter
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: enhancement, PR: needs review

#3470 Docs: Add content security policy
  src/MudBlazor.Docs.Client/wwwroot/index.html
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
Labels: enhancement, PR: needs review

#3342 TimePicker: Fix OnlyHours incorrect behavior
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug, PR: needs review

#2896 Chart: add CustomGraphics RenderFragment to integrate user content
  src/MudBlazor.Docs/Pages/Components/Charts/Chart Types/BarChartPage.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Chart Types/DonutChartPage.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/BarCustomGraphicsExample.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/DonutCustomGraphicsExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/ChartsWithCustomGraphicsTest.razor
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor
  src/MudBlazor/Components/Chart/Charts/Donut.razor
  src/MudBlazor/Components/Chart/Charts/Line.razor
  src/MudBlazor/Components/Chart/Charts/Pie.razor
  src/MudBlazor/Components/Chart/MudChart.razor.cs
Labels: enhancement, PR: needs changes

#3463 Carousel: Fix SelectedIndex two-way binding and add BulletsColor param.
  src/MudBlazor.Docs/Pages/Components/Carousel/CarouselPage.razor
  src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselBindingExample.razor
  src/MudBlazor.UnitTests/Components/CarouselTests.cs
  src/MudBlazor/Base/MudBaseBindableItemsControl.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudBaseItemsControl.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs
Labels: bug

#3252 Dialog: Fix Class, Style and Tag properties ignored in inline dialog
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestInlineDialog.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: bug, PR: needs review

#3476 ThemeProvider: Add dark palette
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesCustomExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesDarkPaletteExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesMultipleExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Overview.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor.UnitTests/Components/MudThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Themes/MudTheme.cs
Labels: enhancement, PR: needs review

#3546 Content Security policy: Fix carousel example + Fix icon example
  src/MudBlazor.Docs.Client/wwwroot/index.html
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
Labels: bug

#3560 Content security policy: Fix contributors page
  src/MudBlazor.Docs.Client/wwwroot/index.html
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
Labels: bug

#3596 API documentation: Add method descriptions on Wasm
  src/MudBlazor.Docs.Compiler/DocStrings.cs
  src/MudBlazor.Docs/Components/DocsApi.razor
  src/MudBlazor.Docs/Models/DocStrings.cs
Labels: bug, docs

#3392 Docs: added example of custom checkbox handling for MudTreeView (#2550)
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomCheckboxExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
Labels: docs

#3607 Output ES6 compatible JavaScript to support older browsers
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/tsconfig.json
Labels: enhancement

#3515 Tooltip: Add IsVisible two-way binding property
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipVisiblePropTest.razor
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
Labels: enhancement

#3613 TextField: Add HTML5 input types
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldNativeInputsExample.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Enums/InputType.cs
Labels: enhancement

#3552 Build: Switch to WASM for docs
  src/MudBlazor.Docs.Client/MudBlazor.Docs.Client.csproj
  src/MudBlazor.Docs.Client/wwwroot/index.html
  src/MudBlazor.Docs.Server/App.razor
  src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj
  src/MudBlazor.Docs.Server/Pages/_Host.cshtml
  src/MudBlazor.Docs.Server/Program.cs
  src/MudBlazor.Docs/Shared/MainLayout.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
Labels: enhancement

#3638 NavMenu: Added color, border, rounded, margin, dense options
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuBorderedExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuColorExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuDenseExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuMarginExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuRoundedExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/NavMenuPage.razor
  src/MudBlazor.UnitTests/Components/NavMenuTests.cs
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor.cs
  src/MudBlazor/Styles/components/_navmenu.scss
Labels: enhancement
