Repository MudBlazor/MudBlazor, pull requests merged in 2021-10, with the labels that each got.

#2894 Added capability to set alt property when Image is used in MudAvatar
  src/MudBlazor.Docs/Pages/Components/Avatar/AvatarPage.razor
  src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarImageExample.razor
  src/MudBlazor.UnitTests/Components/AvatarTests.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
Labels: enhancement

#2851 Services/NumericField: Add KeyboardInterceptor service
  src/MudBlazor.Docs.Server/Properties/launchSettings.json
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockKeyInterceptor.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyInterceptor.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorOptions.cs
  src/MudBlazor/Services/Scroll/ScrollManagerException.cs
  src/MudBlazor/Services/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/ServiceConfiguration.cs
  src/MudBlazor/TScripts/mudKeyInterceptor.js
  src/MudBlazor/Utilities/Exceptions/GenericTypeMismatchException.cs
  src/MudBlazor/Utilities/RuntimeLocation.cs
Labels: bug, enhancement

#2926 MudInput: fix cursor jumping for immediate multiline inputs with two-way binding on BSS
  src/MudBlazor.Docs.Server/Properties/launchSettings.json
  src/MudBlazor/Components/Input/MudInput.razor
Labels: bug

#2914 MudBlazor Documentation: Collapse code examples that are too long (more than 15 lines of code)
  CONTRIBUTING.md
  src/MudBlazor.Docs/Pages/Components/Alert/AlertPage.razor
  src/MudBlazor.Docs/Pages/Components/AppBar/AppBarPage.razor
  src/MudBlazor.Docs/Pages/Components/Avatar/AvatarPage.razor
  src/MudBlazor.Docs/Pages/Components/Button/ButtonPage.razor
  src/MudBlazor.Docs/Pages/Components/ButtonFAB/FabPage.razor
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/ButtonGroupPage.razor
  src/MudBlazor.Docs/Pages/Components/Card/CardPage.razor
  src/MudBlazor.Docs/Pages/Components/Carousel/CarouselPage.razor
  src/MudBlazor.Docs/Pages/Components/Charts/DonutChartPage.razor
  src/MudBlazor.Docs/Pages/Components/Charts/PieChartPage.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/ColorPickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Divider/DividerPage.razor
  src/MudBlazor.Docs/Pages/Components/Element/ElementPage.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/ExpansionPanelPage.razor
  src/MudBlazor.Docs/Pages/Components/FocusTrap/FocusTrapPage.razor
  src/MudBlazor.Docs/Pages/Components/Hidden/HiddenPage.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/HighlighterPage.razor
  src/MudBlazor.Docs/Pages/Components/Icons/IconsPage.razor
  src/MudBlazor.Docs/Pages/Components/List/ListPage.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/MessageBoxPage.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/NavMenuPage.razor
  src/MudBlazor.Docs/Pages/Components/Pagination/PaginationPage.razor
  src/MudBlazor.Docs/Pages/Components/Popover/PopoverPage.razor
  src/MudBlazor.Docs/Pages/Components/Progress/ProgressPage.razor
  src/MudBlazor.Docs/Pages/Components/Radio/RadioPage.razor
  src/MudBlazor.Docs/Pages/Components/Rating/RatingPage.razor
  src/MudBlazor.Docs/Pages/Components/SimpleTable/SimpleTablePage.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/SwipeAreaPage.razor
  src/MudBlazor.Docs/Pages/Components/Switch/SwitchPage.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/TimePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/ToggleIconButton/ToggleIconButtonPage.razor
  src/MudBlazor.Docs/Pages/Components/Tooltip/TooltipPage.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor.Docs/Pages/Features/Converters/ConvertersPage.razor
  src/MudBlazor.Docs/Pages/Features/RTLLanguages/RTLLanguagesPage.razor
Labels: docs

#2920 Docs: Fix missing API section on chips page
  src/MudBlazor.Docs/Models/ApiLink.cs
Labels: docs

#2696 Autocomplete and Select: Dense="true" only affects list, for input use Margin="Margin.Dense" (Breaking change)
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteMarginDenseExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, breaking change, mudblazor-v5.2

#2934 Input: remove tabstop from input adorners
  src/MudBlazor/Components/Input/MudInputAdornment.razor
Labels: bug

#2944 Docs: Fix show code for GridBuilder on grid page
  src/MudBlazor.Docs/Pages/Components/Grid/Examples/GridBuilderExample.razor
  src/MudBlazor.Docs/Pages/Components/Grid/GridPage.razor
Labels: docs

#2942 Docs: Update SnackBar navigation example
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
Labels: docs

#2940 DateRangePicker: Added null safe access to value and _rangeText in the setter of RangeText
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug

#2930 ExpansionPanels: Resolves infinite loop created by cascading StateHasChanged calls
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelExpandedMultipleWithoutMultipleExpansionSetTest.razor
  src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
Labels: bug

#3181 Nav Link Text Wrap
  src/MudBlazor/Styles/components/_navmenu.scss
Labels: bug

#3189 Framework: Add JSDisconnected exception for net6
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
  src/MudBlazor/Services/ResizeListener/BreakpointService .cs
  src/MudBlazor/Services/ResizeListener/ResizeBasedService.cs
  src/MudBlazor/Services/ResizeListener/ResizeService.cs
Labels: net6

#3209 Autocomplete: Increased reliability of ChangeBoundValue test
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: PR: needs review

#3119 Tests: Fix user regional settings dependent unit tests
  src/MudBlazor.UnitTests/Components/MudThemeProviderTests.cs
  src/MudBlazor.UnitTests/Utilities/BindingConverterTests.cs
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
Labels: bug

#3205 Docs: New Icon page
  src/MudBlazor.Docs/Components/DocsColorSelect.razor
  src/MudBlazor.Docs/Components/DocsIconPanel.razor
  src/MudBlazor.Docs/Components/DocsIcons.razor
  src/MudBlazor.Docs/Components/DocsPageHeader.razor
  src/MudBlazor.Docs/Models/MudIcons.cs
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor.cs
  src/MudBlazor.Docs/Styles/components/_icons.scss
Labels: docs, enhancement, PR: needs review

#3211 Fix mini drawer when clipmode is docked
  src/MudBlazor/Styles/layout/_appbar.scss
  src/MudBlazor/Styles/layout/_drawer.scss
Labels: bug, PR: needs review

#3206 Drawer: Fixed mini mode drawer's z-index when "closed"
  src/MudBlazor/Styles/layout/_drawer.scss
Labels: bug, PR: needs review

#3208 MudPopover improved FlipBehaviour
  src/MudBlazor.Docs/wwwroot/JS/docs.js
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, PR: needs review

#3216 Theme: Typography defaults and documentation
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/TypographyDefaultFontExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/TypographySettingsExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Overview.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Typography.razor
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Themes/Models/Typography.cs
Labels: docs, enhancement
