Repository MudBlazor/MudBlazor, pull requests merged in 2021-09, with the labels that each got.

#2628 Table: Make RowsPerPage parameter two-way bindable.
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRowsPerPageTwoWayBindingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRowsPerPageTwoWayBindingTest.razor.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
Labels: enhancement

#2799 ChipSet: enable ChipSet to be readonly (#2548)
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetReadOnlyTest.razor
  src/MudBlazor.UnitTests/Components/ChipSetTests.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
Labels: enhancement, PR: needs review

#2714 Autocomplete: add support for disabled (unselectable) items
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteDisabledItemsTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/TScripts/mudScrollManager.js
Labels: enhancement, PR: needs review

#2736 Select: Reset clears SelectedValues
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: enhancement

#2739 ButtonGroup: Improve the styling when tooltips are used on buttons
  src/MudBlazor.UnitTests.Viewer/TestComponents/Button/ButtonGroupTooltipsTest.razor
  src/MudBlazor/Styles/components/_buttongroup.scss
Labels: bug

#2742 Autocomplete: fix Clear and Reset and keep focused on value selection
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteUsageExample.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement, PR: needs revision

#2835 Inputs: HelperText Show/Hide On Focus/Blur
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldHelperTextExample.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Styles/components/_inputcontrol.scss
Labels: enhancement

#2839 Input: CharacterCount and MaxLength Properties
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldCharacterCountExample.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
Labels: enhancement

#2876 [Bug] Chip: Fix OnClick/OnClose causing NullReferenceException (#2866)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Chip/ChipOnClickTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetReadOnlyTest.razor
  src/MudBlazor.UnitTests/Components/ChipSetTests.cs
  src/MudBlazor.UnitTests/Components/ChipTests.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
Labels: bug, Priority: High

#2857 PageContentNavigation: Fix cut off text
  src/MudBlazor/Styles/components/_pagecontentnavigation.scss
Labels: bug, documentation

#2897 Table: prevent changing sort while row editing
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableInlineEditSortTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
Labels: bug

#2901 CheckBox: Default Cursor when readonly
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Styles/components/_checkbox.scss
Labels: bug
