Repository MudBlazor/MudBlazor, pull requests merged in 2021-11, with the labels that each got.

#3217 Docs: Fix convertors page
  src/MudBlazor.Docs/Pages/Features/Converters/ConvertersPage.razor
Labels: bug, PR: needs review

#3172 Docs: Add tooltips for enum types showing enum constants
  src/MudBlazor.Docs/Components/DocsApi.razor
  src/MudBlazor.Docs/Components/DocsTypeInfo.razor
  src/MudBlazor.Docs/Models/ApiProperty.cs
Labels: docs, enhancement

#3244 Fix #3033 - RowsPerPage Parameter can now be set from code
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagerChangeRowsPerPageTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagerChangeRowsPerPageTest.razor.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
Labels: bug

#3148 Extensions: ToPx for common number types.
  src/MudBlazor.UnitTests/Extensions/WebUnitsExtensionsTests.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Extensions/NumberExtensions.cs
  src/MudBlazor/Extensions/WebUnitsExtensions.cs
Labels: enhancement

#3251 Updated GitHub Workflows
  .github/workflows/ci-net6.yml
  .github/workflows/manual-deploy.yml
  .github/workflows/prepare-release.yml
  .github/workflows/template-pipeline.yml
Labels: enhancement, PR: needs review

#3083 DatePicker: Fix setting culture not leading to DateFormat change (#2962)
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: bug, PR: needs review, hacktoberfest-accepted

#3245 When a row is clicked, only call SetEditingItem if IsEditable is true
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRowClickNotEditableTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: bug, PR: needs changes

#3273 ThemeProvider: Add TextTransform parameter to typography
  src/MudBlazor.UnitTests/Components/MudThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Styles/components/_button.scss
  src/MudBlazor/Styles/components/_fab.scss
  src/MudBlazor/Styles/components/_navmenu.scss
  src/MudBlazor/Styles/components/_typography.scss
  src/MudBlazor/Styles/core/_base.scss
  src/MudBlazor/Themes/Models/Typography.cs
Labels: enhancement, PR: needs review

#3278 HeadElement: remove and use native tag
  src/MudBlazor.Docs.Client/MudBlazor.Docs.Client.csproj
  src/MudBlazor.Docs.Client/Program.cs
  src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj
  src/MudBlazor.Docs.Server/Startup.cs
  src/MudBlazor.Docs/Components/DocsPageHeader.razor
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockHeadElementHelper.cs
Labels: PR: needs review

#3262 PopoverService: may be initializing when browser is disconnected
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
Labels: bug, PR: needs review

#3288 NumericField: HelperTextOnFocus
  src/MudBlazor/Components/NumericField/MudNumericField.razor
Labels: enhancement, PR: needs review

#3299 Build: Make obsolete parameters fail build.
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/AppBar/MudAppBarSpacer.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Components/ToolBar/MudToolBarSpacer.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Icons/Material/_Obsolete.cs
  src/MudBlazor/Interfaces/ISnackbar.cs
  src/MudBlazor/Themes/Models/LayoutProperties.cs
  src/MudBlazor/Utilities/ColorManager.cs
  src/MudBlazor/Utilities/ColorTransformation.cs
Labels: breaking change, PR: needs review

#3234 MudFab: Support for StartIcon and EndIcon
  src/MudBlazor.Docs/Pages/Components/ButtonFAB/Examples/FabSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/ButtonFAB/Examples/FabSizeExample.razor
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Styles/components/_fab.scss
Labels: enhancement

#3319 MudChipSet: Remove debug messages
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
Labels: bug

#3326 TimePicker: Fixed the picker adding a day to the timespan (#3180)
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor
Labels: bug, PR: needs test

#3225 MudScollToTop: Fix data types in ScollEventArgs class (#3185)
  src/MudBlazor/Services/Scroll/ScrollEventArgs.cs
Labels: bug

#3349 MudKeyInterceptor: improve compatibility with older browser
  src/MudBlazor/TScripts/mudKeyInterceptor.js
Labels: bug, PR: needs review

#3362 InputType: Added url to the InputType enum (#3357)
  src/MudBlazor/Enums/InputType.cs
Labels: enhancement

#3352 Table: Fixed incorrect async code path for label sorting
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest5.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableSortLabel.razor.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug

#3393 Dialog: Close on ESC
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/ManualMarkdown/MarkdownDialogParameters.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogOkCancel.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor.UnitTests/Mocks/MockKeyInterceptor.cs
  src/MudBlazor/Components/Dialog/DialogOptions.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyInterceptor.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
  src/MudBlazor/TScripts/mudKeyInterceptor.js
Labels: enhancement

#3204 TimePicker: Keyboard Navigation
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/TimePickerPage.razor
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: enhancement

#3399 Rating: Keyboard Navigation
  src/MudBlazor.Docs/Pages/Components/Rating/Examples/RatingIconsAndColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Rating/Examples/RatingKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/Rating/Examples/RatingMaxValueExample.razor
  src/MudBlazor.Docs/Pages/Components/Rating/Examples/RatingSizesExample.razor
  src/MudBlazor.Docs/Pages/Components/Rating/RatingPage.razor
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor/Components/Rating/MudRating.razor
  src/MudBlazor/Components/Rating/MudRating.razor.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor
  src/MudBlazor/Styles/components/_rating.scss
Labels: enhancement

#3144 MudExpansionPanel: Let Changed handler run before actually expanding.
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelAsyncExample.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/ExpansionPanelPage.razor
  src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
Labels: bug, enhancement

#3383 ProgressLinear: Several new features, fixed bad examples and added new, code cleanup
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressCircularDeterminateExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearBufferExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearDeterminateExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearLabelsExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearMinMaxExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearRoundedExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearSizeExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearStripedExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearVerticalExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/ProgressPage.razor
  src/MudBlazor.UnitTests/Components/ProgressLinearTests.cs
  src/MudBlazor.UnitTests/Components/ProgressTests.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Extensions/DoubleExtentions.cs
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_progress.scss
  src/MudBlazor/Styles/components/_progresscircular.scss
  src/MudBlazor/Styles/components/_progresslinear.scss
  src/MudBlazor/Styles/core/_animations.scss
Labels: bug, enhancement, PR: needs review

#3374 Docs: Icon page implemented blazor virtualization hybrid
  src/MudBlazor.Docs/Models/MudIcons.cs
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor.cs
  src/MudBlazor.Docs/Styles/components/_icons.scss
Labels: bug
