Repository MudBlazor/MudBlazor, pull requests merged in 2022-11, with the labels that each got.

#5661 MudCollapse: Better solution to non-rendering event (Add EventUtil)
  src/MudBlazor.Docs.Compiler/DocStrings.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/EventUtil1Test.razor
  src/MudBlazor.UnitTests/Utilities/EventUtilTests.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Utilities/EventUtil.cs
Labels: enhancement

#5680 Picker: Improve test coverage and fix ColorPicker bug
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormFieldChangedPickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormFieldChangedTest.razor
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug, bug-functional

#5701 Snackbar: Fix accidental API break by PR #5310
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor.cs
  src/MudBlazor/Components/Snackbar/Snackbar.cs
  src/MudBlazor/Components/Snackbar/SnackbarMessage.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
Labels: bug-functional

#5711 Snackbar: Fix break due to trimming of SnackbarMessageType
  src/MudBlazor/Components/Snackbar/SnackbarMessage.cs
Labels: bug, bug-functional

#5713 Build: add net7 library (multi-targeting)
  .github/workflows/ci-cd.yml
  global.json
  src/.editorconfig
  src/Directory.Build.props
  src/MudBlazor/MudBlazor.csproj
Labels: bug, bug-functional, net7

#5491 Fix MudDivider consistent thickness
  src/MudBlazor/Styles/components/_divider.scss
Labels: bug

#5498 MudDataGrid: Fix missing DataGrid reference in FilterDefinition
  src/MudBlazor/Components/DataGrid/Column.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, bug-functional

#5767 README: Update to reflect support for .NET 7
  README.md
Labels: docs

#5785 MudLink: Add OnClick parameter (#1518)
  src/MudBlazor.Docs/Pages/Components/Link/Examples/LinkOnClickExample.razor
  src/MudBlazor.Docs/Pages/Components/Link/LinkPage.razor
  src/MudBlazor.UnitTests/Components/LinkTests.cs
  src/MudBlazor/Components/Link/MudLink.razor
  src/MudBlazor/Components/Link/MudLink.razor.cs
Labels: enhancement, API change

#5484 Charts: Make Legend Clickable
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor
Labels: enhancement

#5582 MudColorPicker: Fix MaxLength on HEX TextField for transparent colors
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
Labels: bug

#5770 ScrollManager: Fix exceptions when no JS environment available
  src/MudBlazor/Extensions/TaskExtensions.cs
  src/MudBlazor/Services/IIJSRuntimeExtentions.cs
  src/MudBlazor/Services/Scroll/ScrollManager.cs
Labels: bug

#5101 MudDialog: Fix Dialog is null in IDialogReference
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogPassingDataExample.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/DialogReference.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
  src/MudBlazor/Interfaces/IDialogService.cs
  src/MudBlazor/Services/DialogService.cs
Labels: bug, API change

#5801 Build: Fix static assets need 2 builds to publish
  .github/workflows/deploy-nuget.yml
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: bug

#5810 Remove unused code in ElementReferenceExtensions
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
  src/MudBlazor/TScripts/mudElementReference.js
Labels: refactor

#5811 MudCarousel: Fix swipe direction for next/previous in rtl
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
Labels: bug

#5813 MudRadio: Fix content placement in rtl
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
Labels: bug

#5823 MudTable: Fix inconsistent row border thickness
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#5836 Tests/Components: Remove unnecessary Console.WriteLine
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCellEditTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEventCallbacksTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionCheckboxExecutesCallback.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/AvatarGroupTests.cs
  src/MudBlazor.UnitTests/Components/AvatarTests.cs
  src/MudBlazor.UnitTests/Components/BadgeTests.cs
  src/MudBlazor.UnitTests/Components/CarouselTests.cs
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor.UnitTests/Components/ChipSetTests.cs
  src/MudBlazor.UnitTests/Components/ChipTests.cs
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor.UnitTests/Components/DynamicTabsTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/HiddenTests.cs
  src/MudBlazor.UnitTests/Components/LinkTests.cs
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor.UnitTests/Components/NavLinkTests.cs
  src/MudBlazor.UnitTests/Components/NavMenuTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/PaginationTests.cs
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Components/ProgressLinearTests.cs
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor.UnitTests/Components/TimelineTests.cs
  src/MudBlazor.UnitTests/Components/ToggleIconButtonTest.cs
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor.UnitTests/Components/TreeViewTest.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs
  src/MudBlazor.UnitTests/Utilities/CodeSnippetUrlTests.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
Labels: refactor

#5760 MudTable: Fixed table grouping item selection issue (#5759)
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs
Labels: bug

#5879 MudBaseButton: Make OnClickHandler virtual
  src/MudBlazor/Base/MudBaseButton.cs
Labels: enhancement, API change

#5881 Build: Automate release notes
  .github/release.yml
Labels: build

#4647 MudTooltip: Activation via Hover, Focus or Click
  src/MudBlazor.Docs.Server/Properties/launchSettings.json
  src/MudBlazor.Docs/Components/SectionContent.razor
  src/MudBlazor.Docs/Pages/Components/Tooltip/Examples/TooltipActivationExample.razor
  src/MudBlazor.Docs/Pages/Components/Tooltip/TooltipPage.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipClickTest.razor
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
Labels: API change

#5858 TreeView: Fix Closing Arrow Transition
  src/MudBlazor/Components/TreeView/MudTreeViewItemToggleButton.razor
Labels: bug
