Repository MudBlazor/MudBlazor, pull requests merged in 2022-02, with the labels that each got.

#3756 Menu: Fix Right Click
  src/MudBlazor/Components/Menu/MudMenu.razor
Labels: bug

#3720 Docs: Culture Title Fix
  src/MudBlazor.Docs/Pages/Components/Icons/IconsPage.razor
  src/MudBlazor.Docs/Shared/NavMenu.razor
Labels: bug

#3860 MudDropZone: New Drag and Drop component
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs.Server/_Imports.razor
  src/MudBlazor.Docs.Server/wwwroot/favicon.ico
  src/MudBlazor.Docs.Server/wwwroot/images/logo.png
  src/MudBlazor.Docs.Server/wwwroot/robots.txt
  src/MudBlazor.Docs/Pages/Components/DropZone/DropZonePage.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneCanDropStylesExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneChessBoardExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneDisabledExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneDraggingStyleExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneDropRulesExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneItemSelectorExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneKanbanExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneOverrideExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Overview/OverviewPage.razor
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneBasicTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneCanDropTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneCustomItemSelectorTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneDisableTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneDraggingTestCantDropSecondZoneTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneDynamicItemCollectionTest.razor
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Attributes/CategoryAttribute.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs
  src/MudBlazor/Icons/Custom/Brands.cs
  src/MudBlazor/Icons/Custom/Uncategorized.cs
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/abstracts/_colors.scss
  src/MudBlazor/Styles/components/_dropzone.scss
  src/MudBlazor/Styles/utilities/_borders.scss
  src/MudBlazor/TScripts/mudDragAndDrop.js
Labels: enhancement, new component, API change

#3877 Better Image support and MudImage
  src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarBadgeExample.razor
  src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarGroupExample.razor
  src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarImageExample.razor
  src/MudBlazor.Docs/Pages/Components/Badge/Examples/BadgeInteractiveExample.razor
  src/MudBlazor.Docs/Pages/Components/Card/Examples/CardCombinedExample.razor
  src/MudBlazor.Docs/Pages/Components/Card/Examples/CardMediaExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/DocsImagePageResizer.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImageFitExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImagePlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImagePositionExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImageResponsiveExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImageSizeExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImageUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/ImagePage.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorExample1.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorOnMouseExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayLoaderExample.razor
  src/MudBlazor.Docs/Pages/Components/Skeleton/Examples/SkeletonPulsateExample.razor
  src/MudBlazor.Docs/Pages/Components/Skeleton/Examples/SkeletonWaveExample.razor
  src/MudBlazor.Docs/Pages/Components/Timeline/Examples/TimelineDotsExample.razor
  src/MudBlazor.Docs/Pages/Features/RTLLanguages/Examples/RTLLanguagesLayoutExample.razor
  src/MudBlazor.Docs/Pages/Index.razor
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor.Docs/wwwroot/images/castle.jpg
  src/MudBlazor.Docs/wwwroot/images/content-template-door.png
  src/MudBlazor.Docs/wwwroot/images/content-template-pilars.png
  src/MudBlazor.Docs/wwwroot/images/door.jpg
  src/MudBlazor.Docs/wwwroot/images/iceland.jpg
  src/MudBlazor.Docs/wwwroot/images/jonny.jpg
  src/MudBlazor.Docs/wwwroot/images/mony.jpg
  src/MudBlazor.Docs/wwwroot/images/mony.png
  src/MudBlazor.Docs/wwwroot/images/pilars.jpg
  src/MudBlazor.Docs/wwwroot/images/sweden.jpg
  src/MudBlazor.Docs/wwwroot/images/toiletvisit.jpg
  src/MudBlazor.Docs/wwwroot/images/toiletvisit.png
  src/MudBlazor.Docs/wwwroot/images/tractor.jpg
  src/MudBlazor.Docs/wwwroot/images/wireframes/wireframe.png
  src/MudBlazor.UnitTests/Components/ImageTests.cs
  src/MudBlazor/Attributes/CategoryAttribute.cs
  src/MudBlazor/Components/Card/MudCardMedia.razor.cs
  src/MudBlazor/Components/Image/MudImage.razor
  src/MudBlazor/Components/Image/MudImage.razor.cs
  src/MudBlazor/Components/Paper/MudPaper.razor
  src/MudBlazor/Components/Paper/MudPaper.razor.cs
  src/MudBlazor/Enums/ObjectFit.cs
  src/MudBlazor/Enums/ObjectPosition.cs
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_image.scss
  src/MudBlazor/Styles/utilities/_cursor.scss
  src/MudBlazor/Styles/utilities/_object.scss
Labels: enhancement, new component, API change

#3788 MudForm : Fix registering of form controls
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormResetTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormShouldRegisterOnlyTopStandaloneFormControlsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/MudFormTestable.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
Labels: bug, PR: needs review

#3793 MudForm : Simplify form with FluentValidation
  src/MudBlazor.Docs/Pages/Components/Form/Examples/FluentValidationComplexExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormValidationOverrideFieldValidationTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Interfaces/IFormComponent.cs
Labels: enhancement, API change

#3900 TextField: add Regex.IPv4 and Regex.IPv6 masks
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/RegexMaskIPv4Example.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/RegexMaskIPv6Example.razor
  src/MudBlazor.Docs/Pages/Features/Masking/MaskingPage.razor
  src/MudBlazor.UnitTests/Utilities/Mask/RegexMaskIPv4Tests.cs
  src/MudBlazor.UnitTests/Utilities/Mask/RegexMaskIPv6Tests.cs
  src/MudBlazor/Utilities/MaskAlgorithms/BaseMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/RegexMask.cs
Labels: enhancement

#3874 Masking: Add DateMask and support Mask in DatePicker
  src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerBasicUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/CustomCharactersExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/DateMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/MultiMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/PatternMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/RegexMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/MaskingPage.razor
  src/MudBlazor.UnitTests/Utilities/Mask/DateMaskTests.cs
  src/MudBlazor.UnitTests/Utilities/Mask/PatternMaskTests.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Utilities/MaskAlgorithms/DateMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/PatternMask.cs
Labels: enhancement

#3966 DOCS: Fix '@' symbol color and fix spaces
  src/MudBlazor.Docs/Styles/core/_markdown.scss
Labels: docs, bug-visual

#3965 Docs: Prevent grid item sizes above 12 or below 1
  src/MudBlazor.Docs/Pages/Components/Grid/Examples/GridBuilderExample.razor
Labels: docs, bug-visual

#3963 MudPopover: Fixes leaks caused by concurrency between OnAfterRenderAsync and DisposeAsync
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
Labels: bug, PR: needs review

#3971 Badge: Fixed default color
  src/MudBlazor.Docs/Pages/Components/Badge/Examples/BadgeBasicExample.razor
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
  src/MudBlazor/Styles/components/_badge.scss
Labels: bug

#3760 Dialog: Fix regression caused by #3252 (issues #3701 #3687)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestInlineDialog.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: bug, enhancement

#4005 Select: fix scroll to selected item when list is long
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectUsageExample.razor
  src/MudBlazor.UnitTests/Mocks/MockScrollServices.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Services/Scroll/ScrollManager.cs
  src/MudBlazor/TScripts/mudScrollManager.js
Labels: bug

#3996 NavMenu: Fix wrong url in turkish culture
  src/MudBlazor.Docs/Models/DocsComponents.cs
  src/MudBlazor.Docs/Shared/NavMenu.razor
Labels: bug

#4024 Autocomplete: Add `DisableSelectOnClick` property
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement

#4018 RegexMask: add predefined Email mask
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/RegexMaskEmailExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/MaskingPage.razor
  src/MudBlazor.UnitTests/Utilities/Mask/RegexMaskEmailTests.cs
  src/MudBlazor/Utilities/MaskAlgorithms/RegexMask.cs
Labels: enhancement, PR: needs review

#4009 MudDialog: Rendering only uncompleted MudDialog tasks
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogRender.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/DialogReference.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor
  src/MudBlazor/Services/DialogService.cs
Labels: bug

#3943 MudFormComponent : Fix field validation when triggered before a required cascading parameter
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FieldValidationWithoutRequiredFormTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
Labels: bug

#3776 `MudAutoComplete`: Fix initial open with server-side, non-async search
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteSyncTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
Labels: bug

#4042 Contributing readme, issue templates: Fix links
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CONTRIBUTING.md
Labels: bug

#3442 FormComponent: Support validation with DataAnnotation attributes without EditContext
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
Labels: bug, PR: needs review

#3539 Dialog: allow to override focus trap behaviour
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogFocusExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogFocusExample_Dialog.razor
  src/MudBlazor/Components/Dialog/MudDialog.razor
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: enhancement, PR: needs tests, API change
