Repository MudBlazor/MudBlazor, pull requests merged in 2022-10, with the labels that each got.

#5455 MudTable: Ensure selection is updated when items are removed
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest8.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug, bug-functional

#4672 MudDatePicker: Add support for custom classes to be applied to specific days
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
Labels: enhancement, API change

#5229 net7: Use native mouse events
  .gitignore
  src/MudBlazor.Docs.Server/_Imports.razor
  src/MudBlazor.Docs.Wasm/_Imports.razor
  src/MudBlazor.Docs/_Imports.razor
  src/MudBlazor.UnitTests.Viewer/_Imports.razor
  src/MudBlazor/Interop/EventHandlers.cs
  src/MudBlazor/_Imports.razor
Labels: enhancement, net7

#5419 MudForm: Only set Validation if For is set
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormAutomaticValidationTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Interfaces/IFormComponent.cs
Labels: bug, bug-functional

#5428 MudDataGrid: Check if property is writable before setting value.
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFormEditTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, bug-functional

#5310 Snackbar: Enable RenderFragment in addition to string message
  src/MudBlazor.Docs/Extensions/DocsViewExtension.cs
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarFromCustomComponentExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarFromRenderFragmentExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarPreventDuplicatesExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarCustomComponent.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarCustomComponentMessageTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarRenderFragmentMessageTest.razor
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageRenderFragment.razor
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageText.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor.cs
  src/MudBlazor/Components/Snackbar/Snackbar.cs
  src/MudBlazor/Components/Snackbar/SnackbarDuplicatesBehavior.cs
  src/MudBlazor/Components/Snackbar/SnackbarMessage.cs
  src/MudBlazor/Components/Snackbar/SnackbarOptions.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
  src/MudBlazor/Interfaces/ISnackbar.cs
Labels: enhancement, API change

#5467 Table: Add the option of triggering edits on button click instead of row click
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableCustomEditButtonRenderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableEditButtonRenderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableInlineEditTestApplyButtons.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/EditButtonContext.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor
  src/MudBlazor/Components/Table/MudTHeadRow.razor
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableApplyButtonPosition.cs
  src/MudBlazor/Components/Table/TableButtonPosition.cs
  src/MudBlazor/Components/Table/TableEditTrigger.cs
  src/MudBlazor/Extensions/TableExtensions.cs
Labels: enhancement, API change

#5454 Docs: Fixed typo in Divider page
  src/MudBlazor.Docs/Pages/Components/Divider/DividerPage.razor
Labels: bug, docs

#5501 MudForm: Assign Validation to Form controls on subscribe
  src/MudBlazor/Components/Form/MudForm.razor.cs
Labels: bug, bug-functional

#5513 Docs: Add workaround for google analytics interop error
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs.Wasm/wwwroot/index.html
  src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml
  src/MudBlazor.Docs/wwwroot/JS/docs.js
Labels: bug, docs

#5496 MudSwipeArea: Add Sensitivity and SwipeDelta
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsPreventDefaultExample.razor
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
Labels: enhancement, API change

#5451 Docs: Installation guide should specify where to register Services
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Labels: docs

#5485 OverflowBehavior: Fix typo in enum (obsoleting misspelled entry)
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Enums/OverflowBehavior.cs
Labels: bug, hacktoberfest, hacktoberfest-accepted

#5564 ScrollManager: Add ScrollIntoView
  src/MudBlazor.UnitTests/Mocks/MockScrollServices.cs
  src/MudBlazor/Services/Scroll/ScrollManager.cs
  src/MudBlazor/TScripts/mudScrollManager.js
Labels: enhancement
