Repository MudBlazor/MudBlazor, pull requests merged in 2022-12, with the labels that each got.

#5873 Build: Update projects to net7
  .vscode/launch.json
  src/MudBlazor.Docs.Compiler/MudBlazor.Docs.Compiler.csproj
  src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Examples.Data/MudBlazor.Examples.Data.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: build

#5893 Docs: Typo in Dropzone #5889
  src/MudBlazor.Docs/Pages/Components/DropZone/DropZonePage.razor
Labels: docs

#5899 Build: New workflows for release pipeline
  .github/workflows/build-test-mudblazor.yml
  .github/workflows/ci-cd.yml
  .github/workflows/deploy-mudblazor-dev.yml
  .github/workflows/deploy-mudblazor-nuget.yml
  .github/workflows/deploy-mudblazor.yml
  .github/workflows/deploy-prod.yml
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs.Wasm/wwwroot/index.html
  src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml
  src/MudBlazor/MudBlazor.csproj
Labels: build

#5903 Table: SelectedItem should fire regardless of EditTrigger setting.
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableSingleSelectionTest1.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: bug

#5897 Popover : Check popoverContentNode null before use
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#5924 Tests: Fix TimePicker validation test
  src/MudBlazor.UnitTests/Components/FormTests.cs
Labels: tests

#5925 Tests: Fix IDialog interface so it can be Moqed
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
Labels: bug, tests

#5930 Docs: Add local development requirements
  CONTRIBUTING.md
Labels: docs

#5931 Build: Don't deploy sites for pre-release packages
  .github/workflows/deploy-mudblazor.yml
  .github/workflows/deploy-trymudblazor.yml
Labels: build

#5851 MudDataGrid: fixed the resizer handle visibility
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnResizerTest.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
Labels: bug, needs changes

#5725 MudDialog: Fix not aligned Toolbar buttons on Dialog header (#5497)
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Styles/components/_dialog.scss
Labels: bug

#5635 MudDataGrid: ServerData initialization fix
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#5449 MudAlert: Variant Filled CloseIcon wrong color (#5436)
  src/MudBlazor/Styles/components/_alert.scss
Labels: bug, needs changes

#5402 Select and Autocomplete: Add ListClass
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: API change

#5963 MudProgress: Fixed border radius for rounded linear progress bar
  src/MudBlazor/Styles/components/_progresslinear.scss
Labels: bug

#5898 BreakpointService: IsMediaSize should will return true for Breakpoint.Always
  src/MudBlazor.UnitTests/Mocks/MockBreakpointService.cs
  src/MudBlazor.UnitTests/Services/BreakpointServiceTests.cs
  src/MudBlazor/Services/ResizeListener/BreakpointService .cs
Labels: bug

#5970 MudAutoComplete: Don't write to console for errors
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#5961 MudTable: Allow row-click without selecting checkbox when in multi-select mode
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiSelectExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelection_CheckboxClickTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelection_IgnoreCheckbox_RowClickTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: enhancement, API change

#5992 MudTable: Fix issue where sub-tables in the last row of a table would not have borders
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#5990 MudTable: Added OverscanCount as a parameter.
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTableBase.cs
Labels: enhancement, API change

#5995 MudDataGrid: Fix CollapseAll not clearing internal variable
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupCollapseAllTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#5985 MudTable: Fixed checkbox state for MultiSelect and (Multi)Grouping
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiGroupingExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiSelectExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelection_CheckboxAndRowClickTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor.cs
  src/MudBlazor/Components/Table/MudTHeadRow.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTableGroupRow.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug, breaking change, API change

#5355 Dialog: Fix Unselectable Content Text
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor
Labels: enhancement

#4856 Rename Cancelled to canceled and forward for non-breaking
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridEditingExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogPassingDataExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogScrollableExample.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/Examples/MessageBoxInlineExample.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/Examples/MessageBoxSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEventCallbacksTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Services/DialogResult.cs
  src/MudBlazor/Services/DialogService.cs
Labels: API change, refactor

#5994 MudTable: Implement "All" option for MudTablePager.
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TabPagerExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagingTest1.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTablePager.razor
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
Labels: enhancement

#6023 Icons: Remove any <Title> tags on generation
  src/MudBlazor/Icons/Material/Filled.cs
  tools/Icons/Update-MudIcons.ps1
Labels: bug

#6044 MudTabs: Add MinimumTabWidth property
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsMinimumTabWidthExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/MinimumWidthTabs.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Styles/components/_tabs.scss
Labels: enhancement, API change

#6058 MudFileUpload: Remove erroneous semi-colons
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor
Labels: refactor

#6065 MudTable: Fix KeyNotFoundException
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug
