Repository MudBlazor/MudBlazor, pull requests merged in 2022-09, with the labels that each got.

#5178 Divider: Fix the color of divider component (#4197)
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Themes/Models/Palette.cs
Labels: bug, bug-visual

#5202 Docs: Fix in Description of MudFormComponent.For
  src/MudBlazor/Base/MudFormComponent.cs
Labels: docs

#5172 TreeView: fix checkbox color not work (#5171)
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
Labels: bug

#5153 Treeview: Fix conflicting iconbutton css selectors
  src/MudBlazor/Styles/components/_treeview.scss
Labels: bug

#3048 MudSwipeArea: Add option to prevent default on touch events.
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsPreventDefaultExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/SwipeAreaPage.razor
  src/MudBlazor.UnitTests/Components/SwipeTests.cs
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
  src/MudBlazor/TScripts/mudElementReference.js
  src/MudBlazor/TScripts/mudHelpers.js
Labels: bug, enhancement, bug-functional, API change

#5210 DataGrid: Update sort indicator from SetSortAsync
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, bug-functional

#4868 Autocomplete: add progress indicator and cancellation token
  src/MudBlazor.Docs.WasmHost/Controllers/AmericanStatesController.cs
  src/MudBlazor.Docs.WasmHost/Controllers/OperationCancelledExceptionFilter.cs
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteCancellationTokenExample.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteProgressExample.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Styles/components/_select.scss
Labels: enhancement, API change

#4650 MudDrawerContainer: Call StateHasChanged after removing Drawer to ensure classes are updated (#4363)
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerContainerTest1.razor
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
Labels: PR: needs changes

#5245 MudTable: Preserve checked state when virtualized and MultiSelection="true"
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionVirtualizedTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
Labels: bug, bug-functional

#5165 MudHighlighter: Support multiple highligted texts
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterUntilNextBoundaryExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithCustomStyleExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithListExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithListMultipleExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/HighlighterPage.razor
  src/MudBlazor.UnitTests/Components/HighlighterTests.cs
  src/MudBlazor/Components/Highlighter/MudHighlighter.razor
  src/MudBlazor/Components/Highlighter/MudHighlighter.razor.cs
  src/MudBlazor/Components/Highlighter/Splitter.cs
Labels: enhancement, API change

#5270 RTLProvider: RightToLeft cascading parameter should be named.
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/TimelineTests.cs
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs
  src/MudBlazor/Components/Chart/MudChart.razor.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
  src/MudBlazor/Components/Pagination/MudPagination.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarProvider.razor.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Components/Timeline/MudTimeline.razor.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Components/Typography/MudText.razor.cs
Labels: enhancement

#5288 MudAutocomplete: Fix FullWidth
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, bug-functional

#5349 Docs: Add page tab to dialog focus trap example
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
Labels: docs

#5348 MudRadioButton: Fixed the content positioning
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioContentPlacementExample.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
Labels: bug

#5273 MudDataGrid: Added new hierarchy feature
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAdvancedExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridChildRowContentTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/UserAttributes/UserAttributesTests.cs
  src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs
  src/MudBlazor/Components/DataGrid/CellContext.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement, API change

#5371 MudDataGrid, MudVirtualize: Add parameter OverscanCount
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs
Labels: enhancement, API change
