Repository MudBlazor/MudBlazor, pull requests merged in 2022-07, with the labels that each got.

#4809 MudMask: Fix crash when navigating quickly on a page containing a mask
  src/MudBlazor/Services/JsEvent/JsEvent.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
Labels: bug, bug-functional

#4819 Fix for dark mode striped table.
  src/MudBlazor/Themes/Models/Palette.cs
Labels: bug

#4832 Docs: fix links in Releases page
  src/MudBlazor.Docs/Pages/Mud/Project/Releases.razor
Labels: bug, docs

#4850 Move _scrollSpy creation into OnInitialized so it's available on time…
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs
Labels: bug, bug-functional

#4702 DataGrid - QuickFilter in GetItemsOfPage
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerDataQuickFilterTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, PR: needs tests, bug-functional

#4857 Fix typos of Initialized
  src/MudBlazor.Docs.WasmHost/Prerender/ICrawlerIdentifier.cs
  src/MudBlazor.Docs.WasmHost/Program.cs
  src/MudBlazor.UnitTests/Components/HiddenTests.cs
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
  src/MudBlazor/TScripts/mudPopover.js
  src/MudBlazor/TScripts/mudResizeObserver.js
  src/MudBlazor/Utilities/MudColor.cs
Labels: bug, refactor

#4841 Checkbox + Radio: Remove top margin on boolean inputs
  src/MudBlazor/Styles/components/_inputcontrol.scss
Labels: bug

#4914 Fix MudChart Donut not centered
  src/MudBlazor.UnitTests/Components/Charts/DonutChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor
  src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
Labels: bug

#4918 MudTextField with mask should respect Readonly property
  src/MudBlazor.UnitTests.Viewer/TestComponents/Mask/ReadonlyMaskedTextFieldTest.razor
  src/MudBlazor.UnitTests/Components/MaskTests .cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
Labels: bug, PR: needs tests

#4913 Add MudTreeView ExpandOnDoubleClick and MudTreeViewItem OnDoubleClick event callback
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewExpandOnDoubleClickExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTest3.razor
  src/MudBlazor.UnitTests/Components/TreeViewTest.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: PR: needs changes

#4854 MudPicker: Add clear button
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: enhancement, PR: needs tests, PR: needs changes

#4970 Corrected name of file to MyNavMenu.razor
  src/MudBlazor.Docs/Pages/Getting Started/Layouts/LayoutsPage.razor
Labels: bug, docs

#4968 MudPicker: Value should reset when Form.Reset() is called.
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormResetTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: waiting for second approval
