Repository MudBlazor/MudBlazor, pull requests merged in 2022-03, with the labels that each got.

#4073 MudProgressLinear: Fix completed bar rendering over child text (#4072)
  src/MudBlazor.UnitTests/Components/ProgressLinearTests.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor
Labels: bug

#4086 Added onfocusin, now keyboard users also get the mudtooltip
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
Labels: bug

#4090 Added missing @ for style in MudFocusTrap
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor
Labels: bug

#4112 Menu and Select: Fix not close on mobile view
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
  src/MudBlazor/Components/Select/MudSelectItem.razor
Labels: bug

#4120 Pagination : Add default English aria-labels
  src/MudBlazor.UnitTests/Components/PaginationTests.cs
  src/MudBlazor/Components/Pagination/MudPagination.razor
Labels: enhancement

#4074 Add AriaLabel params for Adornment Buttons for WCAG Standards
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldAdornmentsExample.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInputAdornment.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: enhancement

#4127 Phase2 issues
  asddsa.txt
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAggregationExample.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
Labels: bug

#4045 MudTable: Fix to include Virtualiation in a grouped rows (#4008)
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicGroupingExample.razor
  src/MudBlazor/Components/Table/MudTable.razor
Labels: enhancement

#4107 Label: added "for" attribute when input "id" attribute is set for WCAG Standards
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DatePickerValidationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerValidationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Field/FieldTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormIsValidTest3.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/NumericFieldTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectRequiredTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/Field/MudField.razor
  src/MudBlazor/Components/Input/MudInputLabel.razor
  src/MudBlazor/Components/Input/MudInputLabel.razor.cs
  src/MudBlazor/Components/InputControl/MudInputControl.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: enhancement

#3556 Tabs: Improve scrolling
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug, PR: needs tests

#4215 DatePicker: Navigate programmatically with GoToDate
  src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerGoToDateExample.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
Labels: enhancement, API change

#4228 MudSlider: Big updates, bunch of new features
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderFilledExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderSizeExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderTickLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderTickMarkExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderValueLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderVerticalExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/SliderPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithContentTest.razor
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/SliderTests.cs
  src/MudBlazor/Components/Slider/MudSlider.razor
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
  src/MudBlazor/Styles/abstracts/_variables.scss
  src/MudBlazor/Styles/components/_pickercolor.scss
  src/MudBlazor/Styles/components/_slider.scss
Labels: bug, enhancement

#4212 CSS Fix: MudTable and MudSimpleTable missing border radius
  src/MudBlazor/Styles/components/_simpletable.scss
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#4272 MudTimePicker: Fix empty string throwing error (#3121)
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug

#4276 DatePicker and TimePicker: Clear shouldn't close the picker when AutoClose is false
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug

#4288 Select: Multiselect Touch Fix
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Select/MudSelectItem.razor
Labels: bug
