Repository MudBlazor/MudBlazor, pull requests merged in 2022-01, with the labels that each got.

#3643 Exclude tsconfig.json from output
  src/MudBlazor/MudBlazor.csproj
Labels: PR: needs review

#3652 Build: Add node requirement to docs.
  CONTRIBUTING.md
Labels: PR: needs review

#3654 MudThemeProvider: Set clearer boundary between MudThemeProvider and M…
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesDarkPaletteExample.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Themes/MudTheme.cs
Labels: bug, PR: needs review

#3647 Added Adornment Color to MudField - resolves issue #3562
  src/MudBlazor.Docs/Pages/Components/Field/Examples/FieldBasicExample.razor
  src/MudBlazor/Components/Field/MudField.razor
  src/MudBlazor/Components/Field/MudField.razor.cs
Labels: bug, enhancement

#3653 NumericField: Fix not updating value from text on blur when debounced
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: bug

#3645 Modify Chart Options to allow for configuring stroke-width - resolves issue #3536
  src/MudBlazor.Docs/Pages/Components/Charts/Chart Types/Examples/LineExample1.razor
  src/MudBlazor/Components/Chart/Charts/Line.razor
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
Labels: enhancement

#3666 Refactor: Only use ES6 language features
  src/MudBlazor/TScripts/mudPopover.js
  src/MudBlazor/TScripts/mudScrollManager.js
Labels: enhancement

#3670 Build: Add JS ES6 compliance check
  .github/workflows/template-pipeline.yml
Labels: enhancement, PR: needs review

#3620 Picker: Add 'context' parameter to 'PickerActions' to simplify creation of actions
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerKeyboardNavigationExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TimePicker/AutoCompleteTimePickerTest.razor
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: enhancement

#3682 Fix wrong redundant height in menu components.
  src/MudBlazor/Styles/components/_menu.scss
Labels: bug, PR: needs review

#3691 NumericField: allow custom formatting, i.e. Format="€0"
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Utilities/BindingConverterTests.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Utilities/BindingConverters/NumericBoundariesConverter.cs
Labels: bug

#3590 Autocomplete: Fix Clear() not clearing when called in a ValueChanged callback
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#3699 ExpansionPanels: Added ExpandAll and CollapseAll methods
  src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
Labels: enhancement, API change

#3713 Landing page: Fix gradients of apps in firefox
  src/MudBlazor.Docs/Styles/pages/_landingpage.scss
  src/MudBlazor.Docs/Theme/Theme.cs
Labels: bug, docs, PR: needs review

#3697 Select: Scroll Fix
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug

#3630 Table: Fix conflicts between MultiSelection callbacks and invalid selection when row enters in edit mode
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: bug

#3762 Docs: Broken Link
  src/MudBlazor.Docs/Pages/Features/Colors/ColorsPage.razor
Labels: bug, docs

#3774 MudTable: Align pager elements vertically
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#3785 Select: Scroll to selected item on open
  src/MudBlazor.UnitTests/Components/BunitTest.cs
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: enhancement

#3775 Breadcrumbs: Adjust icon spacing, vertically center
  src/MudBlazor/Styles/components/_breadcrumbs.scss
Labels: bug

#3786 MudTable, MudDataGrid: Center pager caption text
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#3784 Docs API: Add information from <see cref="..." /> tags
  src/MudBlazor.Docs.Compiler/DocStrings.cs
Labels: bug, docs, enhancement

#3594 MudForm: Add bool parameter override for ResetForm
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormIsTouchedNestedTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
Labels: bug, API change

#3799 Fixed MudSimpleTable uneven horizontal padding
  src/MudBlazor/Styles/components/_simpletable.scss
Labels: bug

#3808 MessageBox: Allow multiline messages with MarkupString
  src/MudBlazor.Docs/Pages/Components/MessageBox/Examples/MessageBoxMarkupContentExample.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/MessageBoxPage.razor
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
  src/MudBlazor/Interfaces/IDialogService.cs
  src/MudBlazor/Services/DialogService.cs
Labels: enhancement

#3480 TextField: Input masking
  src/MudBlazor.Docs.Server/Properties/launchSettings.json
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/BlockMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/CustomCharactersExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/MultiMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/PatternMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/Examples/RegexMaskExample.razor
  src/MudBlazor.Docs/Pages/Features/Masking/MaskCharacterTable.razor
  src/MudBlazor.Docs/Pages/Features/Masking/MaskingPage.razor
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Mask/MaskTwoWayBindingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Mask/MaskedTextFieldTwoWayBindingTest.razor
  src/MudBlazor.UnitTests/Components/MaskTests .cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockJsEvent.cs
  src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs
  src/MudBlazor.UnitTests/Services/JsEventTests.cs
  src/MudBlazor.UnitTests/Utilities/Mask/BlockMaskTests.cs
  src/MudBlazor.UnitTests/Utilities/Mask/MultiMaskTests.cs
  src/MudBlazor.UnitTests/Utilities/Mask/RegexMaskTests.cs
  src/MudBlazor.UnitTests/Utilities/Mask/SimpleMaskTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
  src/MudBlazor/MudBlazor.csproj.DotSettings
  src/MudBlazor/Services/JsEvent/JsEvent.cs
  src/MudBlazor/Services/JsEvent/JsEventOptions.cs
  src/MudBlazor/Services/ServiceCollectionExtensions.cs
  src/MudBlazor/TScripts/mudJsEvent.js
  src/MudBlazor/Utilities/MaskAlgorithms/BaseMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/BlockMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/IMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/MaskChar.cs
  src/MudBlazor/Utilities/MaskAlgorithms/MultiMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/PatternMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/RegexMask.cs
Labels: enhancement, API change
