Repository MudBlazor/MudBlazor, pull requests merged in 2022-08, with the labels that each got.

#4963 Table: Fixes visual bug where NoRecordsContent on stripped table changes background color on hover
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#4999 TimeLineItem: Add DotStyle attribute
  src/MudBlazor.Docs/Pages/Components/Timeline/Examples/TimelineDotsStyleExample.razor
  src/MudBlazor.Docs/Pages/Components/Timeline/TimelinePage.razor
  src/MudBlazor.UnitTests/Components/TimelineTests.cs
  src/MudBlazor/Components/Timeline/MudTimelineItem.razor
  src/MudBlazor/Components/Timeline/MudTimelineItem.razor.cs
Labels: waiting for second approval

#4641 MenuItem: Add optional Icon parameter
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuItemCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuItemIconTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: PR: needs tests

#4995 Breadcrumbs: Fix MaxItems collapsing logic
  src/MudBlazor.Docs/Pages/Components/Breadcrumbs/Examples/BreadcrumbsCollapsedExample.razor
  src/MudBlazor.UnitTests/Components/BreadcrumbTests.cs
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor
Labels: bug, bug-functional

#4948 DefaultConverter: Add AllowThousands flag to all integer type TryParse calls
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor/Utilities/BindingConverters/DefaultConverter.cs
Labels: enhancement

#4998 Table: Add Comparer property to support record types.
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableRecordComparer.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableComparerContextTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRecordComparerTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTrWithValue.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: enhancement, API change

#4973 NumericField: Fix decimal precision and overflows
  src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: bug, bug-functional

#5032 DialogService: Fix for trimming
  src/MudBlazor/Components/Dialog/DialogReference.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
  src/MudBlazor/Interfaces/IDialogService.cs
  src/MudBlazor/Services/DialogService.cs
Labels: bug, bug-functional

#4944 RadioGroup: Add InputClass and InputStyle for backward compatibility
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest1.razor
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
Labels: bug, bug-visual, API change

#4429 SnackbarOptions: Add IconColor and IconSize properties
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarCustomIconExample.razor
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor.cs
  src/MudBlazor/Components/Snackbar/SnackBarMessageState.cs
  src/MudBlazor/Components/Snackbar/SnackbarOptions.cs
Labels: enhancement, API change

#5036 Docs: fix typo
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
Labels: docs

#5061 MudMenuItem: Add IconColor and IconSize properties
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuItemCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuItemIconTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: enhancement, API change

#5060 MudScrollToTop: Fix Exception When Changing Page
  src/MudBlazor/TScripts/mudScrollListener.js
Labels: bug, bug-functional

#5077 NumericField: Resolve nullable issue introduced by #4971
  src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/NumericFieldTest.razor
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: waiting for second approval

#5062 Carousel: Allow to disable swipe gesture
  src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselExample.razor
  src/MudBlazor.UnitTests/Components/CarouselTests.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
Labels: enhancement, API change

#5090 Table: Add ApplyButtonPosition parameter
  src/MudBlazor.Docs.Server/Controllers/AmericanStatesController.cs
  src/MudBlazor.Docs.Server/Controllers/PeriodicTableController.cs
  src/MudBlazor.Docs.Server/Program.cs
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableInlineEditTestApplyButtons.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor
  src/MudBlazor/Components/Table/MudTHeadRow.razor
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableApplyButtonPosition.cs
Labels: enhancement, API change

#3726 Form Inputs: Add OnlyValidateIfDirty to Trigger Validation only if dirty
  src/MudBlazor.Docs/Pages/Components/Form/Examples/ValidateIfDirtyExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/FormPage.razor
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
Labels: enhancement, API change

#5105 JsInteropSerivce: Centralizing JS error handling part one
  src/MudBlazor.UnitTests/Services/IIJSRuntimeExtentionsTests.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
  src/MudBlazor/Services/EventManager/EventManager.cs
  src/MudBlazor/Services/IIJSRuntimeExtentions.cs
  src/MudBlazor/Services/JsEvent/JsEvent.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
  src/MudBlazor/Services/ReseizeObserver/ResizeObserver.cs
  src/MudBlazor/Services/ResizeListener/BreakpointService .cs
  src/MudBlazor/Services/ResizeListener/ResizeBasedService.cs
  src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
  src/MudBlazor/Services/ResizeListener/ResizeService.cs
  src/MudBlazor/Services/Scroll/ScrollListener.cs
  src/MudBlazor/Services/Scroll/ScrollSpy.cs
Labels: enhancement

#4895 Dialog: Fix corrupted Parameters with Multiple open Dialogs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithParameters.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestInlineDialog.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/Dialog/DialogReference.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
  src/MudBlazor/Services/DialogService.cs
Labels: bug, bug-functional

#5133 DataGrid: prevent trimming of FilterOperator
  src/MudBlazor/Components/DataGrid/FilterOperator.cs
Labels: bug, bug-functional

#4962 Select: Update Text when switching to MultiSelection
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest5.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, bug-functional

#5107 Input: Remove tabstop from clear button (#5067)
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Input/MudInput.razor
Labels: enhancement

#5041 Docs: Fixed Typography spelling errors (#5040)
  src/MudBlazor.Docs/Pages/Customization/Theming/Typography.razor
Labels: waiting for second approval

#5125 DataGrid: AggregationDefinition is applied to groups
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridAggregationTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FooterCell.razor
  src/MudBlazor/Components/DataGrid/FooterCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug, bug-functional

#5152 Switch: Add LabelPosition property to specify the label's Start/End position
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchWithLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/SwitchPage.razor
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Enums/LabelPosition.cs
Labels: enhancement, API change

#5016 Docs: Programatically removing a Snackbar
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarRemoveExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
Labels: docs

#5163 Checkbox: Add LabelPosition property to specify the label's Start/End position
  src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxLabelExample.razor
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
Labels: waiting for second approval

#5099 TablePager: Add default English aria-labels
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTablePager.razor
Labels: enhancement

#4985 DataGrid: Added functionality to disable user interaction with MudDataGridPager
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
Labels: On Hold

#4993 DataGrid: Support Guid for FilterDefinition
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterDictionaryGuid.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterGuid.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Filter.razor
  src/MudBlazor/Components/DataGrid/FilterDefinition.cs
  src/MudBlazor/Components/DataGrid/FilterOperator.cs
Labels: PR: needs to merge dev

#5102 PopoverProvider: Throw exception when duplicate providers detected
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDuplicationTest.razor
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Mocks/MockPopoverService.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
  src/MudBlazor/Components/Popover/PopoverOptions.cs
  src/MudBlazor/TScripts/mudPopover.js
Labels: enhancement

#5189 Table: Fix check-all not selecting all items after filtering in multi…
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest7.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: net5, backport
