Repository MudBlazor/MudBlazor, pull requests merged in 2022-04, with the labels that each got.

#4326 Autocomplete: Fix menu staying open on BSS and mobiles
  src/MudBlazor.Docs.Server/Properties/launchSettings.json
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
Labels: bug, bug-functional

#4364 TextField: Focus after clicking clear button (#4354)
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldClearableTest.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
Labels: bug, bug-functional

#4346 Select: Required now also works when MultiSelection="true" (#4328, #4346)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTestRequiredValue.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, bug-functional

#4406 CheckBox, Radio, Switch: UnCheckedColor and CSS cleanup
  src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioGroupColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/RadioPage.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/SwitchPage.razor
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Styles/abstracts/_colors.scss
  src/MudBlazor/Styles/components/_buttongroup.scss
  src/MudBlazor/Styles/components/_checkbox.scss
  src/MudBlazor/Styles/components/_iconbutton.scss
  src/MudBlazor/Styles/components/_switch.scss
Labels: enhancement

#4411 List: Added selected color & fixed parent null issue
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListColorExample.razor
  src/MudBlazor.Docs/Pages/Components/List/ListPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionInitialValueTest.razor
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Styles/components/_select.scss
Labels: bug, enhancement

#4426 Table: Fix check-all not selecting all items after filtering in multiselect mode.
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest7.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug, bug-functional

#4448 Docs: Datepicker API MinDate text fix
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: bug, docs

#4433 Tooltip: Add TabContent render fragment to MudTabPanel
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsContentExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
  src/MudBlazor/Components/Tabs/MudTabPanel.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor
Labels: enhancement, API change

#4425 NavMenu: Fix border stle for RTL layout
  src/MudBlazor/Components/InputControl/MudInputControl.razor
  src/MudBlazor/Styles/components/_navmenu.scss
Labels: bug

#4280 Fix Title property for MudIconButton
  src/MudBlazor.UnitTests.Viewer/TestComponents/Button/IconButtonTest.razor
  src/MudBlazor.UnitTests/Components/ButtonsTests.cs
  src/MudBlazor.UnitTests/Components/ToggleIconButtonTest.cs
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor
Labels: bug

#4479 Popover: fix endless render loop for recursive popups
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
  src/MudBlazor/Components/Render/MudRender.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, bug-functional

#4526 Fixed the spelling error
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
Labels: bug, docs
