Repository MudBlazor/MudBlazor, pull requests merged in 2022-05, with the labels that each got.

#3538 DatePicker: Fixed Values - Don't hide year / date in toolbar
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: enhancement

#4576 Docs: Fix typo in tabs content section
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
Labels: bug, docs

#4185 FormComponent: accessible validation messages
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: enhancement, PR: needs changes

#4076 Select: Fix memory leak caused by key interceptor (#4060)
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
Labels: bug, bug-functional

#4534 MudDropZone: Fix keeping elements order when you drag one out of the MudDropZone (#4311)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneDraggingTestCantDropSecondZoneTest.razor
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
Labels: bug, bug-functional

#4604 fix typo of 'decidce' in https://mudblazor.com/getting-started/instal…
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Labels: bug, docs

#4639 Add Trimming for MudBlazor and rework Icons for the Trimming support
  src/MudBlazor.Docs/Pages/Features/Icons/IconStorage.cs
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor.cs
  src/MudBlazor.UnitTests/Other/WebEventJsonContextTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/DataGrid/Cell.cs
  src/MudBlazor/Components/DataGrid/FilterDefinition.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Icons/Custom/Brands.cs
  src/MudBlazor/Icons/Custom/FileFormats.cs
  src/MudBlazor/Icons/Custom/Uncategorized.cs
  src/MudBlazor/Icons/Icons.cs
  src/MudBlazor/Icons/Material/Filled.cs
  src/MudBlazor/Icons/Material/Outlined.cs
  src/MudBlazor/Icons/Material/Rounded.cs
  src/MudBlazor/Icons/Material/Sharp.cs
  src/MudBlazor/Icons/Material/TwoTone.cs
  src/MudBlazor/Icons/Material/_Obsolete.cs
  src/MudBlazor/Icons/Obsolete/Filled.cs
  src/MudBlazor/Icons/Obsolete/Outlined.cs
  src/MudBlazor/Icons/Obsolete/Rounded.cs
  src/MudBlazor/Icons/Obsolete/Sharp.cs
  src/MudBlazor/Icons/Obsolete/TwoTone.cs
  src/MudBlazor/Icons/Obsolete/_Obsolete.cs
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/Services/EventManager/EventManager.cs
  src/MudBlazor/Services/EventManager/WebEventJsonContext.cs
  src/MudBlazor/Services/JsEvent/JsEvent.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
  src/MudBlazor/Services/ReseizeObserver/ResizeObserver.cs
  src/MudBlazor/Services/ResizeListener/BreakpointService .cs
  src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
  src/MudBlazor/Services/ResizeListener/ResizeService.cs
  src/MudBlazor/Services/Scroll/ScrollListener.cs
  src/MudBlazor/Services/Scroll/ScrollSpy.cs
  src/MudBlazor/Utilities/CodeMessage.cs
  tools/Icons/Update-MudIcons.ps1
Labels: enhancement
