Repository MudBlazor/MudBlazor, pull requests merged in 2022-06, with the labels that each got.

#4692 Autocomplete: Add NoItemsTemplate render fragment
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompletePresentationExtrasExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest7.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement

#4775 Dialog: CancelAll closes all open dialogs
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample_Dialog2.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Labels: enhancement, API change

#4776 MessageBox: Add Keyboard Navigation and Fix Initial Focus
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
Labels: bug, enhancement, PR: needs tests

#4586 Bugfix autocomplete when changing adornment icon
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteAdornmentChange.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug
