Repository MudBlazor/MudBlazor, pull requests merged in 2023-12, with the labels that each got.

#7849 MudTextField: Fix initial height if AutoGrow is enabled (#7839)
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldAutoGrowExample.razor
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: bug

#7872 Tests: Increase BoundingClientRect Coverage
  src/MudBlazor.UnitTests/Services/BoundingClientRectTests.cs
Labels: tests

#7848 Docs: MudFab.Icon is obsolete; Use StartIcon instead
  src/MudBlazor.Docs/Pages/Components/ScrollToTop/Examples/DefaultScrollToTopExample.razor
Labels: docs, PR: needs review

#7890 Build: Fix XML comment warnings
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudItemDropInfo.cs
Labels: bug, PR: needs review

#7892 Inputs: Consistent Naming of the Value Parameter
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxConversionExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxDenseExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxIconExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxIndeterminateExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxReadOnlyExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxSizeExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioContentPlacementExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioDenseExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioGroupColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioGroupExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioReadOnlyDisabledExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioSizeExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchConversionExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchReadOnlyExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchSizeExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchWithIconExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchWithLabelExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/CheckBox/CheckBoxTest3.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/CheckBox/CheckBoxesBindAgainstArrayTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupExceptionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest3.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest4.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest5.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest6.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Switch/MudSwitchTest.razor
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/SelectColumn.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor
  src/MudBlazor/Components/Table/MudTHeadRow.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor
  src/MudBlazor/Components/Table/MudTr.razor
Labels: API change

#7902 Build: Remove nullable annotation warnings
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandAllCollapseAllTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneItemClassSelectorTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithColorPickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithDateRangePickerTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
Labels: bug, build, PR: needs review

#7903 Build: Fix CS8714 warnings by constraining TypeParam to notnull
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs
Labels: bug, build

#7906 Build: Fix some CS0618 obsolete warnings
  src/MudBlazor.UnitTests/Components/CarouselTests.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor
  src/MudBlazor/Components/Chip/MudChip.razor
  src/MudBlazor/Components/NavMenu/MudNavLink.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
Labels: bug, build, PR: needs review

#7910 Build: CS0169 field is never used fix warning by removing
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor.cs
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
Labels: bug, build, PR: needs review

#7912 Build: Revert a change to obsolete prop
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: bug, build

#7909 Build: CS1998 async lacks await fix warnings
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesWatchSystemPreferenceExample.razor
  src/MudBlazor.Docs/Services/LayoutService.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteResetTest.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Extensions/TaskExtensions.cs
Labels: bug, build

#7915 Build: Increase project coverage leniency
  .github/codecov.yml
Labels: build, PR: needs review

#7869 LineChart: Allow to hide graph series
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample4.razor
  src/MudBlazor.Docs/Pages/Components/Charts/LineChartPage.razor
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Models/ChartSeries.cs
  src/MudBlazor/Components/Chart/MudChart.razor.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor
  src/MudBlazor/Components/Chart/Parts/Legend.razor.cs
  src/MudBlazor/Components/Chart/Svg/SvgLegend.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Styles/components/_charts.scss
  src/MudBlazor/Styles/components/_checkbox.scss
Labels: PR: needs review

#7917 Build: Fix keypress obsolete warnings
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: bug, build

#7913 Build: Fix warnings in DataGrid examples and tests
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAdvancedIDictionaryExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterRowAdvancedCustomFilteringTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterRowFilteringTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandAllCollapseAllTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
Labels: bug, build

#7923 Build: Fix warning in datagrid example due to unused fields
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridColumnsPanelExample.razor
Labels: bug, build, PR: needs review

#7924 LineChart: Add a little space between checkbox and text in legend
  src/MudBlazor/Components/Chart/Parts/Legend.razor
Labels: PR: needs review

#7916 Build: Suppress obsolete warnings in source code generator
  src/MudBlazor.SourceCodeGenerator/SourceCodeBuilder.cs
  src/MudBlazor.UnitTests/SourceCodeGenerator/SourceCodeBuilderTest.cs
Labels: bug, build, PR: needs review

#7928 Build: Fix NRE warnings in ThemeProvider
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
Labels: bug, build, PR: needs review

#7925 Build: Suppress IL2075 trimming warning
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Extensions/ExpressionExtensions.cs
Labels: build, PR: needs review

#7929 Build: Suppress obsolete warning for Reset
  src/Directory.Build.props
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: build, v7

#7896 MudAvatarGroup: Add MaxAvatarsTemplate
  src/MudBlazor.UnitTests.Viewer/TestComponents/AvatarGroup/AvatarGroupMaxAvatarsTemplateTest.razor
  src/MudBlazor.UnitTests/Components/AvatarGroupTests.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
Labels: enhancement

#7936 Docs: Fix missing images in BSS
  src/MudBlazor.Docs.Server/wwwroot/images/castle.jpg
  src/MudBlazor.Docs.Server/wwwroot/images/door.jpg
  src/MudBlazor.Docs.Server/wwwroot/images/iceland.jpg
  src/MudBlazor.Docs.Server/wwwroot/images/jonny.jpg
  src/MudBlazor.Docs.Server/wwwroot/images/mony.jpg
  src/MudBlazor.Docs.Server/wwwroot/images/pilars.jpg
  src/MudBlazor.Docs.Server/wwwroot/images/sweden.jpg
  src/MudBlazor.Docs.Server/wwwroot/images/toiletvisit.jpg
  src/MudBlazor.Docs.Server/wwwroot/images/tractor.jpg
Labels: bug

#7939 Docs: Add page for MudCollapse component
  src/MudBlazor.Docs/Pages/Components/Collapse/CollapsePage.razor
  src/MudBlazor.Docs/Pages/Components/Collapse/Examples/CollapseSimpleExample.razor
  src/MudBlazor.Docs/Services/MenuService.cs
Labels: docs

#7940 mudHelpers.js: Add missing closing bracket
  src/MudBlazor/TScripts/mudHelpers.js
Labels: bug

#7934 MudDataGrid: Fix ItemDrop Event Trigger Issue with Disabled ColumnsPanelReordering
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#7309 New Component: MudToggleGroup
  src/MudBlazor.Docs.Server/Properties/launchSettings.json
  src/MudBlazor.Docs/Pages/Components/Toggle/Examples/ToggleBasicsExample.razor
  src/MudBlazor.Docs/Pages/Components/Toggle/Examples/ToggleColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Toggle/Examples/ToggleCustomContentExample.razor
  src/MudBlazor.Docs/Pages/Components/Toggle/Examples/ToggleCustomSelectionStyleExample.razor
  src/MudBlazor.Docs/Pages/Components/Toggle/Examples/ToggleSelectionsExample.razor
  src/MudBlazor.Docs/Pages/Components/Toggle/TogglePage.razor
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleBindMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleBindTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleCustomFragmentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleInitializeTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleToggleSelectionTest.razor
  src/MudBlazor.UnitTests/Components/ToggleTests.cs
  src/MudBlazor.sln
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_toggle.scss
Labels: enhancement, new component

#7876 MudTabs: Rightmost tab is not fully scrolled into view when active
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#7866 MudDatePicker: Setting date null doesn't clear invalid text
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
Labels: bug

#7971 Docs: Add comments explaining the code changes of PR #7866
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
Labels: docs

#7948 New Component: MudToggleGroup
  src/MudBlazor.Docs.Server/Properties/launchSettings.json
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/ButtonGroupPage.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleBasicsExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleCustomContentExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleCustomSelectionStyleExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleSelectionsExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/ToggleGroupPage.razor
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleBindMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleBindTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleCustomFragmentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleInitializeTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleToggleSelectionTest.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor.sln
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
  src/MudBlazor/Enums/SelectionMode.cs
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: new component

#7975 ToggleGroup: Improvements
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleBasicsExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleCustomContentExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleSelectionsExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/ToggleGroupPage.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: bug, PR: needs review
