Repository MudBlazor/MudBlazor, pull requests merged in 2023-04, with the labels that each got.

#6575 MudDrawer: Fix #6154 by not re-rendering on mouse events
  src/MudBlazor/Components/Drawer/MudDrawer.razor
Labels: bug, PR: needs review

#3831 MudTreeViewItem: Add 'BodyContent' which renders instead of text, end text and end icon.
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewBodyContentExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTest5.razor
  src/MudBlazor.UnitTests/Components/TreeViewTest.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: enhancement, needs tests, API change

#6542 IconsPage: remove fixed height to fix footer position (#6532)
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
Labels: docs

#6511 MudForm: Add ReadOnly and Disabled properties
  src/MudBlazor.Docs/Pages/Components/Form/Examples/FormReadonlyDisabledExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/Examples/MudFormExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/FormPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormNestedReadOnlyDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormReadOnlyDisabledTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
  src/MudBlazor/Components/Form/MudForm.razor
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Interfaces/IFormComponent.cs
Labels: enhancement

#6578 MudIcon: Add nullable annotation.
  src/MudBlazor/Components/Icon/MudIcon.razor
  src/MudBlazor/Components/Icon/MudIcon.razor.cs
Labels: PR: needs review

#6579 MudPopover: Fix flickering in delayed bss (#6345)
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
Labels: bug, PR: needs review

#6574 MudSwipeArea: SwipeEventArgs Feature
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsPreventDefaultExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/SwipeArea/SwipeAreaOnSwipeEndTest.razor
  src/MudBlazor.UnitTests/Components/SwipeTests.cs
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Components/SwipeArea/SwipeEventArgs.cs
Labels: enhancement, needs tests

#6534 Docs: Landing page real data
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs.Wasm/wwwroot/index.html
  src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml
  src/MudBlazor.Docs/Extensions/DocsViewExtension.cs
  src/MudBlazor.Docs/Extensions/NumericExtensions.cs
  src/MudBlazor.Docs/Models/DiscordInvite.cs
  src/MudBlazor.Docs/Models/GitHubRepository.cs
  src/MudBlazor.Docs/Models/NugetPackage.cs
  src/MudBlazor.Docs/Pages/Index.razor
  src/MudBlazor.Docs/Services/DiscordApiClient.cs
  src/MudBlazor.Docs/Services/GitHubApiClient.cs
  src/MudBlazor.Docs/Services/NugetApiClient.cs
Labels: docs, enhancement, PR: needs review

#6592 MudDataGrid: Fix ExpandAllGroups/CollapseAllGroups skipping some groups (#6591)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandAllCollapseAllTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#6604 MudDataGrid: Fix GroupExpanded not working
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#6607 MudDataGrid: Filter for Nullable DateTime not working(#6521)
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FieldType.cs
  src/MudBlazor/Components/DataGrid/Filter.cs
  src/MudBlazor/Components/DataGrid/FilterDefinition.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#6368 MudDataGrid: Allow user to use a custom IComparer<object> for sorting
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridCustomSortingExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCustomSortableTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Utilities/NaturalComparerTest.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DataGrid/SortDefinition.cs
  src/MudBlazor/Utilities/NaturalComparer.cs
Labels: enhancement, PR: needs review

#5367 PopoverService: Fix DisposeAsync causing hangs on MAUI
  src/MudBlazor/Components/Popover/MudPopoverService.cs
Labels: bug, dependency bug

#6633 MudBaseInput: Make OnBlurred async
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldOnBlurErrorContenCaughtException.razor
  src/MudBlazor.UnitTests/Components/MaskTests .cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: bug, PR: needs review

#6627 MudDataGrid: Fix filtering modes when using ServerData
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterableServerDataTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerDataColumnFilterMenuTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerDataColumnFilterRowTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Filter.cs
  src/MudBlazor/Components/DataGrid/FilterContext.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#6639 MudDataGrid: Rename AddFilterAsync and ClearFiltersAsync (Breaking Change)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCustomFilteringTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: breaking change, PR: needs review

#6637 MudFormComponent: Deprecate BeginValidate in favor of Async version
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug, PR: needs review

#6647 Docs: Fix possible NullReferenceException and Cross-Origin Request Blocked
  src/MudBlazor.Docs/Extensions/DocsViewExtension.cs
  src/MudBlazor.Docs/Extensions/NumericExtensions.cs
  src/MudBlazor.Docs/Pages/Index.razor
  src/MudBlazor.Docs/Services/DiscordApiClient.cs
  src/MudBlazor.Docs/Services/GitHubApiClient.cs
  src/MudBlazor.Docs/Services/NugetApiClient.cs
Labels: bug, PR: needs review

#6608 MudFormComponent: Add nullable annotation.
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Extensions/ExpressionExtensions.cs
  src/MudBlazor/Utilities/BindingConverters/Converter.cs
Labels: PR: needs review

#6642 MudField: Add nullable annotation.
  src/MudBlazor/Components/Field/MudField.razor
  src/MudBlazor/Components/Field/MudField.razor.cs
Labels: PR: needs review

#6641 MudDivider: Add nullable annotation.
  src/MudBlazor/Components/Divider/MudDivider.razor
Labels: PR: needs review

#6640 MudButtonGroup: Add nullable annotation.
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
Labels: PR: needs review

#6648 MudMenu: Introduce OnClickHandlerAsync to fix #6645
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuErrorContenCaughtException.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: bug

#6666 Introduce MudBlazorGlobal.UnhandledExceptionHandler for handling unawaitable task exceptions
  src/MudBlazor.UnitTests/Extensions/TaskExtensionsTests.cs
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Extensions/TaskExtensions.cs
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/Services/MudBlazorGlobal.cs
Labels: bug

#6667 MudDataGrid: Fix GroupExpanded when using ServerData
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedServerDataTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, PR: needs review

#6489 MudAutocomplete: Fix the highlight of selected item when Strict is set to false (#6412)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteStrictFalseSelectedHighlight.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#6665 MudOverlay: Add nullable annotation.
  src/MudBlazor/Components/Overlay/MudOverlay.razor
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
Labels: PR: needs review

#6664 MudMainContent: Add nullable annotation.
  src/MudBlazor/Components/Main/MudMainContent.razor
Labels: PR: needs review

#6670 MudOverlay: CA2012 Use ValueTasks correctly
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
Labels: bug

#6678 MudVirtualize: Add nullable annotation.
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs
Labels: PR: needs review

#6679 MudSimpleTable: Add nullable annotation.
  src/MudBlazor/Components/TableSimple/MudSimpleTable.razor.cs
Labels: PR: needs review

#6681 MudBooleanInput: Add nullable annotation.
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Interfaces/IForm.cs
  src/MudBlazor/Utilities/BindingConverters/BoolConverter.cs
  src/MudBlazor/Utilities/BindingConverters/Converter.cs
Labels: PR: needs review

#6696 Bug report template had 5.x.x as placeholder
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: bug, PR: needs review

#6693 Form components: Add ResetAsync / ResetValueAsync
  src/MudBlazor.Docs/Pages/Components/Form/Examples/MudFormExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormIsValidTest3.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormResetTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Mask/FormResetMaskTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/MaskTests .cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
  src/MudBlazor/Interfaces/IFormComponent.cs
Labels: enhancement, PR: needs review

#6638 MudSwitch: LabelPosition.Start uses row-reverse instead of RTL
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchWithLabelExample.razor
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: bug, PR: needs review

#6709 Docs: Fix typo in toggle example
  src/MudBlazor.Docs/Pages/Mud/Introduction.razor
Labels: bug

#6701 MudAutocomplete: Fix Race Condition #6475
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteResetTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#6725 Dialog: Add ClassBackground Option to Support Blurred Background
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogBlurryExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogBlurryExample_Dialog.razor
  src/MudBlazor/Components/Dialog/DialogOptions.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Labels: enhancement, PR: needs review

#6720 MudBreakpointProvider: Add nullable annotation.
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor.cs
Labels: PR: needs review

#6727 BreakpointService & ResizeService: KeyNotFoundException fix #3993 #3356 #3698
  src/MudBlazor.Docs/Pages/Components/BreakpointProvider/Examples/BreakpointListenerExample.razor
  src/MudBlazor.Docs/Pages/Components/Hidden/Examples/BrowserResizeEventExample.razor
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor.UnitTests/Components/HiddenTests.cs
  src/MudBlazor.UnitTests/Mocks/MockBreakpointService.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeService.cs
  src/MudBlazor.UnitTests/Services/BreakpointServiceTests.cs
  src/MudBlazor.UnitTests/Services/ResizeBasedServiceTests.cs
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
  src/MudBlazor/Services/ResizeListener/BreakpointService .cs
  src/MudBlazor/Services/ResizeListener/ResizeBasedService.cs
  src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
  src/MudBlazor/Services/ResizeListener/ResizeOptions.cs
  src/MudBlazor/Services/ResizeListener/ResizeService.cs
  src/MudBlazor/Services/ResizeListener/SubscriptionInfo.cs
Labels: bug

#6735 MudChip, MudChipSet: Await where applicable
  src/MudBlazor.UnitTests/Components/ChipSetTests.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
Labels: bug, PR: needs review

#6731 MudHighlighter: Add nullable annotation.
  src/MudBlazor/Components/Highlighter/MudHighlighter.razor.cs
  src/MudBlazor/Components/Highlighter/Splitter.cs
Labels: PR: needs review

#6751 MudDialog: Fix description of the DefaultFocus parameter
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: bug

#6747 MudCollapse: Add nullable annotation and Async AnimationEnd.
  src/MudBlazor.UnitTests/Components/CollapseTests.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
Labels: enhancement

#6700 MudDataGrid: Add drag and drop column reordering
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridColumReorderingExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridDragAndDropTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/FooterContext.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Styles/components/_datagrid.scss
Labels: enhancement

#6773 Obsolete ICommand & CommandParameter
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Base/MudBaseSelectItem.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: PR: needs review

#6753 DateRangePicker: Highlight current date
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: enhancement, needs tests
