Repository MudBlazor/MudBlazor, pull requests merged in 2023-01, with the labels that each got.

#6070 MudTabs: Fix TabPanel collections are not in sync
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/DynamicTabsSimpleExample.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#6120 MudAutocomplete: Fix TextChanged event not sending the text
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#6075 MudTable: Fix 2nd level checkbox default indeterminate state
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiGroupingExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelection_MultiGrouping_DefaultCheckboxStatesTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor.cs
  src/MudBlazor/Components/Table/MudTHeadRow.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableGroupRow.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug

#6071 Docs: added note about Elevation and Outlined properties
  src/MudBlazor.Docs/Pages/Components/Paper/PaperPage.razor
  src/MudBlazor.Docs/Pages/Features/Elevation/ElevationPage.razor
  src/MudBlazor.Docs/Pages/Features/Elevation/Examples/ElevationUsageExample.razor
Labels: docs

#6116 Change background of error when circuit (connection) is lost.
  src/MudBlazor/Styles/core/_blazor.scss
Labels: bug

#5472 MudDivider: Fix fullwidth behavior in flex containers
  src/MudBlazor/Components/Divider/MudDivider.razor
  src/MudBlazor/Styles/components/_divider.scss
Labels: bug

#6051 MudTooltip: Fix Style not forwarded to popover
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipStylingTest.razor
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
Labels: bug

#6083 MudDialog: Added Draggable as a DialogOption.
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogOptionsExample.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/DialogOptions.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Labels: enhancement, API change

#6186 MudTable: Add null check on server data items in FilteredItems
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest6.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
Labels: bug

#6193 MudTable: Enable FluentValidation for TableRowValidator.
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableRowValidator.cs
Labels: enhancement

#6100 MudTabs: Fix incorrect ActivePanelIndex
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/DynamicTabsSimpleExample.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#5531 MudInput: Add Accessibility Titles to Nested Icons
  src/MudBlazor/Components/Input/MudInput.razor
Labels: enhancement

#6225 MudOverlay: Fix Absolute property comment
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
Labels: docs

#6231 MudAutocomplete: Add option to search while an option is selected
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteStrictFalseExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteStrictFalseTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement
