Repository MudBlazor/MudBlazor, pull requests merged in 2023-05, with the labels that each got.

#6777 MudPicker: HandleKeyDown was called twice
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug, PR: needs review

#6301 MudButton: Add ability to set custom rel attribute content
  src/MudBlazor.Docs/Pages/Components/Button/ButtonPage.razor
  src/MudBlazor.Docs/Pages/Components/Button/Examples/ButtonNofollowExample.razor
  src/MudBlazor.UnitTests/Components/ButtonsTests.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudIconButton.razor
Labels: enhancement, PR: needs review

#6801 Remove Parameter attribute from non-component SnackbarOptions class
  src/MudBlazor/Components/Snackbar/SnackbarOptions.cs
Labels: bug

#6752 MudAutoComplete: Add BeforeItemsTemplate and AfterItemsTemplate
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompletePresentationExtrasExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteListEndRendersTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteListStartRendersTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement

#6783 MudTreeView: Don't accept clicks and selection changes for Disabled items
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/DisabledTreeViewTest.razor
  src/MudBlazor.UnitTests/Components/TreeViewTest.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: bug

#6807 LinearProgress: Fix typo in size parameter docs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
Labels: bug, PR: needs review

#6784 MudDataGrid: Fix runtime exception with PageSizeOptions
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
Labels: bug, PR: needs review

#6808 MudToolBar: Allow longer content
  src/MudBlazor/Styles/components/_table.scss
  src/MudBlazor/Styles/components/_toolbar.scss
Labels: PR: needs review

#6798 MudPicker: Add OnClick event (#6797)
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: enhancement

#6828 Docs: Example for nested MudMenu
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuWithNestingExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
Labels: docs

#6805 MudAutocomplete: Fix Value binding not updating
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: needs tests

#6830 MudDropContainer: Fix bad index when dropping item on itself (#5006)
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
Labels: bug, PR: needs review

#6832 Docs: Remove ReadOnly from Form example
  src/MudBlazor.Docs/Pages/Components/Form/Examples/MudFormExample.razor
Labels: docs

#6834 Docs: Toggle MudMini menu icon when menu is open
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
Labels: docs

#6776 MudTable: Fix discrepency with initial RowsPerPage in TablePager
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePageSizeOptionsTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
Labels: bug, PR: needs review

#6864 Build: Temporarily fix SDK at 7.0.203
  src/global.json
Labels: bug, build

#6865 Build: Temporarily fix SDK version on build server
  .github/workflows/deploy-mudblazor-nuget.yml
Labels: bug, build

#6872 Build: Workaround Fix for 7.0.302 SDK bug
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: bug, build

#6873 Build: Remove SDK version fix
  .github/workflows/deploy-mudblazor-nuget.yml
  src/global.json
Labels: bug, build

#6599 MudTimePicker: Fix duplicate hour event in minute mode #6523
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug

#6860 ISnackbar: Add RemoveByKey #6857
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarRemoveByKeyExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
  src/MudBlazor/Interfaces/ISnackbar.cs
Labels: enhancement, PR: needs review

#6870 ScrollToTop: Add OnClick event
  src/MudBlazor.UnitTests.Viewer/TestComponents/Scroll/ScrollToTopTest.razor
  src/MudBlazor.UnitTests/Components/ScrollToTopTests.cs
  src/MudBlazor/Components/ScrollToTop/MudScrollToTop.razor
  src/MudBlazor/Components/ScrollToTop/MudScrollToTop.razor.cs
Labels: enhancement

#6874 PickerToolbar: Fix issue with landscape mode for non-static pickers (#5867)
  src/MudBlazor.UnitTests/Components/PickerToolbarTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor
Labels: bug, PR: needs review

#6885 DataGrid: Fix loading style
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review

#6894 Build: Update AspNetCore Packages
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: build

#6895 Build: Update webcompiler to 3.5.44
  src/MudBlazor.Docs/.config/dotnet-tools.json
  src/MudBlazor.Docs/excubowebcompiler.json
  src/MudBlazor/.config/dotnet-tools.json
  src/MudBlazor/excubowebcompiler.json
Labels: enhancement, build

#6298 Tabs: Add TabHeaderClass property (#5424)
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: enhancement, PR: needs review

#6869 MudToolBar: Optional Wrapping and Appbar compatibility
  src/MudBlazor/Components/AppBar/MudAppBar.razor
  src/MudBlazor/Components/AppBar/MudAppBar.razor.cs
  src/MudBlazor/Components/ToolBar/MudToolBar.razor
  src/MudBlazor/Styles/components/_toolbar.scss
Labels: bug, enhancement, PR: needs review

#6912 MudDataGrid: Removed duplicate code from filter header cell
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
Labels: refactor

#6915 Build: Fix build to 7.0.203 SDK until 7.0.302 SDK is fixed
  .github/workflows/deploy-mudblazor-nuget.yml
Labels: build

#6916 MudToolBar: Add example and test for new WrapContent
  src/MudBlazor.Docs/Pages/Components/ToolBar/Examples/ToolBarWrapContentExample.razor
  src/MudBlazor.Docs/Pages/Components/ToolBar/ToolBarPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToolBar/ToolBarWrapContentTest.razor
  src/MudBlazor.UnitTests/Components/ToolBarTests.cs
  src/MudBlazor/Components/ToolBar/MudToolBar.razor
Labels: enhancement, PR: needs review

#6924 MudColorPicker: Fix/Enable color picker form validation (#6841)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithColorPickerTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
Labels: bug, enhancement

#6945 Fixed dateformat on the Releases-page
  src/MudBlazor.Docs/Pages/Mud/Project/Releases.razor
Labels: bug
