Repository MudBlazor/MudBlazor, pull requests merged in 2023-06, with the labels that each got.

#6942 MudMenuItem: Add AutoClose parameter for controlling closing behavior
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTest1.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: enhancement

#6900 Inputs: Fix order of Value and Text changes for increased stability
  src/MudBlazor/Base/MudBaseInput.cs
Labels: bug

#6981 PopoverService: Remove ConfigureAwait(false)
  src/MudBlazor/Services/Popover/PopoverService.cs
  src/MudBlazor/Utilities/Background/Batch/BatchPeriodicQueue.cs
  src/MudBlazor/Utilities/ObserverManager/ObserverManager.cs
Labels: bug

#6976 MudExpansionPanels: Add nullable annotation.
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
Labels: PR: needs review

#6993 MudProgress: Add nullable annotation.
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
Labels: PR: needs review

#6989 MudHighlighter: Add Markup parameter to render Text using MarkupString
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterUntilNextBoundaryExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/HighlighterPage.razor
  src/MudBlazor.UnitTests/Components/HighlighterTests.cs
  src/MudBlazor/Components/Highlighter/MudHighlighter.razor
  src/MudBlazor/Components/Highlighter/MudHighlighter.razor.cs
Labels: enhancement

#6958 MudNavLink: Fix line-height issue causing UI shift (#5848)
  src/MudBlazor/Styles/components/_navmenu.scss
Labels: bug, PR: needs review

#7016 Fix: Generation of DocStrings fails when generic class with same name exists
  src/MudBlazor.Docs.Compiler/DocStrings.cs
Labels: bug, PR: needs review

#6997 MudImage: Add nullable annotation.
  src/MudBlazor/Components/Image/MudImage.razor.cs
Labels: PR: needs review

#6998 PopoverService: Move StateHasChanged from responsibility
  src/MudBlazor.UnitTests/Services/Popover/Mocks/PopoverObserverMock.cs
  src/MudBlazor.UnitTests/Services/Popover/PopoverServiceTests.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Services/Popover/IPopoverObserver.cs
  src/MudBlazor/Services/Popover/PopoverHolderContainer.cs
  src/MudBlazor/Services/Popover/PopoverHolderOperation.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
Labels: PR: needs review

#7023 MudSelect: Fix loss of focus to receive key strokes
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest6.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, PR: needs review

#7025 ColorPickerTests: Fix flaky test
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
Labels: bug, PR: needs review

#7029 MudDialog: Add generic DialogParameters<T>
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogPassingDataExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogTemplateExample.razor
  src/MudBlazor.UnitTests/Components/Dialog/DialogParametersTests.cs
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/DialogParametersGeneric.cs
Labels: enhancement, PR: needs review

#7044 PopoverService: Fix DisposeAsync deadlock on WPF/WinForm platforms
  src/MudBlazor.UnitTests/Services/Popover/PopoverServiceTests.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
  src/MudBlazor/Utilities/Background/BackgroundWorkerBase.cs
Labels: bug, PR: needs review

#7052 Revert "Build: Fix build to 7.0.203 SDK until 7.0.302 SDK is fixed (#6915)"
  .github/workflows/deploy-mudblazor-nuget.yml
Labels: bug, PR: needs review

#7053 Revert "Build: Workaround Fix for 7.0.302 SDK bug (#6872)"
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: build

#7057 MudDataGrid: Add ability to completely use own IFilterDefinition
  src/MudBlazor.UnitTests/Components/DataGrid/Mocks/CustomFilterDefinitionMock.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/FilterContext.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement

#6890 Docs: Add multiple Accept example to FileUpload.
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadMultipleAcceptExample.razor
Labels: docs

#6991 DataGrid: Allow resizing when overflowing with sticky columns
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridStickyColumnsResizerTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, PR: needs review

#7030 FileUploadTests: set culture to InvariantCulture to remove dependency on local system culture.
  src/MudBlazor.UnitTests/Components/FileUploadTests.cs
Labels: bug, PR: needs review

#7067 SortDefinition: Fix build warning about missing nullable
  src/MudBlazor/Components/DataGrid/SortDefinition.cs
Labels: bug, PR: needs review

#7068 MudBlazor.Docs.Wasm: enable nullable
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.Wasm/Program.cs
Labels: enhancement, PR: needs review

#7071 MudStack: Add nullable annotation.
  src/MudBlazor/Components/Stack/MudStack.razor
  src/MudBlazor/Components/Stack/MudStack.razor.cs
Labels: enhancement

#7072 MudSwipeArea: Add nullable annotation.
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Components/SwipeArea/SwipeEventArgs.cs
Labels: PR: needs review

#7073 MudRTLProvider: Add nullable annotation.
  src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor.cs
Labels: enhancement

#7075 MudContainer: Add nullable annotation.
  src/MudBlazor/Components/Container/MudContainer.razor
Labels: PR: needs review

#7077 MudSlider: Add nullable annotation.
  src/MudBlazor/Components/Slider/MudSlider.razor
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
Labels: PR: needs review

#7024 MudDataGrid: Add Localization Capabilites
  src/MudBlazor.Docs/Pages/Features/Localization/LocalizationPage.razor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationDictionary.razor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationDictionaryCode.html
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationResX.razor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationResXCode.html
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationServiceRegistration.razor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationServiceRegistrationCode.html
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Services/InternalMudLocalizerTests.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
  src/MudBlazor/Services/InternalMudLocalizer.cs
  src/MudBlazor/Services/MudLocalizer.cs
Labels: enhancement

#7079 DataGridServerMultiSelectionTest: use PropertyColumn instead
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerMultiSelectionTest.razor
Labels: bug

#7082 MudCheckBox: Add nullable annotation.
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
Labels: PR: needs review

#7083 MudElement: Add nullable annotation.
  src/MudBlazor.UnitTests/Services/Popover/Mocks/PopoverMock.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Element/MudElement.cs
  src/MudBlazor/Components/Popover/IPopover.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Services/Popover/IMudPopoverHolder.cs
  src/MudBlazor/Services/Popover/MudPopoverHolder.cs
Labels: enhancement

#7084 MudPaper: Add nullable annotation.
  src/MudBlazor/Components/Paper/MudPaper.razor.cs
Labels: enhancement

#7087 MudHidden: Add nullable annotation.
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
Labels: enhancement

#7088 MudSwitch: Add nullable annotation.
  src/MudBlazor/Components/Switch/MudSwitch.razor
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: enhancement

#7090 EventUtil: nullable & XML comments
  src/MudBlazor/Utilities/EventUtil.cs
Labels: enhancement

#7074 ResizeListenerService & BreakpointService: Allow user defined breakpoints
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockBreakpointService.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeService.cs
  src/MudBlazor.UnitTests/Services/BreakpointServiceTests.cs
  src/MudBlazor.UnitTests/Services/ResizeListenerServiceTests.cs
  src/MudBlazor.UnitTests/Services/ResizeOptionsTests.cs
  src/MudBlazor/Extensions/ResizeOptionsExtensions.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/ResizeListener/BreakpointGlobalOptions.cs
  src/MudBlazor/Services/ResizeListener/BreakpointService .cs
  src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
  src/MudBlazor/Services/ResizeListener/ResizeOptions.cs
Labels: bug

#7096 MudTimeline: Add nullable annotation
  src/MudBlazor/Components/Timeline/MudTimeline.razor.cs
  src/MudBlazor/Components/Timeline/MudTimelineItem.razor
  src/MudBlazor/Components/Timeline/MudTimelineItem.razor.cs
Labels: enhancement, PR: needs review

#7095 MudToolBar: Add nullable annotation
  src/MudBlazor/Components/ToolBar/MudToolBar.razor
Labels: enhancement, PR: needs review

#7097 MudThemeProvider: Add nullable annotation
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
Labels: enhancement, PR: needs review

#7104 Localization: fix net6.0 dependencies
  src/MudBlazor/MudBlazor.csproj
Labels: bug, PR: needs review

#7105 PopoverService: Clear all observers on DisposeAsync & nits
  src/MudBlazor.UnitTests/Services/Popover/PopoverServiceTests.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Services/Popover/IPopoverObserver.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
Labels: bug

#7086 MudForm: Remove child form from parent form on Dispose
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithChildForm.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
Labels: bug, PR: needs review

#7113 MudSkeleton: Add nullable annotation.
  src/MudBlazor/Components/Skeleton/MudSkeleton.razor
  src/MudBlazor/Components/Skeleton/MudSkeleton.razor.cs
Labels: enhancement

#7114 MudScrollToTop: Add nullable annotation.
  src/MudBlazor/Components/ScrollToTop/MudScrollToTop.razor.cs
Labels: enhancement

#7124 MudPagination: Add nullable annotation.
  src/MudBlazor/Components/Pagination/MudPagination.razor.cs
Labels: enhancement

#7125 MudPageContentNavigation: Add nullable annotation.
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentSection.cs
Labels: enhancement

#7126 MudBreadcrumbs: Add nullable annotation.
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbItem.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbLink.razor
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbSeparator.razor
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor.cs
Labels: enhancement

#6430 DateRangePicker: Clearable
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DateRangePickerUsageExample.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor.cs
Labels: enhancement, PR: needs review

#7127 MudDatePicker: Fix ArgumentOutOfRangeException (#7120)
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: bug

#7131 Popover: Fix "Cannot read properties of null"(JS)
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, PR: needs review

#7109 Make FilterDefinition compatible with EF Core
  src/MudBlazor/Components/DataGrid/DataGridFilterCaseSensitivity.cs
  src/MudBlazor/Components/DataGrid/Definition/FilterDefinition.cs
  src/MudBlazor/Components/DataGrid/FilterExpressionGenerator.cs
Labels: bug, enhancement, PR: needs review
