Repository MudBlazor/MudBlazor, pull requests merged in 2023-11, with the labels that each got.

#7738 Docs: fix typo in overview page
  src/MudBlazor.Docs/Pages/Components/Overview/OverviewPage.razor
Labels: docs

#7733 MudBaseButton: Add documentation for the ClickPropagation property.
  src/MudBlazor/Base/MudBaseButton.cs
Labels: enhancement, PR: needs review

#7737 MudAutoComplete: Add ListItemClass
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement, PR: needs review

#7720 MudFileUpload: Improve validation in MudForm
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadAppendMultipleExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadButtonExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropCustomScenarioExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropWithFormValidationExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadEventOptionsExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadMultipleAcceptExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadSelectedTemplateExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadValidationExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/FileUploadPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadAppendMultipleTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadButtonTemplateContextTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadButtonTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadFormValidationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadMultipleFilesTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadOnFilesChangedTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormReadOnlyDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithFileUploadAndButtonTemplateContextTest.razor
  src/MudBlazor.UnitTests/Components/FileUploadTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/FileUpload/FileUploadButtonTemplateContext.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
Labels: enhancement, PR: needs review

#7780 BrowserViewportService: Ignore subscription when disposed
  src/MudBlazor.UnitTests/Services/Browser/BrowserViewportServiceTests.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
Labels: bug

#7802 Build: Move global.json so it used in all repo ops
  global.json
Labels: bug, PR: needs review

#7806 Fix html hidden attribute is being overridden
  src/MudBlazor/Styles/utilities/layout/_visibility.scss
Labels: bug, PR: needs review

#7809 MudMenuItem: Don't "click" when scrolling menu on touch devices (#7262)
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: bug, PR: needs review

#7830 Deps: Update net6 libraries
  src/MudBlazor/MudBlazor.csproj
Labels: dependency

#7831 Deps: Update net7 libraries
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: dependency
