Repository MudBlazor/MudBlazor, pull requests merged in 2023-08, with the labels that each got.

#7289 Docs: Fixed content security policy for Carbon Ads
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs.Wasm/wwwroot/index.html
  src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml
Labels: docs, PR: needs review

#7294 Doc: Fix wrong z-index order in themeing doc ( #6707)
  src/MudBlazor.Docs/Pages/Customization/Theming/ZIndex.razor
Labels: bug, docs

#7303 MudColor: Change ToString default mode to RGBA (#7275)
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: bug

#7308 MudDataGrid: Fix CurrentPage not working (#7267)
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
Labels: bug

#6547 MudDataGrid: New parameter "SelectOnRowClick"
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement

#7290 MudMenu: Add IsOpen property (#7266)
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: enhancement

#7293 MudTable: Add doc for default column sorting direction and allow unsorted
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
Labels: docs

#7331 MudFocusTrap: Add nullable annotation.
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs
Labels: enhancement

#7333 Prerendering: Check if JSRuntime is available
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverBase.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#6809 Optimization: Replace .Count() > 0 with .Any()
  src/MudBlazor.Docs/Components/DocsApi.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor
Labels: PR: needs review

#7340 MudInputControl: Add nullable annotation.
  src/MudBlazor/Components/InputControl/MudInputControl.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
Labels: enhancement

#7327 Docs: Add docs page for MudSpacer (#5577)
  src/MudBlazor.Docs/Pages/Components/Spacer/Examples/SpacerBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Spacer/SpacerPage.razor
  src/MudBlazor.Docs/Services/MenuService.cs
Labels: docs

#7174 TimePicker: Added MinuteSelectionStep Parameter
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerStepExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/TimePickerPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TimePicker/SimpleTimePickerTest.razor
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: enhancement, PR: needs review

#7366 MudRadio: Add nullable annotation.
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor/Components/Radio/IMudRadioGroup.cs
  src/MudBlazor/Components/Radio/MudRadio.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
Labels: enhancement

#7342 Docs: Support dark mode loading screen depending on user settings
  src/MudBlazor.Docs.Wasm/wwwroot/index.html
  src/MudBlazor.Docs/wwwroot/JS/docs.js
Labels: docs, enhancement

#7345 Refactor charts, BarChart and LineChart layout fixes
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor
  src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Charts/Pie.razor.cs
  src/MudBlazor/Components/Chart/Interpolation/ILineInterpolator.cs
  src/MudBlazor/Components/Chart/Interpolation/NoInterpolation.cs
Labels: bug, needs changes, PR: needs review

#7295 MudDatePicker: Solves CSP JavaScript issues
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockJsApiService.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/JsApiService.cs
  src/MudBlazor/TScripts/mudWindow.js
Labels: bug

#7380 MudTextField: Fix InputMode not propagated (#4790)
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: bug, PR: needs review

#4728 MudBreadcrumbs: Change from List to IReadOnlyList
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor.cs
Labels: breaking change, API change, v7

#7384 MudTable: Fix the shifting of striped rows when loading
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableLoadingTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
Labels: bug

#7343 Buttons: Add ClickPropagation parameter
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/Element/MudElement.cs
Labels: enhancement

#7387 MudAutocomplete: Fix double scrollbars with Before/AfterItemsTemplate
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteListBeforeAndAfterRendersWithItemsTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
Labels: bug

#7373 Workflow: increase deploy-trymudblazor sleep time to 10m
  .github/workflows/deploy-trymudblazor.yml
Labels: build, PR: needs review

#7401 Support negative y axes in line and bar charts
  src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/ChartsWithCustomGraphicsTest.razor
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
Labels: enhancement, PR: needs review

#7402 MudTimeline: Make horizontal layout responsive
  src/MudBlazor/Styles/components/_timeline.scss
Labels: PR: needs review

#7400 DebouncedTextFieldFormatChangeRerenderTest: fix culture issue on non-english locales
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/DebouncedTextFieldFormatChangeRerenderTest.razor
Labels: bug, PR: needs review

#7393 MudTable: Remove double border when a footer is used
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review

#7424 MudDropZone: Fix for nested drop zones by stopping event propagation
  src/MudBlazor.Docs/Pages/Components/DropZone/DropZonePage.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneNestedZonesExample.razor
  src/MudBlazor/Components/DropZone/MudDropZone.razor
Labels: bug, enhancement

#7427 Buttons: Add nullable annotation.
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Button/MudToggleIconButton.razor
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
Labels: enhancement

#7428 MudCard: Add nullable annotation.
  src/MudBlazor/Components/Card/MudCard.razor.cs
  src/MudBlazor/Components/Card/MudCardActions.razor.cs
  src/MudBlazor/Components/Card/MudCardContent.razor.cs
  src/MudBlazor/Components/Card/MudCardHeader.razor
  src/MudBlazor/Components/Card/MudCardHeader.razor.cs
  src/MudBlazor/Components/Card/MudCardMedia.razor.cs
Labels: PR: needs review

#7429 Snackbar: Improve trimming exclusion
  src/MudBlazor/Components/Snackbar/SnackbarMessage.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
  src/MudBlazor/Interfaces/ISnackbar.cs
Labels: bug

#7406 MudChip, MudAvatar: Fix visual bug
  src/MudBlazor.Docs/Pages/Components/Chip/ChipPage.razor
  src/MudBlazor.Docs/Pages/Components/Chip/Examples/ChipAvatarExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Chip/ChipAvatarContentTest.razor
  src/MudBlazor.UnitTests/Components/ChipTests.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/Chip/MudChip.razor
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Styles/components/_avatar.scss
  src/MudBlazor/Styles/components/_chip.scss
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Themes/Models/PaletteDark.cs
Labels: bug, enhancement

#7383 MudDataGrid: Fix for Guid column filtering (#7381)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFiltersTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Filter.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug, PR: needs review

#7391 MudPicker: Add parameter ImmediateText to update Text while typing (#7390)
  src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerTextParseExample.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/PickerTests.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: bug, needs tests

#7441 PopoverService: do not call JS during OnInitializedAsync
  src/MudBlazor.UnitTests/Mocks/MockPopoverServiceV2.cs
  src/MudBlazor.UnitTests/Services/Popover/PopoverServiceTests.cs
  src/MudBlazor/Services/Popover/IPopoverService.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
Labels: bug

#7447 MudFileUpload: Update summary for MaximumFileCount to better convey its intention (#7227)
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
Labels: bug, PR: needs review
