Repository MudBlazor/MudBlazor, pull requests merged in 2023-02, with the labels that each got.

#5798 MudThemeProvider: Added sudo css selector for generated theme (5781)
  src/MudBlazor.Docs.Wasm/wwwroot/sitemap.xml
  src/MudBlazor.Docs/Pages/Customization/Theming/Overview.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/SudoCss.razor
  src/MudBlazor.Docs/Services/MenuService.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Themes/Models/PseudoCss.cs
  src/MudBlazor/Themes/MudTheme.cs
Labels: enhancement, API change

#6040 MudButton: Add IconSize property
  src/MudBlazor.Docs/Pages/Components/Button/ButtonPage.razor
  src/MudBlazor.Docs/Pages/Components/Button/Examples/ButtonSizeExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Button/ButtonSizeIconSizeTest.razor
  src/MudBlazor.UnitTests/Components/ButtonsTests.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudButton.razor.cs
Labels: enhancement, API change

#5673 MudSwitch: Add Size Parameter
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchWithLabelExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Switch/MudSwitchTest.razor
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Styles/components/_switch.scss
Labels: enhancement, API change

#6268 MudSwitch: Show Validation ErrorText (#6247)
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: enhancement

#6307 Docs: MudSwitch - Added a Size section and removed size from the label section
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchSizeExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchWithLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/SwitchPage.razor
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
Labels: docs

#6308 Fix NullReferenceException in ResizeOptions equality logic #6128
  src/MudBlazor.UnitTests/Services/ResizeOptionsTests.cs
  src/MudBlazor/Services/ResizeListener/ResizeOptions.cs
Labels: bug

#6304 Tabs: Fix scroll buttons not working on low width (#5212)
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#4132 MudDialog: CSS fix for scroll when size is greater than view height
  src/MudBlazor/Styles/components/_dialog.scss
Labels: bug

#6344 MudPicker: Fix flickering in delayed BSS. (#5450)
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
Labels: bug

#6377 MudCheckbox: Use flex-row-reverse instead of mud-rtl for label positioning
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
Labels: bug, PR: needs review

#6374 MudTable: Fix V3022 warning
  src/MudBlazor/Components/Table/MudTable.razor
Labels: bug

#6396 Autocomplete: Correct summary for Strict
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: PR: needs review

#6382 Avatar: Refactor Image support
  src/MudBlazor.Docs/Pages/Components/Avatar/AvatarPage.razor
  src/MudBlazor.Docs/Pages/Components/Avatar/Examples/AvatarImageExample.razor
  src/MudBlazor.UnitTests/Components/AvatarTests.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Styles/components/_avatar.scss
Labels: enhancement

#6390 Dialog: Fix issues with nested inline Dialogs
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedInlineExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedInlineExample_Dialog.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestNestedInlineDialog.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Services/DialogService.cs
Labels: bug

#6394 MudCarousel: Fix wrong transition direction when using SelectedIndex (#6392)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Carousel/CarouselTest.razor
  src/MudBlazor.UnitTests/Components/CarouselTests.cs
  src/MudBlazor/Base/MudBaseItemsControl.cs
Labels: bug

#6358 MudMenu: Fix Touch Bubbling Which Causes Other Unwanted Click Event Firing on Mobile Devices
  src/MudBlazor/Components/Menu/MudMenu.razor
Labels: bug

#6339 Update README.md
  README.md
Labels: PR: needs review
