Repository MudBlazor/MudBlazor, pull requests merged in 2023-07, with the labels that each got.

#7089 Themes: nullable & XML comments
  src/MudBlazor.Docs/Pages/Customization/DefaultTheme.razor
  src/MudBlazor/Themes/Models/Breakpoints.cs
  src/MudBlazor/Themes/Models/LayoutProperties.cs
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Themes/Models/PaletteDark.cs
  src/MudBlazor/Themes/Models/PaletteLight.cs
  src/MudBlazor/Themes/Models/PseudoCss.cs
  src/MudBlazor/Themes/Models/Shadow.cs
  src/MudBlazor/Themes/Models/Typography.cs
  src/MudBlazor/Themes/Models/Z-Index.cs
  src/MudBlazor/Themes/MudTheme.cs
Labels: enhancement

#7134 v7: Drop .net6.0 support
  src/MudBlazor/MudBlazor.csproj
Labels: breaking change, v7

#7136 MudBaseButton: Add nullable annotation.
  src/MudBlazor/Base/MudBaseButton.cs
Labels: enhancement

#7137 MudMessageBox: Add nullable annotation.
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
Labels: PR: needs review

#7138 MudCarousel: Add nullable annotation.
  src/MudBlazor/Base/MudBaseBindableItemsControl.cs
  src/MudBlazor/Base/MudBaseItemsControl.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs
Labels: enhancement

#7139 ResizeService & BreakpointService: Obsolete
  src/MudBlazor.Docs/Pages/Components/BreakpointProvider/BreakpointProviderPage.razor
  src/MudBlazor.Docs/Pages/Components/Hidden/Examples/BrowserResizeEventExample.razor
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockBreakpointService.cs
  src/MudBlazor.UnitTests/Mocks/MockBrowserWindowSizeProvider.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeService.cs
  src/MudBlazor.UnitTests/Services/BreakpointServiceTests.cs
  src/MudBlazor.UnitTests/Services/ResizeBasedServiceTests.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/Services/BrowserWindowSizeProvider.cs
  src/MudBlazor/Services/ResizeListener/BreakpointService .cs
  src/MudBlazor/Services/ResizeListener/ResizeBasedService.cs
  src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
  src/MudBlazor/Services/ResizeListener/ResizeService.cs
  src/MudBlazor/Services/ResizeListener/SubscriptionInfo.cs
Labels: PR: needs review

#7140 mudResizeListener.js: Fix cancelListener
  src/MudBlazor/TScripts/mudResizeListener.js
Labels: bug

#7141 Remove Warning on install
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Examples/InstallationTemplateInstallExample.razor
Labels: PR: needs review

#7143 Add SourceLink support
  .github/workflows/deploy-mudblazor-nuget.yml
  src/MudBlazor/MudBlazor.csproj
Labels: enhancement, PR: needs review

#7147 ResizeService & BreakpointService: Fix Obsolete
  src/MudBlazor.UnitTests/Services/SubscriptionInfoTests.cs
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor.cs
  src/MudBlazor/Services/ResizeListener/SubscriptionInfo.cs
Labels: refactor

#7148 MudLayout: Add nullable annotation.
  src/MudBlazor/Components/Layout/MudLayout.razor.cs
Labels: enhancement

#7149 MudRender: Add nullable annotation.
  src/MudBlazor/Components/Render/MudRender.razor
Labels: enhancement

#7150 SetHueSlider: fix flaky test
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
Labels: bug

#7151 Extensions: Add nullable annotation.
  src/MudBlazor/Extensions/DataGridExtensions.cs
  src/MudBlazor/Extensions/DateTimeExtensions.cs
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
  src/MudBlazor/Extensions/EnumExtensions.cs
  src/MudBlazor/Extensions/ExpressionExtensions.cs
  src/MudBlazor/Extensions/KeepInRangeExtensions.cs
  src/MudBlazor/Extensions/MathExtensions.cs
  src/MudBlazor/Extensions/ObjectExtensions.cs
  src/MudBlazor/Extensions/ParameterViewExtensions.cs
  src/MudBlazor/Extensions/StringExtensions.cs
  src/MudBlazor/Extensions/TableExtensions.cs
  src/MudBlazor/Extensions/TaskExtensions.cs
  src/MudBlazor/Extensions/TimeSpanExtensions.cs
  src/MudBlazor/Extensions/WebUnitsExtensions.cs
Labels: enhancement

#7152 MudSparkLine: Add nullable annotation.
  src/MudBlazor/Components/Sparkline/MudSparkLine.razor
Labels: enhancement

#7157 bUnit: fix Tests for 1.21.9 version
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
Labels: dependency, build

#7160 MudDataGrid: Fix flaky data grid test
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
Labels: bug

#7161 Docs: Fix copy-to-clipboard function for certain snippets
  src/MudBlazor.Docs/Components/SectionContent.razor
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
  src/MudBlazor.Docs/Extensions/DocsViewExtension.cs
  src/MudBlazor.Docs/Models/Snippets.cs
  src/MudBlazor.Docs/Services/DocsJsApi.cs
  src/MudBlazor.Docs/wwwroot/JS/docs.js
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockDocsJsApiService.cs
  src/MudBlazor.UnitTests/Mocks/MockJsApiService.cs
  src/MudBlazor/TScripts/mudWindow.js
Labels: bug, docs

#7159 MudForm/MudBaseInput: Fix swallowed user input on `FieldChanged` re-render (#7158)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormAsyncValidationWithFieldChangedSubscriberTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
Labels: bug, needs tests

#7168 Use PackageLicenseExpression instead of PackageLicenseFile in the nug…
  src/MudBlazor/MudBlazor.csproj
Labels: bug, PR: needs review

#7162 MudDataGrid Fix: Added the EditDialogOptions to inline MudDialog for the DataGridEditMode.Form
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEditFormCustomizedDialogTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug, PR: needs review

#7021 MudDataGrid: Fix SingleSelection
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSingleSelectionTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, PR: needs review

#7175 MudLink: Add nullable annotation.
  src/MudBlazor/Components/Link/MudLink.razor.cs
Labels: enhancement

#7176 MudNavMenu: Add nullable annotation.
  src/MudBlazor/Base/MudBaseSelectItem.cs
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor.cs
Labels: enhancement

#7027 MudFileUpload: Add AppendMultipleFiles property
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadAppendMultipleExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/FileUploadPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadAppendMultipleTest.razor
  src/MudBlazor.UnitTests/Components/FileUploadTests.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
Labels: bug, PR: needs review

#7167 Fix DataGrid Select-All behaviour when filtered
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridMultiSelectionTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FooterContext.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, PR: needs review

#7186 MudDrawer: Add nullable annotation.
  src/MudBlazor/Components/Drawer/MudDrawer.razor
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerHeader.razor
Labels: enhancement

#6947 TimePicker: Handle conversion errors
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor.UnitTests/Utilities/BindingConverterTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Utilities/BindingConverters/DefaultConverter.cs
Labels: bug

#7190 MudTable/MudDataGrid: ItemSize parameter for components using Virtualize
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs
Labels: enhancement, PR: needs review

#7194 MudDebouncedInput: Fix swallowed user input on component re-render (#7193)
  src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/DebouncedNumericFieldCultureChangeRerenderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/DebouncedNumericFieldRerenderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/DebouncedTextFieldFormatChangeRerenderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/DebouncedTextFieldRerenderTest.razor
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Input/MudDebouncedInput.cs
Labels: bug, PR: needs review

#7200 MudRangeInput: fix clearable button is misaligned
  src/MudBlazor/Components/Input/MudRangeInput.razor
Labels: bug

#7198 MudDataGrid: Fix when nested property has same name
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridChildPropertiesWithSameNameSortTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridDragAndDropWithDynamicColumnsTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Utilities/Expressions/ExpressionHasherTests.cs
  src/MudBlazor.UnitTests/Utilities/Expressions/PropertyPathTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
  src/MudBlazor/Components/DataGrid/TemplateColumn.cs
  src/MudBlazor/Utilities/Expressions/PropertyPath.cs
Labels: bug, PR: needs review

#7209 Docs: Fix reference type issue on `DropZone` reorder save example (#7191)
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneReorderSaveExample.razor
Labels: bug

#7226 Date/Time Pickers: Add DisableUnderline param like in MudTextField
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: bug

#7207 MudDataGrid: SelectColumn not rendered in DataGrid with enabled edit mode
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEditableWithSelectColumnTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/SelectColumn.razor
Labels: bug

#6483 FileUpload: Fix top margin CSS
  src/MudBlazor/Styles/components/_fileupload.scss
Labels: bug, breaking change, v7

#7244 MudMask: Fix Clearable with non-PatternMasks (#7238)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Mask/DifferentMaskImplementationTest.razor
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
Labels: bug
