Repository MudBlazor/MudBlazor, pull requests merged in 2023-10, with the labels that each got.

#7571 DataGridExamples: Fix item removal when list is empty
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridObservabilityExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridObservabilityTest.razor
Labels: bug

#7579 MudFormComponent: Fix bad test causing invalid operation exception
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
Labels: bug, PR: needs review

#7578 MudFileUpload: Fix validation in MudForm (#7577)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithFileUploadTest.razor
  src/MudBlazor.UnitTests/Components/FileUploadTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Dummy/DummyBrowserFile.cs
  src/MudBlazor.UnitTests/Extensions/IBrowserFileExtensions.cs
  src/MudBlazor.UnitTests/Extensions/InputFileExtensions.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
Labels: bug

#6760 MudDataDrid: Validation errors now prevent changes being committed (#6748)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFormValidationErrorsPreventUpdateTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#7576 MudTable: Fix misaligned loading bar
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableLoadingTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
Labels: bug, PR: needs review

#7613 MudAutocomplete: Fix doubling of the AfterItemsTemplate
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, breaking change

#7602 MudDataGrid: Adjust simple filter width for consistency (#7538)
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#7626 MudForm: Catch all OnTimerComplete errors and log to console.
  src/MudBlazor/Components/Form/MudForm.razor.cs
Labels: bug, PR: needs review

#7637 MudRipple: Show ripple effect based on click position (#157)
  src/MudBlazor/Styles/core/_ripple.scss
  src/MudBlazor/TScripts/mudRipple.js
Labels: enhancement

#7604 ButtonGroupExamples: Fix alignment in split button section
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupSplitButtonExample.razor
Labels: bug, PR: needs review

#7617 ScrollToTopExamples: Correct Setup section button positioning
  src/MudBlazor/Styles/utilities/layout/_position.scss
Labels: bug, PR: needs review

#7353 TestViewer: Better search and other minor tweaks
  src/MudBlazor.UnitTests.Viewer/Pages/Index.razor
  src/MudBlazor.UnitTests.Viewer/Shared/MainLayout.razor
Labels: bug, enhancement, PR: needs review

#7657 MudFormComponent: Update ValidationMessages on EditContext state change
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormComponentUpdateValidationMessagesOnEditContextChangedTest.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormComponentUpdateValidationMessagesOnEditContextChangedTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
Labels: bug

#7663 Docs: Fix typo and broken link (#6386)
  src/MudBlazor.Docs/Pages/Components/Card/Examples/CardHeaderExample.razor
  src/MudBlazor.Docs/Pages/Components/Paper/PaperPage.razor
Labels: bug, docs

#7644 MudTextInput: Add AutoGrow feature (#7631)
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldAutoGrowExample.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: enhancement

#7670 MudTablePager: Fix Vertical Alignment of Select text (#7501, #7507)
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review

#7596 MudSelect: Allow setting Class on various internal elements
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, needs tests

#7411 MudDataGrid: Added Context menu row click
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAdvancedExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEventCallbacksTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement

#7599 MudDropZone: Add ItemClassSelector parameter.
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneItemClassSelectorTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneItemOnItemPickedTest.razor
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
Labels: enhancement

#7651 MudMenuItem: Add OnAction for either click or touch but invoked only once
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuItemActionTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: enhancement, PR: needs review

#7691 MudLineChart: remove Integrate() call because the return not used
  src/MudBlazor/Components/Chart/Interpolation/EndSlopeSpline.cs
  src/MudBlazor/Components/Chart/Interpolation/PeriodicSpline.cs
Labels: enhancement

#7627 MudDataGrid: Remove redundant column menu (#7566)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridRedundantMenuTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
Labels: bug

#7706 MudDataGrid: Fix HierarchyColumn button not clickable on glyph
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
Labels: bug, PR: needs review

#7513 MudForm: Add ResetTouched() to reset IsTouched w/o resetting the form (#7352)
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
Labels: enhancement, PR: needs review

#7705 Docs: Fixed small typo in FormPage.razor
  src/MudBlazor.Docs/Pages/Components/Form/FormPage.razor
Labels: PR: needs review
