Repository MudBlazor/MudBlazor, pull requests merged in 2023-03, with the labels that each got.

#4818 MudDropZone: Add support for Chromium based browsers on Mobile
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs
  src/MudBlazor/TScripts/mudDragAndDrop.js
Labels: enhancement, needs review

#6306 SourceCodeGenerator: Add support for enum source code generation
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.SourceCodeGenerator/Extensions/StringBuilderExtensions.cs
  src/MudBlazor.SourceCodeGenerator/FastEnumDescriptionGenerator.cs
  src/MudBlazor.SourceCodeGenerator/Models/EnumData.cs
  src/MudBlazor.SourceCodeGenerator/Models/EnumMember.cs
  src/MudBlazor.SourceCodeGenerator/MudBlazor.SourceCodeGenerator.csproj
  src/MudBlazor.SourceCodeGenerator/SourceCodeBuilder.cs
  src/MudBlazor.SourceCodeGenerator/Usings.cs
  src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
  src/MudBlazor.UnitTests/SourceCodeGenerator/FastEnumDescriptionGeneratorTest.cs
  src/MudBlazor.UnitTests/SourceCodeGenerator/SourceCodeBuilderTest.cs
  src/MudBlazor.sln
  src/MudBlazor/Attributes/ExcludeFromCodeGeneratorAttribute.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/Carousel/MudCarousel.razor
  src/MudBlazor/Components/Container/MudContainer.razor
  src/MudBlazor/Components/Divider/MudDivider.razor
  src/MudBlazor/Components/Grid/MudGrid.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor
  src/MudBlazor/Enums/InputMode.cs
  src/MudBlazor/Extensions/EnumExtensions.cs
  src/MudBlazor/MudBlazor.csproj
Labels: enhancement, PR: needs review

#6422 Fix .csproj formatting
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: PR: needs review

#6423 Fix analyzer NullReferenceException in old ToDescriptionString, add test scanrio for it.
  src/MudBlazor.UnitTests/Dummy/DummyEnumEmpty.cs
  src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
  src/MudBlazor/Extensions/EnumExtensions.cs
Labels: bug, PR: needs review

#6415 Datagrid: Fix Dialog
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug, PR: needs review

#6425 Fix code formatting in MudDropZone.razor and MudDynamicDropItem.razor
  src/MudBlazor/Components/DropZone/MudDropZone.razor
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor
Labels: PR: needs review

#5999 MudDataGrid : Fixes Select All when using ServerData
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerMultiSelectionTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FooterContext.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#6320 ThemeProvider: Allow watching dark/light system setting
  src/MudBlazor.Docs/Enums/DarkLightMode.cs
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesWatchSystemPreferenceExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Overview.razor
  src/MudBlazor.Docs/Services/LayoutService.cs
  src/MudBlazor.Docs/Services/UserPreferences/UserPreferences.cs
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/TScripts/mudThemeProvider.js
Labels: enhancement

#4665 MudTable: Show loading indicator whenever table loads data from server
  src/MudBlazor/Components/Table/MudTable.razor.cs
Labels: bug

#6446 Docs: Add Kuro to the contribution team
  src/MudBlazor.Docs/Components/MudTeamCard.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
Labels: docs

#6448 Avatar: Fix obsolete workaround for images.
  src/MudBlazor/Components/Avatar/MudAvatar.razor
Labels: PR: needs review

#6418 RadioGroup: Add ReadOnly and Disabled options.
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioReadOnlyDisabledExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/RadioPage.razor
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor/Components/Radio/MudRadio.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Styles/components/_radio.scss
Labels: enhancement

#6447 Docs: correct class name in Snackbar>Configuration
  src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
Labels: docs, PR: needs review

#6438 MudDatePicker: Add disabled functionality for months only picker
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: bug, enhancement

#6441 MudDataGrid: Fix missing content/error in Cell edit mode for HierarchyColumn (#6024)
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridDetailRowExample.razor
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#6338 MudDatePicker: Add disabling months if day is fixed (#6336)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/SimpleMudDatePickerTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: enhancement, PR: needs review

#6455 Docs: Fix release page and roadmap page
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs.Wasm/wwwroot/index.html
  src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml
  src/MudBlazor.Docs/Pages/Mud/Project/Releases.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Roadmap.razor
  src/MudBlazor.Docs/Styles/pages/_releases.scss
Labels: bug, enhancement

#6464 MudBaseInput: Obsolete OnKeyPress, to be removed in v7
  src/MudBlazor/Base/MudBaseInput.cs
Labels: PR: needs review

#6387 Autocomplete: Fix Autocomplete opening on Reset
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#6151 MudDialog: Change OnBackdropClick Action to EventCallback
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Labels: enhancement

#6470 MudTable: Add filtered items cache for each render.
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
Labels: bug

#6421 MudDataGrid: Improve nullability, encapsulation and some nits
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
  src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
  src/MudBlazor.UnitTests/Other/TypeIdentifierTests.cs
  src/MudBlazor/Components/DataGrid/AggregateDefinition.cs
  src/MudBlazor/Components/DataGrid/Cell.cs
  src/MudBlazor/Components/DataGrid/CellContext.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/DataGridColumnResizeService.cs
  src/MudBlazor/Components/DataGrid/DataGridRowClickEventArgs.cs
  src/MudBlazor/Components/DataGrid/ExpressionModifier.cs
  src/MudBlazor/Components/DataGrid/FieldType.cs
  src/MudBlazor/Components/DataGrid/Filter.cs
  src/MudBlazor/Components/DataGrid/FilterContext.cs
  src/MudBlazor/Components/DataGrid/FilterDefinition.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/FilterOperator.cs
  src/MudBlazor/Components/DataGrid/FooterContext.cs
  src/MudBlazor/Components/DataGrid/GridState.cs
  src/MudBlazor/Components/DataGrid/GroupDefinition.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
  src/MudBlazor/Components/DataGrid/SortDefinition.cs
  src/MudBlazor/Components/DataGrid/TemplateColumn.cs
  src/MudBlazor/Components/DataGrid/TypeIdentifier.cs
  src/MudBlazor/Extensions/DataGridExtensions.cs
  src/MudBlazor/Extensions/EnumExtensions.cs
Labels: bug

#6495 MudDataGrid: Sorting and filtering performance improvements.
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
Labels: bug

#6518 BaseInput: Validation should not run on blur when ReadOnly = true.
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
Labels: bug

#6519 Theming: Make all Palette properties virtual
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesCustomExample.razor
  src/MudBlazor.Docs/Theme/Theme.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Themes/Models/PaletteLight.cs
  src/MudBlazor/Themes/MudTheme.cs
Labels: enhancement

#6539 MudAlert: Add nullable annotation.
  src/MudBlazor/Components/Alert/AlertTextPosition.cs
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
Labels: PR: needs review

#6541 Fixes MudDataGrid NullReferenceExeption
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFormatTest.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug, PR: needs review

#6540 MudAppBar: Add nullable annotation
  src/MudBlazor/Components/AppBar/MudAppBar.razor.cs
Labels: PR: needs review

#6515 MudDataGrid: Make AggregateDefinition work with nullable values and cover with tests
  src/MudBlazor.UnitTests/Components/DataGrid/AggregateDefinitionTests.cs
  src/MudBlazor.UnitTests/Utilities/Expressions/ExpressionHasherTests.cs
  src/MudBlazor/Components/DataGrid/AggregateDefinition.cs
  src/MudBlazor/Utilities/Expressions/ExpressionHasher.cs
Labels: bug, PR: needs review

#6554 MudBadge: Add nullable annotation.
  src/MudBlazor/Components/Badge/MudBadge.razor
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
Labels: enhancement

#6557 MudDatagrid: Fix grouping to work with filtered items cache.
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#6563 MudComponentBase: Add explicit IMudStateHasChange.StateHasChanged
  src/MudBlazor.Docs/Components/DocsPage.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogThatUpdatesItsTitle.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithOnBackdropClickEvent.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithParameters.razor
  src/MudBlazor.UnitTests/Components/ChipTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/PageContentNavigationTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/DataGridColumnResizeService.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverService.cs
  src/MudBlazor/Components/Render/MudRender.razor
  src/MudBlazor/Interfaces/IMudStateHasChanged.cs
Labels: enhancement, PR: needs review

#6561 MudDropZone: Add nullable annotation and fix #6551, #4695.
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Components/DropZone/MudDragAndDropIndexChangedEventArgs.cs
  src/MudBlazor/Components/DropZone/MudDragAndDropItemTransaction.cs
  src/MudBlazor/Components/DropZone/MudDragAndDropTransactionFinishedEventArgs.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs
  src/MudBlazor/Components/DropZone/MudItemDropInfo.cs
Labels: bug, PR: needs review

#6543 MudAvatar: Add nullable annotation
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
Labels: PR: needs review

#6571 MudTabs: Use RenderFragments explicitly
  src/MudBlazor/Components/Tabs/MudDynamicTabs.razor
Labels: bug, PR: needs review

#6572 FileUpload: Add Disabled property
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadButtonExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/FileUploadPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Button/ButtonsNestedDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadDisabledTest.razor
  src/MudBlazor.UnitTests/Components/ButtonsTests.cs
  src/MudBlazor.UnitTests/Components/FileUploadTests.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
Labels: enhancement
