Repository MudBlazor/MudBlazor, pull requests merged in 2023-09, with the labels that each got.

#7444 MudDataGrid: #7440 Fix new groups doesnt respect GroupExpanded property.
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedFalseAsyncTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedFalseServerDataTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedFalseTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#7459 MudTabs: Fix ActivatePanel ArgumentOutOfRange- and NullReferenceException
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug, PR: needs review

#7463 MudMenu: Add IsOpenChanged event
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuIsOpenChangedTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: enhancement, PR: needs review

#7306 MudTable/MudDataGrid: Fix row background color for mobile view.
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#7472 MudScrollManager: fix scroll lock for touch devices
  src/MudBlazor/Styles/layout/_scroll.scss
  src/MudBlazor/TScripts/mudScrollManager.js
Labels: bug

#7497 Popover: add Legacy mode (uses old MudPopoverService)
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverBase.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Popover/MudPopoverHandler.cs
  src/MudBlazor/Services/Popover/PopoverMode.cs
  src/MudBlazor/Services/Popover/PopoverOptions.cs
Labels: enhancement

#7509 MudCarousel: fix incorrect transition description
  src/MudBlazor/Enums/Transition.cs
Labels: bug

#7507 MudTablePager: Fix Vertical Alignment of Select text (#7501)
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review

#7517 MudTimePicker: Fix hour not updating when changed more than once (#7483)
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug, PR: needs review

#5608 MudTable: Fix sticky footer in scss (#2602)
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#7548 MudMask: Handle multiline input case
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Mask/MudMask.razor
Labels: bug

#7412 MudDataGrid: Add ability to mark properties not required during editing (#7325)
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: enhancement, PR: needs review

#7564 MudDatePicker: Retain specific DateTime.Kind when setting undefined kind
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
Labels: bug
