Repository MudBlazor/MudBlazor, pull requests merged in 2024-02, with the labels that each got.

#8110 MudDynamicTabs: Fix disappearing slider with key attribute (#2816)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/DynamicTabsWithKeyTest.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor
Labels: bug, PR: needs review

#8137 MudDrawer: Opening mini drawer pushes MudMainContent to the right (#7775)
  src/MudBlazor/Styles/layout/_main.scss
Labels: bug

#8117 Chart: Fix series coloring issue which restricted specifying more than 20 custom colors (#8099)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/ChartsWithCustomColorsTest.razor
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/DonutChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/PieChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/StackedBarChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor
  src/MudBlazor/Components/Chart/Charts/Donut.razor
  src/MudBlazor/Components/Chart/Charts/Line.razor
  src/MudBlazor/Components/Chart/Charts/Pie.razor
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor
  src/MudBlazor/Components/Chart/Parts/Legend.razor
Labels: bug

#8135 Add X (formerly Twitter) logo to Brands.cs
  src/MudBlazor/Icons/Custom/Brands.cs
Labels: enhancement, PR: needs review

#8150 MudTimePicker: Fix AM|PM (#8032)
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug, PR: needs review

#8158 X Icon Fix
  src/MudBlazor/Icons/Custom/Brands.cs
Labels: bug

#8131 MudBaseInput: Add "ShrinkLabel" parameter that prevents label from moving
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldShrinkLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: enhancement

#8160 MudDataGrid: Make grouping two-way bindable (#8159)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnGroupingTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, PR: needs review

#8178 Skeleton: Allow changes after initialization
  src/MudBlazor.UnitTests/Components/SkeletonTests.cs
  src/MudBlazor/Components/Skeleton/MudSkeleton.razor
  src/MudBlazor/Components/Skeleton/MudSkeleton.razor.cs
Labels: bug, PR: needs review

#8182 Build: Update dotnet packages
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: build

#8177 MudTable : Improve the documentation to customize the pager (#7372)
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TabPagerExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TablePagerExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.Docs/Services/MenuService.cs
Labels: PR: needs review

#8084 DataGrid: Support for sub properties editing
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEditComplexPropertyExpressionTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
Labels: enhancement

#7821 DataGrid: Fix FilterDefinition.Title not updating when selected field is changed
  src/MudBlazor/Components/DataGrid/Filter.cs
Labels: bug

#7765 DataGrid: Add IsOpened property to CellContext (#7432)
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/CellContext.cs
Labels: enhancement

#8188 MudButton: Fix hover effect remaining after touch
  src/MudBlazor/Styles/components/_button.scss
Labels: bug, PR: needs review

#8189 MessageBox: Add "mud-message-box" class
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
Labels: enhancement

#8193 MudTextField: Preserve scroll position while typing with AutoGrow and update when window is resized
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: bug, PR: needs review

#8194 MudMenu: Fix when PositionAtCursor is true and touch is used.
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: bug, PR: needs review

#8201 DataGrid: filter for nullable DateTime is missing in DataGridFilterMode.ColumnFilterRow mode
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnFilterRowPropertyTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
Labels: bug

#7594 MudDataGrid: Do not add duplicate filters
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: needs tests, PR: needs review

#8203 Tests: Fix extra re-render in MudButton tests
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Button/MudButton.razor
Labels: bug, PR: needs review

#7914 MudTable: Retain selection when using ServerData
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest9.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest9.razor.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug

#8212 Fix typo in the CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, PR: needs review

#8231 DataGrid: Fix editing of nullable values such as int?
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCellEditWithNullableChangeTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
Labels: bug

#8232 DialogService: Constrain Dialogs to IComponent instead of ComponentBase
  src/MudBlazor/Interfaces/IDialogService.cs
  src/MudBlazor/Services/DialogService.cs
Labels: enhancement, API change

#8210 PopoverService: Improve performance
  src/MudBlazor.UnitTests/Utilities/AsyncKeyedLocker/AsyncKeyedLockNonPooledTests.cs
  src/MudBlazor.UnitTests/Utilities/AsyncKeyedLocker/AsyncKeyedLockPooledTests.cs
  src/MudBlazor.UnitTests/Utilities/AsyncKeyedLocker/AsyncKeyedLockSynchronizationContext.cs
  src/MudBlazor.UnitTests/Utilities/AsyncKeyedLocker/AsyncKeyedLockTests.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
  src/MudBlazor/Utilities/AsyncKeyedLocker/AsyncKeyedLockDictionary.cs
  src/MudBlazor/Utilities/AsyncKeyedLocker/AsyncKeyedLockOptions.cs
  src/MudBlazor/Utilities/AsyncKeyedLocker/AsyncKeyedLockPool.cs
  src/MudBlazor/Utilities/AsyncKeyedLocker/AsyncKeyedLockReleaser.cs
  src/MudBlazor/Utilities/AsyncKeyedLocker/AsyncKeyedLockTimeoutReleaser.cs
  src/MudBlazor/Utilities/AsyncKeyedLocker/AsyncKeyedLocker.cs
Labels: enhancement

#8235 MudTextField: Remove phantom scrollbars when auto grow is enabled and height is uncapped
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: bug, PR: needs review

#8236 BrowserViewportService: Improve performance
  src/MudBlazor.UnitTests/Services/Browser/BrowserViewportServiceTests.cs
  src/MudBlazor/Interop/ResizeListenerInterop.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/TScripts/mudResizeListener.js
Labels: bug, PR: needs review

#8239 IScrollSpy: Fix DotNetObjectReference instance was already disposed
  src/MudBlazor/Services/Scroll/ScrollSpy.cs
Labels: bug, PR: needs review

#8242 Docs: Fix locale in converter sample page
  src/MudBlazor.Docs/Pages/Features/Converters/Examples/TurkeyTestExample.razor
Labels: bug, PR: needs review

#8247 Revert "MudButton: Fix hover effect remaining after touch"
  src/MudBlazor/Styles/components/_button.scss
Labels: PR: needs review

#8266 MudTable: Fix excessive SelectedItemsChanged callback
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionSelectedItemsChangedTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug
