Repository MudBlazor/MudBlazor, pull requests merged in 2024-03, with the labels that each got.

#8269 Build: Remove custom SASS compiler in favour of original
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: enhancement, build

#8259 MudTabs: Vertical tabs headers now stretch to fill available horizontal space
  src/MudBlazor/Styles/components/_tabs.scss
Labels: bug

#8280 Build: Disable SassCompilerWatcher
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: bug, build, PR: needs review

#8258 Introduce ParameterState framework to facilitate parameter change logic and avoid BL0007
  CONTRIBUTING.md
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridColumnsPanelExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnChooserTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnHiddenTest.razor
  src/MudBlazor.UnitTests/Components/CollapseTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/State/Mocks/ParameterChangedHandlerMock.cs
  src/MudBlazor.UnitTests/State/ParameterSetTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Extensions/ParameterViewExtensions.cs
  src/MudBlazor/State/IParameterChangedHandler.cs
  src/MudBlazor/State/IParameterComponentLifeCycle.cs
  src/MudBlazor/State/ParameterChangedLambdaHandler.cs
  src/MudBlazor/State/ParameterChangedLambdaTaskHandler.cs
  src/MudBlazor/State/ParameterSet.cs
  src/MudBlazor/State/ParameterState.cs
  src/MudBlazor/State/ParameterStateOfT.cs
Labels: enhancement

#7389 Localization: Implement ILocalizationInterceptor
  src/MudBlazor.Docs/Extensions/ResourceSetExtensions.cs
  src/MudBlazor.Docs/Pages/Features/Localization/LocalizationPage.razor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationInterceptor.razor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationInterceptorCode.html
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Services/Localization/DefaultLocalizationInterceptorTests.cs
  src/MudBlazor.UnitTests/Services/Localization/InternalMudLocalizerTests.cs
  src/MudBlazor.sln.DotSettings
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Localization/AbstractLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/DefaultLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/ILocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
  src/MudBlazor/Services/Localization/MudLocalizer.cs
Labels: enhancement

#8305 BrowserViewportService & PopoverService: Decrease PoolSize and set PoolInitialFill
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/Services/Popover/PopoverOptions.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
Labels: enhancement

#8306 Localization: Extend AbstractLocalizationInterceptor to be less specific.
  src/MudBlazor/Services/Localization/AbstractLocalizationInterceptor.cs
Labels: enhancement

#7771 DataGridRowValidator : Mark the Model property as virtual
  src/MudBlazor/Components/DataGrid/DataGridRowValidator.cs
Labels: enhancement

#8309 Refactor: Return 'Task' instead.
  src/MudBlazor.Docs/Components/DocsPage.razor.cs
  src/MudBlazor.Docs/Components/SectionHeader.razor.cs
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressCircularDeterminateExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearBufferExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearDeterminateExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressLinearVerticalExample.razor
  src/MudBlazor.Docs/Services/RenderQueueService.cs
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: refactor

#7484 DatePicker: Fix PerisanCalender change year issue (#3740)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/PersianDatePickerTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug, PR: needs review

#8321 Build: Update PR auto-reply
  .github/workflows/issue.yml
Labels: PR: needs review

#8319 Fix BlockMask: Adjust Regex generation to allow a strict prefix
  src/MudBlazor.UnitTests.Viewer/TestComponents/Mask/DifferentMaskImplementationTest.razor
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor.UnitTests/Utilities/Mask/BlockMaskTests.cs
  src/MudBlazor/Utilities/MaskAlgorithms/BlockMask.cs
Labels: bug

#8320 MudNumericField: Add missing ShrinkLabel
  src/MudBlazor/Components/NumericField/MudNumericField.razor
Labels: bug

#8322 Docs: TreeView Descriptions and Example Fixes
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewHoverExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
Labels: docs

#8327 MudLineChart: All zero series data no longer throws exception
  src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/LineChartWithZeroValuesTest.razor
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
Labels: bug

#8326 MudNumericField: Fix decrementing from null value
  src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/NumericFieldTest.razor
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: bug

#8328 Docs: Remove any mentions of MudStore / MudAcademy
  src/MudBlazor.Docs/NotificationContent/Announcement_MudBlazorIsHereToStay.razor
  src/MudBlazor.Docs/Pages/Mud/Introduction.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/Footer.razor
  src/MudBlazor.Docs/Shared/LandingLayout.razor
Labels: docs, PR: needs review

#8333 MudBarChart: Single x-axis value no longer throws exception
  src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/BarChartWithSingleXAxisTest.razor
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
Labels: bug

#8343 Build: Fix PR auto-reply
  .github/workflows/issue.yml
Labels: bug, build, PR: needs review

#8281 Various components: Avoid re-renderings from interaction events
  src/MudBlazor.Docs/Pages/Components/Chip/ChipPage.razor
  src/MudBlazor.Docs/Pages/Components/Chip/Examples/ChipClickableExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuOnClickExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/NavMenuPage.razor
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/PaginationTests.cs
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Alert/MudAlert.razor
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/Badge/MudBadge.razor
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/Chip/MudChip.razor
  src/MudBlazor/Components/Link/MudLink.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/NavMenu/MudNavLink.razor
  src/MudBlazor/Components/ScrollToTop/MudScrollToTop.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
Labels: bug, PR: needs review

#8342 MudDateRangePicker: Ignore timestamp when setting day classes
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerPresetRangeWithTimestampTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerPresetWithoutTimestampTest.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug

#8345 Fix Mistaken CSS Reordering
  src/MudBlazor/Styles/MudBlazor.scss
Labels: bug, accidental break, PR: needs review

#8347 Docs: Small refactoring
  src/MudBlazor.Docs/Models/ApiLink.cs
  src/MudBlazor.Docs/Models/DocsComponents.cs
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkServiceEntry.cs
  src/MudBlazor.Docs/Services/ApiLink/IApiLinkService.cs
  src/MudBlazor.Docs/Services/ApiLinkService.cs
  src/MudBlazor.Docs/Services/DiscordApiClient.cs
  src/MudBlazor.Docs/Services/DocsJsApi.cs
  src/MudBlazor.Docs/Services/GitHubApiClient.cs
  src/MudBlazor.Docs/Services/LayoutService.cs
  src/MudBlazor.Docs/Services/Menu/IMenuService.cs
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.Docs/Services/Navigation/DocsNavigationService.cs
  src/MudBlazor.Docs/Services/Navigation/IDocsNavigationService.cs
  src/MudBlazor.Docs/Services/Navigation/NavigationOrder.cs
  src/MudBlazor.Docs/Services/Navigation/NavigationSection.cs
  src/MudBlazor.Docs/Services/Notifications/InMemoryNotificationService.cs
  src/MudBlazor.Docs/Services/Notifications/NotificationAuthor.cs
  src/MudBlazor.Docs/Services/Notifications/NotificationMessage.cs
  src/MudBlazor.Docs/Services/NugetApiClient.cs
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
Labels: docs, refactor

#8348 Docs: DateRangePicker documentation page
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/DateRangePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerActionButtonsExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerBasicUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerEditableExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerFormatExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerMinMaxDateExample.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
Labels: enhancement, PR: needs review

#8358 MudDataGrid: Cleanup
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/FieldType.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
  src/MudBlazor/Components/DataGrid/TypeIdentifier.cs
Labels: refactor

#8361 TreeView: Fix the ParameterView instance has expired.
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewCompareMultiSelectTest.razor
  src/MudBlazor.UnitTests/Components/TreeViewTest.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItemComparer.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItemToggleButton.razor
  src/MudBlazor/Extensions/ParameterViewExtensions.cs
Labels: bug

#8325 PopoverService: Attemp to fix SemaphoreFullException
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Services/Popover/Mocks/PopoverObserverMock.cs
  src/MudBlazor.UnitTests/Services/Popover/PopoverServiceTests.cs
  src/MudBlazor.UnitTests/Utilities/Background/BackgroundWorkerTests.cs
  src/MudBlazor.UnitTests/Utilities/Background/BatchPeriodicQueueTests.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Interop/PopoverJsInterop.cs
  src/MudBlazor/Services/IIJSRuntimeExtentions.cs
  src/MudBlazor/Services/Popover/IPopoverObserver.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
  src/MudBlazor/Utilities/Background/BackgroundWorkerBase.cs
  src/MudBlazor/Utilities/Background/Batch/BatchPeriodicQueue.cs
Labels: bug, PR: needs review

#8366 MudDialog: Change default value of DefaultFocus to "Element" to shift the focus into the dialog.
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: bug, PR: needs review

#8332 Dialog: Add ClassTitle property to enable custom styling of the Title
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogStylingExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogStylingExample_Dialog.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithClassActions.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithClassContent.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithTitleClass.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Labels: enhancement, v7

#8329 MudTextField: Fix scrollbars appearing with AutoGrow on scaled displays due to rounding error
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: bug, PR: needs review

#8369 Buttons: Fix exception doesn't flow to ErrorBoundary.
  src/MudBlazor.UnitTests.Viewer/TestComponents/Button/ButtonErrorContenCaughtException.razor
  src/MudBlazor.UnitTests/Components/ButtonsTests.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
Labels: bug

#8334 Snackbar: Keep visible while touched or hovered
  src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor.cs
  src/MudBlazor/Components/Snackbar/Snackbar.cs
Labels: enhancement, PR: needs review

#8372 BrowserViewportService: Revert #8236 AsyncKeyedLock optimization
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
Labels: bug

#8375 MudLink: Fix exception doesn't flow to ErrorBoundary.
  src/MudBlazor.UnitTests.Viewer/TestComponents/Link/LinkErrorContenCaughtException.razor
  src/MudBlazor.UnitTests/Components/LinkTests.cs
  src/MudBlazor/Components/Link/MudLink.razor
  src/MudBlazor/Components/Link/MudLink.razor.cs
Labels: bug

#8384 ParameterState: Call the handler once when parameters reference the same handler.
  CONTRIBUTING.md
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateSharedHandlerTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/SharedStateHandlerTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/SharedStateHandlerTestComp.razor.cs
  src/MudBlazor.UnitTests/State/ParameterHandlerUniquenessComparerTests.cs
  src/MudBlazor.UnitTests/State/ParameterSetTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor.UnitTests/State/Rule/ParameterMetadataRulesTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/State/IParameterComponentLifeCycle.cs
  src/MudBlazor/State/ParameterHandlerUniquenessComparer.cs
  src/MudBlazor/State/ParameterMetadata.cs
  src/MudBlazor/State/ParameterSet.cs
  src/MudBlazor/State/ParameterState.cs
  src/MudBlazor/State/ParameterStateOfT.cs
  src/MudBlazor/State/Rule/Exclusion/IExclusion.cs
  src/MudBlazor/State/Rule/Exclusion/LambdaExclusion.cs
  src/MudBlazor/State/Rule/ParameterMetadataRules.cs
Labels: enhancement

#8336 Various components: Hide blue tap highlight that occurs on mobile
  src/MudBlazor/Styles/core/_base.scss
Labels: bug

#8026 DataGrid: Throw exception when ServerData and Items are supplied (#8020)
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement, breaking change

#8256 Fix sticky hover effects on mobile
  src/MudBlazor.Docs/Styles/components/_docssection.scss
  src/MudBlazor.Docs/Styles/components/_icons.scss
  src/MudBlazor.Docs/Styles/core/_base.scss
  src/MudBlazor.Docs/Styles/layout/_mainlayout.scss
  src/MudBlazor.Docs/Styles/pages/_announcement.scss
  src/MudBlazor.Docs/Styles/pages/_landingpage.scss
  src/MudBlazor.Docs/Styles/pages/_overview.scss
  src/MudBlazor.Docs/Styles/pages/_wireframes.scss
  src/MudBlazor/Styles/abstracts/_colors.scss
  src/MudBlazor/Styles/components/_breadcrumbs.scss
  src/MudBlazor/Styles/components/_button.scss
  src/MudBlazor/Styles/components/_buttongroup.scss
  src/MudBlazor/Styles/components/_checkbox.scss
  src/MudBlazor/Styles/components/_chip.scss
  src/MudBlazor/Styles/components/_datagrid.scss
  src/MudBlazor/Styles/components/_expansionpanel.scss
  src/MudBlazor/Styles/components/_fab.scss
  src/MudBlazor/Styles/components/_iconbutton.scss
  src/MudBlazor/Styles/components/_input.scss
  src/MudBlazor/Styles/components/_link.scss
  src/MudBlazor/Styles/components/_list.scss
  src/MudBlazor/Styles/components/_navmenu.scss
  src/MudBlazor/Styles/components/_pickercolor.scss
  src/MudBlazor/Styles/components/_pickerdate.scss
  src/MudBlazor/Styles/components/_pickertime.scss
  src/MudBlazor/Styles/components/_radio.scss
  src/MudBlazor/Styles/components/_rating.scss
  src/MudBlazor/Styles/components/_simpletable.scss
  src/MudBlazor/Styles/components/_slider.scss
  src/MudBlazor/Styles/components/_switch.scss
  src/MudBlazor/Styles/components/_table.scss
  src/MudBlazor/Styles/components/_tabs.scss
  src/MudBlazor/Styles/components/_togglegroup.scss
  src/MudBlazor/Styles/components/_treeview.scss
  src/MudBlazor/Styles/core/_blazor.scss
Labels: bug

#8382 DatePicker: Show first selected date when DatePicker is nested
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/WrappedDatePickerTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
Labels: bug

#6129 MudTable: Provide contextual item data when using EditButtonContent
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableCustomEditButtonItemContextRenderTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/EditButtonContext.cs
  src/MudBlazor/Components/Table/MudTr.razor
Labels: enhancement

#8385 Input: Make AutoGrow responsive to parameters & Fix empty line after scrollbar is hidden
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: bug, enhancement

#8393 Docs: Format .scss files
  src/MudBlazor.Docs/Styles/components/_docspage.scss
  src/MudBlazor.Docs/Styles/components/_docssection.scss
  src/MudBlazor.Docs/Styles/components/_icons.scss
  src/MudBlazor.Docs/Styles/components/_mudblazorapp.scss
  src/MudBlazor.Docs/Styles/components/_widthslider.scss
  src/MudBlazor.Docs/Styles/core/_base.scss
  src/MudBlazor.Docs/Styles/core/_carbon.scss
  src/MudBlazor.Docs/Styles/core/_markdown.scss
  src/MudBlazor.Docs/Styles/layout/_mainlayout.scss
  src/MudBlazor.Docs/Styles/pages/_announcement.scss
  src/MudBlazor.Docs/Styles/pages/_landingpage.scss
  src/MudBlazor.Docs/Styles/pages/_overview.scss
  src/MudBlazor.Docs/Styles/pages/_releases.scss
  src/MudBlazor.Docs/Styles/pages/_roadmap.scss
  src/MudBlazor.Docs/Styles/pages/_wireframes.scss
  src/MudBlazor/Styles/components/_tabs.scss
Labels: docs

#8398 Build: Update dotnet libraries
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: dependency

#8404 MudToggleIconButton: Add DisableElevation and ClickPropagation properties
  src/MudBlazor/Components/Button/MudToggleIconButton.razor
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
Labels: enhancement, PR: needs review

#8409 Build: Fix dotnet format warning
  src/MudBlazor.sln
Labels: bug, build, PR: needs review

#8412 MudRadio: Fix Stack overflow caused by recurrence.
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
Labels: bug

#8406 MudTimePicker: Double pad hours like minutes already are
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: bug, PR: needs review

#8405 Use ActionDefault as the base for ActionDefaultHover
  src/MudBlazor/Components/ThemeProvider/MudThemingProvider.razor.cs
Labels: bug

#8276 Docs: Add fuzzy search & Make spaces in names consistent
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/Pages/Components/Checkbox/CheckboxPage.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/MessageBoxPage.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/SwipeAreaPage.razor
  src/MudBlazor.Docs/Pages/Components/ToolBar/ToolBarPage.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
Labels: bug

#8418 Column: Fix Sortable parameter documentation
  src/MudBlazor/Components/DataGrid/Column.razor.cs
Labels: docs

#8424 MudDialog: Fix some params not passed when inline
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: bug, PR: needs review

#8426 Fix code style rules in .editorconfig
  src/.editorconfig
Labels: bug, PR: needs review

#8425 MudBaseSelectItem: Clarify OnClick behavior in respect to Href
  src/MudBlazor/Base/MudBaseSelectItem.cs
Labels: docs

#8416 ParameterState: Add optional IEqualityComparer
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateTestComp.razor.cs
  src/MudBlazor.UnitTests/Extensions/ParameterViewExtensionsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockIntEqualityComparer.cs
  src/MudBlazor.UnitTests/State/ParameterHandlerUniquenessComparerTests.cs
  src/MudBlazor.UnitTests/State/ParameterSetTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor.UnitTests/Utilities/Comparer/DoubleEpsilonEqualityComparerTests.cs
  src/MudBlazor/Base/MudComponentBase.RegisterParameter.cs
  src/MudBlazor/Components/Input/MudDebouncedInput.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Extensions/ParameterViewExtensions.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilder.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilderOfT.cs
  src/MudBlazor/State/IParameterComponentLifeCycle.cs
  src/MudBlazor/State/ParameterMetadata.cs
  src/MudBlazor/State/ParameterSet.cs
  src/MudBlazor/State/ParameterState.cs
  src/MudBlazor/State/ParameterStateOfT.cs
  src/MudBlazor/Utilities/BindingConverters/NumericConverter.cs
  src/MudBlazor/Utilities/Comparer/DoubleEpsilonEqualityComparer.cs
Labels: enhancement

#8431 Build: Update copyright year, Exclude revision in informational version
  src/MudBlazor/MudBlazor.csproj
Labels: PR: needs review

#8433 Progress: Use ParameterState framework.
  src/MudBlazor/Components/Progress/MudProgressCircular.razor
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
Labels: enhancement

#8436 Refactor: Remove ICommand
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Base/MudBaseSelectItem.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavLink.razor
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: breaking change, PR: needs review

#8438 FileUpload: Fix top margin CSS
  src/MudBlazor/Styles/components/_fileupload.scss
Labels: bug, breaking change, PR: needs review

#8439 MudBreadcrumbs: Change from List to IReadOnlyList
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor.cs
Labels: breaking change, API change, PR: needs review

#8383 Snackbar: Only allow action invoke once, Add button classes, Add ForceClose
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Components/Snackbar/Snackbar.cs
Labels: bug, enhancement

#8457 ParameterState: Fix when subscribing only to EventCallback
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildBindingTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildBindingTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateParentBindingTestComp.razor
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor/State/ParameterStateOfT.cs
Labels: bug

#8446 MudExpansionPanel: Use ParameterState, remove obsolete API and change to async API
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelSimpleExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelExpandedMultipleWithoutMultipleExpansionSetTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelExpansionsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelMultiExpansionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelStartExpandedMultipleTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelStartExpandedTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelTwoWayBIndingTest.razor
  src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
Labels: bug, breaking change, API change

#8441 v7: Drop .NET6 as supported framework.
  CONTRIBUTING.md
  README.md
  src/MudBlazor/MudBlazor.csproj
Labels: breaking change, PR: needs review

#8458 MudDialogProvider: Add missing BackgroundClass (#8454)
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogBlurryExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogConfigurationExample.razor
  src/MudBlazor/Components/Dialog/DialogOptions.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
Labels: breaking change

#8469 Build: Build and test all branches
  .github/workflows/build-test-mudblazor.yml
Labels: build

#8467 Remove: ResizeListenerService, ResizeService, BrowserWindowSizeProvider, BreakpointService
  src/MudBlazor.Docs/Pages/Components/Hidden/Examples/BrowserResizeEventExample.razor
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockBreakpointService.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeListenerService.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeService.cs
  src/MudBlazor.UnitTests/Services/BreakpointServiceTests.cs
  src/MudBlazor.UnitTests/Services/ResizeBasedServiceTests.cs
  src/MudBlazor.UnitTests/Services/ResizeListenerServiceTests.cs
  src/MudBlazor.UnitTests/Services/SubscriptionInfoTests.cs
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Browser/Breakpoint.cs
  src/MudBlazor/Services/Browser/BreakpointGlobalOptions.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/Services/Browser/IBrowserViewportService.cs
  src/MudBlazor/Services/Browser/ResizeOptions.cs
  src/MudBlazor/Services/ResizeListener/BreakpointService .cs
  src/MudBlazor/Services/ResizeListener/ResizeBasedService.cs
  src/MudBlazor/Services/ResizeListener/ResizeListenerService.cs
  src/MudBlazor/Services/ResizeListener/ResizeService.cs
  src/MudBlazor/Services/ResizeListener/SubscriptionInfo.cs
Labels: breaking change, API change, refactor

#8473 DoubleExtensions: Fix typo, was DoubleExtentions
  src/MudBlazor/Extensions/DoubleExtensions.cs
Labels: breaking change, API change, PR: needs review

#8460 MudRipple: Follow theme colors and improve visibility (#8072)
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
  src/MudBlazor/Components/ThemeProvider/MudThemingProvider.razor.cs
  src/MudBlazor/Styles/abstracts/_colors.scss
  src/MudBlazor/Styles/components/_button.scss
  src/MudBlazor/Styles/components/_buttongroup.scss
  src/MudBlazor/Styles/components/_chip.scss
  src/MudBlazor/Styles/components/_fab.scss
  src/MudBlazor/Styles/components/_navmenu.scss
  src/MudBlazor/Styles/core/_ripple.scss
  src/MudBlazor/Themes/Models/Palette.cs
Labels: bug, enhancement

#8474 EnumExtensions: Remove ToDescriptionString
  src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
  src/MudBlazor/Extensions/EnumExtensions.cs
Labels: breaking change, API change, PR: needs review

#8471 Various components: Remove obsolete Link in favor of Href
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/Link/MudLink.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: breaking change, PR: needs review

#8475 Components: Remove some obsolete Parameters and Tests
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/AppBar/MudAppBarSpacer.razor
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
  src/MudBlazor/Components/ToolBar/MudToolBarSpacer.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Enums/OverflowBehavior.cs
  src/MudBlazor/Interfaces/ISnackbar.cs
  src/MudBlazor/Services/DialogResult.cs
Labels: breaking change, PR: needs review

#8432 Docs: Add Overline to Customization/Typography
  src/MudBlazor.Docs/Pages/Customization/Theming/Typography.razor
Labels: bug, PR: needs review

#8494 Docs: Fix binding regressions in examples
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/StackedBarExample1.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridFilteringExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridSortingExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuAdvancedPopoverExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuAnchorOriginExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuTransformOriginExample.razor
  src/MudBlazor.Docs/Pages/Components/Popover/Examples/PopoverLocationExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackCombinedExample.razor
Labels: docs

#8481 Dialog: Rename ClassContent and ClassActions parameters
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogBlurryExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogBlurryExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogConfigurationExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogFocusExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogFocusExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogInlineExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedExample_Dialog2.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedInlineExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedInlineExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogOptionsExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogOptionsExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogPassingDataExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogPassingDataExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogScrollableExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogScrollableExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogSetOptionsExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogSetOptionsExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogStylingExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogStylingExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogTemplateExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogTemplateExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogUsageExample_Dialog.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogOkCancel.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogRender.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogThatUpdatesItsTitle.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogToggleFullscreen.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithActionsClass.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithContentClass.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithEventCallback.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithEventCallbackTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithOnBackdropClickEvent.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithParameters.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithReturnValue.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/InlineDialogIsVisibleStateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestInlineDialog.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestNestedInlineDialog.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: breaking change, API change, v7

#8407 MudTable: Add CancellationToken into ServerData Function for Cancelable Requests
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableServerSideCancellationTokenExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableServerSidePaginateExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest9.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerDataLoadingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerDataLoadingTestWithCancel.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest3.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest4.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest4b.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest5.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest6.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
Labels: enhancement, breaking change, API change, v7

#8476 MudBaseInput: Remove obsoleted KeyPress related APIs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: breaking change, API change, v7

#8477 Components: Remove some obsoleted methods
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Components/Render/MudRender.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: breaking change, API change, v7

#8452 Theming: Replace all "Grey" spellings with "Gray"
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetVariantsExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicGroupingExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicGroupingInitiallyCollapsedExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiGroupingExample.razor
  src/MudBlazor.Docs/Pages/Features/Colors/ColorsPage.razor
  src/MudBlazor.Docs/Pages/Features/Colors/Examples/ColorsMaterialCodeExample.razor
  src/MudBlazor.Docs/Styles/components/_docspage.scss
  src/MudBlazor.Docs/Styles/components/_docssection.scss
  src/MudBlazor.Docs/Styles/components/_icons.scss
  src/MudBlazor.Docs/Styles/components/_mudblazorapp.scss
  src/MudBlazor.Docs/Styles/core/_base.scss
  src/MudBlazor.Docs/Styles/core/_carbon.scss
  src/MudBlazor.Docs/Styles/core/_markdown.scss
  src/MudBlazor.Docs/Styles/layout/_mainlayout.scss
  src/MudBlazor.Docs/Styles/pages/_landingpage.scss
  src/MudBlazor.Docs/Theme/Theme.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableGroupingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableGroupingTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelection_MultiGrouping_DefaultCheckboxStatesTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Colors/Colors.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/ThemeProvider/MudThemingProvider.razor.cs
  src/MudBlazor/Styles/abstracts/_colors.scss
  src/MudBlazor/Styles/components/_avatar.scss
  src/MudBlazor/Styles/components/_badge.scss
  src/MudBlazor/Styles/components/_datagrid.scss
  src/MudBlazor/Styles/components/_select.scss
  src/MudBlazor/Styles/components/_switch.scss
  src/MudBlazor/Styles/components/_timeline.scss
  src/MudBlazor/Styles/components/_togglegroup.scss
  src/MudBlazor/Styles/components/_tooltip.scss
  src/MudBlazor/Styles/core/_colors.scss
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Themes/Models/PaletteDark.cs
Labels: breaking change, PR: needs review

#6061 MudText: Replace h6 with span for subtitle typos (#6059)
  src/MudBlazor/Components/Typography/MudText.razor
Labels: breaking change, v7, accessibility

#8507 Tests: Fix ScrollToTopTests
  src/MudBlazor.UnitTests/Components/ScrollToTopTests.cs
Labels: bug

#6431 MudDateRangePicker: Add missing properties: PlaceholderStart/End and SeparatorIcon
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug

#8504 DataGrid : Fix sorting when there is Header row (#7645)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSortableHeaderRowTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
Labels: bug

#8506 Pickers: change API to async to avoid async void and fire-and-forget
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerActionButtonsExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DateRangePickerUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerActionButtonsExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerActionButtonsExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerKeyboardNavigationExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ColorPicker/SimpleColorPickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/AutoCloseDateRangePickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/AutoCompleteDatePickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DatePickerStaticTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerValidationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/SimpleMudDatePickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/SimpleMudMudDateRangePickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TimePicker/AutoCompleteTimePickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TimePicker/SimpleTimePickerTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: breaking change, API change, refactor, v7

#8423 Snackbar: Fix type class not taking into account per-snackbar options
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarVariantsExample.razor
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/SnackBarMessageState.cs
  src/MudBlazor/Components/Snackbar/SnackbarOptions.cs
Labels: bug

#8514 Theme: Replace Palette to PaletteLight
  src/MudBlazor/Components/ThemeProvider/MudThemingProvider.razor.cs
Labels: bug

#8513 MudOverlay: Fix two way binding with AutoClose=true
  src/MudBlazor.UnitTests.Viewer/TestComponents/Overlay/OverlayVisibleBindingWithAutoCloseTest.razor
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
Labels: bug

#8519 Code Quality: Remove Console message and unnecessary assignment.
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
Labels: build, PR: needs review

#8518 Build: Fix trim warnings when using dotnet format
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
Labels: bug, build

#8523 Code Quality: dotnet format
  src/MudBlazor.Docs.Wasm/Program.cs
  src/MudBlazor.Docs.WasmHost/Controllers/OperationCancelledExceptionFilter.cs
  src/MudBlazor.Docs.WasmHost/Program.cs
  src/MudBlazor.Docs/Components/DocsPage.razor.cs
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
  src/MudBlazor.Docs/Extensions/ResourceSetExtensions.cs
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor.cs
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor.SourceCodeGenerator/Usings.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormComponentUpdateValidationMessagesOnEditContextChangedTest.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerTestComp.razor.cs
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/DonutChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/PieChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/StackedBarChartTests.cs
  src/MudBlazor.UnitTests/Components/DataGrid/AggregateDefinitionTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/ScrollToTopTests.cs
  src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
  src/MudBlazor.UnitTests/Extensions/ExpressionExtensionsTests.cs
  src/MudBlazor.UnitTests/Extensions/ParameterViewExtensionsTests.cs
  src/MudBlazor.UnitTests/Extensions/TaskExtensionsTests.cs
  src/MudBlazor.UnitTests/Services/Localization/DefaultLocalizationInterceptorTests.cs
  src/MudBlazor.UnitTests/Services/Localization/InternalMudLocalizerTests.cs
  src/MudBlazor.UnitTests/Utilities/Expressions/ExpressionHasherTests.cs
  src/MudBlazor.UnitTests/Utilities/Expressions/PropertyPathTests.cs
  src/MudBlazor/Base/MudBaseColumn.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
  src/MudBlazor/Components/ThemeProvider/MudThemingProvider.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Enums/OverflowBehavior.cs
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilderOfT.cs
  src/MudBlazor/State/ParameterChangedLambdaArgsHandler.cs
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Utilities/ColorManager.cs
Labels: refactor, PR: needs review

#8516 MudTextField: Remove last remaining reference to KeyPress
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: bug

#8377 MudToggleGroup and MudToggleItem: Add Disabled parameter (#8367)
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleBasicsExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleDisabledTest.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: enhancement

#8421 Update icons and remove obsolete API
  src/MudBlazor/Icons/Material/Filled.cs
  src/MudBlazor/Icons/Material/Outlined.cs
  src/MudBlazor/Icons/Material/Rounded.cs
  src/MudBlazor/Icons/Material/Sharp.cs
  src/MudBlazor/Icons/Material/TwoTone.cs
  src/MudBlazor/Icons/Obsolete/Filled.cs
  src/MudBlazor/Icons/Obsolete/Outlined.cs
  src/MudBlazor/Icons/Obsolete/Rounded.cs
  src/MudBlazor/Icons/Obsolete/Sharp.cs
  src/MudBlazor/Icons/Obsolete/TwoTone.cs
  src/MudBlazor/Icons/Obsolete/_Obsolete.cs
  tools/Icons/Update-MudIcons.ps1
Labels: enhancement, breaking change, v7

#8536 Icons: Remove Material.Obsolete, Update formatting
  src/MudBlazor/Icons/Material/Filled.cs
  src/MudBlazor/Icons/Material/Outlined.cs
  src/MudBlazor/Icons/Material/Rounded.cs
  src/MudBlazor/Icons/Material/Sharp.cs
  src/MudBlazor/Icons/Material/TwoTone.cs
  src/MudBlazor/Icons/Material/_Obsolete.cs
  tools/Icons/Update-MudIcons.ps1
Labels: breaking change, API change, refactor, PR: needs review

#8517 MudPicker: Fix code style and naming issues
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerExampleUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerActionButtonsExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerBasicUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerColorExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerDisableCustomizeDaysExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerElevationExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerFixedValuesExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerGoToDateExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerInternationalizationExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerMaskExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerReadOnlyExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerTextParseExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerDialogExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerReadOnlyExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerStaticExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerTimeEditModeExample.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/PickerTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Attributes/CategoryAttribute.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Picker/MudPickerContent.razor
  src/MudBlazor/Components/Picker/MudPickerContent.razor.cs
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
Labels: breaking change, API change, refactor, v7

#8505 Docs: Replace notification with one for v7 & Don't hide read ones
  src/MudBlazor.Docs/NotificationContent/Announcement_MudBlazorIsHereToStay.razor
  src/MudBlazor.Docs/NotificationContent/Announcement_v7_Started_Development.razor
  src/MudBlazor.Docs/Services/Notifications/InMemoryNotificationService.cs
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
Labels: docs

#8533 Refactor: Use regular expression source generator
  src/MudBlazor.Docs.Compiler/CodeSnippets.cs
  src/MudBlazor.Docs.Compiler/DocStrings.cs
  src/MudBlazor.Docs.Compiler/ExamplesMarkup.cs
  src/MudBlazor.Docs.Compiler/StringExtensions.cs
  src/MudBlazor.Docs.Compiler/XmlDocumentation.cs
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
  src/MudBlazor.Docs/Extensions/StringExtensions.cs
  src/MudBlazor.Docs/Models/DocStrings.cs
  src/MudBlazor.Docs/Models/XmlDocumentation.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Utilities/MaskAlgorithms/DateMask.cs
Labels: performance, refactor
