Repository MudBlazor/MudBlazor, pull requests merged in 2024-07, with the labels that each got.

#9279 Docs: Tweaks to API Documentation
  src/MudBlazor.Docs/Components/ApiBreadcrumbs.razor.cs
  src/MudBlazor.Docs/Components/ApiTypeTable.razor
  src/MudBlazor.Docs/Components/ApiTypeTable.razor.cs
  src/MudBlazor.Docs/Components/DocsPage.razor.cs
  src/MudBlazor.Docs/Components/DocsPageHeader.razor
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
  src/MudBlazor.Docs/Models/Generated/ApiDocumentation.cs
  src/MudBlazor.Docs/Pages/Api/Api.razor
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
  src/MudBlazor.Docs/Services/ApiLink/IApiLinkService.cs
  src/MudBlazor.Docs/Shared/NavMenu.razor
Labels: docs, PR: needs review

#9278 MudBaseInput: Add `protected InputElementId` (#9277)
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: enhancement, PR: needs review

#9260 ElementReferenceExtensions: Use delegate for retrieving JSRuntime
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
Labels: performance, PR: needs review

#9293 MudMessageBox: Add button classes
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor
Labels: enhancement, PR: needs review

#9298 MudAlert: Remove `alert` role
  src/MudBlazor/Components/Alert/MudAlert.razor
Labels: PR: needs review, accessibility

#9282 MudDataGridPager: When no items, Pager now shows "0-0 of 0" (#9247)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridPaginationNoItemsTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
Labels: bug

#9303 MudCollapse: Fix `aria-expanded` value
  src/MudBlazor/Components/Collapse/MudCollapse.razor
Labels: bug, accessibility

#9321 Translations: Force keys to follow naming conventions
  src/MudBlazor.UnitTests/Other/LanguageResourceTests.cs
Labels: enhancement, PR: needs review

#9309 MudAvatarGroup: Fix Max default value behavior (#9267)
  src/MudBlazor.UnitTests.Viewer/TestComponents/AvatarGroup/AvatarGroupMaxDefaultTest.razor
  src/MudBlazor.UnitTests/Components/AvatarGroupTests.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
Labels: bug, PR: needs review

#9322 Docs: Improve MudTreeView templating example for more clarity
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewItemTemplateExample.razor
Labels: docs, PR: needs review

#9324 ElementReferenceExtensions: Utilize new UnsafeAccessor
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
Labels: performance, PR: needs review

#9305 MudBadge: Center content with flex instead of negative margins
  src/MudBlazor/Styles/components/_badge.scss
Labels: bug, PR: needs review

#9331 Localization: Use source generated resources
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationDictionaryCode.html
  src/MudBlazor.UnitTests/Other/LanguageResourceTests.cs
  src/MudBlazor.UnitTests/Services/Localization/DefaultLocalizationInterceptorTests.cs
  src/MudBlazor.UnitTests/Services/Localization/InternalMudLocalizerTests.cs
  src/MudBlazor/Components/Alert/MudAlert.razor
  src/MudBlazor/Components/Carousel/MudCarousel.razor
  src/MudBlazor/Components/Chip/MudChip.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/FilterOperator.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor
  src/MudBlazor/Components/Pagination/MudPagination.razor
  src/MudBlazor/Components/Rating/MudRating.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Components/Table/MudTablePager.razor
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
Labels: enhancement, PR: needs review

#9330 MudAutocomplete: Make the autocomplete attribute configurable (#9334)
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#9337 Autocomplete: Allow overriding `autocomplete` via UserAttributes
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement, PR: needs review

#9264 MudFileUpload: Use ParameterState
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
Labels: bug, PR: needs review

#9339 Accessibility: Simplify `aria-label` text
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Resources/LanguageResource.resx
Labels: PR: needs review, accessibility

#9336 DataGrid: Add missing labels for filter value fields in data grid column filter (#9319)
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug, PR: needs review

#9348 Build: Only deploy try.mudblazor.com and mudblazor.com for v7
  .github/workflows/deploy-mudblazor.yml
  .github/workflows/deploy-trymudblazor.yml
Labels: build

#9344 MudDataGrid: Fix Column ungroup
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnGroupingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerDataColumnGroupingTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug, PR: needs review

#9346 MudInputControl: Fix `HelperTextOnFocus` regression
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Input/MudInputLabel.razor.cs
  src/MudBlazor/Components/InputControl/MudInputControl.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
Labels: bug, PR: needs review

#9354 MudAutocomplete: Modify default autocomplete method (#9318)
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#9300 MudTimePicker: Refactor pointer events to support touch dragging
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/TScripts/mudTimePicker.js
Labels: enhancement

#9360 Update TreeViewUsageExample.razor Fixed variable names in markup
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewUsageExample.razor
Labels: docs, PR: needs review

#9373 Remove illegal param detector, this time really
  src/MudBlazor.UnitTests/Components/ComponentBaseTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
Labels: PR: needs review

#9306 DialogService: Fix thread is not associated with the Dispatcher
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
  src/MudBlazor/Services/Dialog/DialogResult.cs
  src/MudBlazor/Services/Dialog/DialogService.cs
  src/MudBlazor/Services/Dialog/IDialogService.cs
Labels: bug

#9387 MudMenuItem: Add missing xml doc for ForceLoad
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: docs

#9385 Autocomplete: Add opt-out `OpenOnFocus` property
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteFocusTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement, PR: needs review

#9368 Theme: Change Typography members to type BaseTypography
  src/MudBlazor/Themes/Models/Typography.cs
Labels: enhancement, PR: needs review

#9366 MudExpansionPanel: Add Gutters padding instead of removing it
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Styles/components/_expansionpanel.scss
Labels: refactor, PR: needs review

#9364 Hook up `Autocomplete.MaxLength`
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
Labels: bug, PR: needs review

#9391 PopoverService: Add CheckForPopoverProvider
  src/MudBlazor.UnitTests/Extensions/TestContextExtensions.cs
  src/MudBlazor.UnitTests/Services/Popover/PopoverServiceTests.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Popover/PopoverOptions.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
Labels: enhancement

#9372 MudPicker: Add OverflowBehavior that is passed to the underlying MudPopover
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: enhancement

#9390 MudListItem: Use disabled color for SecondaryText when item is disabled
  src/MudBlazor/Styles/components/_list.scss
Labels: bug, PR: needs review

#9394 Inputs: Allow custom Clear icon
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
Labels: enhancement, PR: needs review

#9386 MudFormComponent: Fix validation handling (#9215)
  src/MudBlazor.Docs/Pages/Components/Form/FormPage.razor
  src/MudBlazor/Base/MudFormComponent.cs
Labels: bug

#9402 Tests: Disable `CS1998` less
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectValidationDataAttrTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionItemsTest1.razor.cs
  src/MudBlazor.UnitTests/Components/BadgeTests.cs
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor.UnitTests/Components/VirtualizeTests.cs
  src/MudBlazor.UnitTests/Services/JsEventTests.cs
Labels: refactor

#9399 MudText, MudLink: Improve code docs and tests
  src/MudBlazor.UnitTests.Viewer/TestComponents/Typography/TextInlineTest.razor
  src/MudBlazor.UnitTests/Components/LinkTests.cs
  src/MudBlazor.UnitTests/Components/TextTests.cs
  src/MudBlazor.UnitTests/Components/TypographyTests.cs
  src/MudBlazor/Components/Link/MudLink.razor.cs
  src/MudBlazor/Components/Typography/MudText.razor.cs
Labels: PR: needs review

#9323 MudPagination: Control show or hide the page button (#5536)
  src/MudBlazor.Docs/Pages/Components/Pagination/Examples/PaginationHidePagesExample.razor
  src/MudBlazor.Docs/Pages/Components/Pagination/PaginationPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Pagination/PaginationHidePageButtonsTest.razor
  src/MudBlazor.UnitTests/Components/PaginationTests.cs
  src/MudBlazor/Components/Pagination/MudPagination.razor
  src/MudBlazor/Components/Pagination/MudPagination.razor.cs
Labels: enhancement, PR: needs review

#9418 MudTreeView: Improve templating example
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
Labels: PR: needs review

#9401 Tests: Restore `BL0005` more
  src/MudBlazor.UnitTests/Components/ButtonsTests.cs
  src/MudBlazor.UnitTests/Components/CarouselTests.cs
  src/MudBlazor.UnitTests/Components/ChipTests.cs
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor.UnitTests/Components/PickerTests.cs
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
Labels: refactor

#9423 Revert "Theme: Change Typography members to type BaseTypography"
  src/MudBlazor/Themes/Models/Typography.cs
Labels: PR: needs review

#9370 Table, DataGrid: Support localization of pager text
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
  src/MudBlazor/Resources/LanguageResource.resx
Labels: enhancement, PR: needs review

#9428 MudTreeView: Don't select on expand button double click
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItemToggleButton.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItemToggleButton.razor.cs
Labels: bug, PR: needs review

#9375 DialogService: Fix CloseOnEscape in ShowAsync and ShowMessageBox (#9367)
  src/MudBlazor.Docs/Pages/Components/MessageBox/Examples/MessageBoxOptionsExample.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/MessageBoxPage.razor
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
Labels: enhancement

#9431 IDialogService: Forward event DialogInstanceAddedAsync to OnDialogInstanceAdded for compatibility
  src/MudBlazor/Services/Dialog/IDialogService.cs
Labels: accidental break

#9432 TreeItemData<T>: Add virtual to all properties as per request
  src/MudBlazor/Components/TreeView/TreeItemData.cs
  src/MudBlazor/MudBlazor.csproj.DotSettings
Labels: enhancement

#9421 MudField, MudMask: Support typography customization
  src/MudBlazor/Components/Field/MudField.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
Labels: bug, PR: needs review

#9374 MudTable: Add SelectionChangeable parameter
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiSelectExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest9.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor
  src/MudBlazor/Components/Table/MudTFootRow.razor.cs
  src/MudBlazor/Components/Table/MudTHeadRow.razor
  src/MudBlazor/Components/Table/MudTHeadRow.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTableGroupRow.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: enhancement

#9440 Docs: Update terminology in docs from Palette to PaletteLight. (#9433)
  src/MudBlazor.Docs/Pages/Customization/Theming/Overview.razor
Labels: docs

#9444 Docs: Replace markdown links to html in Roadmap page
  src/MudBlazor.Docs/Pages/Mud/Project/Releases.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Roadmap.razor
Labels: docs, PR: needs review

#9451 Localization: Correctly handle templates (#9438)
  src/MudBlazor.UnitTests/Services/Localization/DefaultLocalizationInterceptorTests.cs
  src/MudBlazor/Services/Localization/DefaultLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/MudLocalizer.cs
Labels: bug, PR: needs review

#9448 MudDataGrid: Fix `RowsPerPage` firing ServerData twice
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerPaginationTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#9463 TableGrid: Fix RowsPerPage firing ServerData twice
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerPaginationTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
Labels: bug

#9461 feat: Add CollectionExtensions
  src/MudBlazor/Extensions/CollectionExtensions.cs
Labels: performance

#9469 Docs: Add a section for `ServerData` in the MudDataGrid docs
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridServerSideExample.razor
Labels: docs

#9457 MudDialog: Improve max height and alignment of dialog container on mobile
  src/MudBlazor/Styles/components/_dialog.scss
Labels: enhancement, PR: needs review

#9471 Docs: Update CookieConsent library and embed it's JS to docs.js
  src/MudBlazor.Docs/Extensions/DocsViewExtension.cs
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/wwwroot/JS/docs.js
Labels: docs

#9482 Docs: Fix ShowDialogRegularExpression
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
Labels: docs

#9487 Performance: Add more extension methods for Array and List
  src/MudBlazor.UnitTests/Extensions/CollectionExtensionsTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
  src/MudBlazor/Extensions/CollectionExtensions.cs
Labels: performance

#9458 MudOverlay: Refactor, Deprecate `OnClick` in favor of new `OnClosed`, Fix MudMenu interactions
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayLoaderExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayOnClickExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/OverlayPage.razor
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor/Attributes/CategoryAttribute.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/Drawer/MudDrawer.razor
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Overlay/MudOverlay.razor
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
Labels: bug, enhancement, API change

#9453 Docs: Refresh install guide & warn about render modes
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Examples/InstallationManualComponentsExample.razor
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Labels: docs, PR: needs review

#9500 MudDrawer: Add OverlayAutoClose, use OnClosed instead of OnClick
  src/MudBlazor.Docs/Pages/Components/Drawer/DrawerPage.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerTemporaryExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerTest1.razor
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
Labels: enhancement

#9503 TreeViewItem: ReloadAsync() now also reloads in collapsed state
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewServerTest2.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: bug

#9459 MudForm: Added XML Documentation for Public Members
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Components/Grid/MudFlexBreak.razor.cs
  src/MudBlazor/Components/Input/MudDebouncedInput.cs
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Input/MudInputAdornment.razor
  src/MudBlazor/Components/Input/MudInputAdornment.razor.cs
  src/MudBlazor/Components/Input/MudInputCssHelper.cs
  src/MudBlazor/Components/Input/MudInputLabel.razor.cs
  src/MudBlazor/Components/Input/MudRangeInput.razor.cs
  src/MudBlazor/Components/Input/Range.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
Labels: docs

#9515 Performance: Add FirstOrDefault extension method for Array and List
  src/MudBlazor.UnitTests/Extensions/CollectionExtensionsTests.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor
  src/MudBlazor/Components/Chart/Charts/Pie.razor
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
  src/MudBlazor/Extensions/CollectionExtensions.cs
Labels: performance

#9518 MudDataGrid: Improve the doc about `ServerData`
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
Labels: docs

#9520 Build: potentially fix invalid JS in the minified scripts file
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: build, PR: needs review

#9493 Performance: Add Identifier helper class
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor.UnitTests/Utilities/IdentifierTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Select/MudSelectItem.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Utilities/Identifier.cs
Labels: performance

#9522 DataGrid: Make FilterContext.FilterDefinition public to support custom filters
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCustomPropertyFilterTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridStringContainsFilter.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FilterContext.cs
Labels: enhancement

#9527 Localization: Make InternalMudLocalizer implement IStringLocalizer
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationResXCode.html
  src/MudBlazor.UnitTests/Services/Localization/DefaultLocalizationInterceptorTests.cs
  src/MudBlazor.UnitTests/Services/Localization/InternalMudLocalizerTests.cs
  src/MudBlazor/Services/Localization/AbstractLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/DefaultLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
  src/MudBlazor/Services/Localization/MudLocalizer.cs
Labels: enhancement, localization
