Repository MudBlazor/MudBlazor, pull requests merged in 2024-08, with the labels that each got.

#9546 DataGrid: Fix multiple filter popups can be opened
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#9552 MudTimePicker: Fix dispose method
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/TScripts/mudTimePicker.js
Labels: bug

#9547 MudElement: Fix ElementReferenceCapture
  src/MudBlazor.UnitTests.Viewer/TestComponents/Element/ElementReferenceExceptionTest.razor
  src/MudBlazor.UnitTests/Components/ElementTests.cs
  src/MudBlazor/Components/Element/MudElement.cs
Labels: bug

#9526 Alert: Fix vertical icon position on alerts
  src/MudBlazor/Styles/components/_alert.scss
Labels: PR: needs review

#9525 Docs: Update CSS utils for spacing description
  src/MudBlazor.Docs/Pages/CSS Utilities/Spacing/SpacingPage.razor
Labels: docs, PR: needs review

#9442 MudThemeProvider: Add ObserveSystemThemeChange
  src/MudBlazor.Docs/Services/LayoutService.cs
  src/MudBlazor.Docs/Shared/MainLayout.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/ThemeProvider/ThemeProviderObserveSystemThemeChangeTest.razor
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
Labels: enhancement

#9512 Add migration remarks to a few code docs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Grid/MudGrid.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/Stack/MudStack.razor.cs
  src/MudBlazor/Enums/Typo.cs
  src/MudBlazor/Themes/MudTheme.cs
Labels: docs

#9561 MudInput: Handle AutoGrow dispose when ElementReference is null
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: bug

#9513 Menu: Stay open after being clicked with `MouseOver`
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: bug

#9499 Make object-fit and object-position styles important
  src/MudBlazor/Styles/utilities/layout/_object-fit.scss
  src/MudBlazor/Styles/utilities/layout/_object-position.scss
Labels: bug

#9517 Inputs: Fixed margins on each variant and margin sizes
  src/MudBlazor.UnitTests.Viewer/TestComponents/General/AllInputsTest.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Field/MudField.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
  src/MudBlazor/Styles/components/_inputcontrol.scss
Labels: bug

#9557 MudTreeViewItem: Add ReadOnly
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/ItemSelectableTreeViewTest.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: bug

#9564 Docs: Fix german link in CONTRIBUTING.MD
  CONTRIBUTING.md
Labels: docs

#9558 Performance: Use Identifier helper in more cases
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
  src/MudBlazor/Components/NavMenu/NavigationContext.cs
  src/MudBlazor/Components/Snackbar/SnackBarMessageState.cs
  src/MudBlazor/TScripts/mudDragAndDrop.js
Labels: performance

#9466 MudDateRangePicker: Add parameter to allow capture of disabled dates (#9452)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/SimpleMudMudDateRangePickerTest.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: enhancement

#9565 Docs: Remove duplicate sentence in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#9395 build: Add sonar workflow
  .github/workflows/sonar.yml
Labels: build

#9567 MudTreeView: Allow for parent auto selection configuration
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewMultiSelectionExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewAutoSelectParentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewSelectionBindingTest.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
Labels: enhancement

#9571 Docs: Removal of all language preferences in URLs
  CONTRIBUTING.md
  README.md
  src/MudBlazor.Analyzers/Internal/ComponentDescriptor.cs
  src/MudBlazor.Docs.Compiler/ApiDocumentationBuilder.cs
  src/MudBlazor.Docs/Components/ApiText.cs
  src/MudBlazor.Docs/Components/ApiTypeLink.cs
  src/MudBlazor.Docs/Extensions/DocsViewExtension.cs
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/Pages/Components/FileUpload/FileUploadPage.razor
  src/MudBlazor.Docs/Pages/Components/Form/FormPage.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor.Docs/Pages/Consent/CookiePolicy.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/EventUtil1Test.razor
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/Element/MudElement.cs
  src/MudBlazor/Components/Input/MudInputAdornment.razor.cs
  src/MudBlazor/Components/Typography/MudText.razor.cs
  src/MudBlazor/Enums/InputMode.cs
  src/MudBlazor/Themes/Models/PseudoCss.cs
  src/MudBlazor/Utilities/Clone/SystemTextJsonCloneStrategy.cs
  src/MudBlazor/Utilities/EventUtil.cs
Labels: docs, PR: needs review

#9576 MudText: Handle empty HtmlTag as null
  src/MudBlazor.UnitTests/Components/TextTests.cs
  src/MudBlazor/Components/Typography/MudText.razor.cs
Labels: bug

#9579 Popover: Update obsoletion messages
  src/MudBlazor.UnitTests/Mocks/MockPopoverService.cs
  src/MudBlazor/Components/Popover/MudPopoverBase.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Popover/IMudPopoverService.cs
  src/MudBlazor/Services/Popover/MudPopoverHandler.cs
  src/MudBlazor/Services/Popover/MudPopoverService.cs
  src/MudBlazor/Services/Popover/PopoverMode.cs
Labels: docs

#9578 MudDropContainer: Fixes typos in method names
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
Labels: bug

#9584 Overlay: Un-obsolete OnClick event
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
Labels: refactor

#9478 Icons: Add Empty icon
  src/MudBlazor/Icons/Custom/Uncategorized.cs
Labels: enhancement, PR: needs review

#9410 Build: Update packages
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: dependency, PR: needs review

#9396 Build: Update github-script to v7
  .github/workflows/pr.yml
Labels: build, PR: needs review

#9604 MudTable: Cancel ServerLoad func on Dispose
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableServerSideDataTest7.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
Labels: enhancement

#9609 MudAutocomplete: Cancel SearchFunc on Dispose
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutoCompleteContainer.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest8.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: PR: needs review

#9624 Docs: Fix Localization Dictionary
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/LocalizationDictionaryCode.html
Labels: docs, PR: needs review, localization

#9628 Build: Disable NuGet auditing
  src/Directory.Build.props
Labels: build

#9381 ToggleItem: Use restyled MudButton
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleBasicsExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleInitializeTest.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: refactor

#9627 Build: Downgrade Microsoft.CodeAnalysis.CSharp
  src/MudBlazor.Analyzers/MudBlazor.Analyzers.csproj
  src/MudBlazor.Analyzers/MudComponentUnknownParametersAnalyzer.cs
  src/MudBlazor.SourceGenerator/MudBlazor.SourceGenerator.csproj
Labels: build, PR: needs review

#9641 Icons: Fix Steam icon
  src/MudBlazor/Icons/Custom/Brands.cs
Labels: bug, PR: needs review

#9644 ToggleGroup: Rename test components for clarity
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleGroup/ToggleGroupBindMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleGroup/ToggleGroupBindTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleGroup/ToggleGroupCustomFragmentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleGroup/ToggleGroupDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleGroup/ToggleGroupInitializeTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleGroup/ToggleGroupToggleSelectionTest.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
Labels: tests

#9599 MudAutocomplete: Fix search not being triggered when the text is cleared
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteResetValueOnEmptyText.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#9635 Performance: Reduce memory allocation in CssBuilder and StyleBuilder by using StringBuilderCache
  src/MudBlazor.UnitTests/Utilities/CssBuilderTests.cs
  src/MudBlazor/Utilities/CssBuilder.cs
  src/MudBlazor/Utilities/StringBuilderCache.cs
  src/MudBlazor/Utilities/StyleBuilder.cs
Labels: performance, refactor

#9643 MudDataGrid : Fix Resize column when neighboring is hidden
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridHideAndResizeTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/DataGridColumnResizeService.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#9652 MudInput: Revert left and right margins added in #9517
  src/MudBlazor/Styles/components/_inputcontrol.scss
Labels: bug

#9614 MudRadioGroup: Bind after should not trigger when value is modified externally
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest5.razor
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
Labels: bug, PR: needs review

#9653 Document Color enum and note limited support for some themes
  src/MudBlazor/Enums/Color.cs
Labels: docs

#9666 Docs: Correct MudThemeProvider example for "Watch system preference"
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesWatchSystemPreferenceExample.razor
Labels: docs

#9639 Autocomplete: Improve handling of focus events
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#9454 Snackbar: Add nullable annotation
  src/MudBlazor.UnitTests/Services/SnackbarServiceTests.cs
  src/MudBlazor.sln.DotSettings
  src/MudBlazor/Components/Snackbar/CommonSnackbarOptions.cs
  src/MudBlazor/Components/Snackbar/Defaults.cs
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageMarkupString.razor
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageMarkupString.razor.cs
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageRenderFragment.razor
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageRenderFragment.razor.cs
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageText.razor
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageText.razor.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarProvider.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarProvider.razor.cs
  src/MudBlazor/Components/Snackbar/SnackBarMessageState.cs
  src/MudBlazor/Components/Snackbar/Snackbar.cs
  src/MudBlazor/Components/Snackbar/SnackbarConfiguration.cs
  src/MudBlazor/Components/Snackbar/SnackbarMessage.cs
  src/MudBlazor/Components/Snackbar/SnackbarOptions.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
  src/MudBlazor/Components/Snackbar/SnackbarState.cs
  src/MudBlazor/Extensions/SnackbarStateExtensions.cs
  src/MudBlazor/Interfaces/ISnackbar.cs
Labels: docs, enhancement

#9595 MudSelect: Fix OnKeyDown not triggered correctly for the Enter key
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug

#9613 MudField: Text overflow ellipsis for labels
  src/MudBlazor/Styles/components/_inputlabel.scss
Labels: enhancement

#9686 BrowserViewportService: Fix ResizeOptions
  src/MudBlazor.UnitTests/Services/Browser/BrowserViewportServiceTests.cs
  src/MudBlazor/Services/Browser/BreakpointGlobalOptions.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
Labels: bug, PR: needs review

#9679 Build: Switch from dependabot to renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: build, PR: needs review

#9690 Build: Fix typo in renovate configuration
  .github/renovate.json
Labels: build, PR: needs review

#9696 Build: Group Microsoft.CodeAnalysis
  .github/renovate.json
Labels: PR: needs review

#9677 Docs: Fix spacing in some Form examples
  src/MudBlazor.Docs/Pages/Components/Form/Examples/FormReadonlyDisabledExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/Examples/LabelAttributeExample.razor
Labels: docs, PR: needs review

#9672 Docs: Fix "Size" xml docs for MudSlider
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
Labels: docs

#9706 ToggleGroup: Fix bad layout on initial render
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
Labels: bug, PR: needs review

#9712 Docs: Fix typo for ToggleIconButton docs
  src/MudBlazor.Docs/Pages/Components/ToggleIconButton/ToggleIconButtonPage.razor
Labels: docs

#9714 MudCollapse: Remove `aria-expanded` binding
  src/MudBlazor/Components/Collapse/MudCollapse.razor
Labels: bug, accessibility

#9733 Build: Disable renovate for SassCompiler
  .github/renovate.json
Labels: build, PR: needs review

#9741 Docs: Use spaces for indententation in the examples
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
Labels: docs, PR: needs review
