Repository MudBlazor/MudBlazor, pull requests merged in 2024-12, with the labels that each got.

#10368 Cookie Consent CSS: Fixes the Cookie Consent Popup from Blocking the UI
  src/MudBlazor.Docs/Styles/components/_consent.scss
Labels: bug, PR: needs review

#10371 Docs: Update contributing
  CONTRIBUTING.md
Labels: docs

#10392 MudDatePicker: Fix bugs in FixYear and FixMonth
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/FixYearFixMonthTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: bug

#10377 DateMask: Fix leap year February logic 02/29
  src/MudBlazor.UnitTests/Utilities/Mask/DateMaskTests.cs
  src/MudBlazor/Utilities/MaskAlgorithms/DateMask.cs
Labels: bug, PR: needs review

#10328 MudTextField: With mask, setting parameter value updates the input text
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
Labels: bug

#10402 MudDataGrid: Fix virtualization regression (#10343)
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#10415 Docs: Fixed Missing Link to API Documentation Page
  src/MudBlazor.Docs/Components/DocsPageHeader.razor
Labels: docs

#10406 MudTextField: Add note in docs about TextUpdateSuppression
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
Labels: docs

#10419 MudDataGrid: Add AggregateTemplate render fragment
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAggregationExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridAggregationTest.razor
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/FooterCell.razor
Labels: enhancement

#10387 MudDataGrid: Fix SelectOnRowClick when MultiSelection is false
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#10417 Build: Better sasscompiler workaround
  src/MudBlazor.Docs.Compiler/sasscompiler.json
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
Labels: bug, PR: needs review

#10436 MudDataGrid: Fix Resizable property behavior
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridStickyColumnsResizerTest.razor
  src/MudBlazor/Components/DataGrid/DataGridColumnResizeService.cs
Labels: bug, PR: needs review

#10438 MudDataGrid: Don't remove `Is Not Empty` filter definition on filter close
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#10432 Build: Split test generation
  src/MudBlazor.Docs.Compiler/Paths.cs
  src/MudBlazor.Docs.Compiler/Program.cs
  src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
  src/MudBlazor.Docs.Compiler/TestsForExamples.cs
  src/MudBlazor.Docs/Models/DocStrings.cs
  src/MudBlazor.UnitTests.Docs.Generator/CodeBuilder.cs
  src/MudBlazor.UnitTests.Docs.Generator/MudBlazor.UnitTests.Docs.Generator.csproj
  src/MudBlazor.UnitTests.Docs.Generator/Paths.cs
  src/MudBlazor.UnitTests.Docs.Generator/Program.cs
  src/MudBlazor.UnitTests.Docs.Generator/TestsForApiPages.cs
  src/MudBlazor.UnitTests.Docs.Generator/TestsForExamples.cs
  src/MudBlazor.UnitTests.Docs/MudBlazor.UnitTests.Docs.csproj
Labels: build, PR: needs review

#10353 MudSelect: Prevent adornment `pointerdown` propogating to input
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInputAdornment.razor
  src/MudBlazor/Components/Mask/MudMask.razor
Labels: bug, regression

#10429 Fixing MudRatingItem ADA issue
  src/MudBlazor/Components/Rating/MudRatingItem.razor
Labels: bug

#10401 MudDateRangePicker: Fix #9667: Fix Clearable Button Not Disappearing with No Range Data
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerClearableTest.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug, PR: needs review

#10395 MudSelect: Fixing MultiSelection in MudSelect
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectWithValueContainZeroTest.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, PR: needs review

#10385 MudTextField: Fix MudTextField label background
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/OutlineLabelBackgroundTest.razor
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Field/MudField.razor
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Styles/components/_input.scss
  src/MudBlazor/Styles/components/_inputlabel.scss
Labels: bug

#10445 README: Update support policy
  README.md
Labels: PR: needs review

#10407 Docs: MudRating to MudSkeleton: Add XML Docs for Public Members
  src/MudBlazor/Components/Popover/DropDownSettings.cs
  src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor.cs
  src/MudBlazor/Components/Rating/MudRating.razor.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
  src/MudBlazor/Components/ScrollToTop/MudScrollToTop.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Select/MudSelectItem.razor.cs
  src/MudBlazor/Components/Skeleton/MudSkeleton.razor.cs
  src/MudBlazor/Components/TableSimple/MudSimpleTable.razor.cs
  src/MudBlazor/Enums/Animation.cs
  src/MudBlazor/Enums/SkeletonType.cs
Labels: docs

#10447 Menu: Improve docs & Refactor code
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuItemCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuMaxHeightExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuWithNestingExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: PR: needs review

#10451 MudSelect: Change Visibility of "_currentIcon" to Internal
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: breaking change

#10439 Build: Enable nullable in MudBlazor.Docs.Compiler
  .vscode/tasks.json
  src/MudBlazor.Docs.Compiler/ApiDocumentationBuilder.cs
  src/MudBlazor.Docs.Compiler/ApiDocumentationWriter.cs
  src/MudBlazor.Docs.Compiler/CodeBuilder.cs
  src/MudBlazor.Docs.Compiler/DocumentedEvent.cs
  src/MudBlazor.Docs.Compiler/DocumentedField.cs
  src/MudBlazor.Docs.Compiler/DocumentedLink.cs
  src/MudBlazor.Docs.Compiler/DocumentedMember.cs
  src/MudBlazor.Docs.Compiler/DocumentedMethod.cs
  src/MudBlazor.Docs.Compiler/DocumentedParameter.cs
  src/MudBlazor.Docs.Compiler/DocumentedProperty.cs
  src/MudBlazor.Docs.Compiler/DocumentedType.cs
  src/MudBlazor.Docs.Compiler/ExamplesMarkup.cs
  src/MudBlazor.Docs.Compiler/MudBlazor.Docs.Compiler.csproj
  src/MudBlazor.Docs.Compiler/Paths.cs
  src/MudBlazor.Docs.Compiler/Program.cs
  src/MudBlazor.Docs.Compiler/StringExtensions.cs
  src/MudBlazor.Docs.Compiler/TypeExtensions.cs
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests.Docs.Generator/CodeBuilder.cs
  src/MudBlazor.UnitTests.Docs/MudBlazor.UnitTests.Docs.csproj
  src/MudBlazor.UnitTests.Shared/MudBlazor.UnitTests.Shared.csproj
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
Labels: build, PR: needs review

#10456 Docs: Update MudGlobal page with experimental warning
  src/MudBlazor.Docs/Pages/Customization/Globals/Globals.razor
Labels: docs, PR: needs review

#10364 MudTextField: Fix clickable area in multiline fields
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldAutoGrowTest.razor
  src/MudBlazor/Styles/components/_input.scss
  src/MudBlazor/TScripts/mudInputAutoGrow.js
Labels: bug, PR: needs review

#10400 New Component - MudChat
  src/MudBlazor.Docs/Pages/Components/ChatBubble/ChatPage.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatAvatarExample.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatClickExample.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatFullExample.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatHeaderFooterExample.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatHoverExample.razor
  src/MudBlazor.Docs/Pages/Components/Overview/OverviewPage.razor
  src/MudBlazor.Docs/Pages/Components/Timeline/Examples/TimelineChatExample.razor
  src/MudBlazor.Docs/Pages/Components/Timeline/TimelinePage.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.UnitTests/Components/ChatTests.cs
  src/MudBlazor/Attributes/CategoryAttribute.cs
  src/MudBlazor/Components/ChatBubble/MudChat.razor
  src/MudBlazor/Components/ChatBubble/MudChat.razor.cs
  src/MudBlazor/Components/ChatBubble/MudChatBubble.razor
  src/MudBlazor/Components/ChatBubble/MudChatBubble.razor.cs
  src/MudBlazor/Components/ChatBubble/MudChatFooter.razor
  src/MudBlazor/Components/ChatBubble/MudChatFooter.razor.cs
  src/MudBlazor/Components/ChatBubble/MudChatHeader.razor
  src/MudBlazor/Components/ChatBubble/MudChatHeader.razor.cs
  src/MudBlazor/Enums/ChatArrowPosition.cs
  src/MudBlazor/Enums/ChatBubblePosition.cs
  src/MudBlazor/MudBlazor.csproj.DotSettings
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_chat.scss
Labels: new component, PR: needs review

#10446 MudAutocomplete: Fix overlay
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest8.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Overlay/OverlayNestedFreezeTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Components/UserAttributes/UserAttributesTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor
  src/MudBlazor/TScripts/mudPopover.js
  src/MudBlazor/_Imports.razor
Labels: bug, breaking change

#10459 Menu: Make `Open` a two-way parameter
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuTwoWayBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTwoWayTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: enhancement, PR: needs review

#10462 Tests: Attempt to fix flaky Menu test
  src/MudBlazor.UnitTests/Components/MenuTests.cs
Labels: tests

#10465 Menu: Improve code and web docs
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: docs, PR: needs review

#10466 MudMenu: Small optimization
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: refactor

#10464 Refactor: Cleanup some console messages
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatClickExample.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatHoverExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectWithValueContainZeroTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
Labels: refactor

#10476 MenuItem: Add `Label` parameter
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/ContextMenuExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorExample1.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorExample2.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorOnMouseExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuAdvancedPopoverExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuAnchorOriginExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuIconButtonsExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuMaxHeightExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuTwoWayBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuWithNestingExample.razor
  src/MudBlazor.Docs/Pages/Components/Popover/Examples/PopoverInceptionExampleExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/ContextMenuTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuActivatorsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuHrefTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuItemLabelTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuNoFlipScrollBarTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuPositionAtCursorTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuWithNestingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Overlay/OverlayNestedFreezeTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverAppBarMenuSubMenuTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsWithMenuInHeader.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: enhancement, PR: needs review

#10479 Menu: Optimize pointer events
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: bug, PR: needs review

#10475 MudDataGrid: Align select column and row select behavior
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSelectColumnTest.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#10192 MudNumericField: Use native html input number type
  src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/NumericFieldRenderTest.razor
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: bug

#10494 Docs: Update README
  README.md
Labels: docs, PR: needs review

#10163 Docs: Use a consistent tooltip delay
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor.UnitTests.Viewer/Pages/Index.razor
  src/MudBlazor.UnitTests.Viewer/Shared/MainLayout.razor
Labels: docs, accessibility

#10489 Docs: Reorganize Tabs examples
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsCenteredExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsCustomScrollIconsExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsPositionExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsScrollExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsToolTipExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
Labels: docs, PR: needs review

#10478 MudMenuItem: Decouple from MudListItem & Change icon layout
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarMenuExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuItemCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuItemIconTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
  src/MudBlazor/Styles/components/_menu.scss
Labels: breaking change

#10502 Build: Fixup editorconfig
  src/.editorconfig
Labels: bug, PR: needs review

#10467 MudDrawer: Fix bug related to Z-Index and Overlay
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor/Components/Dialog/MudDialogContainer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, PR: needs review

#10500 MudAutocomplete: Fix OnAdornmentClick regression #10446
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#10483 MudDataGrid: Add CurrentPageChanged EventHandler to enable binding
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCurrentPageParameterTwoWayBindingTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement

#10458 MudTable: Add CurrentPageChanged fot two-way binding (#3563 #6260)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableCurrentPageParameterTwoWayBindingTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
Labels: enhancement

#10507 MudDataGrid: Fix regression ServerData + Virtualize flag (#10495) & Footer columns (#10501)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerDataWithVirtualizeTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#10511 Build: Revert NUnit
  src/MudBlazor.UnitTests.Shared/MudBlazor.UnitTests.Shared.csproj
Labels: build

#10517 README: Fix contribution link when linked from web docs
  ROADMAP.md
Labels: docs, PR: needs review

#10509 MudMenuItem: Add chevrons to submenus and automatically choose anchor origin
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuWithNestingExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuWithNestingTest.razor
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: enhancement, PR: needs review

#10533 MudToggleGroup: Remove `Rounded` in favor of CSS utilities `rounded-*`
  src/MudBlazor.Docs/Components/ApiMemberTable.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleBasicsExample.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: breaking change

#10529 Add theme toggler to unit tests viewer
  src/MudBlazor.UnitTests.Viewer/Pages/Index.razor
  src/MudBlazor.UnitTests.Viewer/Shared/MainLayout.razor
Labels: docs

#10528 DataGrid: Fix the shifting of striped rows when loading
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridLoadingContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridLoadingProgressTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug, PR: needs review

#10540 Docs: Reorganize Menu examples
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorExample1.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorExample2.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuActivatorOnMouseExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuContextMenuExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuDividerExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuIconButtonsExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuItemCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuTwoWayBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
Labels: docs

#10539 MudMenu: Open standard sub menus with left click
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuWithNestingExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuWithNestingTest.razor
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: enhancement

#10542 MudMenu: Bring style closer to Material Design
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
  src/MudBlazor/Styles/components/_menu.scss
Labels: enhancement, PR: needs review
