Repository MudBlazor/MudBlazor, pull requests merged in 2024-05, with the labels that each got.

#8843 Accessibility: Specify website language
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs.Wasm/wwwroot/index.html
  src/MudBlazor.UnitTests.Viewer/wwwroot/index.html
Labels: docs

#8847 Build: Ignore version format check for assembly attribute
  src/.editorconfig
Labels: build

#8833 MudDrawer: Fix initialization behaviour, use ParameterState, remove PreserveOpenState
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerAnchorExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerBreakpointExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerClippingExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerLeftRightExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerMiniCustomExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerMiniExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerOverlayExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerPersistentExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerResponsiveExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerSizeContainerExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerSizeTemporaryExample.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerTemporaryExample.razor
  src/MudBlazor.Docs/Shared/Utilities/IframeLayout.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerResponsiveTest.razor
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
Labels: bug, breaking change, API change, v7

#8829 MudCheckBox/MudChip/MudChipSet/MudCollapse: Added XML Documentation for Public Members
  src/MudBlazor.Docs/Pages/Components/ColorPicker/ColorPickerPage.razor
  src/MudBlazor/Components/AppBar/MudAppBar.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Enums/SelectionMode.cs
  src/MudBlazor/Enums/Variant.cs
Labels: docs

#8735 MudAlert: Fix content alignment issue #8734
  src/MudBlazor/Styles/components/_alert.scss
Labels: PR: needs review

#8867 TreeViewItem: Throw exception when ItemTemplate is misconfigured
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTest8.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: bug, breaking change

#8870 Docs: Standard Language for XML Documentation for Previously Documented Classes
  src/MudBlazor/Base/MudBaseBindableItemsControl.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Base/MudBaseColumn.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudBaseItemsControl.cs
  src/MudBlazor/Base/MudBaseSelectItem.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbItem.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbLink.razor.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbSeparator.razor.cs
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor.cs
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
  src/MudBlazor/Components/Card/MudCard.razor.cs
  src/MudBlazor/Components/Card/MudCardActions.razor.cs
  src/MudBlazor/Components/Card/MudCardContent.razor.cs
  src/MudBlazor/Components/Card/MudCardHeader.razor.cs
  src/MudBlazor/Components/Card/MudCardMedia.razor.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Charts/Pie.razor.cs
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/Chart/Models/ChartSeries.cs
  src/MudBlazor/Components/Chart/MudChart.razor.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor.cs
  src/MudBlazor/Components/Chart/Svg/SvgCircle.cs
  src/MudBlazor/Components/Chart/Svg/SvgLegend.cs
  src/MudBlazor/Components/Chart/Svg/SvgPath.cs
  src/MudBlazor/Components/Chart/Svg/SvgText.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Enums/Edge.cs
Labels: docs

#8866 MudRipple: Fix ripple conditions
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListItemRippleTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsRippleTest.razor
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug, PR: needs review

#8832 Standardise the use of `Visible`
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogInlineExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedInlineExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogNestedInlineExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayAbsoluteExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayColorsExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayLoaderExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayOnClickExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayZIndexExample.razor
  src/MudBlazor.Docs/Pages/Getting Started/Wireframes/WireframesPage.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/InlineDialogIsVisibleStateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestInlineDialog.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/TestNestedInlineDialog.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Overlay/OverlayVisibleBindingWithAutoCloseTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipVisiblePropTest.razor
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Carousel/MudCarouselItem.razor
  src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Models/ChartSeries.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor
  src/MudBlazor/Components/Chart/Svg/SvgLegend.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
Labels: breaking change, API change, v7

#8851 MudDataGrid: Add ICloneStrategy
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFormEditCloneStrategyTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Utilities/Clone/CloneableCloneStrategy.cs
  src/MudBlazor/Utilities/Clone/ICloneStrategy.cs
  src/MudBlazor/Utilities/Clone/SystemTextJsonCloneStrategy.cs
Labels: enhancement, PR: needs review

#8877 MudRating: Use ParameterState framework
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor/Components/Rating/MudRating.razor
  src/MudBlazor/Components/Rating/MudRating.razor.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
Labels: bug

#8649 MudListItem and MudMenuItem: Render as anchor with"Href" property (#1717)
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuWithNestingExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuHrefTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/Element/MudElement.cs
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: bug, breaking change, PR: needs review

#8883 MudRating: make HandleKeyDown async Task
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor/Components/Rating/MudRating.razor
  src/MudBlazor/Components/Rating/MudRating.razor.cs
Labels: bug

#8879 Docs: App bar tweaks to align with v6 & Accessibility
  src/MudBlazor.Docs/Components/DocsPage.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/LandingLayout.razor
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor
Labels: docs

#8881 MudSlider: Add nullable value parameter
  src/MudBlazor.Docs.Compiler/T.cs
  src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
  src/MudBlazor.Docs/Models/T.cs
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderNullableExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/SliderPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithCustomValueLabelContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithNullable.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithTwoBindValues.razor
  src/MudBlazor.UnitTests/Components/SliderTests.cs
  src/MudBlazor/Components/Slider/MudSlider.razor
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
  src/MudBlazor/Components/Slider/SliderContext.cs
Labels: enhancement, breaking change, API change, v7

#8785 MudDialog: When content exceeds hight scroll only content, not title and action buttons
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogScrollableExample_Dialog.razor
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_dialog.scss
  src/MudBlazor/Styles/components/_focustrap.scss
Labels: bug, docs, PR: needs review

#5343 MudDateRangePicker: Add ClearAsync close state test (#5340)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerCloseOnClearTest.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
Labels: tests

#8900 MudGrid: Add nullable annotation.
  src/MudBlazor/Components/Grid/MudFlexBreak.razor
  src/MudBlazor/Components/Grid/MudFlexBreak.razor.cs
  src/MudBlazor/Components/Grid/MudGrid.razor
  src/MudBlazor/Components/Grid/MudGrid.razor.cs
  src/MudBlazor/Components/Grid/MudItem.razor
  src/MudBlazor/Components/Grid/MudItem.razor.cs
Labels: enhancement

#8899 MudText: Return subtitle1 and subtitle2 to block elements (`p`)
  src/MudBlazor/Components/Typography/MudText.razor
Labels: bug, PR: needs review

#8886 Standardise the use of `Selected` and `SelectedChanged`
  src/MudBlazor.Docs/Pages/Components/ChipSet/ChipSetPage.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetChipBindingExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetChipBindingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTemplateTest.razor
  src/MudBlazor.UnitTests/Components/ChipSetTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
  src/MudBlazor/Components/DataGrid/CellContext.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/SelectColumn.razor
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/Select/MudSelectItem.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
Labels: bug, breaking change

#8887 Standardise the use of `ItemDisabled`
  src/MudBlazor.Docs/Pages/Components/DropZone/DropZonePage.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneDisabledExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneDisableTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/ActivateDisabledTabsTest.razor
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
Labels: bug, breaking change, PR: needs review

#8888 Standardise the use of `Active`
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentSection.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
Labels: bug, breaking change, PR: needs review

#8767 Button: Revert sticky focus style
  src/MudBlazor/Styles/components/_button.scss
Labels: bug

#8880 MudForm: Add `Spacing` property
  src/MudBlazor.Docs/Pages/Components/Form/Examples/FormCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/FormPage.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Styles/components/_form.scss
Labels: enhancement, needs tests

#8871 MudInputControl: Fix nested `<div>` inside `<p>`
  src/MudBlazor/Components/InputControl/MudInputControl.razor
Labels: bug

#8892 Standardise the use of `Editable`
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridEditingExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEditableWithSelectColumnTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/DataGrid/Cell.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/SelectColumn.razor
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTableGroupRow.razor
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableButtonPosition.cs
  src/MudBlazor/Components/Table/TableContext.cs
Labels: bug, breaking change, PR: needs review

#8909 MudDatePicker: Fix GoToDate with Persian calendar
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
Labels: bug, PR: needs review

#8915 MudIcon: Add `role="img"`
  src/MudBlazor/Components/Icon/MudIcon.razor
Labels: bug, PR: needs review

#8916 MudText: Ability to control which HTML tag is used
  src/MudBlazor.Docs/Pages/Components/Overview/OverviewPage.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiSelectExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableRecordComparerExample.razor
  src/MudBlazor.Docs/Pages/Components/Typography/Examples/TextGeneralExample.razor
  src/MudBlazor.Docs/Pages/Components/Typography/TypographyPage.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Overview.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/ZIndex.razor
  src/MudBlazor.Docs/Pages/Features/Breakpoints/BreakpointTable.razor
  src/MudBlazor.Docs/Pages/Features/Converters/DefaultConverterTable.razor
  src/MudBlazor.Docs/Pages/Features/Converters/Examples/CustomConverterExample.razor
  src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Content/Examples/Content3WireframeExample.razor
  src/MudBlazor.Docs/Pages/Index.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Releases.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithChildForm.razor
  src/MudBlazor.UnitTests/Components/TextTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor
  src/MudBlazor/Components/Typography/MudText.razor
  src/MudBlazor/Components/Typography/MudText.razor.cs
  src/MudBlazor/Styles/components/_typography.scss
Labels: enhancement, accessibility

#8929 Snackbar: Improve reliability of `InterruptTransitions` test
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
Labels: tests

#8927 MudTable: Code cleanup.
  src/MudBlazor/Components/Table/MudAvatarColumn.razor
  src/MudBlazor/Components/Table/MudAvatarColumn.razor.cs
  src/MudBlazor/Components/Table/MudBaseColumn.cs
  src/MudBlazor/Components/Table/MudColumn.razor
  src/MudBlazor/Components/Table/MudColumn.razor.cs
  src/MudBlazor/Components/Table/MudSortableColumn.razor
  src/MudBlazor/Components/Table/MudSortableColumn.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTemplateColumn.razor
  src/MudBlazor/Components/Table/MudTemplateColumn.razor.cs
Labels: breaking change, refactor, PR: needs review

#8914 Autocomplete: Treat all ways of closing overlay the same
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#8930 MudTable: add QuickColumns as illegal parameter
  src/MudBlazor/Base/MudComponentBase.cs
Labels: PR: needs review

#8935 MudGlobal: Add `InputDefaults.ShrinkLabel`
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: enhancement

#8943 Utilities: Increase max spacing/gap to `20` from `16`
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Components/Stack/MudStack.razor.cs
  src/MudBlazor/Styles/utilities/flexbox/_gap.scss
  src/MudBlazor/Styles/utilities/spacing/_spacing.scss
Labels: enhancement, PR: needs review

#8938 MudPopover: Add DropShadow property
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverPropertyTest.razor
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: enhancement, PR: needs review

#8934 MudContainer: Add `Gutters` property
  src/MudBlazor.UnitTests/Components/ContainerTests.cs
  src/MudBlazor/Components/Container/MudContainer.razor
  src/MudBlazor/Styles/layout/_container.scss
Labels: enhancement, PR: needs review

#8953 MudMenu: Forward DropShadow property
  src/MudBlazor/Components/Menu/MudMenu.razor
Labels: bug, PR: needs review

#8913 MudAutocomplete: `ItemDisabledTemplate` and `ItemSelectedTemplate` will now display even if `ItemTemplate` is not defined.
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteClrObjectsExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteItemTemplateDisplayTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
Labels: bug, breaking change, PR: needs review

#8948 MudTreeviewItem: Fix checkbox in multi-selection mode
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomCheckboxExample.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: bug

#8954 MudSlider: Rename Culture and ValueLabelFormat
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderValueLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/SliderPage.razor
  src/MudBlazor.UnitTests/Components/SliderTests.cs
  src/MudBlazor/Components/Slider/MudSlider.razor
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
Labels: refactor

#8941 MudDrawer: Improve breakpoint logic
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
Labels: bug, PR: needs review

#8921 MudListItem: SecondaryText Feature
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListSimpleExample.razor
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Styles/components/_list.scss
Labels: enhancement, PR: needs review

#8949 Tests: fix slider tests failing on certain cultures
  src/MudBlazor.UnitTests/Components/SliderTests.cs
Labels: PR: needs review

#8872 Docs: MudColorPicker: Added XML Documentation for Public Members
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudBaseSelectItem.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/AppBar/MudAppBar.razor.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbItem.cs
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
  src/MudBlazor/Components/Card/MudCard.razor.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/Chart/Models/ChartSeries.cs
  src/MudBlazor/Components/Chart/MudChart.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor.cs
  src/MudBlazor/Enums/ColorPickerMode.cs
  src/MudBlazor/Enums/ColorPickerView.cs
  src/MudBlazor/Services/MudGlobal.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: docs

#8933 MudCard: Fix content not filling remaining space
  src/MudBlazor/Styles/components/_card.scss
Labels: bug, PR: needs review

#8952 Standardise the use of `Hidden` and `HiddenChanged`
  src/MudBlazor.UnitTests.Viewer/TestComponents/Hidden/SimpleMudHiddenTest.razor
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Hidden/MudHidden.razor
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
Labels: bug, breaking change, PR: needs review

#8853 MudDataGrid: Apply Footer/Header Style Funcs
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridVisualStylingTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/FooterCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
Labels: bug

#8957 TreeView: Update parent selection on item click in multi-selection mode
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomCheckboxExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewMultiSelectionExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: bug, v7

#8963 WasmHost / Examples.Data: Add nullable annotation.
  src/MudBlazor.Docs.Server/Controllers/AmericanStatesController.cs
  src/MudBlazor.Docs.Server/Controllers/PeriodicTableController.cs
  src/MudBlazor.Docs.Server/Program.cs
  src/MudBlazor.Docs.Wasm/Program.cs
  src/MudBlazor.Docs.WasmHost/Controllers/AmericanStatesController.cs
  src/MudBlazor.Docs.WasmHost/Controllers/OperationCancelledExceptionFilter.cs
  src/MudBlazor.Docs.WasmHost/Controllers/PeriodicTableController.cs
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml.cs
  src/MudBlazor.Docs.WasmHost/Prerender/FileBasedCrawlerIdentifier.cs
  src/MudBlazor.Docs.WasmHost/Prerender/ICrawlerIdentifier.cs
  src/MudBlazor.Docs.WasmHost/Prerender/LimitedConcurrentDictionary.cs
  src/MudBlazor.Docs.WasmHost/Prerender/PrerenderMiddleware.cs
  src/MudBlazor.Docs.WasmHost/Prerender/PrerenderMiddlewareExtensions.cs
  src/MudBlazor.Docs.WasmHost/Program.cs
  src/MudBlazor.Examples.Data/AmericanStates.cs
  src/MudBlazor.Examples.Data/IPeriodicTableService.cs
  src/MudBlazor.Examples.Data/Models/Element.cs
  src/MudBlazor.Examples.Data/Models/ElementGroup.cs
  src/MudBlazor.Examples.Data/Models/Server.cs
  src/MudBlazor.Examples.Data/Models/Table.cs
  src/MudBlazor.Examples.Data/MudBlazor.Examples.Data.csproj
  src/MudBlazor.Examples.Data/PeriodicTableService.cs
Labels: enhancement

#8964 Dialog: Fix possible deadlock
  src/MudBlazor/Components/Dialog/DialogReference.cs
Labels: bug

#8962 Tests: Add support for specifying generic type parameters per component and remove class T
  src/.editorconfig
  src/MudBlazor.Docs.Compiler/T.cs
  src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
Labels: docs, PR: needs review

#8910 MudGrid: Refactor and normalize spacing system
  src/MudBlazor.Docs/Pages/Components/Grid/Examples/GridSpacingExample.razor
  src/MudBlazor/Components/Grid/MudGrid.razor.cs
  src/MudBlazor/Components/Grid/MudItem.razor.cs
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_flexbreak.scss
  src/MudBlazor/Styles/components/_grid.scss
Labels: bug, breaking change, PR: needs review

#8950 TaskExtensions: Rename AndForget() to CatchAndLog()
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelAsyncExample.razor
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor.UnitTests/Extensions/TaskExtensionsTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Components/Input/MudDebouncedInput.cs
  src/MudBlazor/Components/Input/MudRangeInput.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Extensions/TaskExtensions.cs
  src/MudBlazor/Services/JsEvent/JsEvent.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
Labels: refactor, PR: needs review

#8955 Docs: MudDrawer: Added XML Documentation for Public Members
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerHeader.razor
  src/MudBlazor/Components/Drawer/MudDrawerHeader.razor.cs
  src/MudBlazor/Enums/Anchor.cs
  src/MudBlazor/Enums/DrawerClipMode.cs
  src/MudBlazor/Enums/DrawerVariant.cs
  src/MudBlazor/Services/Browser/Breakpoint.cs
Labels: docs

#8968 Build: Fix invalid version string in assembly info for dotnet pack
  .github/workflows/deploy-mudblazor-nuget.yml
  .github/workflows/deploy-mudblazor.yml
  src/.editorconfig
Labels: bug, PR: needs review

#8969 Installation: Update Add font and sytle references section
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Labels: docs, PR: needs review

#8970 MudMask: Remove CatchAndLog usage
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
Labels: bug

#8978 Build: Update dotnet runtime libs
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: build, PR: needs review

#8979 EventManager: Fix JsonSerializerOptions instances cannot be modified.
  src/MudBlazor/Services/EventManager/EventManager.cs
Labels: bug

#8972 MudTooltip: Use ParameterState framework
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
Labels: bug, PR: needs review

#8980 MudNavGroup: Use ParameterState framework
  src/MudBlazor.UnitTests/Components/NavigationAccessibilityTests.cs
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
Labels: bug, PR: needs review

#8981 Docs: Update List Docs to replace Clickable with ReadOnly
  src/MudBlazor.Docs/Pages/Components/List/ListPage.razor
Labels: docs

#8932 DatePicker: default OpenTo to Year when both FixDay and FixMonth are provided
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: bug

#5463 MudRating: Added optional parameters for Full and Empty Icon Color
  src/MudBlazor.Docs/Pages/Components/Rating/Examples/RatingIconsAndColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Rating/RatingPage.razor
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor/Components/Rating/MudRating.razor.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
Labels: enhancement, API change

#8990 Autocomplete: Give async methods Async suffix
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
  src/MudBlazor.UnitTests.Viewer/Pages/Index.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: breaking change, API change, PR: needs review

#9002 MudDataGrid: Removed Unused "Row" Class
  src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs
  src/MudBlazor/Components/DataGrid/Row.razor
  src/MudBlazor/Components/DataGrid/Row.razor.cs
Labels: bug, PR: needs review

#8966 MudAlert, MudToggleIconButton, MudChip: Improve accessibility
  src/MudBlazor/Components/Alert/MudAlert.razor
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudToggleIconButton.razor
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor
  src/MudBlazor/Components/Element/MudElement.cs
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
Labels: enhancement, PR: needs review

#8987 Palette: Make all properties `virtual` & Improve docs
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Themes/Models/PaletteDark.cs
Labels: enhancement

#8986 MudAvatar, MudAvatarGroup, MudBadge: Improve accessibility
  src/MudBlazor.UnitTests/Components/BadgeTests.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor
  src/MudBlazor/Components/Badge/MudBadge.razor
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
Labels: enhancement

#9010 MudMessageBox: Fix `visible` should be `Visible`
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
Labels: bug

#8974 Replace mouse events with pointer events in applicable components
  src/MudBlazor.Docs/Pages/Components/Icons/IconsPage.razor
  src/MudBlazor.Docs/Pages/Components/Image/DocsImagePageResizer.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRowHoverTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/DynamicTabsTests.cs
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Components/DataGrid/DataGridColumnResizeService.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/Drawer/MudDrawer.razor
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableRowHoverEventArgs.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
Labels: bug, breaking change, PR: needs review, v7, accessibility

#9008 Remove MudSparkline component
  src/MudBlazor.Docs/Pages/Components/Sparkline/Examples/SparkLineExample.razor
  src/MudBlazor.Docs/Pages/Components/Sparkline/SparklinePage.razor
  src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs
  src/MudBlazor/Components/Sparkline/MudSparkLine.razor
Labels: breaking change, PR: needs review

#9000 Docs: MudDataGrid: Added XML Documentation for Public Members
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/Components/DataGrid/AggregateDefinition.cs
  src/MudBlazor/Components/DataGrid/AggregateType.cs
  src/MudBlazor/Components/DataGrid/CellContext.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/DataGridEditMode.cs
  src/MudBlazor/Components/DataGrid/DataGridEditTrigger.cs
  src/MudBlazor/Components/DataGrid/DataGridFilterCaseSensitivity.cs
  src/MudBlazor/Components/DataGrid/DataGridFilterMode.cs
  src/MudBlazor/Components/DataGrid/DataGridRowClickEventArgs.cs
  src/MudBlazor/Components/DataGrid/DataGridRowValidator.cs
  src/MudBlazor/Components/DataGrid/Definition/FilterDefinition.cs
  src/MudBlazor/Components/DataGrid/Definition/IFilterDefinition.cs
  src/MudBlazor/Components/DataGrid/FieldType.cs
  src/MudBlazor/Components/DataGrid/FilterContext.cs
  src/MudBlazor/Components/DataGrid/FilterExpressionGenerator.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/FilterOperator.cs
  src/MudBlazor/Components/DataGrid/FilterOptions.cs
  src/MudBlazor/Components/DataGrid/FooterCell.razor.cs
  src/MudBlazor/Components/DataGrid/FooterContext.cs
  src/MudBlazor/Components/DataGrid/GridState.cs
  src/MudBlazor/Components/DataGrid/GroupDefinition.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
  src/MudBlazor/Components/DataGrid/SelectColumn.razor.cs
  src/MudBlazor/Components/DataGrid/SortDefinition.cs
  src/MudBlazor/Components/DataGrid/TemplateColumn.cs
  src/MudBlazor/Enums/Page.cs
  src/MudBlazor/Enums/ResizeMode.cs
  src/MudBlazor/Enums/SortMode.cs
Labels: docs

#9007 MudFocusTrap, MudFlexBreak, MudIcon, MudSpacer: Improve accessibility
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor
  src/MudBlazor/Components/Grid/MudFlexBreak.razor
  src/MudBlazor/Components/Grid/MudFlexBreak.razor.cs
  src/MudBlazor/Components/Icon/MudIcon.razor
  src/MudBlazor/Components/Spacer/MudSpacer.razor
Labels: enhancement, PR: needs review

#9022 MudColorPicker, MudBaseDatePicker, MudTimePicker: Add localizable labels
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
Labels: enhancement, PR: needs review

#9017 MudListItem, MudMenu, MudMenuItem: Format razor markup
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor
Labels: refactor, PR: needs review

#9036 Docs: clean up file upload example
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadButtonExample.razor
Labels: docs

#9027 Docs: Announcement and roadmap for v7 GA
  ROADMAP.md
  src/MudBlazor.Docs/NotificationContent/Announcement_v7_GA.razor
  src/MudBlazor.Docs/Services/Notifications/InMemoryNotificationService.cs
Labels: docs, PR: needs review

#9028 Docs: v7 announcement (for v6 branch)
  src/MudBlazor.Docs/NotificationContent/Announcement_v7.razor
  src/MudBlazor.Docs/Services/Notifications/InMemoryNotificationService.cs
Labels: docs, PR: needs review

#9037 MudColor: Add uint support.
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: enhancement

#9042 MudThemeProvider: Wrap JS in a try-catch
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
Labels: bug

#9026 MudIcon: Add font icon support with additional syntax
  src/MudBlazor.Docs/Pages/Components/Icons/Examples/IconsFontAwesomeExample.razor
  src/MudBlazor.Docs/Pages/Components/Icons/Examples/IconsFontMaterialSymbolsSyntaxExample.razor
  src/MudBlazor.Docs/Pages/Components/Icons/IconsPage.razor
  src/MudBlazor.UnitTests/Components/IconTests.cs
  src/MudBlazor/Components/Icon/MudIcon.razor
  src/MudBlazor/Components/Icon/MudIcon.razor.cs
Labels: enhancement

#9019 DataGrid: ServerData with Virtualization
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCellEditVirtualizationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterableVirtualizationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSortableVirtualizationItemsProviderTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs
Labels: enhancement, PR: needs review

#9033 ParameterState: Solve inheritance problem (Solution 2)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateMultipleScopeTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateMultipleScopeTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateSharedInheritanceHandlerTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/SharedStateInheritanceTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/SharedStateInheritanceTestComp.razor.cs
  src/MudBlazor.UnitTests/State/Builder/ParameterRegistrationBuilderScopeTests.cs
  src/MudBlazor.UnitTests/State/ParameterSetTests.cs
  src/MudBlazor.UnitTests/State/ParameterSetUnionTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor/Base/ComponentBaseWithState.cs
  src/MudBlazor/Components/Input/MudDebouncedInput.cs
  src/MudBlazor/Extensions/ComponentBaseWithStateExtensions.cs
  src/MudBlazor/State/Builder/ParameterRegistrationBuilderScope.cs
  src/MudBlazor/State/IParameterStatesReader.cs
  src/MudBlazor/State/IParameterStatesReaderOwner.cs
  src/MudBlazor/State/ParameterMetadata.cs
  src/MudBlazor/State/ParameterSet.cs
  src/MudBlazor/State/ParameterSetUnion.cs
  src/MudBlazor/State/ParameterStateInternalOfT.cs
Labels: bug, enhancement, PR: needs review

#9045 Fix DefaultConverter.DefaultCulture
  src/MudBlazor/Utilities/BindingConverters/Converters.cs
Labels: breaking change, PR: needs review

#9048 MudPicker: Added XML Documentation for Public Members
  src/MudBlazor/Components/DatePicker/DateRange.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
  src/MudBlazor/Components/Input/Range.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Picker/MudPickerContent.razor.cs
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor.cs
  src/MudBlazor/Enums/Margin.cs
  src/MudBlazor/Enums/OpenToView.cs
  src/MudBlazor/Enums/Orientation.cs
  src/MudBlazor/Enums/Origin.cs
  src/MudBlazor/Enums/PickerVariant.cs
  src/MudBlazor/Enums/Size.cs
  src/MudBlazor/Extensions/DateTimeExtensions.cs
Labels: docs, PR: needs review

#9060 Progress: Improve accessibility
  src/MudBlazor/Components/Progress/MudProgressCircular.razor
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
Labels: accessibility

#9030 Dialog: Revert #8964 (Fix possible deadlock)
  src/MudBlazor/Components/Dialog/DialogReference.cs
Labels: bug, accidental break

#9065 MudText: Revert removal of parameter Inline
  src/MudBlazor.Docs/Pages/Components/Typography/Examples/TextInlineExample.razor
  src/MudBlazor.Docs/Pages/Components/Typography/TypographyPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Typography/TextInlineTest.razor
  src/MudBlazor.UnitTests/Components/TypographyTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Typography/MudText.razor.cs
Labels: enhancement, PR: needs review

#9059 MudCollapse, MudStack, MudToolbar: Improve accessibility
  src/MudBlazor/Components/Collapse/MudCollapse.razor
  src/MudBlazor/Components/Stack/MudStack.razor
  src/MudBlazor/Components/ToolBar/MudToolBar.razor
  src/MudBlazor/Components/ToolBar/MudToolBar.razor.cs
Labels: enhancement, PR: needs review, accessibility

#9058 Rating, ToggleGroup: Improve accessibility
  src/MudBlazor/Components/Rating/MudRating.razor
  src/MudBlazor/Components/Rating/MudRating.razor.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor
  src/MudBlazor/Components/Toggle/MudToggleItem.razor
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
Labels: enhancement, PR: needs review, accessibility

#9064 MudLink, MudPagination, MudSnackbarElement: Improve accessibility
  src/MudBlazor/Components/Link/MudLink.razor.cs
  src/MudBlazor/Components/Pagination/MudPagination.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
Labels: enhancement, PR: needs review, accessibility

#9069 MudRating: Fix Color regression #5463
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor/Components/Rating/MudRating.razor.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
Labels: bug, accidental break

#9074 Snackbar: Make tests less flaky
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
Labels: tests

#9001 MudTabPanel: Allow icon color to be set from panel
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabPanelIconColorTest.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabPanel.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: enhancement

#9073 MudDataGrid: Fix column resizing in RTL (#6965)
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridResizeExample.razor
  src/MudBlazor/Components/DataGrid/DataGridColumnResizeService.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Styles/components/_datagrid.scss
Labels: bug, rtl

#9088 Docs: Remove alias Hiliter for Highlighter
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
Labels: docs
