Repository MudBlazor/MudBlazor, pull requests merged in 2024-04, with the labels that each got.

#8543 DateRangePicker: Fix tests - update selected range to use future dates
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerPresetRangeWithTimestampTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerPresetWithoutTimestampTest.razor
Labels: bug

#8463 MudDataGrid: Fix grouping for bound and unbound scenarios using ParameterState
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridColumnsPanelExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnGroupingTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, breaking change

#8544 Docs: Fix Regex
  src/MudBlazor.Docs/Models/DocStrings.cs
Labels: docs, accidental break, PR: needs review

#8531 Remove obsolete Extensions, Services, Utilities
  src/MudBlazor.UnitTests/Mocks/MockBrowserWindowSizeProvider.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Extensions/TaskExtensions.cs
  src/MudBlazor/Services/BrowserWindowSizeProvider.cs
  src/MudBlazor/Utilities/BindingConverters/NumericConverter.cs
  src/MudBlazor/Utilities/ColorManager.cs
  src/MudBlazor/Utilities/ColorTransformation.cs
Labels: breaking change, API change, refactor, v7

#8532 Components: Remove more obsolete members
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDatePickerExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDrawerExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormFieldChangedTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormReadOnlyDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormShouldRegisterOnlyTopSubscribeToParentFormFormControlsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithRadioGroupTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/SwipeArea/SwipeAreaTest.razor
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/Chart/Interpolation/ILineInterpolator.cs
  src/MudBlazor/Components/Chart/Interpolation/NoInterpolation.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
Labels: breaking change, API change, refactor, v7

#8547 MudFileUpload: Make FileUploadButtonTemplateContext.ClearAsync required
  src/MudBlazor/Components/FileUpload/FileUploadButtonTemplateContext.cs
Labels: breaking change, API change, refactor

#8548 MudDataGrid: Remove obsolete API
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Definition/FilterDefinition.cs
  src/MudBlazor/Components/DataGrid/Definition/IFilterDefinition.cs
  src/MudBlazor/Components/DataGrid/FilterContext.cs
  src/MudBlazor/Components/DataGrid/FooterContext.cs
Labels: breaking change, API change, refactor, PR: needs review

#8400 DataGrid: Fix row filter not working when columns are reordered.
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColReorderRowFiltersTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
Labels: bug, PR: needs review

#8540 Input: Don't add margin-top when input has no Label
  src/MudBlazor.UnitTests.Viewer/TestComponents/General/AllInputsTest.razor
  src/MudBlazor/Components/Field/MudField.razor.cs
  src/MudBlazor/Components/Input/MudInputCssHelper.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/Radio/MudRadio.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Styles/components/_inputcontrol.scss
  src/MudBlazor/Styles/components/_radio.scss
  src/MudBlazor/Styles/components/_switch.scss
Labels: bug, breaking change, v7

#8545 MudStack: Add parameter StretchItems to have certain children fill space
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackInteractiveExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackLayoutExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackStretchItemsExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/StackPage.razor
  src/MudBlazor.UnitTests/Components/StackTests.cs
  src/MudBlazor/Components/Stack/MudStack.razor.cs
  src/MudBlazor/Enums/AlignItems.cs
  src/MudBlazor/Enums/Justify.cs
  src/MudBlazor/Enums/StretchItems.cs
  src/MudBlazor/Styles/utilities/flexbox/_flex-grow.scss
Labels: enhancement

#8515 Docs: Style refinements & Always show search bar
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/Footer.razor
  src/MudBlazor.Docs/Shared/LandingLayout.razor
  src/MudBlazor.Docs/Theme/Theme.cs
Labels: docs

#8450 ParameterState: Add GetState extension
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateTestComp.razor.cs
  src/MudBlazor.UnitTests/State/ParameterSetTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor/Base/MudComponentBase.RegisterParameter.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Extensions/MudComponentExtensions.cs
  src/MudBlazor/State/ParameterSet.cs
  src/MudBlazor/State/ParameterStateOfT.cs
Labels: enhancement

#8317 MudDataGrid: Respect indeterminate state in select-all checkboxes
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSelectColumnTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FooterContext.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
  src/MudBlazor/Components/DataGrid/SelectColumn.razor
Labels: bug, breaking change, API change, PR: needs review

#8564 Several Components: Remove obsolete API
  src/MudBlazor.UnitTests.Viewer/TestComponents/Button/ButtonGroupTooltipsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCellEditWithTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnPopupCustomFilteringTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridConditionalLogicOnColumnsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCustomFilteringTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCustomSortableTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterRowCustomFilteringTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFormatTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormIsValidTest3.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormIsValidTest4.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithCheckboxTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithChildForm.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuGroupDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/SwipeArea/SwipeAreaOnSwipeEndTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableGroupLoadingAndNoRecordsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableLoadingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelection_MultiGrouping_DefaultCheckboxStatesTest.razor
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
  src/MudBlazor/Interfaces/IFormComponent.cs
  src/MudBlazor/Services/DialogService.cs
  src/MudBlazor/Services/Scroll/ScrollManager.cs
Labels: breaking change, API change, v7

#8561 MudTabs: Fix overflow when using high border radius values
  src/MudBlazor/Styles/components/_tabs.scss
Labels: bug, PR: needs review

#8569 MudTabs: Rename toolbar to tabbar in C# and CSS
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
  src/MudBlazor.Docs/Styles/pages/_landingpage.scss
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Styles/components/_tabs.scss
Labels: breaking change, v7

#8568 Remove more obsoletes
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithRadioGroupTest.razor
  src/MudBlazor/Components/Carousel/MudCarousel.razor
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Themes/Models/LayoutProperties.cs
Labels: breaking change, API change, refactor, v7

#8573 Docs: Fix link targets not working because of typo in property name
  src/MudBlazor.Docs/Pages/Index.razor
Labels: bug, docs

#8459 MudSelect: Fix Un-SelectAll with Disabled MudSelectItems (#8420)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest7.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: PR: needs review

#8571 Various Components: Rename DisableRipple to Ripple
  src/MudBlazor.UnitTests.Viewer/TestComponents/Switch/MudSwitchTest.razor
  src/MudBlazor/Attributes/CategoryAttribute.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Base/MudBaseSelectItem.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Button/MudToggleIconButton.razor
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
  src/MudBlazor/Components/Pagination/MudPagination.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Rating/MudRating.razor
  src/MudBlazor/Components/Rating/MudRating.razor.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
Labels: breaking change, API change, PR: needs review, v7

#6031 MudTable: Add ContainerStyle and ContainerClass parameters
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTableBase.cs
Labels: enhancement, API change

#8526 Code Cleanup: Improved Performance of MudComponentBase, ResizeObserver, and EventListener
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Services/EventManager/EventManager.cs
  src/MudBlazor/Services/ResizeObserver/ResizeObserver.cs
Labels: bug, PR: needs review

#8579 MudColor: Add XML comments and make it serializable with STJ / NewtonsoftJson
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: bug

#8595 Build: Update wording for Issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.MD
Labels: build

#8600 Docs: remove dead code in IconPage.
  src/MudBlazor.Docs/Models/MudIcons.cs
  src/MudBlazor.Docs/Models/MudVirtualizedIcons.cs
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor.cs
Labels: docs, refactor

#8582 Optimization: Make PeriodicTableService a Singleton Service
  src/MudBlazor.Docs/Extensions/DocsViewExtension.cs
  src/MudBlazor.Examples.Data/PeriodicTableService.cs
Labels: bug, performance, refactor

#8601 CONTRIBUTING.md: Fix code sample
  CONTRIBUTING.md
Labels: docs

#8445 Docs: Fix Color Picker example usage #8444
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerExampleUsageExample.razor
Labels: bug, PR: needs review

#8297 MudList: Add Nullable and use ParameterState
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListSelectionExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionInitialValueTest.razor
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/List/MudListSubheader.razor.cs
Labels: enhancement

#8575 MudButton: fix focus style button when open dialog
  src/MudBlazor/Styles/components/_button.scss
Labels: bug, PR: needs review

#8576 Color Picker: Drag smoothly
  src/MudBlazor.Docs/Pages/Components/ColorPicker/ColorPickerPage.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerDragEffectDisabledExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerDragExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ColorPicker/SimpleColorPickerTest.razor
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Utilities/Debounce/DebounceDispatcherTests.cs
  src/MudBlazor.UnitTests/Utilities/Throttle/ThrottleDispatcherTests.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Styles/components/_pickercolor.scss
  src/MudBlazor/Utilities/Debounce/DebounceDispatcher.cs
  src/MudBlazor/Utilities/MudColor.cs
  src/MudBlazor/Utilities/Throttle/ThrottleDispatcher.cs
Labels: enhancement

#8598 Chip: Don't apply hover or focus effect if not clickable and allow text selection
  src/MudBlazor/Styles/components/_chip.scss
Labels: enhancement, breaking change, v7

#8593 MudExpansionPanels: Rename `DisableBorders` to `Outlined`
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelOutlinedExample.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/ExpansionPanelPage.razor
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
Labels: breaking change, API change, PR: needs review, v7

#8599 Chip: Remove special palette variables
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemingProvider.razor.cs
  src/MudBlazor/Styles/components/_chip.scss
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Themes/Models/PaletteDark.cs
Labels: bug, breaking change, API change, v7

#8612 Tests: Fix flaky ThrottleDispatcherTests
  src/MudBlazor.UnitTests/Utilities/Throttle/ThrottleDispatcherTests.cs
Labels: refactor

#8580 Various Components: Rename DisableGutters to just Gutters
  src/MudBlazor.Docs/Components/DocsPage.razor
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
  src/MudBlazor.Docs/Components/NavigationFooter.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneKanbanExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneMailExample.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelPaddingExample.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/ExpansionPanelPage.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/DragAndDropFileUploadExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropCustomScenarioExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropWithFormValidationExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListInteractiveExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayLoaderExample.razor
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
  src/MudBlazor.Docs/Pages/Mud/Announcements/AnnoucementPage.razor
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/Footer.razor
  src/MudBlazor.Docs/Shared/LandingLayout.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadButtonTemplateContextTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithFileUploadAndButtonTemplateContextTest.razor
  src/MudBlazor/Attributes/CategoryAttribute.cs
  src/MudBlazor/Components/AppBar/MudAppBar.razor
  src/MudBlazor/Components/AppBar/MudAppBar.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/List/MudListSubheader.razor.cs
  src/MudBlazor/Components/ToolBar/MudToolBar.razor
  src/MudBlazor/Styles/components/_expansionpanel.scss
Labels: breaking change, API change, PR: needs review, v7

#8627 RenderQueueService: Changed From Singleton to Scoped
  src/MudBlazor.Docs.WasmHost/Program.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
Labels: bug, PR: needs review

#8631 Docs: Add missing spaces in aliases and register Expander for Collapse
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
Labels: docs

#8621 Docs: Add danielchalmers and jperson2000 to Contributors
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
Labels: docs

#8632 MudMenu: Add nullable annotation.
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: enhancement

#8635 MudBaseInput: Add nullable annotation.
  src/MudBlazor/Base/MudBaseInput.cs
Labels: enhancement

#8638 Docs: Fix DarkLightMode button out of sync
  src/MudBlazor.Docs/Services/LayoutService.cs
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
  src/MudBlazor.Docs/Shared/AppbarButtons.razor.cs
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
Labels: docs

#8618 MudAlert: Add XML Documentation for Public Members
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
Labels: enhancement, PR: needs review

#8623 MudAutocomplete: Fix missing margin-top when label is set
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
Labels: bug, PR: needs review

#8633 Docs: Fix contributor GitHub icon colors in dark mode
  src/MudBlazor.Docs/Components/MudContributor.razor
  src/MudBlazor.Docs/Components/MudTeamCard.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
Labels: docs, PR: needs review

#8613 MudList: Generic MudList<T> and other improvements
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarBottomExample.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteProgressExample.razor
  src/MudBlazor.Docs/Pages/Components/BreakpointProvider/Examples/BreakpointListenerExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerExampleUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Divider/Examples/DividerInsertExample.razor
  src/MudBlazor.Docs/Pages/Components/Divider/Examples/DividerListExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneDisabledExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneItemSelectorExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneItemSelectorReorderingExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneMailExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneReorderSaveExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadButtonExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadEventOptionsExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadMultipleAcceptExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithCustomStyleExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithListExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithListMultipleExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListColorExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListFolderExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListInteractiveExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListNestedExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListSelectionExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/List/ListPage.razor
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
  src/MudBlazor.Docs/Pages/Getting Started/Layouts/LayoutsPage.razor
  src/MudBlazor.Docs/Pages/Getting Started/Usage/Examples/RightClickDrawerExample.razor
  src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Content/Examples/Content2WireframeExample.razor
  src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Content/Examples/Content3WireframeExample.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneItemClassSelectorTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneItemOnItemPickedTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneReorderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListDenseInheritanceTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionInitialValueTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/List/MudList.razor
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: breaking change, API change, PR: needs review, v7

#8363 MudDataGridPager: Add ShowNavigation and ShowPageNumber
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAdvancedExample.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
Labels: enhancement

#8629 ParameterState: Func Comparer, implicit operator support
  CONTRIBUTING.md
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildBindingTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerStaticTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerStaticTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerSwapTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerSwapTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/SharedStateHandlerTestComp.razor.cs
  src/MudBlazor.UnitTests/State/Builder/RegisterParameterBuilderTests.cs
  src/MudBlazor.UnitTests/State/ParameterSetTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor.UnitTests/State/Rule/ParameterMetadataRulesTests.cs
  src/MudBlazor/Base/MudComponentBase.RegisterParameter.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Extensions/MudComponentExtensions.cs
  src/MudBlazor/State/Builder/IParameterSetRegister.cs
  src/MudBlazor/State/Builder/ISmartAttachable.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilder.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilderOfT.cs
  src/MudBlazor/State/Builder/RegisterParameterBuilder.cs
  src/MudBlazor/State/Builder/RegisterParameterBuilderOfT.cs
  src/MudBlazor/State/ParameterChangedEventArgs.cs
  src/MudBlazor/State/ParameterMetadata.cs
  src/MudBlazor/State/ParameterState.cs
  src/MudBlazor/State/ParameterStateInternalOfT.cs
  src/MudBlazor/State/Rule/Exclusion/ComparerParameterLambdaExclusion.cs
  src/MudBlazor/State/Rule/Exclusion/HandlerLambdaExclusion.cs
  src/MudBlazor/State/Rule/Exclusion/IExclusion.cs
  src/MudBlazor/State/Rule/ParameterMetadataRules.cs
  src/MudBlazor/Utilities/Comparer/DoubleEpsilonEqualityComparer.cs
Labels: enhancement

#8637 Alert: Remove AlertTextPosition
  src/MudBlazor/Components/Alert/AlertTextPosition.cs
Labels: breaking change, API change, v7

#8663 Docs: Add TitleContent to first Dialog example for completeness
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogUsageExample_Dialog.razor
Labels: PR: needs review

#8652 ToggleGroup: Fix border rounding overflow on selected item
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleBasicsExample.razor
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: bug, PR: needs review

#8591 Various Components: Rename DisableUnderLine to Underline
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneKanbanExample.razor
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
  src/MudBlazor/Components/Field/MudField.razor.cs
  src/MudBlazor/Components/Input/MudInputCssHelper.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Table/MudTablePager.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: breaking change, API change, PR: needs review, v7

#8662 MudDataGrid: Rename `DisableRowsPerPage` to `PageSizeSelector`
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridPaginationTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
Labels: breaking change, API change, v7

#8643 Docs: Improve appbar UX
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
  src/MudBlazor.Docs/Shared/AppbarButtons.razor.cs
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/LandingLayout.razor
Labels: docs

#8630 Buttons: Make Title a base property
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
Labels: enhancement, PR: needs review

#8602 Docs: Cookie consent.
  src/MudBlazor.Docs.Server/App.razor
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs.Server/Program.cs
  src/MudBlazor.Docs.Wasm/App.razor
  src/MudBlazor.Docs.Wasm/wwwroot/index.html
  src/MudBlazor.Docs/Components/DocsPage.razor
  src/MudBlazor.Docs/Extensions/DocsViewExtension.cs
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/Pages/Consent/CookiePolicy.razor
  src/MudBlazor.Docs/Pages/Consent/Prompt/MudCookieConsentPrompt.razor
  src/MudBlazor.Docs/Pages/Consent/Prompt/MudCookieConsentPrompt.razor.cs
  src/MudBlazor.Docs/Pages/Consent/Prompt/MudCookieConsentPromptVariant.cs
  src/MudBlazor.Docs/Shared/Footer.razor
  src/MudBlazor.Docs/Styles/MudBlazorDocs.scss
  src/MudBlazor.Docs/Styles/components/_consent.scss
  src/MudBlazor.sln
  src/MudBlazor/MudBlazor.csproj
Labels: docs

#8634 MudMenu: Improve Encapsulation, public API is now Async
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTestMouseOver.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
Labels: breaking change, API change, v7

#8668 Docs: Fancify dialog styling example
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogStylingExample_Dialog.razor
Labels: enhancement, PR: needs review

#8655 Docs: Merge nav menu links between all pages
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/NavMenu.razor
Labels: docs

#8677 MudListItem: Replace Avatar and AvatarClass with AvatarContent
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListAvatarExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListFolderExample.razor
  src/MudBlazor.Docs/Pages/Components/List/ListPage.razor
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
Labels: breaking change, API change, v7

#8681 Docs: Update roadmap for v7 previews
  ROADMAP.md
Labels: enhancement, PR: needs review

#8651 Global: Add transition duration and delay options
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
  src/MudBlazor/Styles/components/_picker.scss
Labels: enhancement, PR: needs review

#8682 Docs: Improve navigation UX & Several misc tweaks
  src/MudBlazor.Docs/Pages/Components/AppBar/AppBarPage.razor
  src/MudBlazor.Docs/Pages/Components/Overview/OverviewPage.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor.Docs/Pages/Index.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/Footer.razor
  src/MudBlazor.Docs/Shared/LandingLayout.razor
  src/MudBlazor.Docs/Shared/NavMenu.razor
  src/MudBlazor.Docs/Shared/NavMenu.razor.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor
Labels: docs

#8688 DateRangePicker: Margin top missing when label is set
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
Labels: bug

#8640 MudAppBar: Add XML Documentation for Public Members
  src/MudBlazor.Docs/Pages/Components/AppBar/AppBarPage.razor
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarDenseExample.razor
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarElevationExample.razor
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarUsageExample.razor
  src/MudBlazor/Components/AppBar/MudAppBar.razor.cs
Labels: enhancement, PR: needs review

#8696 Docs: Cookie prompt style changes
  src/MudBlazor.Docs/Pages/Consent/Prompt/MudCookieConsentPrompt.razor
  src/MudBlazor.Docs/Styles/components/_consent.scss
Labels: docs

#8699 MudCheckBox: Add state CSS classes for easier testing
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
Labels: enhancement

#8689 Build: Add Documentation PR type
  .github/PULL_REQUEST_TEMPLATE.MD
  .github/workflows/pr.yml
Labels: PR: needs review

#8703 Docs: Change DisableElevation to DropShadow
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackLayoutExample.razor
  src/MudBlazor.Docs/Pages/Consent/CookiePolicy.razor
Labels: docs

#8683 ParameterState: Add scope registration, lock mechanism, ComponentBaseWithState
  CONTRIBUTING.md
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildBindingTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerStaticTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerSwapTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateScopeExceptionTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateScopeExceptionTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/SharedStateHandlerTestComp.razor.cs
  src/MudBlazor.UnitTests/State/Builder/ParameterRegistrationBuilderScopeTests.cs
  src/MudBlazor.UnitTests/State/Builder/RegisterParameterBuilderTests.cs
  src/MudBlazor.UnitTests/State/ParameterSetTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor/Base/ComponentBaseWithState.cs
  src/MudBlazor/Base/MudComponentBase.RegisterParameter.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/Hidden/MudHidden.razor.cs
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Extensions/ComponentBaseWithStateExtensions.cs
  src/MudBlazor/State/Builder/IParameterBuilderAttach.cs
  src/MudBlazor/State/Builder/IParameterRegistrationBuilderScope.cs
  src/MudBlazor/State/Builder/IParameterSetRegister.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilder.cs
  src/MudBlazor/State/Builder/ParameterRegistrationBuilderScope.cs
  src/MudBlazor/State/Builder/RegisterParameterBuilder.cs
  src/MudBlazor/State/Builder/RegisterParameterBuilderOfT.cs
  src/MudBlazor/State/IParameterStatesReader.cs
  src/MudBlazor/State/ParameterSet.cs
Labels: enhancement

#8674 MudNavMenu: Use `nav` instead of `div` for better accessibility
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor
Labels: bug, breaking change, PR: needs review

#8669 MudTreeView: Add ripple effect (#8570)
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewRippleTest.razor
  src/MudBlazor.UnitTests/Components/TreeViewTest.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Styles/components/_treeview.scss
  src/MudBlazor/Styles/core/_ripple.scss
Labels: enhancement

#8708 Build: Ask for PRs to be labeled under only one category
  .github/PULL_REQUEST_TEMPLATE.MD
Labels: PR: needs review

#8707 TreeView: Add disabled style
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Styles/components/_treeview.scss
Labels: enhancement

#8705 Add GeneratedCodeAttribute to Docs.Compiler output
  src/MudBlazor.Docs.Compiler/CodeSnippets.cs
  src/MudBlazor.Docs.Compiler/DocStrings.cs
  src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
  src/MudBlazor.Docs.Compiler/TestsForExamples.cs
Labels: build

#8704 Docs: Revert landing page search bar to icon
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
  src/MudBlazor.Docs/Shared/LandingLayout.razor
  src/MudBlazor.Docs/Theme/Theme.cs
Labels: docs, PR: needs review

#8394 Various components: Prevent panning page by touch
  src/MudBlazor/Styles/components/_pickertime.scss
  src/MudBlazor/Styles/components/_popover.scss
  src/MudBlazor/Styles/components/_slider.scss
  src/MudBlazor/Styles/components/_snackbar.scss
Labels: bug, PR: needs review

#7302 MudSlider: Center track tick labels
  src/MudBlazor/Styles/components/_slider.scss
Labels: bug

#8700 MudVirtualize: Sync With Native Virtualize Parameters
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs
Labels: enhancement

#8686 Docs: Make code copy button always visible
  src/MudBlazor.Docs/Styles/components/_docssection.scss
Labels: docs

#8693 BooleanInput: Fix form validation (#8690)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithCheckBoxAndTextFieldsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithCheckBoxTest.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: bug

#8720 Docs: Misc refinements (April 16)
  src/MudBlazor.Docs/Components/MudContributor.razor
  src/MudBlazor.Docs/Components/MudTeamCard.razor
  src/MudBlazor.Docs/Models/TeamMember.cs
  src/MudBlazor.Docs/Pages/Consent/CookiePolicy.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/Footer.razor
Labels: docs, PR: needs review

#8709 Button: Don't apply :focus effect on mobile so it's not sticky
  src/MudBlazor/Styles/components/_button.scss
Labels: bug

#8732 MudAvatar*: Added XML Documentation for Public Members
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
Labels: docs, PR: needs review

#8719 MudMenu: Disable text selection in activator
  src/MudBlazor/Styles/components/_menu.scss
Labels: bug, PR: needs review

#8730 MudSlider: Fix tick count calculation for certain cases. Fixes #8713
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
Labels: bug

#8684 Navigation: Improve accessibility (#4651, #4755, #4756)
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuGroupDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Navigation/NavigationAccessibilityTest.razor
  src/MudBlazor.UnitTests/Components/NavGroupTests.cs
  src/MudBlazor.UnitTests/Components/NavMenuTests.cs
  src/MudBlazor.UnitTests/Components/NavigationAccessibilityTests.cs
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavLink.razor
  src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor.cs
  src/MudBlazor/Components/NavMenu/NavigationContext.cs
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
  src/MudBlazor/Services/Localization/AbstractLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/DefaultLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/ILocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
Labels: bug

#8672 MudBaseInput: match `input`s `id` with `label`'s `for` attribute (#6249, #6460)
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: bug, enhancement

#8739 ParameterState: Improve hot swappable IEqualityComparer system
  src/MudBlazor.UnitTests/Comparer/DoubleArrayEpsilonEqualityComparer.cs
  src/MudBlazor.UnitTests/State/Builder/RegisterParameterBuilderTests.cs
  src/MudBlazor.UnitTests/State/ParameterSetTests.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilderOfT.cs
  src/MudBlazor/State/Builder/RegisterParameterBuilderOfT.cs
  src/MudBlazor/State/Comparer/IParameterEqualityComparerSwappable.cs
  src/MudBlazor/State/Comparer/ParameterEqualityComparerSwappable.cs
  src/MudBlazor/State/Comparer/ParameterEqualityComparerTransformSwappable.cs
  src/MudBlazor/State/ParameterStateInternalOfT.cs
Labels: enhancement

#8698 MudTabs: Add ActiveTabClass for better customization
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsContentExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
  src/MudBlazor.UnitTests/Utilities/StyleBuilderTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Utilities/StyleBuilder.cs
Labels: enhancement, PR: needs review

#8701 MudAutocomplete: Add XML Documentation for Public Members
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: docs, PR: needs review

#8722 MudChipSet: use `SelectionMode` instead of `MultiSelect` and `Mandatory`
  src/MudBlazor.Docs.Server/Properties/launchSettings.json
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
  src/MudBlazor.Docs/Pages/Components/Chip/Examples/ChipIconExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/ChipSetPage.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetAddRemoveExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetChipBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetDefaultChipsExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetMultiselectionExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetSelectedColorExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetVariantsExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridGroupingExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropWithFormValidationExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImageFitExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImagePositionExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListSelectionExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackAlignExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackCombinedExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackInteractiveExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackJustifyExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackStretchItemsExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackWrappingExample.razor
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Chip/ChipHrefCursorTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Chip/ChipLinkTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Chip/ChipOnClickTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetChipBindingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetClearSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetComparerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetDefaultChipsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetLateDefaultTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetReadOnlyTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetSelectionTwoWayBindingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetSingleSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionInitialValueTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionTest.razor
  src/MudBlazor.UnitTests/Components/ChipSetTests.cs
  src/MudBlazor/Components/ChipSet/MudChipSet.razor.cs
Labels: breaking change, API change, v7

#8743 MudDialog: Fix content not stretched in fullscreen mode
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs
  src/MudBlazor/Styles/components/_dialog.scss
Labels: bug

#8710 Menu: Add `AriaLabel` property (#5783)
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuIconButtonsExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuAccessibilityTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: enhancement, PR: needs review

#8691 Input: Add `required` and `aria-required` attributes (#5437)
  src/MudBlazor.UnitTests.Viewer/TestComponents/ColorPicker/SimpleColorPickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupRequiredTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/FileUploadTests.cs
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/Radio/MudRadioGroup.razor
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Switch/MudSwitch.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: bug, enhancement

#8745 MudSlider: Use ParameterState and generic math
  src/MudBlazor.Docs.Compiler/T.cs
  src/MudBlazor.Docs/Models/T.cs
  src/MudBlazor.UnitTests/Components/SliderTests.cs
  src/MudBlazor.UnitTests/Components/UserAttributes/MudComponentFactory.cs
  src/MudBlazor/Components/Slider/MudSlider.razor
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
Labels: enhancement, PR: needs review

#8755 Build: Use GitHub README for NuGet package
  src/MudBlazor/MudBlazor.csproj
Labels: build

#8718 Standardise the use of `Expanded`, `Expandable`, `IsExpanded` and `IsExpandable`
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
  src/MudBlazor.Docs/Pages/Components/Collapse/Examples/CollapseSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelAsyncExample.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/Examples/ExpansionPanelTitleExample.razor
  src/MudBlazor.Docs/Pages/Components/ExpansionPanel/ExpansionPanelPage.razor
  src/MudBlazor.Docs/Pages/Components/List/ListPage.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuTwoWayBindableExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/NavMenuPage.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomCheckboxExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewItemTemplateExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelExpandedMultipleWithoutMultipleExpansionSetTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelStartExpandedMultipleTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelStartExpandedTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelTwoWayBIndingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuTwoWay.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildBindingTestComp.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildBindingTestComp.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateParentBindingTestComp.razor
  src/MudBlazor.UnitTests/Components/CollapseTests.cs
  src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
  src/MudBlazor.UnitTests/Components/NavMenuTests.cs
  src/MudBlazor.UnitTests/Components/TreeViewTest.cs
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Components/DataGrid/GroupDefinition.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor
  src/MudBlazor/Components/Table/MudTFootRow.razor.cs
  src/MudBlazor/Components/Table/MudTHeadRow.razor
  src/MudBlazor/Components/Table/MudTHeadRow.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableGroupRow.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableGroupDefinition.cs
Labels: bug, breaking change, API change, PR: needs review, v7

#8756 Docs: Revise v7 development announcement
  src/MudBlazor.Docs/NotificationContent/Announcement_v7_In_Development.razor
  src/MudBlazor.Docs/NotificationContent/Announcement_v7_Started_Development.razor
  src/MudBlazor.Docs/Pages/Mud/Announcements/AnnoucementPage.razor
  src/MudBlazor.Docs/Services/Notifications/InMemoryNotificationService.cs
  src/MudBlazor.Docs/Styles/pages/_announcement.scss
Labels: docs, PR: needs review

#8757 Docs: Fix landing page not shrinking top section subtitle
  src/MudBlazor.Docs/Styles/pages/_landingpage.scss
Labels: docs, PR: needs review

#8761 Docs: Weight search toward closer matches for more accurate results
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
Labels: docs, PR: needs review

#8760 MudSlider: Add ValueLabelStringFormat, ValueLabelCultureInfo, ValueLabelContent
  src/MudBlazor.Docs/Pages/Components/Slider/Examples/SliderValueLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/Slider/SliderPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithCustomValueLabelContentTest.razor
  src/MudBlazor.UnitTests/Components/SliderTests.cs
  src/MudBlazor/Components/Slider/MudSlider.razor
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
Labels: enhancement, PR: needs review

#8680 MudComponentBase: UserAttributes cannot be null
  src/MudBlazor/Base/MudComponentBase.cs
Labels: refactor

#8766 Docs: Add note about `Accept` filter for `FileUpload`
  src/MudBlazor.Docs/Pages/Components/FileUpload/FileUploadPage.razor
Labels: docs, PR: needs review

#8750 MudTreeView: Move checkbox icon customization from item to treeview
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: breaking change, API change, v7

#8764 Standardise the use of `IsEnabled` and `Enabled`
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverProviderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Virtualize/VirtualizeTest.razor
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs
Labels: bug, breaking change, PR: needs review

#8770 MudSelect: Revert #8309
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, accidental break

#8769 CssBuilder, StyleBuilder: Fix method with optional parameter is hidden by overload
  src/MudBlazor.UnitTests/Utilities/BuilderExtensions.cs
  src/MudBlazor.UnitTests/Utilities/CssBuilderTests.cs
  src/MudBlazor.UnitTests/Utilities/StyleBuilderTests.cs
  src/MudBlazor/Utilities/CssBuilder.cs
  src/MudBlazor/Utilities/StyleBuilder.cs
Labels: bug, PR: needs review

#8768 DatePickerTests: Fix CS1998, BL0005, nullable
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
Labels: refactor, PR: needs review

#8765 MudRTLProvider: Use ParameterState
  src/MudBlazor/Components/RTLProvider/MudRTLProvider.razor.cs
Labels: bug

#8711 MudPageContentNavigation: Fix automatic highlighting of centered section
  src/MudBlazor.Docs/Components/DocsPage.razor
  src/MudBlazor.Docs/Components/SectionHeader.razor.cs
  src/MudBlazor.UnitTests/Mocks/MockScrollSpy.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs
  src/MudBlazor/Services/Scroll/ScrollSpy.cs
  src/MudBlazor/TScripts/mudScrollSpy.js
Labels: bug

#8759 MudCheckBox, MudRadio, MudSwitch: Fix shouldn't hover when ReadOnly and rename UncheckedColor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Radio/Examples/RadioGroupColorExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchColorExample.razor
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Styles/components/_checkbox.scss
  src/MudBlazor/Styles/components/_radio.scss
Labels: bug, breaking change, API change, v7

#8772 Docs: Fix DataGridAggregationExample
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridAggregationExample.razor
Labels: docs

#8762 MudTreeView: Add AutoExpand, ExpandAll() and CollapseAll()
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewAutoExpandExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewBindItemsExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewAutoExpandTest.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: enhancement

#8777 Better Illegal Razor Parameter Runtime Detection for v7
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarBottomExample.razor
  src/MudBlazor.Docs/Pages/Components/Divider/Examples/DividerInsertExample.razor
  src/MudBlazor.Docs/Pages/Components/Divider/Examples/DividerListExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListNestedExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewMultiSelectionExample.razor
  src/MudBlazor.Docs/Pages/Getting Started/Usage/Examples/RightClickDrawerExample.razor
  src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Content/Examples/Content3WireframeExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/ReselectValueTest.razor
  src/MudBlazor.UnitTests/Components/ComponentBaseTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
Labels: bug

#8779 DateRangePicker: Fix DateFormat (#8737)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerFormatTest.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug, PR: needs review

#8748 New Component: Add MudFlexBreak component for forcing flex items onto a new line
  src/MudBlazor.Docs/Pages/Components/Grid/Examples/GridLineBreakExample.razor
  src/MudBlazor.Docs/Pages/Components/Grid/GridPage.razor
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackBreakExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/StackPage.razor
  src/MudBlazor/Components/Grid/MudFlexBreak.razor
  src/MudBlazor/Styles/components/_grid.scss
Labels: enhancement, new component

#8641 Docs: Fix Error When Creating Solution From MudBlazor Template in .NET 8 (#8546)
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Examples/InstallationTemplateUsageExample.razor
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Examples/InstallationTemplateUsageExampleAuto.razor
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Examples/InstallationTemplateUsageExampleServer.razor
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Examples/InstallationTemplateUsageExampleWasm.razor
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Labels: docs, PR: needs review

#8758 MudAutocomplete: Open menu on focus, Rename `ToggleMenu` to `ToggleMenuAsync`
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: enhancement, PR: needs review

#8694 FileUpload: Rewrite using `ActivatorContent` pattern
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadAppendMultipleExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadButtonExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropCustomScenarioExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropWithFormValidationExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadEventOptionsExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadMultipleAcceptExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadSelectedTemplateExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadValidationExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/FileUploadPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadAppendMultipleTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadButtonTemplateContextTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadButtonTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadFormValidationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadMultipleFilesTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadOnFilesChangedTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/FileUpload/FileUploadWithDragAndDropActivatorTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormReadOnlyDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithFileUploadAndDragAndDropActivatorTest.razor
  src/MudBlazor.UnitTests/Components/FileUploadTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/FileUpload/FileUploadButtonTemplateContext.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
  src/MudBlazor/TScripts/mudWindow.js
Labels: bug, enhancement, breaking change, API change, v7

#8792 Further improve outward-facing language to be more welcoming
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/issue.yml
  README.md
  ROADMAP.md
Labels: docs, PR: needs review

#8776 Docs: MudBadge/MudBreadcrumbs/MudButton: Added XML Documentation for Public Members
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbItem.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbLink.razor
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbLink.razor.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbSeparator.razor
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbSeparator.razor.cs
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor.cs
  src/MudBlazor/Components/BreakpointProvider/MudBreakpointProvider.razor.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
Labels: docs, PR: needs review

#8806 Docs: Fix MudDateRangePicker editable example
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerEditableExample.razor
Labels: docs

#8706 DataGrid: Remove 'Value not null' criteria for FilterDefinition
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
Labels: bug

#8823 MudColor: Make H, S, L readonly
  src/MudBlazor/Utilities/MudColor.cs
Labels: refactor

#8810 Docs: MudButtonGroup/MudCard/MudCarousel/MudChart: Added XML Documentation for Public Members
  src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselExample.razor
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
  src/MudBlazor/Components/Card/MudCard.razor.cs
  src/MudBlazor/Components/Card/MudCardActions.razor.cs
  src/MudBlazor/Components/Card/MudCardContent.razor.cs
  src/MudBlazor/Components/Card/MudCardHeader.razor.cs
  src/MudBlazor/Components/Card/MudCardMedia.razor.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/Carousel/MudCarouselItem.razor.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Charts/Pie.razor.cs
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/Chart/Models/ChartSeries.cs
  src/MudBlazor/Components/Chart/MudChart.razor
  src/MudBlazor/Components/Chart/MudChart.razor.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor.cs
  src/MudBlazor/Components/Chart/Svg/SvgCircle.cs
  src/MudBlazor/Components/Chart/Svg/SvgLegend.cs
  src/MudBlazor/Components/Chart/Svg/SvgPath.cs
  src/MudBlazor/Components/Chart/Svg/SvgText.cs
Labels: docs

#8798 ButtonGroup: Add `FullWidth`, Rename `VerticalAlign` to `Vertical`
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/ButtonGroupPage.razor
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupVerticalExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Button/ButtonGroupTooltipsTest.razor
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
Labels: enhancement, breaking change, API change, v7

#8800 TimePicker: Prepare for touch support & ColorPicker: Prevent touch pan in static mode
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Styles/components/_pickercolor.scss
  src/MudBlazor/Styles/components/_pickertime.scss
Labels: PR: needs review

#8825 Standardise the use of `Checked`, `CheckedChanged` and `Checkable`
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableHeaderAndFooterExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomCheckboxExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest2B.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableMultiSelectionTest6B.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Rating/MudRatingItem.razor
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor
  src/MudBlazor/Components/Table/MudTFootRow.razor.cs
  src/MudBlazor/Components/Table/MudTHeadRow.razor
  src/MudBlazor/Components/Table/MudTHeadRow.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: breaking change, API change, v7

#8787 Autocomplete: Improve menu behavior
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteChangeBoundObjectTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Input/MudInputAdornment.razor
Labels: bug

#8804 Docs: Fix missing binding in TimePicker example
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerBasicUsageExample.razor
Labels: docs, PR: needs review

#8826 Rename remaining Disable... properties
  src/MudBlazor.Docs/Pages/Components/ColorPicker/ColorPickerPage.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerAlphaExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerColorModeExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerDialogExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerDragExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerExampleUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerInlineExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerPlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerSwitchModeExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerBasicUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerDialogExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogConfigurationExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogOptionsExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogScrollableExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/DrawerPage.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerOverlayExample.razor
  src/MudBlazor.Docs/Pages/Components/Timeline/Examples/TimelineItemModifiersExample.razor
  src/MudBlazor.Docs/Pages/Components/Timeline/TimelinePage.razor
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
  src/MudBlazor.Docs/Pages/Getting Started/Usage/Examples/RightClickDrawerExample.razor
  src/MudBlazor.UnitTests.Viewer/Pages/Index.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/ChartsWithCustomColorsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ColorPicker/PickerWithFixedView.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ColorPicker/SimpleColorPickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogWithContentClass.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/ToggleTabsSlideAnimationTest.razor
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor.UnitTests/Components/TimelineTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/Dialog/DialogOptions.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Components/Timeline/MudTimeline.razor.cs
Labels: breaking change, API change, v7

#8775 MudList: Implement selection modes Single-, Toggle- and MultiSelection
  src/MudBlazor.Docs/Pages/Components/ChipSet/ChipSetPage.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListInteractiveExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListMultiSelectionExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListSelectionExample.razor
  src/MudBlazor.Docs/Pages/Components/List/Examples/ListSingleSelectionExample.razor
  src/MudBlazor.Docs/Pages/Components/List/ListPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListDenseInheritanceTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListMultiSelectionBindingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListSelectionTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelectItem.razor
Labels: enhancement, breaking change, API change, v7

#8754 Inputs: Add typography customization
  README.md
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldTypoExample.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
  src/MudBlazor.Docs/Pages/Components/Typography/Examples/TextGeneralExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Typography.razor
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Input/MudInputCssHelper.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Enums/Typo.cs
  src/MudBlazor/Styles/components/_input.scss
  src/MudBlazor/Styles/components/_typography.scss
  src/MudBlazor/Themes/Models/Typography.cs
Labels: enhancement
