Repository MudBlazor/MudBlazor, pull requests merged in 2024-06, with the labels that each got.

#9071 Various components: Improve localization and ARIA
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Badge/MudBadge.razor.cs
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
  src/MudBlazor/Components/Card/MudCardMedia.razor.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Icon/MudIcon.razor.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInputAdornment.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Components/Table/MudTablePager.razor
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
Labels: enhancement, PR: needs review, accessibility

#9095 MudFocusTrap: Don't hide focusable elements from accessibility tree
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor
Labels: bug, PR: needs review, accessibility

#9075 Docs: Improve accessibility for screen readers
  src/MudBlazor.Docs/Components/DocsExploreCard.razor
  src/MudBlazor.Docs/Components/LandingPage/Browser.razor
  src/MudBlazor.Docs/Components/LandingPage/Phone.razor
  src/MudBlazor.Docs/Components/LandingPage/WorldMap.razor
  src/MudBlazor.Docs/Components/SectionContent.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/LandingLayout.razor
Labels: docs, PR: needs review, accessibility

#9086 MudDataGrid: Fixed serverData + virtualization bug (#5664)
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridVirtualizeServerDataExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridCellEditVirtualizeServerDataTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterableVirtualizeServerDataTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSortableVirtualizeServerDataTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridVirtualizeServerDataLoadingTestWithCancel.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/FooterContext.cs
  src/MudBlazor/Components/DataGrid/GridState.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Resources/LanguageResource.Designer.cs
  src/MudBlazor/Resources/LanguageResource.resx
Labels: bug

#9096 MudDialog: Added XML Documentation for Public Members
  src/MudBlazor.UnitTests/Components/Dialog/DialogParametersTests.cs
  src/MudBlazor/Components/Dialog/DialogOptions.cs
  src/MudBlazor/Components/Dialog/DialogParameters.cs
  src/MudBlazor/Components/Dialog/DialogParametersGeneric.cs
  src/MudBlazor/Components/Dialog/DialogReference.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
  src/MudBlazor/Enums/DialogPosition.cs
  src/MudBlazor/Interfaces/IDialogService.cs
  src/MudBlazor/Services/DialogResult.cs
  src/MudBlazor/Services/DialogService.cs
Labels: docs

#9101 MudNavGroup: Fix NavigationContext not updating on Expanded
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavGroupWithExpandedBindingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuGroupDisabledTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuOneWay.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuTwoWay.razor
  src/MudBlazor.UnitTests/Components/NavGroupTests.cs
  src/MudBlazor.UnitTests/Components/NavMenuTests.cs
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
Labels: bug, accidental break, PR: needs review

#9110 Docs: Link to the related pull request on Release page
  src/MudBlazor.Docs/Pages/Mud/Project/Releases.razor
Labels: docs, PR: needs review

#9116 MudDivider/MudDrawer/MudDropZone: Add XML Documentation for Public Members
  src/MudBlazor.Docs/Pages/Components/DropZone/DropZonePage.razor
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Components/Divider/MudDivider.razor
  src/MudBlazor/Components/Divider/MudDivider.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerContainer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawerHeader.razor.cs
  src/MudBlazor/Components/DropZone/MudDragAndDropIndexChangedEventArgs.cs
  src/MudBlazor/Components/DropZone/MudDragAndDropItemTransaction.cs
  src/MudBlazor/Components/DropZone/MudDragAndDropTransactionFinishedEventArgs.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
  src/MudBlazor/Enums/DividerType.cs
Labels: docs

#9134 mudScrollManager.js: Fix scrollToBottom ignoring scroll behavior
  src/MudBlazor/TScripts/mudScrollManager.js
Labels: bug

#9138 MudNavLink: Fix exception doesn't flow to ErrorBoundary.
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavLink/NavLinkErrorContenCaughtException.razor
  src/MudBlazor.UnitTests/Components/NavLinkTests.cs
  src/MudBlazor/Components/NavMenu/MudNavLink.razor
  src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
Labels: bug

#9120 Datagrid: Add NumberFormat and NumberCulture to AggregateDefinition (#9112)
  src/MudBlazor.UnitTests/Components/DataGrid/AggregateDefinitionTests.cs
  src/MudBlazor/Components/DataGrid/AggregateDefinition.cs
Labels: enhancement

#9098 Buttons: Remove unnecessary `Title`, `AriaLabel` properties
  src/MudBlazor.UnitTests/Components/ButtonsTests.cs
  src/MudBlazor.UnitTests/Components/ToggleIconButtonTest.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Button/MudToggleIconButton.razor
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
Labels: breaking change

#9145 BrowserViewportService: Allow ReportRate of 0 to disable debounce
  src/MudBlazor/Services/Browser/ResizeOptions.cs
  src/MudBlazor/TScripts/mudResizeListener.js
Labels: enhancement, PR: needs review

#9140 DateRangePicker: fix `Underline` parameter not working (#9124)
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
Labels: bug, PR: needs review

#9151 MudTreeView: Change type of Items and ServerData to use TreeItemData<T>
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewBodyContentExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewCustomExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewItemTemplateExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewServerExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewServerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTemplateTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTest5.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTest8.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Components/TreeView/TreeItemData.cs
  src/MudBlazor/MudBlazor.csproj.DotSettings
Labels: breaking change

#9142 DataGrid: Change default values of TemplateColumn
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEditableWithSelectColumnTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSelectColumnTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSortableTemplateColumnTest.razor
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor.cs
  src/MudBlazor/Components/DataGrid/SelectColumn.razor
  src/MudBlazor/Components/DataGrid/SelectColumn.razor.cs
  src/MudBlazor/Components/DataGrid/TemplateColumn.cs
Labels: breaking change

#9150 MudDataGrid: Refresh grouping after InvokeServerLoadFunc, ExpandAllGroups, CollapseAllGroups
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupableServerDataTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#9155 Build: Remove AssemblyVersion and PackageVersion
  .github/workflows/deploy-mudblazor-nuget.yml
Labels: build

#9153 Updates CONTRIBUTING.md with info on viewing changes locally
  CONTRIBUTING.md
Labels: docs, PR: needs review

#9157 FileUpload: fix issue with file picker not opening in Safari with Blazor Server (#9148)
  src/MudBlazor.UnitTests/Components/FileUploadTests.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
  src/MudBlazor/TScripts/mudFileUpload.js
  src/MudBlazor/TScripts/mudWindow.js
Labels: bug

#9139 FileUpload: fix uploading same file before and after clearing the input on chromium browsers (#9082)
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
  src/MudBlazor/TScripts/mudInput.js
Labels: bug

#9173 Build: Use latest github actions
  .github/workflows/deploy-mudblazor-nuget.yml
Labels: build

#9178 Build: Update dotnet libs
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: build, PR: needs review

#9179 Build: Remove "Use primary constructor" suggestion
  src/.editorconfig
Labels: build, PR: needs review

#9154 MudElement-MudFocusTrap: Add XML Documentation for Public Members
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Element/MudElement.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
  src/MudBlazor/Components/Field/MudField.razor.cs
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Enums/DefaultFocus.cs
Labels: docs

#9192 Docs: Add another level of depth to the MudTreeView ServerData example
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewServerExample.razor
Labels: PR: needs review

#9174 ComponentBase, Field, DateRangePicker: fix unreliable field id
  src/MudBlazor.UnitTests/Components/ComponentBaseTests.cs
  src/MudBlazor.UnitTests/Dummy/DummyComponentBase.cs
  src/MudBlazor/Base/MudComponentBase.cs
Labels: bug, PR: needs review

#9191 Build: Add LangVersion latest property
  src/Directory.Build.props
  src/MudBlazor.SourceGenerator/MudBlazor.SourceGenerator.csproj
Labels: build, PR: needs review

#9195 Docs: Improve MudTreeView server data example by splitting off server data
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewServerExample.razor
Labels: docs

#9146 MudDialog: Add nullable annotation
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogOkCancel.razor
  src/MudBlazor.UnitTests/Components/Dialog/DialogParametersTests.cs
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/DialogOptions.cs
  src/MudBlazor/Components/Dialog/DialogParameters.cs
  src/MudBlazor/Components/Dialog/DialogParametersGeneric.cs
  src/MudBlazor/Components/Dialog/DialogReference.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
  src/MudBlazor/Interfaces/IDialogService.cs
  src/MudBlazor/Services/DialogResult.cs
  src/MudBlazor/Services/DialogService.cs
Labels: enhancement

#9198 Docs: Full fetched -> Fully-fledged
  src/MudBlazor.Docs/Pages/Index.razor
Labels: docs, PR: needs review

#9206 Docs: Fix regressions in v7
  src/MudBlazor.Docs/Components/LandingPage/Browser.razor
  src/MudBlazor.Docs/Components/LandingPage/CalculatorApp/Calculator.razor
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
  src/MudBlazor.Docs/Components/LandingPage/Phone.razor
  src/MudBlazor.Docs/Pages/Features/Colors/ColorsPage.razor
  src/MudBlazor.Docs/Pages/Getting Started/Wireframes/Content/Examples/Content3WireframeExample.razor
  src/MudBlazor.Docs/Pages/Index.razor
  src/MudBlazor.Docs/Styles/pages/_landingpage.scss
Labels: docs, accessibility

#9216 Code quality: Fix using order
  src/MudBlazor.Docs.Wasm/Program.cs
  src/MudBlazor.Docs.WasmHost/Controllers/OperationCancelledExceptionFilter.cs
  src/MudBlazor.Docs.WasmHost/Program.cs
  src/MudBlazor.Docs/Components/DocsPage.razor.cs
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
  src/MudBlazor.Docs/Extensions/ResourceSetExtensions.cs
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor.cs
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor.SourceCodeGenerator/Usings.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormComponentUpdateValidationMessagesOnEditContextChangedTest.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateComparerTestComp.razor.cs
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/DonutChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/PieChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/StackedBarChartTests.cs
  src/MudBlazor.UnitTests/Components/DataGrid/AggregateDefinitionTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/ScrollToTopTests.cs
  src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
  src/MudBlazor.UnitTests/Extensions/ExpressionExtensionsTests.cs
  src/MudBlazor.UnitTests/Extensions/ParameterViewExtensionsTests.cs
  src/MudBlazor.UnitTests/Extensions/TaskExtensionsTests.cs
  src/MudBlazor.UnitTests/Services/Localization/DefaultLocalizationInterceptorTests.cs
  src/MudBlazor.UnitTests/Services/Localization/InternalMudLocalizerTests.cs
  src/MudBlazor.UnitTests/Utilities/Expressions/ExpressionHasherTests.cs
  src/MudBlazor.UnitTests/Utilities/Expressions/PropertyPathTests.cs
  src/MudBlazor/Base/MudBaseColumn.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Dialog/IDialogReference.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Enums/OverflowBehavior.cs
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilderOfT.cs
  src/MudBlazor/State/ParameterChangedLambdaArgsHandler.cs
  src/MudBlazor/Utilities/ColorManager.cs
Labels: v6

#9217 Build: Fix trim warnings when using dotnet format
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
Labels: v6

#9208 Popover: Allow panning by touch
  src/MudBlazor/Styles/components/_popover.scss
Labels: bug, PR: needs review

#9031 Add a Roslyn analyzer to detect parameter/attribute issues
  src/Directory.Build.targets
  src/MudBlazor.Analyzers.TestComponents/AdditonalDiagnostics.razor
  src/MudBlazor.Analyzers.TestComponents/InheritedMudChip.razor
  src/MudBlazor.Analyzers.TestComponents/MudBlazor.Analyzers.TestComponents.csproj
  src/MudBlazor.Analyzers.TestComponents/ParametersTest.razor
  src/MudBlazor.Analyzers.TestComponents/Properties/launchSettings.json
  src/MudBlazor.Analyzers.TestComponents/Util.cs
  src/MudBlazor.Analyzers.TestComponents/_Imports.razor
  src/MudBlazor.Analyzers/AllowedAttributePattern.cs
  src/MudBlazor.Analyzers/IllegalParameterSet.cs
  src/MudBlazor.Analyzers/IllegalParameters.cs
  src/MudBlazor.Analyzers/Internal/Attributes.cs
  src/MudBlazor.Analyzers/Internal/CompilationExtensions.cs
  src/MudBlazor.Analyzers/Internal/ComponentDescriptor.cs
  src/MudBlazor.Analyzers/Internal/MetadataSymbolComparer.cs
  src/MudBlazor.Analyzers/Internal/OperationExtensions.cs
  src/MudBlazor.Analyzers/Internal/SymbolExtensions.cs
  src/MudBlazor.Analyzers/Internal/SyntaxNodeExtensions.cs
  src/MudBlazor.Analyzers/Internal/TypeSymbolExtensions.cs
  src/MudBlazor.Analyzers/MudBlazor.Analyzers.csproj
  src/MudBlazor.Analyzers/MudComponentUnknownParametersAnalyzer.cs
  src/MudBlazor.Analyzers/Resources.Designer.cs
  src/MudBlazor.Analyzers/Resources.resx
  src/MudBlazor.Analyzers/Usings.cs
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridCustomSortingExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerInternationalizationExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneDraggingStyleExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneItemSelectorOnlyZoneExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadSelectedTemplateExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiSelectExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsHeadersWrapExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleIconButton/Examples/ToggleIconButtonEventCallbackExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleIconButton/Examples/ToggleIconButtonTwoWayBindingExample.razor
  src/MudBlazor.Docs/Pages/Features/Analyzers/Analyzers.razor
  src/MudBlazor.Docs/Pages/Features/Analyzers/MUD0001ConfigurationTable.razor
  src/MudBlazor.Docs/Pages/Features/Analyzers/MUD0002ConfigurationTable.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.UnitTests/Analyzers/Internal/DiagnosticHelper.cs
  src/MudBlazor.UnitTests/Analyzers/Internal/ExpectedDiagnostic.cs
  src/MudBlazor.UnitTests/Analyzers/Internal/ProjectCompilation.cs
  src/MudBlazor.UnitTests/Analyzers/Internal/TestAdditionalText.cs
  src/MudBlazor.UnitTests/Analyzers/Internal/TestAnalyzerOptions.cs
  src/MudBlazor.UnitTests/Analyzers/ParametersTests.cs
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
  src/MudBlazor.sln
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/MudBlazor.csproj
Labels: enhancement, PR: needs review

#9225 MudFormComponent: call base OnParametersSet
  src/MudBlazor/Base/MudFormComponent.cs
Labels: bug

#9226 Components: Add missing base OnParametersSet
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
  src/MudBlazor/Components/Chart/Charts/Pie.razor.cs
  src/MudBlazor/Components/Highlighter/MudHighlighter.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#9203 MudDataGrid: Add correct class to the th element in HeaderCell
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
Labels: bug

#9229 Fix bug in parameter analyzer
  src/MudBlazor/MudBlazor.csproj
Labels: bug, PR: needs review

#9193 MudBaseInput components: add helper text reference to `aria-describedby` attribute
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor.UnitTests/Dummy/DummyErrorConverter.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: enhancement

#9234 Revert "MudTabs: add WrapHeaders (#9108)"
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsHeadersWrapExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/ScrollableTabsTest.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeObserver.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Services/ResizeObserver/IResizeObserver.cs
  src/MudBlazor/Services/ResizeObserver/ResizeObserver.cs
  src/MudBlazor/Styles/components/_tabs.scss
  src/MudBlazor/TScripts/mudResizeObserver.js
Labels: PR: needs review

#9238 feat: Escape Description attribute value
  src/MudBlazor.SourceGenerator/FastEnumDescriptionGenerator.cs
  src/MudBlazor.SourceGenerator/SourceCodeBuilder.cs
  src/MudBlazor.UnitTests/SourceGenerator/FastEnumDescriptionGeneratorTest.cs
  src/MudBlazor.UnitTests/SourceGenerator/SourceCodeBuilderTest.cs
Labels: enhancement

#9233 Docs: Use same expand icon in nav menu
  src/MudBlazor.Docs/Shared/NavMenu.razor
Labels: docs, PR: needs review

#9180 MudForm: Support `For` expressions refering to non-nullable properties
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Extensions/ExpressionExtensionsTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Extensions/ExpressionExtensions.cs
Labels: bug, PR: needs review, v6

#9239 MudDataGridPager: Add AllItemsText Parameter (#9235)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridPaginationAllItemsTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
Labels: enhancement, PR: needs review

#8254 MudDataGrid: Add extensions method on `IQueryable` for easy filtering and ordering
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/QueryFilterExtensions.cs
  src/MudBlazor/Components/DataGrid/QuerySortExtensions.cs
Labels: enhancement, PR: needs review

#9255 QuerySortExtensions: Make more trim safe, add more xml comments
  src/MudBlazor/Components/DataGrid/QueryFilterExtensions.cs
  src/MudBlazor/Components/DataGrid/QuerySortExtensions.cs
  src/MudBlazor/Extensions/QueryFilterExtensions.cs
  src/MudBlazor/Extensions/QuerySortExtensions.cs
Labels: enhancement

#9261 MudTable: Use InvokeAsync() in method InvokeServerLoadFunc
  src/MudBlazor/Components/Table/MudTable.razor.cs
Labels: bug

#9189 MudTable: Add XML Documentation for Public Members
  src/MudBlazor/Components/Table/EditButtonContext.cs
  src/MudBlazor/Components/Table/MudTFootRow.razor.cs
  src/MudBlazor/Components/Table/MudTHeadRow.razor.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTableGroupRow.razor.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
  src/MudBlazor/Components/Table/MudTableSortLabel.razor.cs
  src/MudBlazor/Components/Table/MudTd.razor.cs
  src/MudBlazor/Components/Table/MudTh.razor.cs
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableApplyButtonPosition.cs
  src/MudBlazor/Components/Table/TableContext.cs
  src/MudBlazor/Components/Table/TableEditButtonPosition.cs
  src/MudBlazor/Components/Table/TableEditTrigger.cs
  src/MudBlazor/Components/Table/TableGroupData.cs
  src/MudBlazor/Components/Table/TableGroupDefinition.cs
  src/MudBlazor/Components/Table/TableRowClickEventArgs.cs
  src/MudBlazor/Components/Table/TableRowHoverEventArgs.cs
  src/MudBlazor/Components/Table/TableRowValidator.cs
  src/MudBlazor/Components/Table/TableState.cs
  src/MudBlazor/Enums/HorizontalAlignment.cs
  src/MudBlazor/Enums/SortDirection.cs
Labels: docs

#8132 MudDataGrid: Add Hide Parameters to HierarchyColumn and SelectColumn
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor.cs
  src/MudBlazor/Components/DataGrid/SelectColumn.razor
  src/MudBlazor/Components/DataGrid/SelectColumn.razor.cs
Labels: enhancement

#8103 Datagrid: Add hierarchycolumn InitiallyExpandedFunc
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridDetailRowExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridHierarchyColumnTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor.cs
Labels: enhancement, PR: needs review

#9272 Docs: Update v7 announcement date
  src/MudBlazor.Docs/Services/Notifications/InMemoryNotificationService.cs
Labels: docs, PR: needs review

#9275 Remove illegal parameter detection in favor of code analyzer
  src/MudBlazor/Base/MudComponentBase.cs
Labels: PR: needs review

#9269 Build: Update bug template placeholder version for v7
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: docs, v7

#9280 Build: Only deploy try.mudblazor.com and mudblazor.com for v7
  .github/workflows/deploy-mudblazor.yml
  .github/workflows/deploy-trymudblazor.yml
Labels: build

#9287 Build: Fix bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: docs
