Repository MudBlazor/MudBlazor, pull requests merged in 2024-10, with the labels that each got.

#9869 MudListItem: Fix redundant whitespace in CSS class (#9868)
  src/MudBlazor/Components/List/MudListItem.razor
Labels: bug, PR: needs review

#9815 MudSkeleton: add dark mode support
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Styles/components/_skeleton.scss
  src/MudBlazor/Themes/Models/Palette.cs
  src/MudBlazor/Themes/Models/PaletteDark.cs
Labels: enhancement

#9889 MudTabs: Add nullable annotation
  src/MudBlazor/Components/Tabs/MudDynamicTabs.razor
  src/MudBlazor/Components/Tabs/MudDynamicTabs.razor.cs
  src/MudBlazor/Components/Tabs/MudTabPanel.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Components/Tabs/TabHeaderPosition.cs
  src/MudBlazor/Components/Tabs/TabInteractionEventArgs.cs
  src/MudBlazor/Components/Tabs/TabInteractionType.cs
Labels: enhancement, hacktoberfest accepted, hacktoberfest2024

#9892 DataGrid: Document that GridState has a zero-based page index
  src/MudBlazor/Components/DataGrid/GridState.cs
Labels: docs

#9897 MudTextField: Add nullable annotation.
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Input/MudDebouncedInput.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9896 Introduce KeyInterceptorService withs sync/async support to replace KeyInterceptor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockKeyInterceptor.cs
  src/MudBlazor.UnitTests/Mocks/MockKeyInterceptorService.cs
  src/MudBlazor.UnitTests/Services/KeyInterceptor/KeyInterceptorServiceTests.cs
  src/MudBlazor.UnitTests/Services/KeyInterceptor/KeyObserverTests.cs
  src/MudBlazor.UnitTests/Services/KeyInterceptor/KeyOptionsTests.cs
  src/MudBlazor.UnitTests/Services/KeyInterceptor/Mocks/KeyInterceptorObserverMock.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Interop/KeyInterceptorInterop.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyDownObserver.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyInterceptor.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyInterceptorFactory.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyInterceptorObserver.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyInterceptorService.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyUpObserver.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorFactory.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorOptions.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorService.cs
  src/MudBlazor/Services/KeyInterceptor/KeyObserver.cs
  src/MudBlazor/Services/KeyInterceptor/KeyOptions.cs
  src/MudBlazor/Services/KeyInterceptor/KeyboardEvent.cs
  src/MudBlazor/TScripts/mudKeyInterceptor.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9906 MudDialog: Add OnKeyDown and OnKeyUp events
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample_Dialog.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/DialogOkCancel.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9907 MudChart: Add nullable annotation
  src/MudBlazor/Components/Chart/Charts/Bar.razor
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor
  src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Charts/Pie.razor
  src/MudBlazor/Components/Chart/Charts/Pie.razor.cs
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor.cs
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor.cs
  src/MudBlazor/Components/Chart/Interpolation/EndSlopeSpline.cs
  src/MudBlazor/Components/Chart/Interpolation/ILineInterpolator.cs
  src/MudBlazor/Components/Chart/Interpolation/Matrix.cs
  src/MudBlazor/Components/Chart/Interpolation/MatrixSolver.cs
  src/MudBlazor/Components/Chart/Interpolation/NaturalSpline.cs
  src/MudBlazor/Components/Chart/Interpolation/PeriodicSpline.cs
  src/MudBlazor/Components/Chart/Interpolation/SplineInterpolator.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/Chart/Models/ChartSeries.cs
  src/MudBlazor/Components/Chart/Models/TimeSeriesChartSeries.cs
  src/MudBlazor/Components/Chart/MudChart.razor.cs
  src/MudBlazor/Components/Chart/MudTimeSeriesChart.razor.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor
  src/MudBlazor/Components/Chart/Parts/Legend.razor.cs
  src/MudBlazor/Components/Chart/Svg/SvgCircle.cs
  src/MudBlazor/Components/Chart/Svg/SvgLegend.cs
  src/MudBlazor/Components/Chart/Svg/SvgPath.cs
  src/MudBlazor/Components/Chart/Svg/SvgText.cs
Labels: enhancement, PR: needs review, hacktoberfest2024

#9890 MudDateRangePicker: Incorrect margins and align when on a stack or grid
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Field/MudField.razor.cs
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
Labels: bug

#9849 MudMask: Added XML Documentation for Public Members
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor.cs
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor.cs
  src/MudBlazor/Enums/MouseEvent.cs
  src/MudBlazor/Utilities/MaskAlgorithms/BaseMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/BlockMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/DateMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/IMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/MaskChar.cs
  src/MudBlazor/Utilities/MaskAlgorithms/MultiMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/PatternMask.cs
  src/MudBlazor/Utilities/MaskAlgorithms/RegexMask.cs
Labels: docs

#9912 Update KeyInterceptorService API usage
  src/MudBlazor.UnitTests/Services/KeyInterceptor/KeyInterceptorServiceTests.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: hacktoberfest, hacktoberfest-accepted, refactor, PR: needs review, hacktoberfest2024

#9455 MudChip: Improve keyboard accessibility
  src/MudBlazor.Docs/Pages/Components/Chip/ChipPage.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/ChipSetPage.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetForKeyboardNavigationExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ChipSet/ChipSetKeyboardNavigationTests.razor
  src/MudBlazor.UnitTests/Components/ChipSetTests.cs
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/Chip/MudChip.razor
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Styles/components/_chip.scss
Labels: enhancement, accessibility

#9916 MudDataGrid: Fix NRE when property has a nested null value
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridNestedNullPropertyTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/PropertyColumn.cs
  src/MudBlazor/Utilities/Expressions/ExpressionHasher.cs
  src/MudBlazor/Utilities/Expressions/ExpressionNull.cs
  src/MudBlazor/Utilities/Expressions/PropertyPath.cs
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9911 MudStepper: New Component
  src/MudBlazor.Docs/Pages/Components/Overview/OverviewPage.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperBasicAlternativeLabelExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperBasicVerticalExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperCustomizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperDynamicExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperNonLinearExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperStepBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/StepperPage.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Stepper/StepperTwoWayBindingTestComponent.razor
  src/MudBlazor.UnitTests/Components/StepperTests.cs
  src/MudBlazor.UnitTests/Components/UserAttributes/UserAttributesTests.cs
  src/MudBlazor/Components/Stepper/MudStep
  src/MudBlazor/Components/Stepper/MudStep.cs
  src/MudBlazor/Components/Stepper/MudStepper.razor
  src/MudBlazor/Components/Stepper/MudStepper.razor.cs
  src/MudBlazor/Components/Stepper/StepAction.cs
  src/MudBlazor/Components/Stepper/StepperInteractionEventArgs.cs
  src/MudBlazor/MudBlazor.csproj.DotSettings
  src/MudBlazor/Resources/LanguageResource.resx
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_stepper.scss
Labels: enhancement, new component, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9922 Docs: Fix `borderradius` variable being shown as `border-radius`
  src/MudBlazor.Docs/Pages/Customization/DefaultTheme.razor
Labels: docs

#6743 MudExpansionPanel: Add HeaderClass
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
Labels: enhancement, PR: needs review

#9904 MudCheckBox and MudRadio: Do not grey out when read-only (#9876)
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9913 MudAutocomplete: Incorrect horizontal spacing on RTL mode
  src/MudBlazor/Styles/components/_select.scss
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9925 MudStepper: Refactor CSS and HTML structure
  src/MudBlazor.UnitTests/Components/StepperTests.cs
  src/MudBlazor/Components/Stepper/MudStep.cs
  src/MudBlazor/Components/Stepper/MudStepper.razor
  src/MudBlazor/Components/Stepper/MudStepper.razor.cs
  src/MudBlazor/Styles/components/_stepper.scss
Labels: hacktoberfest, hacktoberfest-accepted, refactor, PR: needs review, hacktoberfest2024

#9877 DataGrid: Prevent applying same filters twice
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#9885 MudDataGrid: Remove empty filters when closing the filter menu without applying (#8998)
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, PR: needs review

#9926 Improved elevation docs by adding playground example, and visual formatting
  src/MudBlazor.Docs/Pages/Features/Elevation/ElevationPage.razor
  src/MudBlazor.Docs/Pages/Features/Elevation/Examples/ElevationAllExample.razor
  src/MudBlazor.Docs/Pages/Features/Elevation/Examples/ElevationPlaygroundExample.razor
Labels: docs

#9931 MudStepper: Fix step number alignment
  src/MudBlazor/Styles/components/_stepper.scss
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9935 Docs: Update team members
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
Labels: docs

#9937 MudSelect: Add nullable annotation.
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Select/MudSelectItem.razor
  src/MudBlazor/Components/Select/MudSelectItem.razor.cs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#9938 PopoverService: Remove locking
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Utilities/AsyncKeyedLock/AsyncKeyedLockNonPooledTests.cs
  src/MudBlazor.UnitTests/Utilities/AsyncKeyedLock/AsyncKeyedLockPooledTests.cs
  src/MudBlazor.UnitTests/Utilities/AsyncKeyedLock/AsyncKeyedLockSynchronizationContext.cs
  src/MudBlazor.UnitTests/Utilities/AsyncKeyedLock/AsyncKeyedLockTests.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Popover/PopoverOptions.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
  src/MudBlazor/Utilities/AsyncKeyedLock/AsyncKeyedLockDictionary.cs
  src/MudBlazor/Utilities/AsyncKeyedLock/AsyncKeyedLockOptions.cs
  src/MudBlazor/Utilities/AsyncKeyedLock/AsyncKeyedLockPool.cs
  src/MudBlazor/Utilities/AsyncKeyedLock/AsyncKeyedLockReleaser.cs
  src/MudBlazor/Utilities/AsyncKeyedLock/AsyncKeyedLockTimeoutReleaser.cs
  src/MudBlazor/Utilities/AsyncKeyedLock/AsyncKeyedLocker.cs
Labels: bug

#9933 MudPopover: Fix negative results in JS calculations for overflow behavior
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#7470 MudForm: Expose ChildForms to derived classes
  src/MudBlazor/Components/Form/MudForm.razor.cs
Labels: enhancement

#9511 Build: Drop support for .NET 7
  src/MudBlazor.UnitTests/Services/EventListenerTests.cs
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
  src/MudBlazor/Interop/EventHandlers.cs
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/State/ParameterContainer.cs
  src/MudBlazor/State/ParameterScopeContainer.cs
Labels: breaking change, PR: needs review, v8

#9434 Theme: Change Typography members to type BaseTypography
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/TypographyDefaultFontExample.razor
  src/MudBlazor.Docs/Theme/Theme.cs
  src/MudBlazor/Themes/Models/Typography.cs
Labels: enhancement, breaking change, v8

#9952 MudTable: Rename MudBlazorFix namespace to MudBlazor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/CrowdsourcedTranslationsInstallExampleCode.html
  src/MudBlazor/Components/Table/EditButtonContext.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor
Labels: bug

#9954 Return CrowdsourcedTranslationsInstallExampleCode
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/CrowdsourcedTranslationsInstallExampleCode.html
Labels: docs

#9582 Rename utilities to fix typos
  src/MudBlazor.UnitTests/Services/IIJSRuntimeExtensionsTests.cs
  src/MudBlazor.UnitTests/Utilities/SortingAssistantTests.cs
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor.cs
  src/MudBlazor/Services/IIJSRuntimeExtensions.cs
  src/MudBlazor/Utilities/SortingAssistant.cs
Labels: breaking change, API change, refactor, v8

#9592 Typography: Make `FontWeight` and `LineHeight` strings
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/TypographySettingsExample.razor
  src/MudBlazor.Docs/Theme/Theme.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Themes/Models/Typography.cs
Labels: enhancement, breaking change, API change, v8

#9580 MudGlobal: Remove `EnableIllegalRazorParameterDetection`
  src/MudBlazor/Services/MudGlobal.cs
Labels: breaking change, API change, refactor, v8

#9955 ParameterState: Small optimization & using cleanup
  src/MudBlazor/State/Builder/IParameterRegistrationBuilderScope.cs
  src/MudBlazor/State/Builder/ParameterAttachBuilderOfT.cs
  src/MudBlazor/State/Builder/ParameterRegistrationBuilderScope.cs
  src/MudBlazor/State/Builder/RegisterParameterBuilderOfT.cs
  src/MudBlazor/State/Comparer/IParameterEqualityComparerSwappable.cs
  src/MudBlazor/State/Comparer/ParameterEqualityComparerSwappable.cs
  src/MudBlazor/State/Comparer/ParameterEqualityComparerTransformSwappable.cs
  src/MudBlazor/State/Comparer/ParameterHandlerUniquenessComparer.cs
  src/MudBlazor/State/Comparer/ParameterNameUniquenessComparer.cs
  src/MudBlazor/State/IParameterChangedHandler.cs
  src/MudBlazor/State/IParameterComponentLifeCycle.cs
  src/MudBlazor/State/IParameterContainer.cs
  src/MudBlazor/State/IParameterScopeContainer.cs
  src/MudBlazor/State/IParameterStatesReader.cs
  src/MudBlazor/State/ParameterChangedEventArgs.cs
  src/MudBlazor/State/ParameterChangedLambdaArgsHandler.cs
  src/MudBlazor/State/ParameterChangedLambdaArgsTaskHandler.cs
  src/MudBlazor/State/ParameterChangedLambdaHandler.cs
  src/MudBlazor/State/ParameterChangedLambdaTaskHandler.cs
  src/MudBlazor/State/ParameterContainer.cs
  src/MudBlazor/State/ParameterScopeContainer.cs
  src/MudBlazor/State/ParameterState.cs
  src/MudBlazor/State/ParameterStateInternalOfT.cs
  src/MudBlazor/State/Rule/Exclusion/ComparerParameterLambdaExclusion.cs
  src/MudBlazor/State/Rule/Exclusion/HandlerLambdaExclusion.cs
  src/MudBlazor/State/Rule/ParameterMetadataRules.cs
Labels: enhancement

#9956 Remove KeyInterceptor, Replaced by KeyInterceptorService
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockKeyInterceptorService.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyInterceptor.cs
  src/MudBlazor/Services/KeyInterceptor/IKeyInterceptorFactory.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorFactory.cs
Labels: breaking change

#9957 Remove MudPopoverService
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockPopoverService.cs
  src/MudBlazor.UnitTests/Mocks/MockPopoverServiceV2.cs
  src/MudBlazor/Components/Popover/IPopover.cs
  src/MudBlazor/Components/Popover/MudPopoverBase.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Popover/IMudPopoverHolder.cs
  src/MudBlazor/Services/Popover/IMudPopoverService.cs
  src/MudBlazor/Services/Popover/IPopoverObserver.cs
  src/MudBlazor/Services/Popover/IPopoverService.cs
  src/MudBlazor/Services/Popover/MudPopoverHandler.cs
  src/MudBlazor/Services/Popover/MudPopoverHolder.cs
  src/MudBlazor/Services/Popover/MudPopoverService.cs
  src/MudBlazor/Services/Popover/PopoverHolderContainer.cs
  src/MudBlazor/Services/Popover/PopoverMode.cs
  src/MudBlazor/Services/Popover/PopoverOptions.cs
Labels: breaking change

#9921 Key handling followup work
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
Labels: breaking change, v8

#9961 MudTheme: Fix STJ Deserialization & add test
  src/MudBlazor.UnitTests/Dummy/MudThemeSerializerContext.cs
  src/MudBlazor.UnitTests/Themes/MudThemeTests.cs
  src/MudBlazor/Themes/Models/Typography.cs
Labels: bug

#9969 KeyInterceptorService: Make KeyOptions immutable
  src/MudBlazor/Services/KeyInterceptor/KeyOptions.cs
Labels: breaking change, PR: needs review

#9970 MudTabs: Fix ElementReference regression in #9889
  src/MudBlazor/Components/Tabs/MudTabPanel.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#9971 KeyInterceptorOptions: Fix breaking change introduced in #9896
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorOptions.cs
Labels: bug, PR: needs review

#9977 MudSelect: Disable logging for KeyInterceptor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug

#9978 MudMainContent: Add xmldoc
  src/MudBlazor/Components/Main/MudMainContent.razor
  src/MudBlazor/Components/Main/MudMainContent.razor.cs
Labels: docs

#9980 DialogService: Remove obsolete OnDialogInstanceAdded
  src/MudBlazor/Services/Dialog/DialogResult.cs
  src/MudBlazor/Services/Dialog/DialogService.cs
  src/MudBlazor/Services/Dialog/IDialogService.cs
Labels: breaking change

#9981 MudDropContainer: Remove obsolete API
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
Labels: breaking change, PR: needs review

#9691 MudGlobal: Add more component defaults
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Card/MudCard.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Grid/MudGrid.razor.cs
  src/MudBlazor/Components/Link/MudLink.razor.cs
  src/MudBlazor/Components/Stack/MudStack.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: enhancement

#9982 MudDataGrid: Remove obsolete CancelledEditingItem
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: breaking change

#9983 EventListener: Use [JsonSourceGenerationOptions] & cleanup
  src/MudBlazor/Services/EventManager/EventListener.cs
  src/MudBlazor/Services/EventManager/EventListenerFactory.cs
  src/MudBlazor/Services/EventManager/IEventListener.cs
  src/MudBlazor/Services/EventManager/IEventListenerFactory.cs
  src/MudBlazor/Services/EventManager/WebEventJsonContext.cs
Labels: enhancement, v8

#9984 StringExtensions: Remove not used API & add tests
  src/MudBlazor.UnitTests/Extensions/StringExtensionsTests.cs
  src/MudBlazor/Extensions/StringExtensions.cs
Labels: refactor, tests

#9973 Docs: Add complex object example for MudSelect
  src/MudBlazor.Docs/Pages/Components/Select/Examples/MultiSelectComplexExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/MultiSelectExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
Labels: docs

#9987 TimeSpanExtensions: Remove not used API & add tests
  src/MudBlazor.UnitTests/Extensions/TimeSpanExtensionsTests.cs
  src/MudBlazor/Extensions/TimeSpanExtensions.cs
Labels: docs, refactor, tests

#9988 DateTimeExtensions: Add unit tests.
  src/MudBlazor.UnitTests/Extensions/DateTimeExtensionTests.cs
  src/MudBlazor/Extensions/DateTimeExtensions.cs
Labels: docs, PR: needs review

#9990 BrowserViewportService: Add CancellationTokenSource
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor.UnitTests/Components/HiddenTests.cs
  src/MudBlazor.UnitTests/Services/Browser/BrowserViewportServiceTests.cs
  src/MudBlazor.UnitTests/Services/Browser/ResizeOptionsTests.cs
  src/MudBlazor/Interop/ResizeListenerInterop.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/Services/IIJSRuntimeExtensions.cs
Labels: enhancement

#9992 KeyInterceptorService: Improve DisposeAsync
  src/MudBlazor.UnitTests/Services/KeyInterceptor/KeyInterceptorServiceTests.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorService.cs
Labels: enhancement

#9994 JsApiService: Make implementation internal & add xmldoc.
  src/MudBlazor/Services/JsApi/IJsApiService.cs
  src/MudBlazor/Services/JsApi/JsApiService.cs
  src/MudBlazor/Services/JsApiService.cs
Labels: breaking change

#9996 JsEvent: Make implementation internal & add xmldoc.
  src/MudBlazor/Services/JsEvent/IJsEvent.cs
  src/MudBlazor/Services/JsEvent/IJsEventFactory.cs
  src/MudBlazor/Services/JsEvent/JsEvent.cs
  src/MudBlazor/Services/JsEvent/JsEventFactory.cs
  src/MudBlazor/Services/JsEvent/JsEventOptions.cs
Labels: breaking change

#9997 IJSRuntimeExtensions: Adjust pre-rendering handling for .NET8
  src/MudBlazor.UnitTests/Extensions/IJSRuntimeExtensionsTests.cs
  src/MudBlazor.UnitTests/Mocks/UnsupportedJavaScriptRuntime.cs
  src/MudBlazor/Extensions/IJSRuntimeExtensions.cs
Labels: bug, breaking change, v8

#9998 Build: Include "refactor" and "reverter" in release notes.
  .github/release.yml
Labels: build

#9999 TableExtensions: Add unit tests.
  src/MudBlazor.UnitTests/Extensions/TableExtensionsTests.cs
  src/MudBlazor/Extensions/TableExtensions.cs
Labels: tests

#10001 Localization: Remove obsolete code
  src/MudBlazor.UnitTests/Services/Localization/InternalMudLocalizerTests.cs
  src/MudBlazor/Services/Localization/DefaultLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
Labels: breaking change, hacktoberfest, hacktoberfest-accepted, localization, hacktoberfest2024

#9993 Popover: Hide all element overflow
  src/MudBlazor/Styles/components/_popover.scss
Labels: bug

#9995 ToggleGroup: Promote from experimental to stable
  src/MudBlazor.Docs/Pages/Components/Stepper/StepperPage.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/ToggleGroupPage.razor
Labels: docs, PR: needs review

#10000 DialogService: Mark sync API as obsolete
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Services/Dialog/DialogOptions.cs
  src/MudBlazor/Services/Dialog/DialogParameters.cs
  src/MudBlazor/Services/Dialog/DialogParametersGeneric.cs
  src/MudBlazor/Services/Dialog/DialogReference.cs
  src/MudBlazor/Services/Dialog/DialogService.cs
  src/MudBlazor/Services/Dialog/IDialogReference.cs
  src/MudBlazor/Services/Dialog/IDialogService.cs
  src/MudBlazor/Services/Dialog/MessageBoxOptions.cs
Labels: enhancement

#9967 EventUtil: Propagate exceptions.
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/EventUtil1Test.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Base/ComponentBaseWithState.cs
  src/MudBlazor/Base/MudComponentBase.cs
  src/MudBlazor/Components/Alert/MudAlert.razor
  src/MudBlazor/Components/Badge/MudBadge.razor
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudFab.razor
  src/MudBlazor/Components/Button/MudFab.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Chip/MudChip.razor
  src/MudBlazor/Components/Collapse/MudCollapse.razor
  src/MudBlazor/Components/Drawer/MudDrawer.razor
  src/MudBlazor/Components/Link/MudLink.razor
  src/MudBlazor/Components/Link/MudLink.razor.cs
  src/MudBlazor/Components/Menu/MudMenuItem.razor
  src/MudBlazor/Components/NavMenu/MudNavLink.razor
  src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
  src/MudBlazor/Components/ScrollToTop/MudScrollToTop.razor
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor
  src/MudBlazor/Utilities/EventUtil.cs
Labels: bug, breaking change, v8

#9581 TimeSeries: Rename `TimeSeriesDiplayType` to fix typo
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/TimeSeriesExample1.razor
  src/MudBlazor.UnitTests/Components/Charts/TimeSeriesChartTests.cs
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor.cs
  src/MudBlazor/Components/Chart/Models/TimeSeriesChartSeries.cs
Labels: breaking change, API change, refactor, v8

#9919 MudCharts: Update Namespace, set some classes visibility to internal
  src/MudBlazor.Docs/Models/ApiLink.cs
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/TimeSeriesExample1.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/DonutChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/PieChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/StackedBarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/TimeSeriesChartTests.cs
  src/MudBlazor/Components/Chart/ChartType.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Charts/Pie.razor.cs
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor.cs
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor.cs
  src/MudBlazor/Components/Chart/Interpolation/EndSlopeSpline.cs
  src/MudBlazor/Components/Chart/Interpolation/ILineInterpolator.cs
  src/MudBlazor/Components/Chart/Interpolation/Matrix.cs
  src/MudBlazor/Components/Chart/Interpolation/MatrixSolver.cs
  src/MudBlazor/Components/Chart/Interpolation/NaturalSpline.cs
  src/MudBlazor/Components/Chart/Interpolation/PeriodicSpline.cs
  src/MudBlazor/Components/Chart/Interpolation/SplineInterpolator.cs
  src/MudBlazor/Components/Chart/Models/TimeSeriesChartSeries.cs
  src/MudBlazor/Components/Chart/Models/TimeSeriesDisplayType.cs
  src/MudBlazor/Components/Chart/MudCategoryChartBase.cs
  src/MudBlazor/Components/Chart/MudChart.razor.cs
  src/MudBlazor/Components/Chart/MudChartBase.cs
  src/MudBlazor/Components/Chart/MudTimeSeriesChart.razor.cs
  src/MudBlazor/Components/Chart/Parts/Legend.razor.cs
  src/MudBlazor/Components/Chart/Svg/SvgCircle.cs
  src/MudBlazor/Components/Chart/Svg/SvgLegend.cs
  src/MudBlazor/Components/Chart/Svg/SvgPath.cs
  src/MudBlazor/Components/Chart/Svg/SvgText.cs
Labels: breaking change, hacktoberfest, hacktoberfest-accepted, v8, hacktoberfest2024

#9962 Add `Typography` suffix to all typography classes
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/TypographySettingsExample.razor
  src/MudBlazor.Docs/Theme/Theme.cs
  src/MudBlazor/Themes/Models/Typography.cs
Labels: breaking change, v8

#9909 MudDialog: Don't override `Class` param and convert BackgroundClass to getter
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Labels: breaking change, hacktoberfest, hacktoberfest-accepted, refactor, v8, hacktoberfest2024

#10009 ParameterState: Add more tests.
  src/MudBlazor.UnitTests/State/Comparer/ParameterEqualityComparerSwappableTests.cs
  src/MudBlazor.UnitTests/State/Comparer/ParameterEqualityComparerTransformSwappableTests.cs
Labels: tests

#10008 MudChart: Add null check for InputData (#10007)
  src/MudBlazor.UnitTests/Components/Charts/PieChartTests.cs
  src/MudBlazor/Components/Chart/MudCategoryChartBase.cs
Labels: bug, PR: needs review

#10012 BrowserViewportSubscription: Improve CancellationToken logic
  src/MudBlazor/Services/Browser/BrowserViewportEventArgs.cs
  src/MudBlazor/Services/Browser/BrowserViewportLambdaObserver.cs
  src/MudBlazor/Services/Browser/BrowserViewportLambdaTaskObserver.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/Services/Browser/BrowserViewportSubscription.cs
  src/MudBlazor/Services/Browser/BrowserWindowSize.cs
  src/MudBlazor/Services/Browser/IBrowserViewportObserver.cs
  src/MudBlazor/Services/Browser/IBrowserViewportService.cs
  src/MudBlazor/Services/Browser/ResizeOptions.cs
Labels: bug

#10013 PopoverService: Improve CancellationToken logic
  src/MudBlazor/Services/Popover/PopoverService.cs
Labels: bug

#10014 ParameterState: Add more tests.
  src/MudBlazor.UnitTests/State/Builder/ParameterRegistrationBuilderScopeTests.cs
  src/MudBlazor.UnitTests/State/Builder/RegisterParameterBuilderTests.cs
  src/MudBlazor.UnitTests/State/Comparer/ParameterEqualityComparerSwappableTests.cs
  src/MudBlazor.UnitTests/State/Mocks/ParameterChangedHandlerMock.cs
  src/MudBlazor.UnitTests/State/ParameterContainerTests.cs
  src/MudBlazor.UnitTests/State/ParameterScopeContainerTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateTests.cs
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor.UnitTests/State/Rule/ParameterMetadataRulesTests.cs
  src/MudBlazor/State/Builder/RegisterParameterBuilderOfT.cs
Labels: tests

#10018 Build: Inherit secrets for workflow.
  .github/workflows/build-test-mudblazor.yml
Labels: build

#10019 KeyInterceptorService: Add more tests
  src/MudBlazor.UnitTests/Services/KeyInterceptor/KeyInterceptorServiceTests.cs
Labels: PR: needs review

#10020 BrowserViewportService: Remove semaphore, Drawer: Use IAsyncDisposable
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
Labels: bug

#10023 ObserverManager: Use ConcurrentDictionary
  src/MudBlazor.UnitTests/Extensions/MoqExtensions.cs
  src/MudBlazor.UnitTests/Utilities/ObserverManager/ObserverManagerTests.cs
  src/MudBlazor/Utilities/ObserverManager/ObserverManager.cs
Labels: enhancement, PR: needs review

#8581 DataGrid: Allow using enum with Display attributes for filter #7621
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterEnumLocalizationTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Services/Localization/DefaultLocalizationEnumInterceptorTests.cs
  src/MudBlazor.UnitTests/Services/Localization/DefaultLocalizationInterceptorTests.cs
  src/MudBlazor.UnitTests/Services/Localization/InternalMudLocalizerTests.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Extensions/EnumExtensions.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/Localization/DefaultLocalizationEnumInterceptor.cs
  src/MudBlazor/Services/Localization/DefaultLocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/ILocalizationEnumInterceptor.cs
  src/MudBlazor/Services/Localization/ILocalizationInterceptor.cs
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
Labels: enhancement, localization

#10024 Localization: Remove IStringLocalizer from InternalMudLocalizer
  src/MudBlazor.UnitTests/Services/Localization/InternalMudLocalizerTests.cs
  src/MudBlazor/Services/Localization/InternalMudLocalizer.cs
Labels: refactor

#10025 JsEvent: Use InvokeVoidAsyncWithErrorHandling
  src/MudBlazor/Services/JsEvent/JsEvent.cs
Labels: enhancement

#9914 Table: Avoid checkbox overflow
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, hacktoberfest, hacktoberfest2024

#10028 Typography: Remove `input` in favor of `subtitle1`
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldTypoExample.razor
  src/MudBlazor.Docs/Pages/Components/Typography/Examples/TextGeneralExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Typography.razor
  src/MudBlazor.UnitTests/Components/TextTests.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Field/MudField.razor.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Enums/Typo.cs
  src/MudBlazor/Styles/components/_typography.scss
  src/MudBlazor/Themes/Models/Typography.cs
Labels: breaking change, PR: needs review

#9881 MudAutocomplete : CoerceValue only on Blur with Immediate=false
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#10037 Components: Use IAsyncDisposable
  src/MudBlazor.UnitTests/Mocks/MockKeyInterceptorService.cs
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
  src/MudBlazor/Components/Input/MudDebouncedInput.cs
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorService.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
Labels: breaking change, PR: needs review, v8

#10043 EventUtil: Fix UnsafeAccessor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Button/ButtonErrorContenCaughtException.razor
  src/MudBlazor.UnitTests/Components/ButtonsTests.cs
  src/MudBlazor/Utilities/EventUtil.cs
Labels: bug, PR: needs review

#10045 MudSelectItem, MudNavLink: Remove MudBaseSelectItem
  src/MudBlazor/Base/MudBaseSelectItem.cs
  src/MudBlazor/Components/NavMenu/MudNavLink.razor
  src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
  src/MudBlazor/Components/Select/MudSelectItem.razor
  src/MudBlazor/Components/Select/MudSelectItem.razor.cs
Labels: breaking change, v8

#9537 MudMenu: Fix nested menu to support multiple levels. (#7376)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTestNestWithMouseOver.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: bug

#10044 MudDataGrid: Accessibility fixes
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor
  src/MudBlazor/Resources/LanguageResource.resx
Labels: enhancement, PR: needs review, accessibility, localization

#10048 Scroll services: Clean up, make implementations internal, add xmodoc
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs
  src/MudBlazor/Services/Scroll/IScrollListener.cs
  src/MudBlazor/Services/Scroll/IScrollListenerFactory.cs
  src/MudBlazor/Services/Scroll/IScrollManager.cs
  src/MudBlazor/Services/Scroll/IScrollSpy.cs
  src/MudBlazor/Services/Scroll/IScrollSpyFactory.cs
  src/MudBlazor/Services/Scroll/ScrollBehavior.cs
  src/MudBlazor/Services/Scroll/ScrollEventArgs.cs
  src/MudBlazor/Services/Scroll/ScrollListener.cs
  src/MudBlazor/Services/Scroll/ScrollListenerFactory.cs
  src/MudBlazor/Services/Scroll/ScrollManager.cs
  src/MudBlazor/Services/Scroll/ScrollManagerException.cs
  src/MudBlazor/Services/Scroll/ScrollOptions.cs
  src/MudBlazor/Services/Scroll/ScrollSectionCenteredEventArgs.cs
  src/MudBlazor/Services/Scroll/ScrollSpy.cs
  src/MudBlazor/Services/Scroll/ScrollSpyFactory.cs
Labels: breaking change

#10049 Tests: Use more precise selectors for elements
  src/MudBlazor.UnitTests.Viewer/TestComponents/AvatarGroup/AvatarGroupChangeMaxTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/AvatarGroup/AvatarGroupRemoveTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerContainerTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerResponsiveTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectWithCustomComparerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/DebouncedTextFieldFormatChangeRerenderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/DebouncedTextFieldRerenderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipWithRenderFragmentContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipWithTextTest.razor
  src/MudBlazor.UnitTests/Components/AvatarGroupTests.cs
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor
  src/MudBlazor/Components/Table/MudTablePager.razor
Labels: tests, PR: needs review

#10051 EventListener: Clean up, make implementations internal, add xmodoc
  src/MudBlazor.UnitTests/Services/EventListenerTests.cs
  src/MudBlazor/Services/EventManager/EventListener.cs
  src/MudBlazor/Services/EventManager/EventListenerFactory.cs
  src/MudBlazor/Services/EventManager/IEventListener.cs
  src/MudBlazor/Services/EventManager/IEventListenerFactory.cs
  src/MudBlazor/Services/EventManager/WebEventJsonContext.cs
Labels: breaking change, v8

#10054 Docs: Add "Accordion" as alias for Expansion Panels
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
Labels: docs

#10060 MudStepper: Add opt-out Ripple property
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperNonLinearExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/StepperPage.razor
  src/MudBlazor.UnitTests/Components/StepperTests.cs
  src/MudBlazor/Components/Stepper/MudStepper.razor
  src/MudBlazor/Components/Stepper/MudStepper.razor.cs
  src/MudBlazor/Styles/components/_stepper.scss
Labels: enhancement, PR: needs review

#10059 Inputs: Restore original line height
  src/MudBlazor/Styles/components/_input.scss
Labels: bug

#10055 ResizeObserver: Clean up, make implementations internal, add xmodoc
  src/MudBlazor.UnitTests/Services/ResizeObserverTests.cs
  src/MudBlazor/Services/ResizeObserver/IResizeObserver.cs
  src/MudBlazor/Services/ResizeObserver/IResizeObserverFactory.cs
  src/MudBlazor/Services/ResizeObserver/ResizeObserver.cs
  src/MudBlazor/Services/ResizeObserver/ResizeObserverFactory.cs
  src/MudBlazor/Services/ResizeObserver/ResizeObserverOptions.cs
  src/MudBlazor/Services/ResizeObserver/SizeChanged.cs
Labels: breaking change, v8

#10061 JsEvent: Use IAsyncDisposable
  src/MudBlazor.UnitTests/Mocks/MockJsEvent.cs
  src/MudBlazor.UnitTests/Services/JsEventTests.cs
  src/MudBlazor/Services/JsEvent/IJsEvent.cs
  src/MudBlazor/Services/JsEvent/JsEvent.cs
  src/MudBlazor/Services/JsEvent/JsEventFactory.cs
Labels: breaking change, v8

#10062 MudTabs, MudDataGrid: Fix memory leaks #9735
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor.cs
  src/MudBlazor/Components/DataGrid/DataGridColumnResizeService.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Services/EventManager/IEventListenerFactory.cs
  src/MudBlazor/Services/JsEvent/IJsEventFactory.cs
  src/MudBlazor/Services/ResizeObserver/IResizeObserverFactory.cs
  src/MudBlazor/Services/ResizeObserver/ResizeObserver.cs
  src/MudBlazor/Services/Scroll/IScrollListenerFactory.cs
  src/MudBlazor/Services/Scroll/IScrollSpyFactory.cs
Labels: bug, PR: needs review

#10056 MudCollapse: Rework animation
  src/MudBlazor.UnitTests.Viewer/TestComponents/Collapse/CollapseBindingTest.razor
  src/MudBlazor.UnitTests/Components/CollapseTests.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Interop/EventHandlers.cs
  src/MudBlazor/Styles/components/_collapse.scss
Labels: enhancement, breaking change, v8

#10064 MudAutocomplete: add `InputClass`
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: enhancement

#10006 MudGlobal: Add more defaults for Button and Input
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: enhancement, PR: needs review

#10057 Inputs: Refactor adornment related code
  src/MudBlazor.UnitTests/Extensions/EnumExtensionsTests.cs
  src/MudBlazor/Components/Field/MudField.razor
  src/MudBlazor/Components/Field/MudField.razor.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Input/MudInputAdornment.razor
  src/MudBlazor/Components/Input/MudInputAdornment.razor.cs
  src/MudBlazor/Components/Input/MudInputCssHelper.cs
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Enums/Adornment.cs
  src/MudBlazor/Enums/Edge.cs
  src/MudBlazor/Extensions/EnumExtensions.cs
Labels: breaking change, hacktoberfest, hacktoberfest-accepted, v8, hacktoberfest2024

#10065 MudDataGrid Validator [Parameter] (#9860)
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridValidatorExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridValidatorTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement

#10069 Docs: Update ROADMAP for v8 previews
  ROADMAP.md
Labels: docs

#10075 MudStepper: Fix CompletedContent not shown in Vertical variant
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperBasicVerticalExample.razor
  src/MudBlazor.UnitTests/Components/StepperTests.cs
  src/MudBlazor/Components/Stepper/MudStepper.razor
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#10079 MudStepper: Use nameof() instead of hardcoded strings
  src/MudBlazor/Components/Stepper/MudStepper.razor
Labels: PR: needs review

#10063 MudAutocomplete: Fix ResetAsync without debounce not opening the menu
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteStates.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#10004 Docs: Bug Fixes for API Documentation Pages
  src/MudBlazor.Docs.Compiler/ApiDocumentationBuilder.cs
  src/MudBlazor.Docs.Compiler/ApiDocumentationWriter.cs
  src/MudBlazor.Docs.Compiler/DocumentedEvent.cs
  src/MudBlazor.Docs.Compiler/DocumentedMember.cs
  src/MudBlazor.Docs.Compiler/DocumentedMethod.cs
  src/MudBlazor.Docs.Compiler/DocumentedParameter.cs
  src/MudBlazor.Docs.Compiler/DocumentedProperty.cs
  src/MudBlazor.Docs.Compiler/DocumentedType.cs
  src/MudBlazor.Docs.Compiler/MudBlazor.Docs.Compiler.csproj
  src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
  src/MudBlazor.Docs.Compiler/TypeExtensions.cs
  src/MudBlazor.Docs.Server/Program.cs
  src/MudBlazor.Docs.Wasm/Program.cs
  src/MudBlazor.Docs.WasmHost/Program.cs
  src/MudBlazor.Docs/Components/ApiBreadcrumbs.razor.cs
  src/MudBlazor.Docs/Components/ApiGlobalSettingTable.razor.cs
  src/MudBlazor.Docs/Components/ApiMemberTable.razor
  src/MudBlazor.Docs/Components/ApiMemberTable.razor.cs
  src/MudBlazor.Docs/Components/ApiText.cs
  src/MudBlazor.Docs/Components/ApiTypeHierarchy.razor
  src/MudBlazor.Docs/Components/ApiTypeHierarchy.razor.cs
  src/MudBlazor.Docs/Components/ApiTypeLink.cs
  src/MudBlazor.Docs/Components/ApiTypeTable.razor.cs
  src/MudBlazor.Docs/Components/SectionContent.razor
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
  src/MudBlazor.Docs/Extensions/RenderTreeExtensions.cs
  src/MudBlazor.Docs/Models/Generated/ApiDocumentation.cs
  src/MudBlazor.Docs/Models/Generated/DocumentedEvent.cs
  src/MudBlazor.Docs/Models/Generated/DocumentedField.cs
  src/MudBlazor.Docs/Models/Generated/DocumentedMember.cs
  src/MudBlazor.Docs/Models/Generated/DocumentedMethod.cs
  src/MudBlazor.Docs/Models/Generated/DocumentedParameter.cs
  src/MudBlazor.Docs/Models/Generated/DocumentedProperty.cs
  src/MudBlazor.Docs/Models/Generated/DocumentedType.cs
  src/MudBlazor.Docs/Models/MudComponent.cs
  src/MudBlazor.Docs/Pages/Api/Api.razor
  src/MudBlazor.Docs/Pages/Api/Api.razor.cs
  src/MudBlazor.Docs/Services/Menu/IMenuService.cs
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.UnitTests/Components/Documentation/ApiMemberTableTests.cs
  src/MudBlazor.UnitTests/Components/Documentation/ApiTextTests.cs
  src/MudBlazor.UnitTests/Components/Documentation/ApiTypeLinkTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor/Base/MudBaseButton.cs
Labels: docs

#10071 Inputs, Menu: Standardize default origin point
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, breaking change, v8

#10095 MudDrawer: Make Temporary Drawer non-responsive
  src/MudBlazor.Docs/Pages/Components/Drawer/DrawerPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerNonResponsiveTest.razor
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
Labels: bug, breaking change, v8

#10087 MudDatePicker: Use TimeProvider to allow mocking current date
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DatePickerCustomDateTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#10089 MudPopover: Fix z-index issues with nested popovers
  src/MudBlazor.Docs/Pages/Components/AppBar/AppBarPage.razor
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarMenuExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverAppBarMenuSubMenuTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDataGridFilterOptionsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDrawerWithSelectTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverOverlaySelectTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverTooltipInOverlayTest.razor
  src/MudBlazor/Styles/components/_popover.scss
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, v8, epic

#10102 Refactor: Remove CodeMessage
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbLink.razor
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Utilities/CodeMessage.cs
Labels: refactor

#10103 Docs: Add null check for Appbar Search
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
Labels: docs

#10070 Inputs: Hide Clear button when readonly
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/InputTests.cs
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/TextField/MudTextField.razor
  src/MudBlazor/Components/TextField/MudTextField.razor.cs
Labels: enhancement

#10105 Refactor: Fix formatting
  src/MudBlazor.Docs/Components/LandingPage/LandingSection.razor
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/InputTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/FooterCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGridPager.razor.cs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDynamicDropItem.razor.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Input/MudRangeInput.razor.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/Stepper/MudStepper.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: refactor

#10106 MudPopover: Fix regression with respect to direction and location and z-index
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDirectionAndLocationTest.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, PR: needs review

#10110 Fix origin points that relied on previous defaults
  src/MudBlazor.Docs/Pages/Components/Dialog/Examples/DialogKeyboardNavigationExample_Dialog.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImagePlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/MultiSelectCustomizedExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectCustomConverterExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectKeyboardNavigationExample.razor
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTestNestWithMouseOver.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectVariantsTest.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#10091 MudToggleGroup: Unregister removed items
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleGroup/ToggleGroupRemoveTest.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
Labels: bug

#10118 Docs: Fix Releases page not linking PR IDs other than 4 in length
  src/MudBlazor.Docs/Pages/Mud/Project/Releases.razor
Labels: docs

#10121 Picker: Add nullable annotation
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Picker/MudPickerContent.razor.cs
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor.cs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#10084 MudNavGroup up to MudPaper: Add XML Documentation for Public Members
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavLink.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor.cs
  src/MudBlazor/Components/NavMenu/NavigationContext.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/PageContentNavigation/MudPageContentNavigation.razor.cs
  src/MudBlazor/Components/Pagination/MudPagination.razor.cs
  src/MudBlazor/Components/Paper/MudPaper.razor.cs
Labels: docs

#10135 UnitTests.Viewer: Work on nulalble annotation, formatting, code style
  src/MudBlazor.UnitTests.Viewer/TestComponents/General/AllInputsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/DebouncedNumericFieldCultureChangeRerenderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Overlay/OverlayVisibleBindingWithAutoCloseTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Pagination/PaginationButtonTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Pagination/PaginationCountTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Picker/SimplePickerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverAppBarMenuSubMenuTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverComplexContent.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDataGridFilterOptionsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDirectionAndLocationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDrawerWithSelectTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverDuplicationTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverOverlaySelectTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverPropertyTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverProviderTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverTooltipInOverlayTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupExceptionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupRequiredTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest3.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest4.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest5.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/RadioGroup/RadioGroupTest6.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Scroll/ScrollToTopTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectCustomizedTextTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest3.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest4.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest5.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest6.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest7.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTestRequiredValue.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectWithCustomComparerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectWithInitialValues.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/ReloadSelectItemsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/ReselectValueTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectClearableTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectEventCountTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectEventCountTest.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectRequiredTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectUnrepresentableValueTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectUnrepresentableValueTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectValidationDataAttrTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectVariantsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectWithEnumTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectWithoutItemPresentersTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithCustomValueLabelContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithNullable.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Slider/SliderWithTwoBindValues.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarCustomComponent.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarCustomComponentMessageTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarLongMessageTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarRenderFragmentMessageTest.razor
Labels: docs

#10112 MudBreadcrumbs: Fix separator template not vertically centered
  src/MudBlazor/Styles/components/_breadcrumbs.scss
Labels: bug, PR: needs review

#10133 MudDataGrid: Correctly render initially expanded rows
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor.cs
Labels: bug

#10108 MudAutocomplete: Add test to MudAutocomplete.ResetAsync
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteStates.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
Labels: tests

#10142 IJSRuntimeExtensions: Fix when pre-rendering
  src/MudBlazor.UnitTests/Extensions/IJSRuntimeExtensionsTests.cs
  src/MudBlazor.UnitTests/Mocks/RemoteJSRuntime.cs
  src/MudBlazor/Extensions/IJSRuntimeExtensions.cs
Labels: bug

#10122 MudMenu: Fix PositionAtCursor
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridContextMenuExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridContextMenuTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuPositionAtCursorTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, enhancement

#10125 Form: Add nullable annotation
  src/MudBlazor/Components/Form/MudForm.razor
  src/MudBlazor/Components/Form/MudForm.razor.cs
Labels: enhancement

#10134 MudTextField: Fix ShrinkLabel for text fields with Mask
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldShrinkLabelTest.razor
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Mask/MudMask.razor.cs
  src/MudBlazor/Components/TextField/MudTextField.razor
Labels: bug

#10149 MudDataGrid: Rename _classname to Classname etc
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Cell.cs
  src/MudBlazor/Components/DataGrid/CellContext.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/FooterCell.razor
  src/MudBlazor/Components/DataGrid/FooterCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderContext.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: breaking change, PR: needs review
