Repository MudBlazor/MudBlazor, pull requests merged in 2024-11, with the labels that each got.

#10096 MudTreeView: Add parameter FilterFunc for selectively displaying tree nodes
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewFilteringExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewFilterFuncTest.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/TreeItemData.cs
Labels: enhancement, PR: needs review

#10145 Docs: Improved Responsiveness for Mobile Devices
  src/MudBlazor.Docs.Compiler/ApiDocumentationBuilder.cs
  src/MudBlazor.Docs/Components/ApiMemberTable.razor
  src/MudBlazor.Docs/Pages/Api/Api.razor
  src/MudBlazor.UnitTests/Components/Documentation/ApiMemberTableTests.cs
Labels: docs

#10154 MudPagination: Use ParameterState
  src/MudBlazor.UnitTests/Components/PaginationTests.cs
  src/MudBlazor/Components/Pagination/MudPagination.razor
  src/MudBlazor/Components/Pagination/MudPagination.razor.cs
Labels: bug, breaking change, PR: needs review, v8

#10165 Chore: Drop CollectionExtensions for .NET 9+
  src/MudBlazor/Extensions/CollectionExtensions.cs
Labels: performance

#10164 Build: Remove sonar.yml workflow
  .github/workflows/sonar.yml
Labels: build, PR: needs review

#10116 MudBreadcrumbs: Convert BreadcrumbItem to record type
  src/MudBlazor.Docs/Pages/Components/Breadcrumbs/Examples/BreadcrumbsBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Breadcrumbs/Examples/BreadcrumbsCollapsedExample.razor
  src/MudBlazor.Docs/Pages/Components/Breadcrumbs/Examples/BreadcrumbsItemIconsExample.razor
  src/MudBlazor.Docs/Pages/Components/Breadcrumbs/Examples/BreadcrumbsItemTemplateExample.razor
  src/MudBlazor.Docs/Pages/Components/Breadcrumbs/Examples/BreadcrumbsSeparatorExample.razor
  src/MudBlazor.Docs/Pages/Components/Breadcrumbs/Examples/BreadcrumbsSeparatorTemplateExample.razor
  src/MudBlazor.UnitTests/Components/BreadcrumbTests.cs
  src/MudBlazor.UnitTests/Components/UserAttributes/MudComponentFactory.cs
  src/MudBlazor/Components/Breadcrumbs/BreadcrumbItem.cs
Labels: breaking change

#10115 MudBreadcrumbs: Change HTML structure and semantics for accessibility
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor
Labels: enhancement, breaking change, PR: needs review, accessibility

#10160 MudNavGroup: Add TitleContent parameter
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuGroupTitleExample.razor
  src/MudBlazor.Docs/Pages/Components/NavMenu/NavMenuPage.razor
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
Labels: enhancement

#10167 Add Sonar badge
  README.md
Labels: PR: needs review

#10166 Build: Disable Renovate Badges
  .github/renovate.json
Labels: build

#10156 MudDataGrid: Custom comparer
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSelectionComparerTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement

#10127 Autocomplete: Add nullable annotation
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutoCompleteContainer.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteChangeBoundObjectTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteFocusTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteItemTemplateDisplayTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteListBeforeAndAfterRendersWithItemsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteListEndRendersTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteListStartRendersTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteSetParametersInitialization.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteStrictFalseTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteSyncTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest4.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest5.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest6.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest7.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest8.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTestClearable.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTestCoersionAndBlur.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteValidationTest.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/InputControl/MudInputControl.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
Labels: enhancement

#10169 Docs: Change Member Table to MudToggleGroup
  src/MudBlazor.Docs/Components/ApiMemberTable.razor
  src/MudBlazor.Docs/Pages/Api/Api.razor
  src/MudBlazor.Docs/Styles/components/_docssection.scss
Labels: docs, PR: needs review

#10170 MudPopover: Add XML Documentation for Public Members
  src/MudBlazor/Components/Breadcrumbs/MudBreadcrumbs.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Picker/MudPickerContent.razor.cs
  src/MudBlazor/Components/Picker/MudPickerToolbar.razor.cs
  src/MudBlazor/Components/Popover/IPopover.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverBase.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Components/Radio/IMudRadioGroup.cs
  src/MudBlazor/Components/Radio/MudRadio.razor.cs
  src/MudBlazor/Components/Radio/MudRadioGroup.razor.cs
  src/MudBlazor/Enums/OverflowBehavior.cs
Labels: docs

#10162 MudToggleGroup: Fix icon margins
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: bug, breaking change

#10129 MudSelect: Open menu on pointer down instead of click
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor
Labels: breaking change

#10183 Tests: Fix CS1998 and remove the pragma for this rule
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/BunitTest.cs
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/DynamicTabsTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/InputTests.cs
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor.UnitTests/Components/NavLinkTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
Labels: tests

#10161 MudAutocomplete: Don't wrap around selected index with down arrow
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: breaking change, accessibility

#10151 MudDataGrid: Fix Sticky Columns with Sticky Headers
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableStickyVisualTest.razor
  src/MudBlazor/Styles/components/_datagrid.scss
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review

#10202 JS: Fix cannot read properties of undefined / null
  src/MudBlazor/TScripts/mudJsEvent.js
  src/MudBlazor/TScripts/mudKeyInterceptor.js
Labels: bug, PR: needs review

#10203 MudInputAdornment: Add nullable annotation.
  src/MudBlazor/Components/Input/MudInputAdornment.razor.cs
Labels: enhancement

#10199 MudList: Fix logic of the Gutters parameter
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListItemGuttersTest.razor
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor/Components/List/MudList.razor.cs
  src/MudBlazor/Components/List/MudListItem.razor
  src/MudBlazor/Components/List/MudListItem.razor.cs
Labels: bug

#10184 MudTabs: Fix scrolling to active index
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/ScrollableTabsRenderTest.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockResizeObserver.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#10097 Fix`--mud-appbar-height` not always match `MudAppBar`'s actual height
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Styles/abstracts/_variables.scss
  src/MudBlazor/Styles/components/_dialog.scss
  src/MudBlazor/Styles/layout/_appbar.scss
  src/MudBlazor/Styles/layout/_drawer.scss
  src/MudBlazor/Styles/layout/_main.scss
  src/MudBlazor/Themes/Models/LayoutProperties.cs
Labels: breaking change, PR: needs review

#10213 MudDataGrid: Allow grouping by null values
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnGroupingTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Utilities/NullableObjectTests.cs
  src/MudBlazor/Components/DataGrid/GroupDefinition.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Utilities/NullableObject.cs
Labels: bug

#10215 [MudSelect] Control popover width
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectPopoverRelativeWidthTest.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, PR: needs review

#10123 NumericField: Add nullable annotation
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#10124 Input: Add nullable annotation
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Input/MudInputCssHelper.cs
  src/MudBlazor/Components/Input/MudInputLabel.razor.cs
  src/MudBlazor/Components/Input/MudRangeInput.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor.cs
  src/MudBlazor/Components/Input/Range.cs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#10221 MudInput: Remove `@onmousewheel`
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor/Components/Input/MudInput.razor
Labels: refactor

#10210 MudAppBar: Add contextual action bar implementation
  src/MudBlazor.Docs/Pages/Components/AppBar/AppBarPage.razor
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarContextualExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/AppBar/ContextualAppBarTest.razor
  src/MudBlazor.UnitTests/Components/AppBarTests.cs
  src/MudBlazor.UnitTests/Components/UserAttributes/UserAttributesTests.cs
  src/MudBlazor/Components/AppBar/MudAppBar.razor
  src/MudBlazor/Components/AppBar/MudAppBar.razor.cs
  src/MudBlazor/Components/AppBar/MudContextualActionBar.razor
  src/MudBlazor/Components/AppBar/MudContextualActionBar.razor.cs
Labels: enhancement

#10216 MudSelect, MudMenu: Fix max height exceeds window
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuNoFlipScrollBarTest.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, PR: needs review

#10138 MudAutocomplete: Coerce value immediately
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteStates.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: breaking change

#10231 Build: Support .NET 9 in workflows
  .github/workflows/deploy-mudblazor-nuget.yml
Labels: build, PR: needs review

#10238 MudSelect/MudDatePicker: Fix accidental MudDatePicker break while maintaining desired MudSelect behavior
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#10218 MudDataGrid: Fix virtualized indexes (#10179)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridVirtualizeServerDataLoadingLargeDataSetTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridVirtualizeServerDataLoadingWithCancelTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridVirtualizeServerDataLoadingWithSearchTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Virtualize/VirtualizeNoRecordsContentTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/VirtualizeTests.cs
  src/MudBlazor/Components/DataGrid/IndexBag.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs
Labels: bug

#10172 MudMenu: Fix menu closing if mouse move too quickly
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuTestNestWithQuicklyMouseMove.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: bug, PR: needs review

#10223 Docs: Improved Documentation for MudGlobal Settings
  src/MudBlazor.Docs.Compiler/ApiDocumentationBuilder.cs
  src/MudBlazor.Docs/Components/ApiGlobalSettingTable.razor
  src/MudBlazor.Docs/Components/ApiGlobalSettingTable.razor.cs
  src/MudBlazor.Docs/Components/ApiMemberTable.razor
  src/MudBlazor.Docs/Components/ApiMemberTable.razor.cs
  src/MudBlazor.Docs/Components/ApiMemberTableMode.cs
  src/MudBlazor.Docs/Models/DocsLink.cs
  src/MudBlazor.Docs/Pages/Api/Api.razor
  src/MudBlazor.Docs/Pages/Api/Index.razor.cs
  src/MudBlazor.Docs/Pages/Customization/Globals/Examples/ButtonGlobalsExample.razor
  src/MudBlazor.Docs/Pages/Customization/Globals/Examples/ButtonGlobalsStartupExample.razor
  src/MudBlazor.Docs/Pages/Customization/Globals/Examples/GlobalExceptionHandlerExample.razor
  src/MudBlazor.Docs/Pages/Customization/Globals/Globals.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.Docs/Shared/NavMenu.razor
  src/MudBlazor.UnitTests/Components/Documentation/ApiMemberTableTests.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: docs

#10260 Docs: Globals - fix grammar
  src/MudBlazor.Docs/Pages/Customization/Globals/Globals.razor
Labels: docs

#10261 MudBlazor.Docs.Compiler: Improve nullability
  src/MudBlazor.Docs.Compiler/ApiDocumentationBuilder.cs
  src/MudBlazor.Docs.Compiler/ApiDocumentationWriter.cs
  src/MudBlazor.Docs.Compiler/CodeBuilder.cs
  src/MudBlazor.Docs.Compiler/CodeSnippets.cs
  src/MudBlazor.Docs.Compiler/DocStrings.cs
  src/MudBlazor.Docs.Compiler/DocumentedEvent.cs
  src/MudBlazor.Docs.Compiler/DocumentedField.cs
  src/MudBlazor.Docs.Compiler/DocumentedMember.cs
  src/MudBlazor.Docs.Compiler/DocumentedMethod.cs
  src/MudBlazor.Docs.Compiler/DocumentedParameter.cs
  src/MudBlazor.Docs.Compiler/DocumentedProperty.cs
  src/MudBlazor.Docs.Compiler/DocumentedType.cs
  src/MudBlazor.Docs.Compiler/ExamplesMarkup.cs
  src/MudBlazor.Docs.Compiler/Paths.cs
  src/MudBlazor.Docs.Compiler/Program.cs
  src/MudBlazor.Docs.Compiler/StringExtensions.cs
  src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
  src/MudBlazor.Docs.Compiler/TestsForExamples.cs
  src/MudBlazor.Docs.Compiler/TypeExtensions.cs
  src/MudBlazor.Docs.Compiler/XmlDocumentation.cs
Labels: build

#9908 Build: Disable warnings about files being in the wrong namespace
  src/.editorconfig
Labels: build

#10264 MudGlobal: Add defaults for MudPaper
  src/MudBlazor/Components/Paper/MudPaper.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: enhancement, PR: needs review

#10220 DataGridTests: Fix test failure by using Invariant Culture
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/ListTests.cs
Labels: bug

#10258 Docs: Reorganize menu examples
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuTransformOriginExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuWithExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuWithNestingExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
Labels: docs

#10270 Pickers: Fix popover elevation and gap
  src/MudBlazor.Docs/Pages/Components/ColorPicker/ColorPickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/TimePickerPage.razor
  src/MudBlazor.UnitTests/Components/ColorPickerTests.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Styles/components/_picker.scss
Labels: bug

#10289 Docs: Fix error on Icons and Typography pages after #10262
  src/MudBlazor.Docs/Pages/Customization/Theming/Typography.razor
  src/MudBlazor.Docs/Pages/Features/Icons/IconsPage.razor
Labels: docs

#10275 MudColor: Add Lerp
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: enhancement

#10293 Docs: Rename files to avoid dotnet clean removal
  src/MudBlazor.Docs/Pages/Features/Localization/LocalizationPage.razor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/CrowdsourcedTranslationsInstall.razor
  src/MudBlazor.Docs/Pages/Features/Localization/ManualMarkdown/CrowdsourcedTranslationsInstallCode.html
Labels: bug, docs, PR: needs review

#10295 MudColor: Add IFormattable
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: enhancement

#10296 Build: Update SASS compiler
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: bug, build

#10268 MudNavGroup: Add HeaderClass for title customization
  src/MudBlazor.Docs/Pages/Components/NavMenu/Examples/NavMenuGroupTitleExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NavMenu/NavMenuGroupDisabledTest.razor
  src/MudBlazor/Components/NavMenu/MudNavGroup.razor.cs
Labels: enhancement, PR: needs review

#10304 Build: Unblock SassCompiler updates
  .github/renovate.json
Labels: bug, PR: needs review

#10285 Snackbar: Move Icon configs to CommonSnackbarOptions
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarIconConfiguationTest.razor
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor/Components/Snackbar/CommonSnackbarOptions.cs
  src/MudBlazor/Components/Snackbar/SnackbarOptions.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#9445 MudSwipeArea: Replace ontouch with onpointer
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDatePickerExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsPreventDefaultExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDrawerExample.razor
  src/MudBlazor.UnitTests/Components/CarouselTests.cs
  src/MudBlazor.UnitTests/Components/SwipeTests.cs
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Components/SwipeArea/SwipeEventArgs.cs
  src/MudBlazor/TScripts/mudElementReference.js
Labels: bug, enhancement, breaking change, API change, v8

#10280 RegexMask: Add note to specify the regex must start with ^ and end with $
  src/MudBlazor.Docs/Pages/Features/Masking/MaskingPage.razor
Labels: docs, PR: needs review

#10226 MudDialog: Fix exception when closing a dialog while rendering
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/ComponentThatOpensAndClosesDialog.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/SimpleDialog.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor
  src/MudBlazor/Components/Dialog/MudDialogProvider.razor.cs
Labels: bug

#8589 Snackbar: Allow to attach custom task on close button click
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarActionButtonExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarOnClickExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarOnCloseExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/Examples/SnackbarRequireInteractionExample.razor
  src/MudBlazor.Docs/Pages/Components/Snackbar/SnackbarPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Snackbar/SnackbarCustomActionOnCloseTest.razor
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/MudSnackbarElement.razor.cs
  src/MudBlazor/Components/Snackbar/SnackBarMessageState.cs
  src/MudBlazor/Components/Snackbar/Snackbar.cs
  src/MudBlazor/Components/Snackbar/SnackbarOptions.cs
Labels: enhancement, breaking change, PR: needs review

#10313 MudColor: Add Palette algorithms
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerPaletteExample.razor
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.Algorithms.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: enhancement

#10316 MudColor: Fix special case in GenerateGradientPalette
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerPaletteExample.razor
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.Algorithms.cs
Labels: bug

#10254 MudDataGrid: Allow overriding default filter operators per column
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterPerColumnTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/Filter.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: enhancement

#10321 MudColorPicker: Add nullable annotation.
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: enhancement

#10333 MudColor: Add IParsable and Deconstruct
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: enhancement

#10352 DataGridContextMenuExample: Fix null exception
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridContextMenuExample.razor
Labels: docs

#10292 MudDataGrid: Fix Filter Panel Positioning with FixedHeader = true
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFixedHeaderFilterTest.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#10346 MudTimeline: Fix item alignment in nested horizontal timeline (#9958)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Timeline/HorizontalTimelineInsideVerticalTimelineTest.razor
  src/MudBlazor.UnitTests/Components/TimelineTests.cs
  src/MudBlazor/Styles/components/_timeline.scss
Labels: bug, PR: needs review

#10263 New Chart: HeatMap
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/HeatMapExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/HeatMapExample2.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/HeatMapExample3.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/HeatMapExample4.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/HeatMapExample5.razor
  src/MudBlazor.Docs/Pages/Components/Charts/HeatMapChartPage.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/HeatMapChartTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Charts/HeatMapDynamicFontTest.razor
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor/Components/Chart/ChartType.cs
  src/MudBlazor/Components/Chart/Charts/HeatMap.razor
  src/MudBlazor/Components/Chart/Charts/HeatMap.razor.cs
  src/MudBlazor/Components/Chart/Charts/HeatMapCell.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/Chart/Models/InterpolationOption.cs
  src/MudBlazor/Components/Chart/Models/XAxisLabelPosition.cs
  src/MudBlazor/Components/Chart/Models/YAxisLabelPosition.cs
  src/MudBlazor/Components/Chart/MudChart.razor
  src/MudBlazor/Components/Chart/MudChartBase.cs
  src/MudBlazor/Styles/components/_charts.scss
Labels: enhancement, epic

#10356 IJSRuntimeExtensions: Fix InvokeVoidAsyncIgnoreErrors to catch JSException
  src/MudBlazor.UnitTests/Extensions/IJSRuntimeExtensionsTests.cs
  src/MudBlazor.UnitTests/Mocks/ExceptionJavascriptRuntime.cs
  src/MudBlazor/Extensions/IJSRuntimeExtensions.cs
Labels: bug

#10355 MudColor: Change Equals logic
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: enhancement, breaking change

#10327 MudAutocomplete, MudSelect: Allow popover customization and add scroll events
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectScrollDrawerTest.razor
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Popover/DropDownSettings.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, enhancement

#10349 MudMenu: Hide Button when Label, Icon and Content are unset
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/ContextMenuExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/ContextMenuTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuHrefTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Styles/components/_menu.scss
Labels: enhancement, PR: needs review

#10359 ParameterState: Add IsChildOriginatedChange to ParameterChangedEventArgs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildComp1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildComp1.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildComp2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildComp2.razor.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Utilities/ParameterStateChildParentTestComp.razor
  src/MudBlazor.UnitTests/State/ParameterStateUsageTests.cs
  src/MudBlazor/State/ParameterChangedEventArgs.cs
  src/MudBlazor/State/ParameterStateInternalOfT.cs
Labels: enhancement
