Repository MudBlazor/MudBlazor, pull requests merged in 2024-01, with the labels that each got.

#7933 Build: Generate staticwebassets with MSBuild Tasks to fix dotnet SDK 8.0 build
  .gitignore
  global.json
  src/MudBlazor.Docs/.config/dotnet-tools.json
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/excubowebcompiler.json
  src/MudBlazor.Docs/sasscompiler.json
  src/MudBlazor/.config/dotnet-tools.json
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/excubowebcompiler.json
  src/MudBlazor/sasscompiler.json
Labels: build

#7981 Code Quality: Remove commented out tests
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
Labels: PR: needs review

#7979 Build: net8.0 - multitarget v6 library and update docs and tests
  .vscode/launch.json
  src/MudBlazor.Docs.Compiler/MudBlazor.Docs.Compiler.csproj
  src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs.WasmHost/Prerender/PrerenderMiddleware.cs
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/Services/DiscordApiClient.cs
  src/MudBlazor.Docs/Services/GitHubApiClient.cs
  src/MudBlazor.Docs/Services/NugetApiClient.cs
  src/MudBlazor.Examples.Data/MudBlazor.Examples.Data.csproj
  src/MudBlazor.SourceCodeGenerator/MudBlazor.SourceCodeGenerator.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
  src/MudBlazor/MudBlazor.csproj
  src/MudBlazor/Services/IIJSRuntimeExtentions.cs
  src/MudBlazor/Services/Scroll/ScrollManagerException.cs
Labels: enhancement, build, PR: needs review

#7989 Tests: Update to nunit 4.0.1
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/Dialog/DialogParametersTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/MessageBoxTests.cs
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor.UnitTests/Components/RadioTests.cs
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
  src/MudBlazor.UnitTests/Other/CategoryAttributeTests.cs
  src/MudBlazor.UnitTests/Services/Browser/BrowserViewportServiceTests.cs
  src/MudBlazor.UnitTests/Services/Browser/BrowserViewportSubscriptionTests.cs
  src/MudBlazor.UnitTests/Services/EventListenerTests.cs
  src/MudBlazor.UnitTests/Services/Popover/PopoverServiceTests.cs
  src/MudBlazor.UnitTests/Utilities/Background/BackgroundWorkerTests.cs
  src/MudBlazor.UnitTests/Utilities/Background/BatchPeriodicQueueTests.cs
  src/MudBlazor.UnitTests/Utilities/Expressions/PropertyPathTests.cs
  src/MudBlazor.UnitTests/Utilities/MarkupCompilerTests.cs
  src/MudBlazor.UnitTests/Utilities/ObserverManager/ObserverManagerTests.cs
Labels: tests, PR: needs review

#7994 MudToggleGroup: Rename SelectedValues and warn if misconfigured
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleSelectionsExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/ToggleGroupPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleBindMultiSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Toggle/ToggleInitializeTest.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
Labels: enhancement, breaking change

#7996 MudTextField: Fix double triggering of validation on blur (#7034)
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
Labels: bug

#8006 Tests: Update bunit
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
Labels: bug, tests, PR: needs review

#8007 Build: Remove github sourcelink (now native in SDK 8.0)
  src/MudBlazor/MudBlazor.csproj
Labels: build, PR: needs review

#8013 Docs: Autofocusing on search field in search dialog
  src/MudBlazor.Docs/Shared/Appbar.razor
Labels: docs, enhancement

#8002 Docs: Fix Canonical for search engines
  src/MudBlazor.Docs.Server/Pages/_Layout.cshtml
  src/MudBlazor.Docs/Components/DocsPageHeader.razor
Labels: bug, docs

#8010 DataGrid: Throw exception when ServerData and QuickFilter are supplied (#7998)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerDataQuickFilterTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, breaking change

#8033 DataGrid: Make RowsPerPage two-way bindable
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridRowsPerPageBindingTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement

#8024 Docs: Fix pre-render running twice per page
  src/MudBlazor.Docs.Compiler/TestsForApiPages.cs
  src/MudBlazor.Docs.Wasm/Program.cs
  src/MudBlazor.Docs.WasmHost/CrawlerInfo.json
  src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml
  src/MudBlazor.Docs.WasmHost/Pages/_Host.cshtml.cs
  src/MudBlazor.Docs/Components/DocsPageHeader.razor
  src/MudBlazor.Docs/Extensions/NavigationManagerExtensions.cs
  src/MudBlazor.Docs/wwwroot/JS/docs.js
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockNavigationManager.cs
Labels: bug, docs

#8036 Docs: Make drawer breakpoint same as layout breakpoint
  src/MudBlazor.Docs/Shared/DocsLayout.razor
Labels: bug, docs, PR: needs review

#8040 Docs: Remove MudHidden for perf and prerendering
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/DocsLayout.razor.cs
Labels: docs, enhancement

#8047 Docs: Link to codecov from badge
  README.md
Labels: docs, enhancement, PR: needs review

#8050 Build: Update dotnet packages
  src/MudBlazor.Docs.Wasm/MudBlazor.Docs.Wasm.csproj
  src/MudBlazor.Docs.WasmHost/MudBlazor.Docs.WasmHost.csproj
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.UnitTests.Viewer/MudBlazor.UnitTests.Viewer.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: build, PR: needs review

#8055 Docs: MudBlazor text alignment on docs/landingpage
  src/MudBlazor.Docs/Shared/Appbar.razor
Labels: bug, docs, PR: needs review

#8014 MudTable: add OnRowMouseEnter and OnRowMouseLeave events
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableRowHoverEventsExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableRowHoverTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Components/Table/TableRowHoverEventArgs.cs
Labels: enhancement, PR: needs review

#8008 MudTable: fix Bordered in RTL mode
  src/MudBlazor/Styles/components/_table.scss
Labels: bug

#8071 BrowserViewportService: Fix when the circuit has disconnected in BSS
  src/MudBlazor/Interop/ResizeListenerInterop.cs
  src/MudBlazor/Services/IIJSRuntimeExtentions.cs
Labels: bug

#8069 MudToggle: Make first example mobile ready
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleBasicsExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleCustomContentExample.razor
Labels: bug, docs, PR: needs review

#8057 MudPopoverProvider: Don't static render
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Extensions/TestContextExtensions.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockRenderContext.cs
  src/MudBlazor.UnitTests/Mocks/MockStaticRenderContext.cs
  src/MudBlazor.UnitTests/Services/RenderContextTests.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/RenderContext/IRenderContext.cs
  src/MudBlazor/Services/RenderContext/RenderContext.cs
Labels: enhancement, PR: needs review

#8077 Revert "MudPopoverProvider: Don't static render (#8057)"
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Extensions/TestContextExtensions.cs
  src/MudBlazor.UnitTests/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests/Mocks/MockRenderContext.cs
  src/MudBlazor.UnitTests/Mocks/MockStaticRenderContext.cs
  src/MudBlazor.UnitTests/Services/RenderContextTests.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Services/RenderContext/IRenderContext.cs
  src/MudBlazor/Services/RenderContext/RenderContext.cs
Labels: bug, PR: needs review

#7810 MudTreeView: Fix selection issues
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/DelegateEqualityComparer.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewCompareMultiSelectTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewCompareTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTest6.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewTest7.razor
  src/MudBlazor.UnitTests/Components/TreeViewTest.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItemComparer.cs
Labels: bug

#8081 MudTable: Optimize event handling for OnRowMouseEnter/Leave
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: bug

#8059 MudTable: make OnRowClicked async/awaitable
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
Labels: enhancement, PR: needs review

#8102 MudThemingProvider: MudThemeProvider without MudPopoverProvider
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Components/ThemeProvider/MudThemingProvider.razor
  src/MudBlazor/Components/ThemeProvider/MudThemingProvider.razor.cs
Labels: enhancement
