Repository MudBlazor/MudBlazor, pull requests merged in 2024-09, with the labels that each got.

#9693 Docs: Reorganize TextField examples
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
Labels: docs, PR: needs review

#9680 Docs: Reorganize button examples
  src/MudBlazor.Docs/Pages/Components/Button/ButtonPage.razor
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/ButtonGroupPage.razor
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupSizesColorsExample.razor
  src/MudBlazor.Docs/Pages/Components/ButtonGroup/Examples/ButtonGroupVerticalExample.razor
  src/MudBlazor.Docs/Pages/Components/IconButton/Examples/IconButtonFontIconExample.razor
  src/MudBlazor.Docs/Pages/Components/IconButton/Examples/IconButtonSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/IconButton/IconButtonPage.razor
  src/MudBlazor.Docs/Pages/Components/ToggleIconButton/Examples/ToggleIconButtonEventCallbackExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleIconButton/Examples/ToggleIconButtonTwoWayBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleIconButton/ToggleIconButtonPage.razor
Labels: docs

#9678 Docs: Add visual playgrounds for MudSelect and MudAutocomplete
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompleteMarginDenseExample.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompletePlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectPlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectPropsExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectVariantsExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
Labels: docs, PR: needs review

#9745 Build: Prevent Sonar workflow in forks
  .github/workflows/sonar.yml
Labels: build

#9744 Docs: Make default switches use the primary color
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarUsageExample.razor
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompletePlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxReadOnlyExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridCustomSortingExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridEditingExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridResizeExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/Examples/LabelAttributeExample.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/Examples/MessageBoxOptionsExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectPlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/SimpleTable/Examples/SimpleTableFixedHeaderExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableFixedHeaderExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableHeaderAndFooterExample.razor
Labels: docs, PR: needs review

#9738 Typography: Improve code docs
  src/MudBlazor/Themes/Models/Typography.cs
Labels: docs, PR: needs review

#9763 Snackbar: Revert ReaderWriterLockSlim dispose in SnackbarService
  src/MudBlazor.UnitTests/Components/SnackbarTests.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
Labels: bug

#9765 CsssBuilder/StyleBuilder: Fix for initialized as default
  src/MudBlazor.UnitTests/Utilities/CssBuilderTests.cs
  src/MudBlazor.UnitTests/Utilities/StyleBuilderTests.cs
  src/MudBlazor/Utilities/CssBuilder.cs
  src/MudBlazor/Utilities/StringBuilderCache.cs
  src/MudBlazor/Utilities/StyleBuilder.cs
Labels: bug

#9798 MudTreeViewItem: Add property Visible for conditionally hiding sub-trees without reloading
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewFilteringExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/ItemVisibleTreeViewTest.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Components/TreeView/TreeItemData.cs
Labels: enhancement

#9713 MudButtonGroup: Stretch child buttons
  src/MudBlazor.UnitTests.Viewer/TestComponents/ButtonGroup/ButtonGroupFullWidth.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ButtonGroup/ButtonGroupFullWidthWithButtonFullWidth.razor
  src/MudBlazor.UnitTests/Components/ButtonGroupTests.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
Labels: enhancement

#9818 MudDialogInstance: SetTitle mark parameter as nullable (#9817)
  src/MudBlazor/Components/Dialog/MudDialogInstance.razor.cs
Labels: bug

#9822 MudListItem: Allow overriding `tabindex` via UserAttributes
  src/MudBlazor.UnitTests.Viewer/TestComponents/List/ListItemTabIndexTest.razor
  src/MudBlazor.UnitTests/Components/ListTests.cs
  src/MudBlazor/Components/List/MudListItem.razor
Labels: bug, PR: needs review

#9834 Fix some off-screen tabbing on main docs page
  src/MudBlazor.Docs/Components/LandingPage/MiniApp/MiniApp.razor
Labels: docs

#9838 MudColor: Remove [JsonInclude] from public properties
  src/MudBlazor.UnitTests/Dummy/MudColorSerializerContext.cs
  src/MudBlazor.UnitTests/Utilities/MudColorTests.cs
  src/MudBlazor/Utilities/MudColor.cs
Labels: bug

#9840 Typography: Fix cannot resolve symbol in the xmldoc
  src/MudBlazor/Themes/Models/Typography.cs
Labels: docs

#9835 MudButton : Implement IDisposable
  src/MudBlazor.UnitTests.Viewer/TestComponents/ButtonGroup/ButtonGroupFullWidth.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ButtonGroup/ButtonGroupFullWidthWithButtonFullWidth.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/ButtonGroup/ButtonGroupWithThreeButtons.razor
  src/MudBlazor.UnitTests/Components/ButtonGroupTests.cs
  src/MudBlazor/Components/Button/MudButton.razor
  src/MudBlazor/Components/Button/MudButton.razor.cs
Labels: bug

#9844 MudButton: Fix sonar warning about Dispose implementation
  src/MudBlazor/Components/Button/MudButton.razor.cs
Labels: bug

#9846 ThrottleDispatcherTests: Attempt to fix flaky test
  src/MudBlazor.UnitTests/Utilities/Throttle/ThrottleDispatcherTests.cs
Labels: tests, PR: needs review

#9814 Add dark mode to native html input controls
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Styles/components/_input.scss
Labels: enhancement

#9827 Update installation instructions in readme
  README.md
Labels: docs

#9801 MudDataGrid: properly clear the filter values
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnFilterRowPropertyTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#9861 DateMask: Remove logging in ModifyFinalText
  src/MudBlazor/Utilities/MaskAlgorithms/DateMask.cs
Labels: enhancement

#9879 ParameterMetadata: add missing xmdoc
  src/MudBlazor/State/ParameterMetadata.cs
Labels: docs

#9781 MudTimeSeriesChart: Add X & Y Axis Title parameters
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor
  src/MudBlazor/Components/Chart/MudTimeSeriesChart.razor
  src/MudBlazor/Components/Chart/MudTimeSeriesChart.razor.cs
Labels: enhancement

#9884 FileUpload: Fix code documentation of IReadOnlyCollection to supported IReadOnlyList
  src/MudBlazor/Components/FileUpload/MudFileUpload.razor.cs
Labels: docs
