Repository MudBlazor/MudBlazor, pull requests merged in 2025-08, with the labels that each got.

#11581 MudTabs: Improve accessibility
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsKeyboardAccessibilityTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/VerticalTabsKeyboardAccessibilityTest.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudDynamicTabs.razor
  src/MudBlazor/Components/Tabs/MudDynamicTabs.razor.cs
  src/MudBlazor/Components/Tabs/MudTabPanel.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug, accessibility

#11745 MudTable : Fix bug where CurrentPage is reset at the initialization
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableCurrentPageParameterIntialized.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
Labels: bug

#11741 Build: Specify more style rules
  .gemini/styleguide.md
  .github/codecov.yml
  src/.editorconfig
Labels: refactor, build

#11734 MudPopover: MudList MaxHeight Adjustments
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverListMaxHeightTest.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#11706 MudDataGrid: Add hierarchy visibility toggled parameter
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridHierarchyVisibilityToggledTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/DataGridHierarchyVisibilityToggledEventArgs.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement

#11765 MudPopover: Maintain Scroll Position
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#11778 Build: Update automation
  .gemini/config.yaml
  .gemini/styleguide.md
  .github/scripts/AutoTriage.js
  .github/scripts/AutoTriage.prompt
  .github/workflows/triage-backlog.yml
Labels: build

#11779 Build: Refactor AutoTriage to run one instance per batch
  .github/scripts/AutoTriage.js
  .github/workflows/triage-backlog.yml
Labels: refactor, build

#11804 MudDialog: Fix when a dialog is canceled, it can be reopened
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/InlineDialogShowMethodTest.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: bug
