Repository MudBlazor/MudBlazor, pull requests merged in 2025-05, with the labels that each got.

#11270 DataGridExtensions: support GridStateVirtualize and sort comparer
  src/MudBlazor.UnitTests/Extensions/DataGridExtensionsTests.cs
  src/MudBlazor/Extensions/DataGridExtensions.cs
Labels: enhancement

#10803 MudTabPanel: Implement Sorting by Text, SortKey, or Custom IComparer
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsSortByComparerExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsSortBySortKeyExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsSortByTextExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/LabelSortTest.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabPanel.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: enhancement

#11307 SwipeArea: Real Time Swipe Support
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/RealTimeSwipeExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeBoxExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/SwipeAreaPage.razor
  src/MudBlazor.UnitTests/Components/CarouselTests.cs
  src/MudBlazor.UnitTests/Components/SwipeTests.cs
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Components/SwipeArea/MultiDimensionSwipeEventArgs.cs
Labels: enhancement

#11324 MudCarousel: Utilize ParameterState
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
Labels: bug, PR: needs review

#11328 Update Contribution Team
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
Labels: docs, PR: needs review

#11345 Build: Ignore analyzer tests
  src/MudBlazor.UnitTests/Analyzers/ValidAttributeTests.cs
Labels: bug, build

#11342 Pickers: Use `InputDefaults` for inputs in `Picker` components
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
Labels: enhancement

#11335 Test: Fix Culture Dependent Tests
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/SimpleMudDatePickerTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Utilities/NaturalComparerTest.cs
Labels: bug, tests

#11084 MudBooleanInput, MudRating: Improve accessibility
  src/MudBlazor.Docs/Pages/Components/Radio/RadioPage.razor
  src/MudBlazor.Docs/Pages/Components/Rating/RatingPage.razor
  src/MudBlazor.UnitTests/Components/CheckBoxTests.cs
  src/MudBlazor.UnitTests/Components/CollapseTests.cs
  src/MudBlazor.UnitTests/Components/RatingTests.cs
  src/MudBlazor.UnitTests/Components/SwitchTests.cs
  src/MudBlazor/Components/CheckBox/MudCheckBox.razor
  src/MudBlazor/Components/Radio/MudRadio.razor
  src/MudBlazor/Components/Rating/MudRating.razor
  src/MudBlazor/Components/Rating/MudRatingItem.razor
  src/MudBlazor/Components/Rating/MudRatingItem.razor.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor
  src/MudBlazor/Styles/components/_iconbutton.scss
Labels: bug

#11325 MudDataGrid: improved doc about sorting on complex fields (#9041)
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridServerSideExample.razor
Labels: docs

#10925 Docs: Add XML Documentation for MudToggleGroup-
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Components/Toggle/MudToggleItem.razor.cs
  src/MudBlazor/Components/ToolBar/MudToolBar.razor.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItemToggleButton.razor.cs
  src/MudBlazor/Components/TreeView/TreeItemData.cs
  src/MudBlazor/Components/Typography/MudText.razor.cs
Labels: docs

#11347 MudInput: Fix Disposal of IOS Blur
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/TScripts/mudElementReference.js
Labels: bug

#11352 MudTable: Add TableClass parameter #11351
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
Labels: enhancement

#11282 MudOverlay: Check JSRuntime
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
Labels: bug

#11356 MudCheckBox: Use disabled style on text
  src/MudBlazor/Styles/components/_checkbox.scss
Labels: enhancement, PR: needs review

#11359 Docs: Prevent cookie dialog being mangled by ad blockers
  src/MudBlazor.Docs/Pages/Consent/Prompt/MudCookieConsentPrompt.razor
  src/MudBlazor.Docs/Styles/components/_consent.scss
Labels: docs

#11271 MudCircularProgress: Add ChildContent to Show Centered Content in the Progress
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressCircularInterminateExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/Examples/ProgressCircularPercentageExample.razor
  src/MudBlazor.Docs/Pages/Components/Progress/ProgressPage.razor
  src/MudBlazor.UnitTests/Components/ProgressCircularTests.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Styles/components/_progresscircular.scss
Labels: enhancement, PR: needs review

#11309 MudToggleGroup: Fix MudToggleItem selection when asynchronously loaded
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
Labels: bug, PR: needs review

#11368 MudColorPicker: Reduce default throttle
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor.cs
Labels: enhancement

#11361 Docs: Add "Segmented Buttons" as alias for Toggle Group
  src/MudBlazor.Docs/Services/ApiLink/ApiLinkService.cs
Labels: docs

#11248 MudPopover: Expand Flip Logic to Include Anchor
  src/MudBlazor/TScripts/mudPopover.js
Labels: enhancement, PR: needs review

#11306 MudToggleGroup: Fix FixedContent Visual Options
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleBasicsExample.razor
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: bug, PR: needs review

#11376 MudInput: Fix Proper Blur
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/TScripts/mudElementReference.js
Labels: bug

#11375 Docs: Refine wording on Dialog, Message Box pages
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/MessageBoxPage.razor
Labels: docs

#11365 MudAutocomplete: Fix `AutoFocus` not opening item list
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#11358 Docs: Remove static rendering mode warnings
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Labels: docs, PR: needs review

#11302 DataGrid: GroupingByOrder / Style Fix / Expansion StateHasChanged
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnGroupingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupByNullTest.razor
  src/MudBlazor.UnitTests/Components/DataGridGroupingTests.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/DataGridGroupRow.razor
  src/MudBlazor/Components/DataGrid/DataGridGroupRow.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#11381 Line chart: Fix index out of bounds error
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
Labels: bug

#11382 Refactor LayoutService
  src/MudBlazor.Docs/Enums/DarkLightMode.cs
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesSystemPreferenceExample.razor
  src/MudBlazor.Docs/Pages/Customization/Theming/Examples/OverviewThemesWatchSystemPreferenceExample.razor
  src/MudBlazor.Docs/Services/LayoutService.cs
  src/MudBlazor.Docs/Services/UserPreferences/UserPreferences.cs
  src/MudBlazor.Docs/Shared/AppbarButtons.razor
  src/MudBlazor.Docs/Shared/AppbarButtons.razor.cs
  src/MudBlazor.Docs/Shared/DocsLayout.razor.cs
  src/MudBlazor.Docs/Shared/LandingLayout.razor.cs
  src/MudBlazor.Docs/Shared/MainLayout.razor
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/TScripts/mudThemeProvider.js
Labels: refactor

#11367 MudMenu: Fix submenu activators being too wide
  src/MudBlazor/Styles/components/_menu.scss
Labels: bug, PR: needs review

#11362 Docs: Modernize landing page phone example
  src/MudBlazor.Docs/Styles/pages/_landingpage.scss
Labels: docs, PR: needs review

#11360 Docs: Show snackbar when copying code
  src/MudBlazor.Docs/Components/SectionContent.razor.cs
Labels: docs, PR: needs review

#11391 Add `d-contents` display class, Fix missing gap between MessageBox action buttons
  src/MudBlazor/Components/MessageBox/MudMessageBox.razor
  src/MudBlazor/Styles/components/_dialog.scss
  src/MudBlazor/Styles/utilities/layout/_display.scss
Labels: bug, enhancement

#11379 MudDataGrid: Form Dialog Focus
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: enhancement, PR: needs review

#11223 [Docs] MudSwipeArea improve docs
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDirectionsPreventDefaultExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/Examples/SwipeDrawerExample.razor
  src/MudBlazor.Docs/Pages/Components/SwipeArea/SwipeAreaPage.razor
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
Labels: docs

#11405 MudTabs: Fix slider misalignment when component is scaled
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug, PR: needs review

#11400 Docs: Remove tooltip delay
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/AppbarButtons.razor.cs
  src/MudBlazor.Docs/Shared/MainLayout.razor.cs
  src/MudBlazor.UnitTests.Viewer/Pages/Index.razor
  src/MudBlazor.UnitTests.Viewer/Shared/MainLayout.razor
Labels: docs, PR: needs review

#11401 MudColorPicker: Improve ARIA labels & doc page wording
  src/MudBlazor.Docs/Pages/Components/ColorPicker/ColorPickerPage.razor
  src/MudBlazor/Components/ColorPicker/MudColorPicker.razor
  src/MudBlazor/Resources/LanguageResource.resx
Labels: enhancement, PR: needs review

#11366 MudMask: Fix `⌘` shortcuts on MacOS & `cut` shortcut in general
  src/MudBlazor.UnitTests/Components/MaskTests.cs
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Mask/MudMask.razor.cs
Labels: bug

#11389 MudPopover: Fix Event Order
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipScrollTest.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, PR: needs review

#11395 MudToggleGroup: Selection Tracking
  src/MudBlazor.UnitTests.Viewer/TestComponents/ToggleGroup/ToggleGroupInterceptValueTest.razor
  src/MudBlazor.UnitTests/Components/ToggleGroupTests.cs
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
Labels: bug, PR: needs review

#11419 Docs: Fix mangled `AppbarButtons.razor.cs` merge
  src/MudBlazor.Docs/Shared/AppbarButtons.razor.cs
Labels: bug, PR: needs review

#11424 Docs: Update render mode warning
  src/MudBlazor.Docs/Pages/Getting Started/Installation/Installation.razor
Labels: docs

#11408 MudExpansionPanel: Fix `Gutters` property not taking effect
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
Labels: bug, PR: needs review

#11427 MudDropZone and MudDropContainer: Fix ItemSelector xmldocs
  src/MudBlazor/Components/DropZone/MudDropContainer.razor.cs
  src/MudBlazor/Components/DropZone/MudDropZone.razor.cs
Labels: docs, PR: needs review

#11049 MudAutocomplete: Scroll to selected item when not strict
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: PR: needs review
