Repository MudBlazor/MudBlazor, pull requests merged in 2025-09, with the labels that each got.

#11569 MudTable: Scroll to row & focus cell
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableScrollFocusExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Shared/Mocks/MockScrollServices.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTable.razor.cs
  src/MudBlazor/Components/Table/MudTr.razor
  src/MudBlazor/Components/Table/MudTr.razor.cs
  src/MudBlazor/Services/Scroll/IScrollManager.cs
  src/MudBlazor/Services/Scroll/ScrollManager.cs
  src/MudBlazor/TScripts/mudScrollManager.js
  src/MudBlazor/TScripts/mudTableCell.js
Labels: enhancement

#11893 Docs: Use fake people data in Simple Table examples
  src/MudBlazor.Docs/Pages/Components/SimpleTable/Examples/SimpleTableExample.razor
  src/MudBlazor.Docs/Pages/Components/SimpleTable/Examples/SimpleTableFixedHeaderExample.razor
  src/MudBlazor.Docs/Pages/Components/SimpleTable/Examples/SimpleTableHoverDenseExample.razor
Labels: docs

#11904 MudDataGrid: Hierarchy ExpandAll/CollapseAll when one item is present
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridHierarchyColumnTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
Labels: bug

#11864 MudDataGrid: Add parameters for filter icons
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFilterIconsTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: enhancement, needs: changes
