Repository MudBlazor/MudBlazor, pull requests merged in 2025-06, with the labels that each got.

#11444 MudMenu: Hide popover overflow
  src/MudBlazor/Styles/components/_menu.scss
Labels: bug

#11445 Docs: Revise Overlay, Popover, DropdownSettings descriptions
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/OverlayPage.razor
  src/MudBlazor.Docs/Pages/Components/Popover/PopoverPage.razor
  src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
Labels: docs

#11452 MudDataGrid: Filters and Options Popover changed to Position At Cursor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#11383 MudDataGrid: Groupable Logic
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedTest.razor
  src/MudBlazor.UnitTests/Components/DataGridGroupingTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#11468 MudTablePager: Fix InfoFormat ignoring custom text (#11466)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagerInfoTextTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TablePagerInfoTextTest2.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTablePager.razor.cs
Labels: bug

#11470 Make some XML docs more concise
  src/MudBlazor/Base/MudBooleanInput.cs
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
  src/MudBlazor/Components/ButtonGroup/MudButtonGroup.razor.cs
  src/MudBlazor/Components/Card/MudCard.razor.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/ChatBubble/MudChat.razor.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor.cs
  src/MudBlazor/Components/Paper/MudPaper.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Components/Snackbar/InternalComponents/SnackbarMessageText.razor.cs
  src/MudBlazor/Components/Snackbar/Snackbar.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/TableSimple/MudSimpleTable.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Components/Virtualize/MudVirtualize.razor.cs
  src/MudBlazor/Themes/Models/Breakpoints.cs
  src/MudBlazor/Themes/Models/LayoutProperties.cs
  src/MudBlazor/Themes/Models/Shadow.cs
  src/MudBlazor/Themes/Models/Typography.cs
  src/MudBlazor/Themes/Models/Z-Index.cs
  src/MudBlazor/Themes/MudTheme.cs
Labels: docs

#11474 Update OnAdornmentClick documentation to match actual behavior
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Field/MudField.razor.cs
Labels: docs

#11479 Add FormCraft to CommunityExtensions
  src/MudBlazor.Docs/wwwroot/CommunityExtensions.json
Labels: docs

#11496 MudToggleGroup: Refactor borders, Add border opacity support
  src/MudBlazor/Components/Toggle/MudToggleGroup.razor.cs
  src/MudBlazor/Styles/components/_togglegroup.scss
Labels: enhancement

#11436 MudInput: Dispose iOS Blur With Error Handling
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
Labels: bug

#11501 Docs: Revise Tree View page wording
  src/MudBlazor.Docs/Pages/Components/TreeView/TreeViewPage.razor
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
Labels: docs

#11487 README: Add guide for testing a PR locally
  README.md
  TESTING.md
Labels: docs

#11527 Docs: Fixed installation JS reference typo
  src/MudBlazor.Docs/Pages/Getting Started/Installation/ManualMarkdown/InstallScriptManualNet8Code.html
  src/MudBlazor.Docs/Pages/Getting Started/Installation/ManualMarkdown/InstallScriptManualWasmStandaloneCode.html
Labels: docs

#11488 Fix logo for dark mode for CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#11504 MudDialog: Fix Inline Dialog Title Refresh
  src/MudBlazor.UnitTests.Viewer/TestComponents/Dialog/InlineDialogTitleRefreshTest.razor
  src/MudBlazor.UnitTests/Components/DialogTests.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: bug

#11534 Docs: Bring more attention to team members
  src/MudBlazor.Docs/Components/MudTeamCard.razor
  src/MudBlazor.Docs/Models/TeamMember.cs
  src/MudBlazor.Docs/Models/TeamMemberData.cs
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
Labels: docs

#11533 MudAutocomplete: Fix Strict mode regression
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, regression

#11531 MudExpansionPanel: Add toggle keyboard hotkeys, Add ability to remove content from DOM
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelKeyboardTest.razor
  src/MudBlazor.UnitTests/Components/ExpansionPanelTests.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanel.razor.cs
Labels: accessibility

#11566 MudSimpleTable: Fix missing row borders in nested tables (#11559)
  src/MudBlazor/Styles/components/_simpletable.scss
Labels: bug

#11557 MudProgressCircular: Calculate view box size based on stroke width
  src/MudBlazor.UnitTests.Viewer/TestComponents/Progress/MudProgressCircularWidthTest.razor
  src/MudBlazor.UnitTests/Components/ProgressCircularTests.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
Labels: bug
