Repository MudBlazor/MudBlazor, pull requests merged in 2025-01, with the labels that each got.

#10551 MudMenu: Fix pointer event timing with cascading menus
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
Labels: bug, PR: needs review

#10554 MudPopover: Fix overlay regression in nested popovers inside Dialog
  src/MudBlazor.UnitTests.Viewer/TestComponents/Overlay/OverlayDialogTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Overlay/OverlayTestDialog.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#10341 MudStepper: ResetAsync now sends correct StepAction arg
  src/MudBlazor.UnitTests/Components/StepperTests.cs
  src/MudBlazor/Components/Stepper/MudStepper.razor.cs
Labels: bug

#10461 MudSwipeArea: Fix onpointer on touch devices
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Styles/MudBlazor.scss
  src/MudBlazor/Styles/components/_swipearea.scss
Labels: bug

#10564 Build: Sass compiler file contention fix
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: bug, PR: needs review

#10482 Docs: Simplify inheritance tree, Expand API 404
  src/MudBlazor.Docs/Components/ApiTypeHierarchy.razor
  src/MudBlazor.Docs/Components/ApiTypeHierarchy.razor.cs
  src/MudBlazor.Docs/Components/ApiTypeTable.razor
  src/MudBlazor.Docs/Pages/Api/Api.razor
  src/MudBlazor.Docs/Styles/components/_docspage.scss
  src/MudBlazor.Docs/Styles/components/_docssection.scss
Labels: docs, PR: needs review

#10433 MudSelect: Enhance Keyboard Searching
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectFocusAndTypeTest.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: enhancement

#10521 Docs: MudSlider to MudStepper: Add XML Documentation for Public Members
  src/MudBlazor/Components/Slider/MudSlider.razor.cs
  src/MudBlazor/Components/Slider/SliderContext.cs
  src/MudBlazor/Components/Snackbar/CommonSnackbarOptions.cs
  src/MudBlazor/Components/Snackbar/Defaults.cs
  src/MudBlazor/Components/Snackbar/Snackbar.cs
  src/MudBlazor/Components/Snackbar/SnackbarDuplicatesBehavior.cs
  src/MudBlazor/Components/Snackbar/SnackbarOptions.cs
  src/MudBlazor/Components/Snackbar/SnackbarService.cs
  src/MudBlazor/Components/Stack/MudStack.razor.cs
  src/MudBlazor/Components/Stepper/MudStep
  src/MudBlazor/Components/Stepper/MudStep.cs
  src/MudBlazor/Components/Stepper/MudStepper.razor.cs
  src/MudBlazor/Components/Stepper/StepAction.cs
  src/MudBlazor/Components/Stepper/StepperInteractionEventArgs.cs
  src/MudBlazor/Enums/AlignItems.cs
  src/MudBlazor/Enums/Justify.cs
  src/MudBlazor/Enums/StretchItems.cs
  src/MudBlazor/Enums/Wrap.cs
  src/MudBlazor/Interfaces/ISnackbar.cs
Labels: docs

#10579 Build: Deploy v8 CI changes
  .github/workflows/deploy-mudblazor.yml
  .github/workflows/deploy-trymudblazor.yml
Labels: build, PR: needs review, v8

#10411 Converter: Enable translation for error messages (#3313)
  src/MudBlazor.UnitTests/Utilities/BindingConverterTests.cs
  src/MudBlazor/Base/MudFormComponent.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
  src/MudBlazor/Resources/LanguageResource.resx
  src/MudBlazor/Utilities/BindingConverters/BoolConverter.cs
  src/MudBlazor/Utilities/BindingConverters/Converter.cs
  src/MudBlazor/Utilities/BindingConverters/DateConverter.cs
  src/MudBlazor/Utilities/BindingConverters/DefaultConverter.cs
  src/MudBlazor/Utilities/BindingConverters/NumericConverter.cs
Labels: enhancement

#10516 MudGlobal: Remove low impact properties
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Alert/MudAlert.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Components/Button/MudButton.razor.cs
  src/MudBlazor/Components/Button/MudIconButton.razor.cs
  src/MudBlazor/Components/Button/MudToggleIconButton.razor.cs
  src/MudBlazor/Components/Card/MudCard.razor.cs
  src/MudBlazor/Components/ChatBubble/MudChat.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
  src/MudBlazor/Components/Grid/MudGrid.razor.cs
  src/MudBlazor/Components/Link/MudLink.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor.cs
  src/MudBlazor/Components/Paper/MudPaper.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Components/Stack/MudStack.razor.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/TableSimple/MudSimpleTable.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: breaking change, API change, v8

#10589 Revert "Build: Sass compiler file contention fix (#10564)"
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: bug

#10565 DropdownSettings and RelativeWidth updates
  src/MudBlazor.Docs/Pages/Components/Autocomplete/AutocompletePage.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.Docs/Pages/Components/Popover/Examples/PopoverDropdownSettingsExample.razor
  src/MudBlazor.Docs/Pages/Components/Popover/Examples/PopoverRelativeWidthExample.razor
  src/MudBlazor.Docs/Pages/Components/Popover/PopoverPage.razor
  src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverPropertyTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectPopoverRelativeWidthTest.razor
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Popover/DropDownSettings.cs
  src/MudBlazor/Components/Popover/MudPopover.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Enums/DropdownWidth.cs
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, enhancement, breaking change, v8

#10595 Add MIGRATION.md
  MIGRATION.md
  README.md
Labels: docs, PR: needs review

#10597 HeatMap: Use invariant culture
  src/MudBlazor/Components/Chart/Charts/HeatMap.razor
  src/MudBlazor/Components/Chart/Charts/HeatMap.razor.cs
Labels: bug, PR: needs review

#10611 CSS: Remove `ul` from base reset
  src/MudBlazor.Docs/Styles/core/_base.scss
  src/MudBlazor/Styles/components/_breadcrumbs.scss
  src/MudBlazor/Styles/core/_reset.scss
Labels: PR: needs review

#10602 Docs: Add Community Extensions
  src/MudBlazor.Docs/Enums/CommunityCategories.cs
  src/MudBlazor.Docs/Models/CommunityExtension.cs
  src/MudBlazor.Docs/Models/Context/CommunityApiJsonSerializerContext.cs
  src/MudBlazor.Docs/Pages/Mud/Community/CommunityExtensions.razor
  src/MudBlazor.Docs/Pages/Mud/Community/ExtensionCard.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/Shared/Appbar.razor.cs
  src/MudBlazor.Docs/Shared/Footer.razor
  src/MudBlazor.Docs/Shared/NavMenu.razor
  src/MudBlazor.Docs/Styles/MudBlazorDocs.scss
  src/MudBlazor.Docs/Styles/pages/_extensions.scss
  src/MudBlazor.Docs/wwwroot/CommunityExtensions.json
Labels: docs, PR: needs review

#10621 Docs: Update Mobile Menu
  src/MudBlazor.Docs/Shared/DocsLayout.razor
  src/MudBlazor.Docs/Shared/LandingLayout.razor
Labels: docs

#10636 Build: Don't update to FluentAssertions v8 due to licensing changes
  .github/renovate.json
Labels: build

#10642 MudTextField: Fix Outlined text field variant label in RTL
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/OutlineLabelBackgroundTest.razor
  src/MudBlazor/Styles/components/_input.scss
Labels: bug

#10647 MudDataGrid: Backport #10436 #10220
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridStickyColumnsResizerTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/DataGridColumnResizeService.cs
Labels: bug, v7

#10648 Docs: Update "App Bar with Menu" example
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarMenuExample.razor
Labels: docs, PR: needs review

#10644 Updated analyzer for v8
  src/Directory.Build.targets
  src/MudBlazor.Analyzers.TestComponents/AttributeTest.razor
  src/MudBlazor.Analyzers/AllowedAttributePattern.cs
  src/MudBlazor.Analyzers/HTMLAttributes.cs
  src/MudBlazor.Analyzers/IllegalParameterSet.cs
  src/MudBlazor.Analyzers/IllegalParameters.cs
  src/MudBlazor.Analyzers/MudComponentUnknownParametersAnalyzer.cs
  src/MudBlazor.Analyzers/Resources.Designer.cs
  src/MudBlazor.Analyzers/Resources.resx
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor.Docs/Pages/Features/Analyzers/Analyzers.razor
  src/MudBlazor.Docs/Pages/Features/Analyzers/MUD0001ConfigurationTable.razor
  src/MudBlazor.Docs/Pages/Features/Analyzers/MUD0002ConfigurationTable.razor
  src/MudBlazor.Docs/Pages/Features/Analyzers/MUD0002CustomAttributeList.razor
  src/MudBlazor.UnitTests/Analyzers/Internal/ExpectedDiagnostic.cs
  src/MudBlazor.UnitTests/Analyzers/Internal/TestAnalyzerOptions.cs
  src/MudBlazor.UnitTests/Analyzers/ParametersTests.cs
  src/MudBlazor.UnitTests/Analyzers/ValidAttributeTests.cs
  src/MudBlazor/MudBlazor.csproj
Labels: enhancement

#10558 [Sunday 19] Docs: Update communications for v8
  CHANGELOG.md
  README.md
  ROADMAP.md
  src/MudBlazor.Docs/NotificationContent/Announcement_MudBlazorIsHereToStay.razor
  src/MudBlazor.Docs/NotificationContent/Announcement_v8_GA.razor
  src/MudBlazor.Docs/Services/Notifications/InMemoryNotificationService.cs
  src/MudBlazor/MudBlazor.csproj
Labels: docs, v8

#10599 MudImage: Add fallback source
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImageFallbackExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/ImagePage.razor
  src/MudBlazor.UnitTests/Components/ImageTests.cs
  src/MudBlazor/Components/Image/MudImage.razor
  src/MudBlazor/Components/Image/MudImage.razor.cs
Labels: enhancement, v8

#10580 MudDataGrid: Fix Column Options Popover FixedHeader positioning
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFixedHeaderFilterTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review, v8

#10386 MudDataGrid: Sticky toolbars (table menu bar & pagination bar)
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridStickyColumnsResizerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableStickyVisualTest.razor
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review, v8

#10649 MudTextField: Fix line height for outlined frame
  src/MudBlazor/Styles/components/_inputcontrol.scss
Labels: bug, PR: needs review

#10654 Docs: Add Chat Bubble example to the DocsExplore demos
  src/MudBlazor.Docs/Pages/Components/Overview/OverviewPage.razor
Labels: docs

#10657 MudPagination: Restore list style CSS
  src/MudBlazor/Styles/components/_pagination.scss
Labels: bug, PR: needs review

#10668 MudChat: Adjust example for mobile screens
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatFullExample.razor
Labels: docs

#10667 MudThemeProvider: Add ClassName Style tag
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
Labels: enhancement, PR: needs review

#10666 MudOverlay: Introduce `mud-skip-overlay-section`
  src/MudBlazor.UnitTests/Components/DrawerTest.cs
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor/Components/Dialog/MudDialogContainer.razor.cs
  src/MudBlazor/Components/Drawer/MudDrawer.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug, PR: needs review

#10670 MudDateRangePicker: Fix Outlined Variant label rendering
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerMaskExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerEditableExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerFormatExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerMinMaxDateExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/VarientDatePickerRenderTest.razor
  src/MudBlazor/Components/Input/MudRangeInput.razor
Labels: bug

#10677 Docs: Change term "Revert" to "Invert" in Numeric Field example
  src/MudBlazor.Docs/Pages/Components/NumericField/Examples/ChangeTheValueWithTheMouseWheelExample.razor
Labels: docs, PR: needs review

#10672 MudInput: Fix outline label conflict with third-party CSS
  src/MudBlazor/Styles/components/_input.scss
Labels: bug, PR: needs review

#10581 MudDataGrid: remove detrimental ChildRowContent CSS
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Styles/components/_datagrid.scss
Labels: bug, enhancement, PR: needs review, v8

#10678 Analyzer: Fix HTMLAttributes mode defaults
  src/MudBlazor.Analyzers/MudComponentUnknownParametersAnalyzer.cs
  src/MudBlazor.UnitTests/Analyzers/Internal/TestAnalyzerOptions.cs
Labels: bug

#10680 MudDateRangePicker: Allow select end before start
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: enhancement

#10582 MudDatePicker/MudDateRangePicker: Open static picker on bound date
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DatePickerBindingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DatePickerStaticTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerPresetWithoutTimestampTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug, v8

#10671 MudTextField : With Required parameter, shows error when only one space is entered
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Base/MudBaseInput.cs
Labels: bug

#10682 DialogService: Return DialogHelperComponent
  src/MudBlazor/Services/Dialog/DialogService.cs
Labels: bug

#10683 MudInput: Fix legend style incorrectly inherited to child components
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldNestedInFieldTest.razor
  src/MudBlazor/Styles/components/_input.scss
Labels: bug, PR: needs review

#10633 Docs: Add XML Documentation for MudSwipeArea to MudTabs
  src/MudBlazor/Components/SwipeArea/MudSwipeArea.razor.cs
  src/MudBlazor/Components/SwipeArea/SwipeEventArgs.cs
  src/MudBlazor/Components/Switch/MudSwitch.razor.cs
  src/MudBlazor/Components/Tabs/MudDynamicTabs.razor.cs
  src/MudBlazor/Components/Tabs/MudTabPanel.razor
  src/MudBlazor/Components/Tabs/MudTabPanel.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Components/Tabs/TabHeaderPosition.cs
  src/MudBlazor/Components/Tabs/TabInteractionEventArgs.cs
  src/MudBlazor/Components/Tabs/TabInteractionType.cs
  src/MudBlazor/Enums/SwipeDirection.cs
Labels: docs

#10615 MudTable: Enable text selection in sortable table header columns
  src/MudBlazor/Styles/components/_table.scss
Labels: enhancement, PR: needs review

#10643 Build: Fix for missing MudBlazor.min.css in SassCompiler
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: bug, build

#10684 MudTreeViewItem: make Items two-way for returning server-loaded children
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewServerExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewServerTest.razor
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeView.razor.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: bug

#10679 MudGlobal: Inherit TooltipDefaults from TransitionDefaults
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: bug, PR: needs review

#10693 RegexMask: Update `RegexMask.Email` to allow hyphens (`-`) in the domain
  src/MudBlazor.UnitTests/Utilities/Mask/RegexMaskEmailTests.cs
  src/MudBlazor/Utilities/MaskAlgorithms/RegexMask.cs
Labels: bug, PR: needs review

#10629 MudPicker/MudDateRangePicker: Only highlight selected date
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DatePickerStaticTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerPresetWithoutTimestampTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDatePicker.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug, v8

#10712 Build: Revert SassCompiler version
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: bug, PR: needs review

#10652 MudDropContainer: Fix drag preview "ghost" glitch
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneNestedZonesExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DropZone/DropzoneReorderTest.razor
  src/MudBlazor.UnitTests/Components/DropZoneTests.cs
  src/MudBlazor/Styles/components/_dropzone.scss
Labels: bug, PR: needs review

#10623 MudDataGrid: Remove sort when clicking after descending sort
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
Labels: enhancement

#10718 Select: Don't open while scrolling via touch
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInputAdornment.razor
  src/MudBlazor/Components/Mask/MudMask.razor
  src/MudBlazor/Components/Select/MudSelect.razor
Labels: bug

#10717 MudAutocomplete: Restore `ScrollToListItemAsync` API method
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#10737 MudInput: Fix adornment click passing through to field
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInputAdornment.razor
  src/MudBlazor/Components/Mask/MudMask.razor
Labels: bug, PR: needs review

#10720 MudTooltip: Remove `width:fit-content`
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipFlexScenariosTest.razor
  src/MudBlazor/Styles/components/_tooltip.scss
Labels: bug, PR: needs review

#10741 MudDropContainer: Re-enable content selection
  src/MudBlazor/Styles/components/_dropzone.scss
Labels: bug

#10743 MudDataGrid: Grouping Icon RTL Support
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review

#10758 Build: Static asset checks for dotnet pack
  .github/workflows/deploy-mudblazor-nuget.yml
  tools/CheckPackageContainsStaticAssets.ps1
Labels: enhancement, build, PR: needs review

#10760 MudTabs: Fix scroll button appearing when zooming page (#10686)
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#10694 MudTabPanel: Add BadgeIcon property
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsWithBagdesExample.razor
  src/MudBlazor/Components/Tabs/MudTabPanel.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor
Labels: enhancement

#10740 MudAutocomplete, MudSelect: Fix Focus and Clear
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteRetainFocusTest.razor
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
Labels: bug, PR: needs review

#10735 MudPopover: Fix Z-Index edge cases
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridInDialogFilterTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerDialogSelectTest.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#10766 Docs: Fix indentation in TableRelationalExample
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableRelationalExample.razor
Labels: docs

#10767 Build: Move to AwesomeAssertions to prevent accidental license violation
  src/MudBlazor.UnitTests.Docs/MudBlazor.UnitTests.Docs.csproj
  src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj
Labels: bug, build, PR: needs review

#10734 MudNumericField: Ignore default UI Culture
  src/MudBlazor.Docs/Pages/Components/NumericField/NumericFieldPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/NumericField/NumericFieldRenderTest.razor
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: bug, PR: needs review

#10752 Build: Fork sasscompiler to always include Content Items
  src/MudBlazor.Docs/MudBlazor.Docs.csproj
  src/MudBlazor/MudBlazor.csproj
Labels: bug, build, PR: needs review
