Repository MudBlazor/MudBlazor, pull requests merged in 2025-03, with the labels that each got.

#10944 MudProgressLinear: Use MudGlobal.Rounded as default.
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
Labels: bug, PR: needs review

#10961 Tests: Filter out hidden dates
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
Labels: tests

#10957 Fix usages of MudGlobal.Rounded
  src/MudBlazor/Components/Avatar/MudAvatar.razor.cs
  src/MudBlazor/Components/Avatar/MudAvatarGroup.razor.cs
  src/MudBlazor/Components/NavMenu/MudNavMenu.razor.cs
  src/MudBlazor/Components/Progress/MudProgressCircular.razor.cs
  src/MudBlazor/Components/Progress/MudProgressLinear.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug, PR: needs review

#10769 MudDateRangePicker: Limit Date Range selection based on min/max days constraint
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/DateRangePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerMinMaxDaysExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/DateRangePickerMinMaxDaysTest.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: enhancement, PR: needs review

#10865 MudChart: Timeseries charting improvements
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/BarExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExampleInterpolation.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/StackedBarExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/TimeSeriesExample1.razor
  src/MudBlazor.Docs/Styles/components/_docssection.scss
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/DonutChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/PieChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/StackedBarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/TimeSeriesChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor
  src/MudBlazor/Components/Chart/Charts/Donut.razor.cs
  src/MudBlazor/Components/Chart/Charts/Line.razor
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Charts/Pie.razor
  src/MudBlazor/Components/Chart/Charts/Pie.razor.cs
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor.cs
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor.cs
  src/MudBlazor/Components/Chart/Models/AxisChartOptions.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/Chart/Models/ChartSeries.cs
  src/MudBlazor/Components/Chart/Models/LineDisplayType.cs
  src/MudBlazor/Components/Chart/Models/TimeSeriesChartSeries.cs
  src/MudBlazor/Components/Chart/Models/TimeSeriesDisplayType.cs
  src/MudBlazor/Components/Chart/MudCategoryAxisChartBase.cs
  src/MudBlazor/Components/Chart/MudChart.razor
  src/MudBlazor/Components/Chart/MudChart.razor.cs
  src/MudBlazor/Components/Chart/MudChartBase.cs
  src/MudBlazor/Components/Chart/MudTimeSeriesChart.razor
  src/MudBlazor/Components/Chart/MudTimeSeriesChart.razor.cs
  src/MudBlazor/Components/Chart/Parts/ChartTooltip.razor
  src/MudBlazor/Components/Chart/Parts/ChartTooltip.razor.cs
  src/MudBlazor/Components/Chart/Svg/SvgCircle.cs
  src/MudBlazor/Components/Chart/Svg/SvgPath.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor
  src/MudBlazor/Interop/ElementSize.cs
  src/MudBlazor/Styles/components/_charts.scss
  src/MudBlazor/TScripts/mudHelpers.js
Labels: bug, enhancement

#10884 MudTable: Add CellClass parameter
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableCellClassExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/TablePage.razor
  src/MudBlazor.UnitTests.Docs/Documentation/ApiMemberTableTests.cs
  src/MudBlazor/Components/Table/MudTableBase.cs
  src/MudBlazor/Components/Table/MudTd.razor.cs
  src/MudBlazor/Components/Table/MudTh.razor.cs
  src/MudBlazor/Components/Table/MudTr.razor
Labels: enhancement

#10979 MudDialog: Fix duplicate dialogs
  src/MudBlazor/Components/Dialog/MudDialog.razor.cs
Labels: bug

#10965 MudRadio: Fix incorrect aria checked radio
  src/MudBlazor/Components/Radio/MudRadio.razor
Labels: bug, PR: needs review

#10866 ParameterState: Add documentation
  src/MudBlazor.Docs/Pages/Features/ParameterState/BestPracticesList.razor
  src/MudBlazor.Docs/Pages/Features/ParameterState/Examples/AccessParameterValueExample.razor
  src/MudBlazor.Docs/Pages/Features/ParameterState/Examples/IncorrectParameterModificationExample.razor
  src/MudBlazor.Docs/Pages/Features/ParameterState/Examples/ParameterStateUsageExample.razor
  src/MudBlazor.Docs/Pages/Features/ParameterState/Examples/ProblemUsageExample.razor
  src/MudBlazor.Docs/Pages/Features/ParameterState/Examples/TwoWayBindingExample.razor
  src/MudBlazor.Docs/Pages/Features/ParameterState/ParameterStatePage.razor
  src/MudBlazor.Docs/Services/Menu/MenuService.cs
Labels: docs, PR: needs review

#10986 Docs: Added missing sponsor
  src/MudBlazor.Docs/Pages/Index.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Sponsors.razor
  src/MudBlazor.Docs/wwwroot/images/sponsors/blackhawk.png
  src/MudBlazor.Docs/wwwroot/images/sponsors/blackhawk_color.png
Labels: docs, PR: needs review

#10985 MudChart/Heatmap: Add Min/Max Overrides
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/HeatMapExample4.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/HeatMapExample7.razor
  src/MudBlazor.Docs/Pages/Components/Charts/HeatMapChartPage.razor
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor/Components/Chart/Charts/HeatMap.razor.cs
  src/MudBlazor/Components/Chart/MudHeatMapCell.razor.cs
Labels: bug, PR: needs review

#10856 MudPopover: Adjust Overlay Add Throttle and Debounce
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#10853 Prevent Rendering of unused MudPopover and MudOverlay
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor.UnitTests/Components/DynamicTabsTests.cs
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor.UnitTests/Components/TimePickerTests.cs
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
Labels: bug

#10829 DataGrid: SelectedItem(s) ParameterState Refactor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEditFormCustomizedDialogTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSelectedItemOnInitTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug, PR: needs review

#10886 Docs: Add XML Documentation for MudThemeProvider-MudTimePicker
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
  src/MudBlazor/Components/TimePicker/MudTimePicker.razor.cs
  src/MudBlazor/Components/Timeline/MudTimeline.razor.cs
  src/MudBlazor/Components/Timeline/MudTimelineItem.razor.cs
  src/MudBlazor/Enums/TimeEditMode.cs
  src/MudBlazor/Enums/TimelineAlign.cs
  src/MudBlazor/Enums/TimelineOrientation.cs
  src/MudBlazor/Enums/TimelinePosition.cs
Labels: docs

#10842 MudInput: Implement Streamlined Blur event
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
  src/MudBlazor/TScripts/mudElementReference.js
Labels: bug

#10993 Refactor: Fix code styling, tests
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEditFormCustomizedDialogTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridSelectedItemOnInitTest.razor
  src/MudBlazor/Components/Input/MudInput.razor
  src/MudBlazor/Components/Picker/MudPicker.razor
Labels: PR: needs review

#10948 MudCollapse: Apply scroll to expanded content overflow
  src/MudBlazor.UnitTests.Viewer/TestComponents/ExpansionPanel/ExpansionPanelExpansionsTest.razor
  src/MudBlazor.UnitTests/Components/CollapseTests.cs
  src/MudBlazor/Components/Collapse/MudCollapse.razor.cs
  src/MudBlazor/Styles/components/_collapse.scss
Labels: bug, PR: needs review

#10999 MudButtonGroup: Fix some disabled styles not applying to buttons
  src/MudBlazor.UnitTests.Viewer/TestComponents/ButtonGroup/ButtonGroupDisabledStylesTest.razor
  src/MudBlazor/Styles/components/_buttongroup.scss
Labels: bug

#11002 MudSelect: Fix menu toggled on non-primary mouse clicks
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor.UnitTests/TestData/MouseEventArgsTestCase.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug, PR: needs review

#11012 MudStepper: Fix final step completed color
  src/MudBlazor.UnitTests/Components/StepperTests.cs
  src/MudBlazor/Components/Stepper/MudStep.cs
Labels: bug, PR: needs review

#10974 MudTabs: Fix underline display for active tab (#10970)
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsVisibleTest.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
Labels: bug

#10932 MudTextField: Fix AutoGrow Adornment padding
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldRenderTest.razor
  src/MudBlazor/Styles/components/_input.scss
Labels: bug, PR: needs review

#11029 MudInput: Fix trimming issue
  src/MudBlazor/Components/Input/MudInput.razor.cs
Labels: bug

#11022 MudTable: Fix table sort label style
  src/MudBlazor.UnitTests.Viewer/Program.cs
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableSortLabelTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableSortLabel.razor
  src/MudBlazor/Components/Table/MudTableSortLabel.razor.cs
  src/MudBlazor/Styles/components/_table.scss
Labels: bug, PR: needs review

#11033 MudDateRangePicker: Fix error with MaxDays and IsDateDisabledFunc
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/DateRangePickerPage.razor
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug

#11040 MudPopover: Remove shadow if the popover is empty
  src/MudBlazor/Styles/components/_popover.scss
Labels: bug

#11023 MudAutocomplete: Fix duplicate search calls when opened on click
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#11038 MudPopover: Overlay Position Exclusion
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#11067 ObserverManager: Optimize to reduce dictionary lookups
  src/MudBlazor.UnitTests/Utilities/ObserverManager/ObserverManagerTests.cs
  src/MudBlazor/Extensions/ResizeOptionsExtensions.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorService.cs
  src/MudBlazor/Utilities/ObserverManager/ObserverManager.cs
Labels: bug, performance

#11070 DataGrid: Mutlisort key fix on mac
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
Labels: bug

#10894 MudSelect: Add FitContent Parameter
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectFitContentExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectPlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/Select/SelectPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectCustomizedTextTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest2.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest5.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTest7.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTestRequiredValue.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectWithInitialValuesTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectWithValueContainZeroTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/ReloadSelectItemsTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/ReselectValueTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectFitContentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectFocusAndTypeTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectRequiredTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectScrollDrawerTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectTest1.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectValidationDataAttrTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectVariantsTest.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Styles/components/_select.scss
Labels: bug

#11051 MudToolTip: Move Duration Delay
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipDurationDelayTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipInMenuTest.razor
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor.UnitTests/TestData/MouseEventArgsTestCase.cs
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Utilities/Debounce/DebounceDispatcher.cs
Labels: bug

#11039 MudInput Dispose JS OnBlur
  src/MudBlazor.UnitTests/Components/TextFieldTests.cs
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Extensions/ElementReferenceExtensions.cs
  src/MudBlazor/TScripts/mudElementReference.js
Labels: bug

#11107 MudPopover: Fix positioning delay (partial revert of #10856)
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#11041 MudChart: Fix culture and perfomance issues
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/BarExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/DonutCustomGraphicsExample.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/DonutExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/PieExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/StackedBarExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/TimeSeriesExample1.razor
  src/MudBlazor.UnitTests/Components/Charts/BarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/ChartSeriesExtensions.cs
  src/MudBlazor.UnitTests/Components/Charts/ChartToolTipTests.cs
  src/MudBlazor.UnitTests/Components/Charts/DonutChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/LineChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/PieChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/StackedBarChartTests.cs
  src/MudBlazor.UnitTests/Components/Charts/TimeSeriesChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
  src/MudBlazor/Components/Chart/Charts/Donut.razor
  src/MudBlazor/Components/Chart/Charts/Line.razor
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Charts/Pie.razor
  src/MudBlazor/Components/Chart/Charts/Pie.razor.cs
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor
  src/MudBlazor/Components/Chart/Charts/StackedBar.razor.cs
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor.cs
  src/MudBlazor/Components/Chart/Models/AxisChartOptions.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
  src/MudBlazor/Components/Chart/Models/ChartSeries.cs
  src/MudBlazor/Components/Chart/Models/TimeSeriesChartSeries.cs
  src/MudBlazor/Components/Chart/MudCategoryAxisChartBase.cs
  src/MudBlazor/Components/Chart/MudChartBase.cs
  src/MudBlazor/Components/Chart/Parts/ChartTooltip.razor
  src/MudBlazor/Components/Chart/Parts/ChartTooltip.razor.cs
  src/MudBlazor/GlobalUsings.cs
  src/MudBlazor/Interop/ElementSize.cs
  src/MudBlazor/TScripts/mudHelpers.js
  src/MudBlazor/Utilities/StringHelpers.cs
Labels: bug, enhancement

#11110 Analyzers/SourceGenerator: Update Roslyn
  src/MudBlazor.Analyzers/MudBlazor.Analyzers.csproj
  src/MudBlazor.SourceGenerator/MudBlazor.SourceGenerator.csproj
  src/MudBlazor.UnitTests/Analyzers/ValidAttributeTests.cs
Labels: bug

#11077 MudSwitch: Change track color to improve visibility on dark theme
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchColorExample.razor
  src/MudBlazor/Styles/components/_switch.scss
Labels: enhancement, PR: needs review

#11011 MudMenu: Autocomplete/Select adornment click no longer causes menu to close
  src/MudBlazor.UnitTests.Viewer/TestComponents/Overlay/OverlayNestedFreezeTest.razor
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Base/MudBaseButton.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Input/MudInput.razor.cs
  src/MudBlazor/Components/Input/MudInputAdornment.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
Labels: bug

#11108 MudTreeViewItem: Fix NullReferenceException
  src/MudBlazor.UnitTests.Viewer/TestComponents/TreeView/TreeViewHeterogeneous.razor
  src/MudBlazor.UnitTests/Components/TreeViewTests.cs
  src/MudBlazor/Components/TreeView/MudTreeViewItem.razor.cs
Labels: bug

#11032 MudDataGrid - Preserve Selection with ParameterState
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEventCallbacksTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridEventSelectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/_README.txt
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#11116 Analyzer: Lower the Roslyn version
  src/MudBlazor.Analyzers.TestComponents/MudBlazor.Analyzers.TestComponents.csproj
  src/MudBlazor.Analyzers/MudBlazor.Analyzers.csproj
Labels: bug, PR: needs review

#11117 MudMenu Nested Fix
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: bug
