Repository MudBlazor/MudBlazor, pull requests merged in 2025-02, with the labels that each got.

#10782 MudProgressLinear: prevent buffer clipping on Medium/Large sizes
  src/MudBlazor/Styles/components/_progresslinear.scss
  src/MudBlazor/Styles/core/_animations.scss
Labels: bug

#10785 BaseDatePicker- Fix failing scenario
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: bug, PR: needs review

#10784 docs: fix spacing, typos, and cleanup unused code blocks
  src/MudBlazor.Docs/Pages/Components/AppBar/Examples/AppBarMenuExample.razor
  src/MudBlazor.Docs/Pages/Components/BreakpointProvider/Examples/BreakpointProviderPageHiddenExample.razor
  src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/Carousel/Examples/CarouselTemplatesExample.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/DonutExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExample1.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/LineExampleInterpolation.razor
  src/MudBlazor.Docs/Pages/Components/Charts/Examples/PieExample1.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatFullExample.razor
  src/MudBlazor.Docs/Pages/Components/ChatBubble/Examples/ChatHoverExample.razor
  src/MudBlazor.Docs/Pages/Components/Checkbox/Examples/CheckboxConversionExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetAddRemoveExample.razor
  src/MudBlazor.Docs/Pages/Components/ChipSet/Examples/ChipSetChipBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridColumReorderingExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridSortingExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneItemSelectorExample.razor
  src/MudBlazor.Docs/Pages/Components/DropZone/Examples/DropZoneItemSelectorReorderingExample.razor
  src/MudBlazor.Docs/Pages/Components/Element/Examples/MudElementChangingExample.razor
  src/MudBlazor.Docs/Pages/Components/FileUpload/Examples/FileUploadDragAndDropWithFormValidationExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/Examples/EditFormExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/Examples/MudFormExample.razor
  src/MudBlazor.Docs/Pages/Components/Form/Examples/ValidateIfDirtyExample.razor
  src/MudBlazor.Docs/Pages/Components/Grid/Examples/GridBuilderExample.razor
  src/MudBlazor.Docs/Pages/Components/Highlighter/Examples/HighlighterWithTableExample.razor
  src/MudBlazor.Docs/Pages/Components/Image/Examples/ImagePlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuAdvancedPopoverExample.razor
  src/MudBlazor.Docs/Pages/Components/MessageBox/Examples/MessageBoxSimpleExample.razor
  src/MudBlazor.Docs/Pages/Components/Stepper/Examples/StepperDynamicExample.razor
  src/MudBlazor.Docs/Pages/Components/Switch/Examples/SwitchConversionExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableBasicExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableMultiGroupingExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableRelationalExample.razor
  src/MudBlazor.Docs/Pages/Components/Table/Examples/TableVirtualizationExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldBindingExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerReadOnlyExample.razor
  src/MudBlazor.Docs/Pages/Components/Timeline/Examples/TimelineAlignExample.razor
  src/MudBlazor.Docs/Pages/Components/ToggleGroup/Examples/ToggleCustomContentExample.razor
  src/MudBlazor.Docs/Pages/Components/TreeView/Examples/TreeViewServerExample.razor
Labels: docs

#10783 MudDateRangePicker: Fix highlight for single day range
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
Labels: bug, PR: needs review

#10714 MudEventManager: Correctly handle TouchList properties in touch-related events
  src/MudBlazor/TScripts/mudEventManager.js
Labels: bug

#10780 MudInput: Fix label text being cut vertically
  src/MudBlazor/Styles/components/_inputcontrol.scss
Labels: bug

#10808 Build: Use 4 space indents for razor files
  src/.editorconfig
Labels: build

#10796 MudNumericField: Ignore default UI Culture
  src/MudBlazor.UnitTests/Components/NumericFieldTests.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
Labels: bug

#10703 MudTable: Show the default cursor for sortable headers when sorting is disabled
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableSortLabelTest.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTableSortLabel.razor.cs
  src/MudBlazor/Styles/components/_table.scss
Labels: enhancement, PR: needs review

#10805 MudTextField: Fix break style if label text too long
  src/MudBlazor.UnitTests.Viewer/TestComponents/TextField/TextFieldWithLongLabelTest.razor
  src/MudBlazor/Styles/components/_input.scss
  src/MudBlazor/Styles/components/_inputlabel.scss
Labels: bug, PR: needs review

#10825 Build: Fix typo in assets check script
  tools/CheckPackageContainsStaticAssets.ps1
Labels: bug, build, PR: needs review

#10828 MudSelect: Fix ResetAsync
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/MultiSelectTestRequiredValue.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug

#10797 MudTabPanel: Add Visible property
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsToolTipExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsVisibleExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsVisibleTest.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabPanel.razor
  src/MudBlazor/Components/Tabs/MudTabPanel.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Styles/components/_tabs.scss
Labels: docs, enhancement, PR: needs review

#10836 MudTable: Fix TableRowClassStyleTest
  src/MudBlazor.UnitTests/Components/TableTests.cs
Labels: tests

#7729 FilterHeaderCell: Display filter icons based on ShowFilterIcon value
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnShowFilterIconsTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/FilterHeaderCell.razor
Labels: bug, PR: needs review

#10837 MudAutocomplete: Fix unintended autofocus when adornment clicked
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteAdornmentClickHandlingTest.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug

#10596 MudStack: Responsive Breakpoint Attributes
  src/MudBlazor.Docs/Pages/Components/Stack/Examples/StackBreakpointExample.razor
  src/MudBlazor.Docs/Pages/Components/Stack/StackPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Stack/BreakpointReverseRowTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Stack/BreakpointReverseTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Stack/BreakpointRowTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Stack/BreakpointTest.razor
  src/MudBlazor.UnitTests/Components/StackTests.cs
  src/MudBlazor/Components/Stack/MudStack.razor.cs
  src/MudBlazor/Styles/utilities/flexbox/_flex-direction.scss
Labels: enhancement, PR: needs review

#10859 Refactor: Fix formatting
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Utilities/Debounce/DebounceDispatcherTests.cs
Labels: refactor, PR: needs review

#10845 MudDataGrid: Use key row item instead of row index.
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridUniqueRowKeyTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
Labels: bug

#10883 Add MudPdfViewer to community extensions
  src/MudBlazor.Docs/wwwroot/CommunityExtensions.json
Labels: docs, PR: needs review

#10885 Tests: Ignore Analyzers tests
  src/MudBlazor.UnitTests/Analyzers/ValidAttributeTests.cs
Labels: tests

#10892 Refactor: Fix code style
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridOtherOptionsExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteAdornmentClickHandlingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteRetainFocusTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Autocomplete/AutocompleteTest8.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridFixedHeaderFilterTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridInDialogFilterTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Drawer/DrawerDialogSelectTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/ExpansionPanel/MudExpansionPanels.razor.cs
  src/MudBlazor/Components/NumericField/MudNumericField.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: refactor

#10913 MudChip: Fix memory allocation
  src/MudBlazor.UnitTests/Utilities/ObserverManager/ObserverManagerTests.cs
  src/MudBlazor/Components/Chip/MudChip.razor.cs
  src/MudBlazor/Services/Browser/BrowserViewportService.cs
  src/MudBlazor/Services/KeyInterceptor/KeyInterceptorService.cs
  src/MudBlazor/Utilities/ObserverManager/ObserverManager.cs
Labels: bug

#10811 MudForm: Fire IsTouchChanged when ChildForm triggers
  src/MudBlazor.UnitTests.Viewer/TestComponents/Form/FormWithChildForm.razor
  src/MudBlazor.UnitTests/Components/FormTests.cs
  src/MudBlazor/Components/Form/MudForm.razor.cs
Labels: bug, PR: needs review

#10921 MudChart: Fix radius error in donut chart (#8780)
  src/MudBlazor/Components/Chart/Charts/Donut.razor
Labels: bug

#10854 MudDatePicker: Fix Persian year in header
  src/MudBlazor.UnitTests.Viewer/TestComponents/DatePicker/PersianDatePickerTest.razor
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudBaseDatePicker.razor.cs
Labels: bug, PR: needs review

#10861 MudChart: Fix so chart type Line uses ChartOptions.YAxisRequireZeroPoint (#10832)
  src/MudBlazor/Components/Chart/Charts/Line.razor.cs
  src/MudBlazor/Components/Chart/Models/ChartOptions.cs
Labels: bug, docs, PR: needs review

#10901 MudTextField: Cleaning a doc example
  src/MudBlazor.Docs/Pages/Components/TextField/Examples/TextFieldCharacterCountExample.razor
Labels: docs
