Repository MudBlazor/MudBlazor, pull requests merged in 2025-07, with the labels that each got.

#11553 MudSelect: Always call `FieldChanged` when `MultiSelection=true`
  src/MudBlazor.UnitTests.Viewer/TestComponents/Select/SelectMultiSelectFieldChangedTest.razor
  src/MudBlazor.UnitTests/Components/SelectTests.cs
  src/MudBlazor/Components/Select/MudSelect.razor.cs
Labels: bug

#11589 MudStepper: Remove StepStyle property
  src/MudBlazor/Components/Stepper/MudStep.cs
  src/MudBlazor/Components/Stepper/MudStepper.razor
  src/MudBlazor/Components/Stepper/MudStepper.razor.cs
Labels: breaking change

#11600 MudTextField: Fix excessive height with AutoGrow, Outlined, Dense, and Adornment
  src/MudBlazor/Styles/components/_input.scss
Labels: bug

#11601 Docs: Restructure Field pages for better flow
  src/MudBlazor.Docs/Pages/Components/Field/FieldPage.razor
  src/MudBlazor.Docs/Pages/Components/NumericField/NumericFieldPage.razor
  src/MudBlazor.Docs/Pages/Components/TextField/TextFieldPage.razor
Labels: docs

#11608 Docs: Move official projects out of Community Extensions
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.Docs/wwwroot/CommunityExtensions.json
Labels: docs

#11604 Docs: Replace version announcements with links to migration guides
  src/MudBlazor.Docs/NotificationContent/Announcement_v7_GA.razor
  src/MudBlazor.Docs/NotificationContent/Announcement_v8_GA.razor
  src/MudBlazor.Docs/Services/Notifications/InMemoryNotificationService.cs
Labels: docs

#11627 Build: Add operating system choice back to bug report
  .github/ISSUE_TEMPLATE/01_bug_report.yml
Labels: build

#11632 Build: Simplify issue templates further
  .github/ISSUE_TEMPLATE/01_bug_report.yml
  .github/ISSUE_TEMPLATE/02_feature_request.yml
  .github/ISSUE_TEMPLATE/03_documentation.md
  .github/ISSUE_TEMPLATE/04_performance_issue.md
Labels: build

#11635 Build: Remove code of conduct checkboxes from issue templates
  .github/ISSUE_TEMPLATE/01_bug_report.yml
  .github/ISSUE_TEMPLATE/02_feature_request.yml
Labels: build

#11641 Build: Remove `info required` label after author responds
  .github/workflows/issue-info-required-status.yml
Labels: build

#11642 Build: Use AI to apply PR labels
  .github/PULL_REQUEST_TEMPLATE.MD
  .github/scripts/AutoTriage.js
  .github/workflows/issue.yml
  .github/workflows/pr.yml
Labels: build

#11643 Build: Improve README
  README.md
Labels: build

#11644 Build: Add stale issue management
  .github/workflows/issue-stale.yml
Labels: build

#11646 Build: Update issue workflows
  .github/workflows/issue-info-required.yml
  .github/workflows/issue-stale.yml
  .github/workflows/issue.yml
Labels: build

#11648 Build: Automatically triage backlog issues & include more metadata
  .github/scripts/AutoTriage.js
  .github/scripts/AutoTriageBacklog.js
  .github/workflows/autotriage-backlog.yml
  .github/workflows/issue-stale.yml
Labels: build

#11586 MudFocusTrap: Prevent JSException on Disposed Component
  src/MudBlazor/Components/FocusTrap/MudFocusTrap.razor.cs
Labels: bug

#11568 MudTabs: Update ActiveIndex On Render and Refresh when Drag and Drop Enabled
  src/MudBlazor.Docs/Pages/Components/Tabs/Examples/TabsDragAndDropExample.razor
  src/MudBlazor.Docs/Pages/Components/Tabs/TabsPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/ActivatePanelDragAndDropTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tabs/TabsDragAndDropTest.razor
  src/MudBlazor.UnitTests/Components/TabsTests.cs
  src/MudBlazor/Components/Tabs/MudTabPanel.razor.cs
  src/MudBlazor/Components/Tabs/MudTabs.razor
  src/MudBlazor/Components/Tabs/MudTabs.razor.cs
  src/MudBlazor/Styles/components/_tabs.scss
Labels: bug

#11679 Docs: Update MudDrawer Mini Example
  src/MudBlazor.Docs/Pages/Components/Drawer/DrawerPage.razor
  src/MudBlazor.Docs/Pages/Components/Drawer/Examples/DrawerMiniExample.razor
Labels: docs

#11678 Docs: Add Positioning Explanation for MudOverlay
  src/MudBlazor.Docs/Pages/Components/Overlay/Examples/OverlayPositionExample.razor
  src/MudBlazor.Docs/Pages/Components/Overlay/OverlayPage.razor
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
Labels: docs

#11628 MudSimpleTable: Remove redundant bottom border from the last row header
  src/MudBlazor/Styles/components/_simpletable.scss
Labels: bug

#11684 Build: Update AutoTriage
  .github/scripts/AutoTriage.js
  .github/scripts/AutoTriage.prompt
  .github/workflows/issue.yml
  .github/workflows/pr.yml
  .github/workflows/triage-backlog.yml
Labels: refactor, build

#11685 Build: Update AutoTriage
  .github/scripts/AutoTriage.js
  .github/scripts/AutoTriage.prompt
  .github/workflows/triage-backlog.yml
Labels: build

#11681 MudTable: Maintains group row state when group list is modified
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableGroupingNestedTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Table/TableGroupingTest3.razor
  src/MudBlazor.UnitTests/Components/TableTests.cs
  src/MudBlazor/Components/Table/MudTable.razor
  src/MudBlazor/Components/Table/MudTableGroupRow.razor
Labels: bug

#11682 Build: Add Gemini review rules
  .gemini/config.yaml
  .gemini/styleguide.md
Labels: build

#11711 Build: Refactor and fine-tune AutoTriage
  .github/scripts/AutoTriage.js
  .github/scripts/AutoTriage.prompt
  .github/workflows/triage-backlog.yml
Labels: refactor, build

#11720 Build: Update AutoTriage
  .github/scripts/AutoTriage.js
  .github/scripts/AutoTriage.prompt
  .github/workflows/triage-backlog.yml
Labels: build

#11669 MudField: AdornmentAria and ShrinkLabel
  src/MudBlazor.Docs/Pages/Components/Field/Examples/FieldLabelPlaceholderExample.razor
  src/MudBlazor.Docs/Pages/Components/Field/FieldPage.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Field/FieldStartAdornmentTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Field/FieldTest.razor
  src/MudBlazor.UnitTests/Components/FieldTests.cs
  src/MudBlazor/Components/Field/MudField.razor
  src/MudBlazor/Components/Field/MudField.razor.cs
Labels: enhancement, accessibility

#11744 Tests: Attempt to fix two flaky tests
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
Labels: build, tests
