Repository MudBlazor/MudBlazor, pull requests merged in 2025-04, with the labels that each got.

#10893 MudOverlay: Add parameter Modal allowing click-through
  src/MudBlazor.Docs/Pages/Components/Autocomplete/Examples/AutocompletePlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/ColorPickerPage.razor
  src/MudBlazor.Docs/Pages/Components/ColorPicker/Examples/ColorPickerInlineModelessExample.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/DatePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DatePicker/Examples/DatePickerInlineModelessExample.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/DateRangePickerPage.razor
  src/MudBlazor.Docs/Pages/Components/DateRangePicker/Examples/DateRangePickerInlineModelessExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/Examples/MenuModalExample.razor
  src/MudBlazor.Docs/Pages/Components/Menu/MenuPage.razor
  src/MudBlazor.Docs/Pages/Components/Select/Examples/SelectPlaygroundExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/Examples/TimePickerInlineModelessExample.razor
  src/MudBlazor.Docs/Pages/Components/TimePicker/TimePickerPage.razor
  src/MudBlazor.Docs/Shared/Appbar.razor
  src/MudBlazor.UnitTests.Docs/Generated/ApiDocsTests.cs
  src/MudBlazor.UnitTests.Docs/Generated/ExampleDocsTests.cs
  src/MudBlazor.UnitTests.Shared/Mocks/MockPointerEventsNoneService.cs
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
  src/MudBlazor.UnitTests/Services/PointerEvents/Mocks/PointerEventsNoneObserverMock.cs
  src/MudBlazor.UnitTests/Services/PointerEvents/PointerEventsNoneObserverTests.cs
  src/MudBlazor.UnitTests/Services/PointerEvents/PointerEventsNoneServiceTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
  src/MudBlazor/Components/Picker/MudPicker.razor.cs
  src/MudBlazor/Components/Select/MudSelect.razor
  src/MudBlazor/Components/Select/MudSelect.razor.cs
  src/MudBlazor/Extensions/ServiceCollectionExtensions.cs
  src/MudBlazor/Interop/PointerEventsNoneInterop.cs
  src/MudBlazor/Services/PointerEvents/IPointerDownObserver.cs
  src/MudBlazor/Services/PointerEvents/IPointerEventsNoneObserver.cs
  src/MudBlazor/Services/PointerEvents/IPointerEventsNoneService.cs
  src/MudBlazor/Services/PointerEvents/IPointerUpObserver.cs
  src/MudBlazor/Services/PointerEvents/PointerEventsNoneObserver.cs
  src/MudBlazor/Services/PointerEvents/PointerEventsNoneOptions.cs
  src/MudBlazor/Services/PointerEvents/PointerEventsNoneService.cs
  src/MudBlazor/TScripts/mudPointerEventsNone.js
Labels: enhancement

#11129 MudMenu: Revert hide delay to match show delay again
  src/MudBlazor.UnitTests/Components/MenuTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Services/MudGlobal.cs
Labels: PR: needs review

#11135 MudInput - Heap Locked When Disabled
  src/MudBlazor.UnitTests.Viewer/TestComponents/Input/InputHeapLockedTest.razor
  src/MudBlazor/TScripts/mudElementReference.js
Labels: bug

#11139 Misc: Update version numbers in bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: docs, PR: needs review

#11150 BarChart: Fix tooltip display value
  src/MudBlazor.UnitTests/Components/ChartTests.cs
  src/MudBlazor/Components/Chart/Charts/Bar.razor.cs
Labels: bug

#11153 MudTimeSeriesChart: Fix Unhandled Exception
  src/MudBlazor/Components/Chart/Charts/TimeSeries.razor
Labels: bug

#11144 MudPicker: Set TextUpdateSuppression based on Readonly state
  src/MudBlazor/Base/MudBaseInput.cs
  src/MudBlazor/Components/Picker/MudPicker.razor
Labels: bug

#11156 Update README.md, ROADMAP.md
  README.md
  ROADMAP.md
Labels: docs, PR: needs review

#11155 Docs: Clarify MudGlobal support policy
  src/MudBlazor.Docs/Pages/Customization/Globals/Examples/ButtonGlobalsExample.razor
  src/MudBlazor.Docs/Pages/Customization/Globals/Examples/ButtonGlobalsStartupExample.razor
  src/MudBlazor.Docs/Pages/Customization/Globals/Globals.razor
  src/MudBlazor/Services/MudGlobal.cs
Labels: docs, PR: needs review

#11130 MudAutocomplete: Fix various activation issues
  src/MudBlazor.UnitTests/Components/AutocompleteTests.cs
  src/MudBlazor/Components/Autocomplete/MudAutocomplete.razor.cs
Labels: bug, PR: needs review

#11103 MudDataGrid: Enhance HierarchyColumn for RTL and Expand/Collapse All
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridDetailRowExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridHierarchyColumnTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/CellContext.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: bug

#11186 [Docs] Fix color preview getting cut off
  src/MudBlazor.Docs/Pages/Customization/DefaultTheme.razor
Labels: docs

#11192 MudCarousel: Fix timer creation after component disposal
  src/MudBlazor/Components/Carousel/MudCarousel.razor.cs
Labels: bug

#11181 MudDataGrid: Hierarchy Column Header
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridDetailRowExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridHierarchyColumnTest.razor
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor
  src/MudBlazor/Components/DataGrid/HierarchyColumn.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Styles/components/_table.scss
Labels: enhancement

#11165 MudPopover: Javascript refactor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Menu/MenuEdgeCasesTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Popover/PopoverFlipDirectionTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/Tooltip/TooltipNotRemovedTest.razor
  src/MudBlazor.UnitTests/Components/DynamicTabsTests.cs
  src/MudBlazor.UnitTests/Components/PopoverTests.cs
  src/MudBlazor.UnitTests/Components/ToolTipTests.cs
  src/MudBlazor.UnitTests/Services/Popover/PopoverServiceTests.cs
  src/MudBlazor/Components/Menu/MudMenu.razor
  src/MudBlazor/Components/Menu/MudMenu.razor.cs
  src/MudBlazor/Components/Popover/MudPopoverProvider.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor
  src/MudBlazor/Components/Tooltip/MudTooltip.razor.cs
  src/MudBlazor/Interop/PopoverJsInterop.cs
  src/MudBlazor/Services/Popover/PopoverOptions.cs
  src/MudBlazor/Services/Popover/PopoverService.cs
  src/MudBlazor/Styles/components/_popover.scss
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#11211 Docs - Dialog - Fix spelling
  src/MudBlazor.Docs/Pages/Components/Dialog/DialogPage.razor
Labels: docs

#11198 MudDataGrid: Add XML comment to ToggleHierarchyVisibilityAsync
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
Labels: docs

#11219 MudChat: RTL Display / Remove Expiramental Tag
  src/MudBlazor.Docs/Pages/Components/ChatBubble/ChatPage.razor
  src/MudBlazor/Styles/components/_chat.scss
Labels: bug, PR: needs review

#11222 mudElementReference.js: Fix null exception
  src/MudBlazor/TScripts/mudElementReference.js
Labels: bug

#11214 MudThemeProvider: Only wrap multi-word font names in quotes in CSS font-family declarations
  src/MudBlazor.UnitTests/Components/ThemeProviderTests.cs
  src/MudBlazor/Components/ThemeProvider/MudThemeProvider.razor.cs
Labels: bug

#11104 MudDateRangePicker: BlurAsync() MudRangeInput can now blur both inputs at once
  src/MudBlazor.UnitTests/Components/DateRangePickerTests.cs
  src/MudBlazor/Components/DatePicker/MudDateRangePicker.razor.cs
  src/MudBlazor/Components/Input/MudRangeInput.razor.cs
Labels: enhancement

#11243 MudDataGrid: Multi Level Grouping
  src/MudBlazor.Docs/Pages/Components/DataGrid/DataGridPage.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridGroupingExample.razor
  src/MudBlazor.Docs/Pages/Components/DataGrid/Examples/DataGridGroupingMultiLevelExample.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridColumnGroupingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupCollapseAllTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandAllCollapseAllTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedAsyncTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedFalseAsyncTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedFalseServerDataTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedFalseTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedServerDataTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupExpandedTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridGroupingMultiLevelTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridServerDataColumnGroupingTest.razor
  src/MudBlazor.UnitTests.Viewer/TestComponents/DataGrid/DataGridUniqueRowKeyTest.razor
  src/MudBlazor.UnitTests/Components/DataGridGroupingTests.cs
  src/MudBlazor.UnitTests/Components/DataGridTests.cs
  src/MudBlazor.UnitTests/Components/UserAttributes/UserAttributesTests.cs
  src/MudBlazor/Attributes/CategoryAttribute.cs
  src/MudBlazor/Components/DataGrid/Column.razor.cs
  src/MudBlazor/Components/DataGrid/DataGridGroupRow.razor
  src/MudBlazor/Components/DataGrid/DataGridGroupRow.razor.cs
  src/MudBlazor/Components/DataGrid/DataGridVirtualizeRow.razor
  src/MudBlazor/Components/DataGrid/DataGridVirtualizeRow.razor.cs
  src/MudBlazor/Components/DataGrid/GroupDefinition.cs
  src/MudBlazor/Components/DataGrid/HeaderCell.razor.cs
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor.cs
  src/MudBlazor/Styles/components/_datagrid.scss
Labels: enhancement

#11220 Popover: Z-Index Alignment
  src/MudBlazor/Components/DataGrid/MudDataGrid.razor
  src/MudBlazor/TScripts/mudPopover.js
Labels: bug

#11174 MudOverlay: Prevent unnecessary LockScroll changes
  src/MudBlazor.UnitTests/Components/OverlayTests.cs
  src/MudBlazor/Components/Overlay/MudOverlay.razor.cs
  src/MudBlazor/Services/Scroll/ScrollManager.cs
  src/MudBlazor/TScripts/mudScrollManager.js
Labels: bug

#11254 MudInput: Dispose DotNetObjectReference
  src/MudBlazor/Components/Input/MudInput.razor.cs
Labels: bug

#11256 Docs: Updated sponsorship info and added team member sponsor links
  src/MudBlazor.Docs/Components/MudTeamCard.razor
  src/MudBlazor.Docs/Models/TeamMember.cs
  src/MudBlazor.Docs/Pages/Mud/Project/Sponsors.razor
  src/MudBlazor.Docs/Pages/Mud/Project/Team.razor
Labels: docs, PR: needs review

#11257 GitHubActions: Fix TryMudBlazor deploy
  .github/workflows/deploy-trymudblazor.yml
Labels: PR: needs review

#11265 Unit Tests: Fix selecting hidden dates
  src/MudBlazor.UnitTests/Components/DatePickerTests.cs
Labels: tests
